/**
 * Response Mode Constants
 *
 * Static content, phrases, and detection patterns.
 *
 * @module @ferni/conversation/response-mode/constants
 */

import type { ResponseMode, ResponseModeRule } from './types.js';

// ============================================================================
// MODE CONTENT
// ============================================================================

/**
 * Pre-defined phrases for each response mode
 * SSML is included for proper voice delivery
 */
export const MODE_CONTENT: Record<ResponseMode, string[]> = {
  presence: [
    "<break time='500ms'/>I'm here.",
    "<break time='500ms'/>I'm listening.",
    "<break time='500ms'/>Take your time.",
    "<break time='500ms'/>I'm with you.",
    "<break time='400ms'/>I hear you.",
  ],
  brief: [
    "That's a lot to carry.",
    'I hear you.',
    'That makes sense.',
    'Of course you feel that way.',
    'That sounds really hard.',
    'I get it.',
    'Yeah.',
  ],
  invitation: [
    'Tell me more?',
    'Go on...',
    'What else is there?',
    "I'm curious...",
    'And?',
    "What's on your mind?",
  ],
  celebration: [
    "That's wonderful!",
    'Yes!',
    'I love that.',
    "That's amazing.",
    'How great!',
    "That's so good to hear.",
  ],
  clarify: [
    'What do you mean by that?',
    'Can you tell me more?',
    'I want to make sure I understand...',
    'Help me understand...',
  ],
  silence: [], // Intentionally empty - no response
  full: [], // Full response generated by LLM
};

/**
 * Plain text versions (SSML stripped)
 */
export const MODE_CONTENT_PLAIN: Record<ResponseMode, string[]> = Object.fromEntries(
  Object.entries(MODE_CONTENT).map(([mode, phrases]) => [
    mode,
    phrases.map((p) => p.replace(/<[^>]+>/g, '').trim()),
  ])
) as Record<ResponseMode, string[]>;

// ============================================================================
// DECISION RULES
// ============================================================================

/**
 * Rules for determining response mode (in priority order)
 * Lower priority number = higher precedence
 */
export const RESPONSE_MODE_RULES: ResponseModeRule[] = [
  // Rule 1: After heavy venting, just acknowledge
  {
    condition: (ctx) => ctx.wasVenting && ctx.userTurnIntensity > 0.7,
    mode: 'brief',
    maxWords: 15,
    suggestedPhrases: MODE_CONTENT.brief,
    priority: 1,
  },

  // Rule 2: After vulnerability, presence only
  {
    condition: (ctx) => ctx.wasVulnerable && ctx.emotionalState === 'raw',
    mode: 'presence',
    maxWords: 5,
    suggestedPhrases: MODE_CONTENT.presence,
    pauseBeforeMs: 1500,
    priority: 2,
  },

  // Rule 3: After vulnerability (not raw), still gentle
  {
    condition: (ctx) => ctx.wasVulnerable,
    mode: 'presence',
    maxWords: 8,
    suggestedPhrases: MODE_CONTENT.presence,
    pauseBeforeMs: 1000,
    priority: 3,
  },

  // Rule 4: Positive moment with high intensity, let them savor
  {
    condition: (ctx) =>
      ctx.sentiment === 'positive' && ctx.userTurnIntensity > 0.6 && !ctx.askedQuestion,
    mode: 'celebration',
    maxWords: 20,
    suggestedPhrases: MODE_CONTENT.celebration,
    priority: 4,
  },

  // Rule 5: User asked a question - full response
  {
    condition: (ctx) => ctx.askedQuestion,
    mode: 'full',
    priority: 5,
  },

  // Rule 6: Very short user turn - invite more
  {
    condition: (ctx) => ctx.userTurnLength < 10 && !ctx.askedQuestion,
    mode: 'invitation',
    suggestedPhrases: MODE_CONTENT.invitation,
    priority: 6,
  },

  // Rule 7: Declining emotional trajectory - validate first
  {
    condition: (ctx) =>
      ctx.trajectory === 'declining' && ctx.sentiment === 'negative' && ctx.userTurnIntensity > 0.5,
    mode: 'brief',
    maxWords: 20,
    suggestedPhrases: MODE_CONTENT.brief,
    priority: 7,
  },

  // Rule 8: Mixed sentiment, might need clarification
  {
    condition: (ctx) => ctx.sentiment === 'mixed' && ctx.userTurnLength > 30,
    mode: 'clarify',
    suggestedPhrases: MODE_CONTENT.clarify,
    priority: 8,
  },

  // Rule 9: Moderate venting (not heavy)
  {
    condition: (ctx) => ctx.wasVenting && ctx.userTurnIntensity > 0.4,
    mode: 'brief',
    maxWords: 25,
    suggestedPhrases: MODE_CONTENT.brief,
    priority: 9,
  },
];

// ============================================================================
// DETECTION PATTERNS
// ============================================================================

/**
 * Patterns indicating venting/emotional release
 */
export const VENTING_PATTERNS = {
  /** High-intensity venting markers */
  highIntensity: [
    /I (just )?(can't|cannot) (believe|stand|take|handle)/i,
    /I('m| am) so (frustrated|angry|upset|annoyed|tired|exhausted|sick)/i,
    /This is (ridiculous|insane|unbelievable|crazy)/i,
    /(hate|despise|loathe) (this|that|it|them|him|her)/i,
    /I've (had|have) (enough|it)/i,
    /What the (hell|heck|f)/i,
    /Are you (kidding|serious)/i,
  ],
  /** Moderate venting markers */
  moderateIntensity: [
    /I('m| am) (feeling )?(so )?(overwhelmed|stressed|anxious)/i,
    /I('m| am) so (overwhelmed|stressed|anxious|frustrated|tired)/i,
    /It('s| is) (really|so|just) (hard|difficult|tough)/i,
    /I (don't|do not) know (what to do|how to|anymore)/i,
    /Everything is (going wrong|falling apart|a mess)/i,
    /I('m| am) (struggling|having trouble) with/i,
  ],
  /** Length indicator - long messages often indicate venting */
  minLengthForVenting: 50,
};

/**
 * Patterns indicating vulnerability
 */
export const VULNERABILITY_PATTERNS = {
  /** High vulnerability markers */
  high: [
    /I('ve| have) never told (anyone|somebody|anyone else)/i,
    /This is (hard|difficult|scary) (to say|to admit|to share)/i,
    /I('m| am) (scared|afraid|terrified) (to|of|that)/i,
    /I feel (so )?(alone|lonely|isolated)/i,
    /I('m| am) (ashamed|embarrassed) (of|to|that)/i,
    /Please don't (judge|tell|think)/i,
  ],
  /** Medium vulnerability markers */
  medium: [
    /I('ve| have) been (thinking|wondering|worried)/i,
    /I (don't|do not) (usually|normally) (talk about|share|mention)/i,
    /Can I (tell|ask|share|say) you something/i,
    /Between (you and me|us)/i,
    /I trust you/i,
  ],
  /** Low vulnerability markers */
  low: [/I('m| am) not sure (if|how|whether)/i, /I guess/i, /I think/i, /Maybe/i],
};

/**
 * Patterns for question detection
 */
export const QUESTION_PATTERNS = {
  /** Direct questions */
  direct: [
    /^(what|where|when|why|who|how|which|whose|whom)\b/i,
    /\?$/,
    /^(do|does|did|is|are|was|were|can|could|will|would|should|have|has|had)\b/i,
  ],
  /** Indirect questions */
  indirect: [
    /I('m| am) wondering/i,
    /I('d| would) like to know/i,
    /Can you (tell|explain|help)/i,
    /Could you/i,
    /I was hoping you could/i,
  ],
  /** Rhetorical questions (don't need answer) */
  rhetorical: [
    /you know\?$/i,
    /right\?$/i,
    /isn't it\?$/i,
    /don't you think\?$/i,
    /what (even|the hell|the heck) is/i,
  ],
};

// ============================================================================
// THRESHOLDS
// ============================================================================

export const THRESHOLDS = {
  /** Minimum intensity to consider high-intensity venting */
  highIntensityVenting: 0.7,

  /** Minimum intensity for moderate venting */
  moderateIntensityVenting: 0.4,

  /** Minimum words to consider "short" turn */
  shortTurnWords: 10,

  /** Minimum words to consider "long" turn */
  longTurnWords: 50,

  /** Maximum consecutive brief modes before switching */
  maxConsecutiveBrief: 3,

  /** Minimum confidence for mode decision */
  minConfidence: 0.6,
};
