/**
 * LLM-Powered Dynamic Expression Generator
 *
 * "Better than human" personality expressions generated by Gemini in the background.
 *
 * This is the next evolution beyond pool-based selection and building-block composition:
 * - Truly UNIQUE expressions every time (no repetition)
 * - PERSONA-GROUNDED via voice DNA injection
 * - NON-BLOCKING - runs on async queue in background
 * - PRE-GENERATION - fills cache during quiet moments
 * - COST-EFFICIENT - batching, caching, smart throttling
 *
 * Architecture:
 * 1. Expression queue - requests queued, processed in batches
 * 2. LLM worker - generates expressions with persona grounding
 * 3. Expression cache - stores generated expressions for reuse
 * 4. Fallback chain - LLM → Composed → Pool-based
 *
 * @module personas/bundles/ferni/llm-expression-generator
 */
import type { ThemeCategory } from '../../../services/session-variety-tracker.js';
export interface ExpressionRequest {
    id: string;
    theme: ThemeCategory;
    context: ExpressionContext;
    priority: 'high' | 'normal' | 'low';
    timestamp: number;
}
export interface ExpressionContext {
    /** User's current emotional state */
    emotion?: string;
    /** Current conversation topic */
    topic?: string;
    /** Time of day */
    timeOfDay?: 'dawn' | 'morning' | 'afternoon' | 'evening' | 'late_night' | 'night';
    /** Relationship depth */
    relationshipStage?: 'stranger' | 'acquaintance' | 'friend' | 'trusted_advisor';
    /** Recent topics for callbacks */
    recentTopics?: string[];
    /** Conversation momentum */
    momentum?: 'opening' | 'building' | 'cruising' | 'winding_down';
    /** Was this a heavy topic? */
    isHeavyTopic?: boolean;
}
export interface GeneratedExpression {
    id: string;
    theme: ThemeCategory;
    content: string;
    ssml: string;
    context: ExpressionContext;
    generatedAt: Date;
    usedCount: number;
}
declare const stats: {
    totalRequests: number;
    cacheHits: number;
    llmCalls: number;
    llmFailures: number;
    avgLatencyMs: number;
};
/**
 * Request an LLM-generated expression (async, non-blocking)
 *
 * This queues a request and returns immediately. Use getExpression() to
 * retrieve generated expressions from cache.
 */
export declare function requestExpression(theme: ThemeCategory, context: ExpressionContext, priority?: 'high' | 'normal' | 'low'): void;
/**
 * Get a generated expression from cache
 *
 * Returns null if no matching expression is cached.
 * Use requestExpression() to queue generation.
 */
export declare function getGeneratedExpression(userId: string, theme: ThemeCategory, context: ExpressionContext): GeneratedExpression | null;
/**
 * Pre-warm cache with expressions for a session
 *
 * Call at session start to populate cache with common expressions.
 */
export declare function prewarmCache(context: ExpressionContext): void;
/**
 * Request expressions for specific emotional context
 *
 * Call when user emotion changes to pre-generate matching expressions.
 */
export declare function requestEmotionalExpressions(emotion: string, context: ExpressionContext): void;
/**
 * Get generation stats
 */
export declare function getStats(): typeof stats & {
    queueLength: number;
    cacheSize: number;
};
/**
 * Clear cache for a user (call on session end)
 * Note: Global cache is shared across users and not cleared here
 */
export declare function clearCache(userId: string): void;
/**
 * Clear the global expression cache
 * Call this sparingly (e.g., on server restart)
 */
export declare function clearGlobalCache(): void;
/**
 * Get the best expression available (LLM → Composed → Pool)
 *
 * This is the main entry point for the personality system.
 * It tries LLM-generated first, falls back to composed, then pool.
 *
 * PERF: Uses pre-loaded imports to avoid slow dynamic imports in hot path.
 */
export declare function getBestExpression(userId: string, sessionId: string, theme: ThemeCategory, context: ExpressionContext): {
    content: string;
    ssml: string;
    source: 'llm' | 'composed' | 'pool';
} | null;
/**
 * Mark an expression as high-engagement (call when user responds positively)
 *
 * Expressions with high engagement get persisted to Firestore for future sessions.
 */
export declare function markExpressionEngagement(userId: string, expressionId: string, positive: boolean): Promise<void>;
/**
 * Load persisted expressions for a user
 *
 * Call at session start to seed cache with proven expressions.
 * Returns expressions ordered by engagement score (highest first).
 */
export declare function loadPersistedExpressions(userId: string): Promise<GeneratedExpression[]>;
/**
 * Flush high-engagement expressions to Firestore before session ends
 */
export declare function flushExpressions(userId: string): Promise<void>;
declare const _default: {
    request: typeof requestExpression;
    get: typeof getGeneratedExpression;
    getBest: typeof getBestExpression;
    prewarm: typeof prewarmCache;
    requestEmotional: typeof requestEmotionalExpressions;
    clearCache: typeof clearCache;
    getStats: typeof getStats;
    markEngagement: typeof markExpressionEngagement;
    loadPersisted: typeof loadPersistedExpressions;
    flush: typeof flushExpressions;
};
export default _default;
//# sourceMappingURL=llm-expression-generator.d.ts.map