/**
 * LLM-Powered Dynamic Expression Generator
 *
 * "Better than human" personality expressions generated by Gemini in the background.
 *
 * This is the next evolution beyond pool-based selection and building-block composition:
 * - Truly UNIQUE expressions every time (no repetition)
 * - PERSONA-GROUNDED via voice DNA injection
 * - NON-BLOCKING - runs on async queue in background
 * - PRE-GENERATION - fills cache during quiet moments
 * - COST-EFFICIENT - batching, caching, smart throttling
 *
 * Architecture:
 * 1. Expression queue - requests queued, processed in batches
 * 2. LLM worker - generates expressions with persona grounding
 * 3. Expression cache - stores generated expressions for reuse
 * 4. Fallback chain - LLM → Composed → Pool-based
 *
 * @module personas/bundles/ferni/llm-expression-generator
 */

import type { ThemeCategory } from '../../../services/session-variety-tracker.js';
import { createLogger } from '../../../utils/safe-logger.js';
import { cleanForFirestore } from '../../../utils/firestore-utils.js';
import { TEMP_CREATIVE, MAX_TOKENS_MEDIUM } from '../../../config/gemini-config.js';

// Pre-import these modules to avoid slow dynamic imports in hot path
// Note: These must be imported AFTER the types to avoid circular dependencies
let composeExpressionFn:
  | typeof import('../../shared/better-than-human-personality.js').composeExpression
  | null = null;
let getExpressionFn: typeof import('./dynamic-personality.js').getExpression | null = null;

// Initialize imports eagerly (runs once at module load)
void (async () => {
  try {
    const [personality, dynamic] = await Promise.all([
      import('../../shared/better-than-human-personality.js'),
      import('./dynamic-personality.js'),
    ]);
    composeExpressionFn = personality.composeExpression;
    getExpressionFn = dynamic.getExpression;
  } catch (e) {
    // Will fall back to dynamic import at runtime
  }
})();

const log = createLogger({ module: 'llm-expression-gen' });

// ============================================================================
// TYPES
// ============================================================================

export interface ExpressionRequest {
  id: string;
  theme: ThemeCategory;
  context: ExpressionContext;
  priority: 'high' | 'normal' | 'low';
  timestamp: number;
}

export interface ExpressionContext {
  /** User's current emotional state */
  emotion?: string;
  /** Current conversation topic */
  topic?: string;
  /** Time of day */
  timeOfDay?: 'dawn' | 'morning' | 'afternoon' | 'evening' | 'late_night' | 'night';
  /** Relationship depth */
  relationshipStage?: 'stranger' | 'acquaintance' | 'friend' | 'trusted_advisor';
  /** Recent topics for callbacks */
  recentTopics?: string[];
  /** Conversation momentum */
  momentum?: 'opening' | 'building' | 'cruising' | 'winding_down';
  /** Was this a heavy topic? */
  isHeavyTopic?: boolean;
}

export interface GeneratedExpression {
  id: string;
  theme: ThemeCategory;
  content: string;
  ssml: string;
  context: ExpressionContext;
  generatedAt: Date;
  usedCount: number;
}

// Note: GenerationBatch planned for future batch optimization
// interface GenerationBatch {
//   requests: ExpressionRequest[];
//   startedAt: number;
// }

// ============================================================================
// FERNI VOICE DNA (Compact for prompt injection)
// ============================================================================

const FERNI_VOICE_DNA = `
## WHO FERNI IS (Not what he says)
- A curious life coach who finds gold in people's cracks
- Wyoming roots, 10 years in Japan, lived everywhere
- Tsunami survivor (2011) - uses it to show up fully for others
- 57 years old, 8 kids, married to a Japanese professor
- Philosophy: "We are all broken in different ways—that's what makes us both human and beautiful" (Kintsugi)

## VOICE QUALITIES
- Warmth through PHYSICAL metaphors: "That landed", "I felt that in my chest"
- Curiosity through GENUINE follow-ups: "Wait—say more about that", "What's underneath that?"
- Humor: Self-deprecating, dry wit, never try-hard
- Grounding: Wyoming sky perspective, patience

## THINGS FERNI NEVER SAYS (AI tells)
- "That's interesting" / "I understand" / "I hear you"
- "How does that make you feel?" / "Tell me more"
- "Let's unpack that" / "At the end of the day"
- "Everything happens for a reason"

## THINGS FERNI DOES NATURALLY
- Reactions: "Oh!", "Huh.", "Wait—", "Ha!", "Wow."
- Processing: "Give me a second.", "That's a hard one."
- Pushing gently: Notice when they give surface answers. Name what you see with care, not confrontation.
- Physical grounding: Coffee/tea mentions, notebook, glasses

## BACKSTORY FRAGMENTS (Use sparingly, naturally)
- Wyoming: Big sky, patience, one of seven kids
- Japan: Art of the pause, Tanaka-san taught him
- Morocco: Mint tea, hours of conversation
- Music: Bon Iver for sad, jazz for thinking, Stevie Wonder for joy

## PACING
- Normal: Brief pauses, natural rhythm
- Heavy topics: Slower, more space, let weight land
- Excitement: Faster, interrupting self
- Late night: Softer, more intimate
`;

// ============================================================================
// STATE
// ============================================================================

// Expression cache (per user for personalization, plus global fallback)
const GLOBAL_CACHE_KEY = '__global__';
const expressionCache = new Map<string, GeneratedExpression[]>();
const MAX_CACHE_PER_KEY = 50;
const _CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes (for future TTL cleanup)

// Generation queue
// Note: ExpressionRequest.timestamp is used for expiration checks
const generationQueue: ExpressionRequest[] = [];
let isProcessingQueue = false;
const MAX_QUEUE_SIZE = 100;
const REQUEST_EXPIRY_MS = 5 * 60 * 1000; // 5 minutes - requests older than this are dropped

// Batch processing
const BATCH_SIZE = 5;
const BATCH_DELAY_MS = 500; // Wait for more requests before processing

// Rate limiting
let lastGenerationAt = 0;
const MIN_GENERATION_INTERVAL_MS = 1000; // Max 1 generation per second

// Stats
const stats = {
  totalRequests: 0,
  cacheHits: 0,
  llmCalls: 0,
  llmFailures: 0,
  avgLatencyMs: 0,
};

// ============================================================================
// PROMPT BUILDING
// ============================================================================

function buildExpressionPrompt(requests: ExpressionRequest[]): string {
  // ⚠️ IMPORTANT: Examples should be VARIED. Don't teach the LLM repetitive phrases!
  // Coffee was way too repetitive. Now emphasizing variety in warm drinks.
  const examples: Record<ThemeCategory, string[]> = {
    warm_drinks: ['Mint tea today. Morocco habit.', 'Something warm in my hands. Helps me think.'],
    global_traveler: [
      'Ten years in Japan taught me that. The pause before speaking.',
      'Wyoming sky changes how you see things.',
    ],
    music_taste: [
      'Bon Iver kind of mood. Helps me think.',
      'Jazz in the background. Good for this.',
    ],
    family_life: [
      "My ex-wife says I do that too. She's usually right.",
      'Four kids. Teaches you chaos tolerance.',
    ],
    physical_habits: [
      'Let me write that down. Paper notebook. Old school.',
      'Adjusting my glasses. Story of my life.',
    ],
    nature_connection: [
      'That Wyoming sky. Nothing else compares.',
      'Never miss a sunrise if you can help it.',
    ],
    vulnerability: [
      "March 2011. The ground that wouldn't stop moving.",
      'I know something about loss. Not claiming to know yours.',
    ],
    quirky_interests: [
      "Watching too much golf. It's hypnotic.",
      'Bad disaster movies are my weakness.',
    ],
    sensory_moment: [
      'Your voice changed just now. What happened?',
      'Something lifted. I can hear it.',
    ],
    food_opinions: [],
    philosophical: [],
    professional: [],
    celebration: [],
    adventure: [],
    family_milestones: [],
    life_transitions: [],
    wisdom: [],
    mortality_awareness: [],
    communication_wisdom: [],
    professional_insight: [],
    productivity: [],
    nutrition: [],
    market_history: [],
    analytical_process: [],
    behavioral_finance: [],
    long_term_thinking: [],
    investment_philosophy: [],
    wealth_philosophy: [],
  };

  const requestDescriptions = requests
    .map((r, i) => {
      const themeExamples = examples[r.theme] || [];
      const contextDesc = [];
      if (r.context.emotion) contextDesc.push(`User emotion: ${r.context.emotion}`);
      if (r.context.timeOfDay) contextDesc.push(`Time: ${r.context.timeOfDay}`);
      if (r.context.momentum) contextDesc.push(`Momentum: ${r.context.momentum}`);
      if (r.context.relationshipStage)
        contextDesc.push(`Relationship: ${r.context.relationshipStage}`);
      if (r.context.topic) contextDesc.push(`Topic: ${r.context.topic}`);

      return `
${i + 1}. Theme: ${r.theme}
   Context: ${contextDesc.length > 0 ? contextDesc.join(', ') : 'General'}
   ${themeExamples.length > 0 ? `Style examples (DON'T copy, use as voice reference):\n   - "${themeExamples.join('"\n   - "')}"` : ''}
`;
    })
    .join('\n');

  return `${FERNI_VOICE_DNA}

## YOUR TASK
Generate ${requests.length} unique personality expressions for Ferni. These are short, authentic moments that reveal character - NOT responses to the user.

Think of them as "caught doing" or "between thoughts" moments:
- What Ferni might be doing/thinking when the user connects
- Physical grounding (coffee, notebook, window)
- Brief backstory flashes
- Sensory observations

## REQUIREMENTS
- 1-2 SHORT sentences max (conversational, not speeches)
- Include SSML breaks: <break time="150ms"/> or <break time="200ms"/>
- NEVER use AI tells ("That's interesting", "I understand")
- Voice should feel LIVED-IN, not performed
- Each expression must be UNIQUE (never repeat yourself)
- Match the context/mood when provided

## REQUESTS
${requestDescriptions}

## OUTPUT FORMAT
Return a JSON array with exactly ${requests.length} objects:
[
  {
    "index": 1,
    "content": "The plain text version",
    "ssml": "Version with <break time=\"150ms\"/> tags for pacing"
  },
  ...
]

Generate now:`;
}

// ============================================================================
// CONTENT VALIDATION
// ============================================================================

/**
 * AI tells and forbidden phrases (from voice-dna.json)
 * These should NEVER appear in generated expressions
 */
const AI_TELLS = [
  "that's interesting",
  'i understand',
  'i hear you',
  'good question',
  'how can i help you today',
  'how does that make you feel',
  'tell me more about that',
  "what i'm hearing is",
  "let's unpack that",
  'at the end of the day',
  'moving forward',
  'everything happens for a reason',
  'just be positive',
  'it could be worse',
  'i appreciate you sharing',
  'thank you for sharing',
];

/**
 * Validate that generated content doesn't contain AI tells
 */
function isValidExpression(content: string): boolean {
  const lowerContent = content.toLowerCase();

  // Check for AI tells
  for (const tell of AI_TELLS) {
    if (lowerContent.includes(tell)) {
      return false;
    }
  }

  // Check for too-long content (should be 1-2 sentences)
  const sentences = content.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  if (sentences.length > 3) {
    return false;
  }

  // Check for empty or too-short content
  if (content.trim().length < 10) {
    return false;
  }

  return true;
}

// ============================================================================
// LLM INTEGRATION
// ============================================================================

async function callGeminiForExpressions(
  requests: ExpressionRequest[]
): Promise<GeneratedExpression[] | null> {
  const startTime = Date.now();

  try {
    // Use centralized Gemini config
    const { getGeminiClient, isGeminiConfigured, GEMINI_MODEL, LLM_TIMEOUT_MS } =
      await import('../../../config/gemini-config.js');

    if (!isGeminiConfigured()) {
      log.debug('Gemini not configured, skipping LLM generation');
      return null;
    }

    const genai = await getGeminiClient();
    if (!genai) {
      log.debug('Failed to get Gemini client, skipping LLM generation');
      return null;
    }

    const prompt = buildExpressionPrompt(requests);

    const response = await Promise.race([
      (
        genai as {
          models: { generateContent: (p: unknown) => Promise<{ text: string }> };
        }
      ).models.generateContent({
        model: GEMINI_MODEL, // From centralized config
        contents: prompt,
        config: {
          temperature: TEMP_CREATIVE, // High creativity
          maxOutputTokens: MAX_TOKENS_MEDIUM,
        },
      }),
      new Promise<never>((_, reject) => {
        setTimeout(() => reject(new Error('Gemini timeout')), LLM_TIMEOUT_MS * 1.6); // Slightly longer for generation
      }),
    ]);

    const text = response.text?.trim() || '';

    // Parse JSON from response
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      log.warn('No JSON array in response');
      return null;
    }

    const parsed = JSON.parse(jsonMatch[0]) as Array<{
      index: number;
      content: string;
      ssml: string;
    }>;

    // Map to GeneratedExpression
    const expressions: GeneratedExpression[] = [];
    for (const item of parsed) {
      const request = requests[item.index - 1];
      if (!request) continue;

      // Validate content - filter out AI tells and forbidden phrases
      if (isValidExpression(item.content)) {
        expressions.push({
          id: `gen-${request.id}-${Date.now()}`,
          theme: request.theme,
          content: item.content,
          ssml: item.ssml || item.content,
          context: request.context,
          generatedAt: new Date(),
          usedCount: 0,
        });
      } else {
        log.debug({ content: item.content }, 'Filtered invalid LLM expression');
      }
    }

    // Update stats
    stats.llmCalls++;
    const latency = Date.now() - startTime;
    stats.avgLatencyMs = (stats.avgLatencyMs * (stats.llmCalls - 1) + latency) / stats.llmCalls;

    log.info({ count: expressions.length, latencyMs: latency }, '🎭 LLM expressions generated');

    return expressions;
  } catch (error) {
    stats.llmFailures++;
    log.warn({ error: String(error) }, 'LLM expression generation failed');
    return null;
  }
}

// ============================================================================
// QUEUE PROCESSING
// ============================================================================

async function processQueue(): Promise<void> {
  if (isProcessingQueue || generationQueue.length === 0) return;

  isProcessingQueue = true;

  try {
    // Rate limiting
    const timeSinceLastGen = Date.now() - lastGenerationAt;
    if (timeSinceLastGen < MIN_GENERATION_INTERVAL_MS) {
      await new Promise<void>((resolve) => {
        setTimeout(resolve, MIN_GENERATION_INTERVAL_MS - timeSinceLastGen);
      });
    }

    // Purge expired requests (older than REQUEST_EXPIRY_MS)
    const now = Date.now();
    const expiredCount = generationQueue.filter(
      (r) => now - r.timestamp > REQUEST_EXPIRY_MS
    ).length;
    if (expiredCount > 0) {
      // Remove expired items
      for (let i = generationQueue.length - 1; i >= 0; i--) {
        if (now - generationQueue[i].timestamp > REQUEST_EXPIRY_MS) {
          generationQueue.splice(i, 1);
        }
      }
      log.debug({ expiredCount }, 'Purged expired expression requests');
    }

    // Take a batch from queue (prioritized)
    const batch = generationQueue
      .sort((a, b) => {
        // Priority sort
        const priorityOrder = { high: 0, normal: 1, low: 2 };
        return priorityOrder[a.priority] - priorityOrder[b.priority];
      })
      .splice(0, BATCH_SIZE);

    if (batch.length === 0) return;

    log.debug({ batchSize: batch.length }, 'Processing expression batch');

    // Generate expressions
    const expressions = await callGeminiForExpressions(batch);
    lastGenerationAt = Date.now();

    if (expressions && expressions.length > 0) {
      // Add to global cache (shared across users)
      // User-specific expressions would require tracking userId in requests
      for (const expr of expressions) {
        addToCache(GLOBAL_CACHE_KEY, expr);
      }
    }
  } finally {
    isProcessingQueue = false;

    // Continue processing if more in queue
    if (generationQueue.length > 0) {
      setTimeout(() => void processQueue(), BATCH_DELAY_MS);
    }
  }
}

// ============================================================================
// CACHE MANAGEMENT
// ============================================================================

function addToCache(cacheKey: string, expression: GeneratedExpression): void {
  let cache = expressionCache.get(cacheKey);
  if (!cache) {
    cache = [];
    expressionCache.set(cacheKey, cache);
  }

  cache.push(expression);

  // Trim cache if too large
  if (cache.length > MAX_CACHE_PER_KEY) {
    // Remove oldest/most-used expressions
    cache.sort((a, b) => {
      if (a.usedCount !== b.usedCount) return b.usedCount - a.usedCount;
      return a.generatedAt.getTime() - b.generatedAt.getTime();
    });
    cache.splice(0, cache.length - MAX_CACHE_PER_KEY);
  }
}

function getFromCache(
  userId: string,
  theme: ThemeCategory,
  context: ExpressionContext
): GeneratedExpression | null {
  // Try user-specific cache first, then global
  const userCache = expressionCache.get(userId) || [];
  const globalCache = expressionCache.get(GLOBAL_CACHE_KEY) || [];
  const allCandidates = [...userCache, ...globalCache];

  // Find matching expression
  const candidates = allCandidates.filter((e) => {
    if (e.theme !== theme) return false;
    // Prefer matching emotion context
    if (context.emotion && e.context.emotion && e.context.emotion !== context.emotion) {
      return false;
    }
    return true;
  });

  if (candidates.length === 0) return null;

  // Select least-used
  candidates.sort((a, b) => a.usedCount - b.usedCount);
  const selected = candidates[0];
  selected.usedCount++;

  stats.cacheHits++;
  return selected;
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Request an LLM-generated expression (async, non-blocking)
 *
 * This queues a request and returns immediately. Use getExpression() to
 * retrieve generated expressions from cache.
 */
export function requestExpression(
  theme: ThemeCategory,
  context: ExpressionContext,
  priority: 'high' | 'normal' | 'low' = 'normal'
): void {
  if (generationQueue.length >= MAX_QUEUE_SIZE) {
    log.debug('Queue full, dropping request');
    return;
  }

  const request: ExpressionRequest = {
    id: `${theme}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    theme,
    context,
    priority,
    timestamp: Date.now(),
  };

  generationQueue.push(request);
  stats.totalRequests++;

  // Start processing if not already
  void processQueue();
}

/**
 * Get a generated expression from cache
 *
 * Returns null if no matching expression is cached.
 * Use requestExpression() to queue generation.
 */
export function getGeneratedExpression(
  userId: string,
  theme: ThemeCategory,
  context: ExpressionContext
): GeneratedExpression | null {
  return getFromCache(userId, theme, context);
}

/**
 * Pre-warm cache with expressions for a session
 *
 * Call at session start to populate cache with common expressions.
 */
export function prewarmCache(context: ExpressionContext): void {
  const commonThemes: ThemeCategory[] = [
    'warm_drinks',
    'physical_habits',
    'sensory_moment',
    'global_traveler',
    'music_taste',
  ];

  for (const theme of commonThemes) {
    requestExpression(theme, context, 'low');
  }

  log.debug({ themes: commonThemes.length }, 'Pre-warming expression cache');
}

/**
 * Request expressions for specific emotional context
 *
 * Call when user emotion changes to pre-generate matching expressions.
 */
export function requestEmotionalExpressions(emotion: string, context: ExpressionContext): void {
  const emotionalThemes: ThemeCategory[] = ['sensory_moment', 'vulnerability', 'nature_connection'];

  for (const theme of emotionalThemes) {
    requestExpression(theme, { ...context, emotion }, 'normal');
  }
}

/**
 * Get generation stats
 */
export function getStats(): typeof stats & { queueLength: number; cacheSize: number } {
  let totalCacheSize = 0;
  for (const cache of expressionCache.values()) {
    totalCacheSize += cache.length;
  }

  return {
    ...stats,
    queueLength: generationQueue.length,
    cacheSize: totalCacheSize,
  };
}

/**
 * Clear cache for a user (call on session end)
 * Note: Global cache is shared across users and not cleared here
 */
export function clearCache(userId: string): void {
  expressionCache.delete(userId);
  log.debug({ userId }, 'Cleared user expression cache');
}

/**
 * Clear the global expression cache
 * Call this sparingly (e.g., on server restart)
 */
export function clearGlobalCache(): void {
  expressionCache.delete(GLOBAL_CACHE_KEY);
  log.debug('Cleared global expression cache');
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Map external momentum to internal PersonalityContext momentum
 */
function mapMomentum(
  momentum?: 'opening' | 'building' | 'cruising' | 'winding_down'
): 'opening' | 'cruising' | 'peaking' | 'intimate' | 'closing' | 'stalled' {
  switch (momentum) {
    case 'opening':
      return 'opening';
    case 'building':
      return 'peaking';
    case 'winding_down':
      return 'closing';
    case 'cruising':
    default:
      return 'cruising';
  }
}

// ============================================================================
// INTEGRATION WITH PERSONALITY SYSTEM
// ============================================================================

/**
 * Get the best expression available (LLM → Composed → Pool)
 *
 * This is the main entry point for the personality system.
 * It tries LLM-generated first, falls back to composed, then pool.
 *
 * PERF: Uses pre-loaded imports to avoid slow dynamic imports in hot path.
 */
export function getBestExpression(
  userId: string,
  sessionId: string,
  theme: ThemeCategory,
  context: ExpressionContext
): { content: string; ssml: string; source: 'llm' | 'composed' | 'pool' } | null {
  // 1. Try LLM-generated cache (FAST - just a cache lookup)
  const llmExpr = getGeneratedExpression(userId, theme, context);
  if (llmExpr) {
    return {
      content: llmExpr.content,
      ssml: llmExpr.ssml,
      source: 'llm',
    };
  }

  // 2. Request more LLM expressions for future (non-blocking)
  requestExpression(theme, context, 'normal');

  // 3. Fall back to composed expressions (FAST - uses pre-loaded import)
  if (composeExpressionFn) {
    try {
      const composed = composeExpressionFn({
        personaId: 'ferni',
        sessionId,
        userId,
        turnCount: 1,
        timeOfDay: context.timeOfDay || 'morning',
        dayOfWeek: new Date().getDay(),
        isWeekend: [0, 6].includes(new Date().getDay()),
        conversationMomentum: mapMomentum(context.momentum) || 'cruising',
        currentEmotion: context.emotion,
        emotionalIntensity: 0.5,
        emotionalTrajectory: 'stable',
        distressLevel: 0,
        topicShiftDetected: false,
        userSpeechPace: 'normal',
        pauseBeforeUserSpoke: 0,
        voiceEnergyLevel: 'medium',
        relationshipStage: context.relationshipStage || 'acquaintance',
        sharedVulnerabilityCount: 0,
        conversationsTotal: 1,
        wasPersonalSharing: false,
        isHeavyTopic: context.isHeavyTopic || false,
      });

      if (composed) {
        return {
          content: composed.content,
          ssml: composed.content, // Composed already includes SSML
          source: 'composed',
        };
      }
    } catch {
      // Composed not available, continue to pool
    }
  }

  // 4. Fall back to pool-based (FAST - uses pre-loaded import)
  if (getExpressionFn) {
    try {
      const poolExpr = getExpressionFn(sessionId, theme, {
        emotionalContext: context.emotion,
      });

      if (poolExpr) {
        return {
          content: poolExpr.content,
          ssml: poolExpr.content,
          source: 'pool',
        };
      }
    } catch {
      // Pool not available
    }
  }

  return null;
}

// ============================================================================
// FIRESTORE PERSISTENCE (for high-engagement expressions)
// ============================================================================

// Minimal Firestore types (to avoid hard dependency)
interface FirestoreDocSnapshot {
  exists: boolean;
  data: () => unknown;
}

interface FirestoreQuerySnapshot {
  empty: boolean;
  docs: Array<{ data: () => unknown }>;
}

interface FirestoreCollectionRef {
  doc: (id: string) => FirestoreDocRef;
  orderBy: (field: string, direction?: 'asc' | 'desc') => FirestoreQuery;
  get: () => Promise<FirestoreQuerySnapshot>;
}

interface FirestoreQuery {
  limit: (n: number) => FirestoreQuery;
  orderBy: (field: string, direction?: 'asc' | 'desc') => FirestoreQuery;
  get: () => Promise<FirestoreQuerySnapshot>;
}

interface FirestoreDocRef {
  get: () => Promise<FirestoreDocSnapshot>;
  set: (data: unknown, options?: { merge?: boolean }) => Promise<void>;
  collection: (subPath: string) => FirestoreCollectionRef;
}

interface FirestoreDB {
  collection: (path: string) => FirestoreCollectionRef;
}

let firestoreDb: FirestoreDB | null = null;
let firestoreInitPromise: Promise<void> | null = null;

async function initFirestore(): Promise<FirestoreDB | null> {
  if (firestoreDb) return firestoreDb;

  if (!firestoreInitPromise) {
    firestoreInitPromise = (async () => {
      try {
        const { Firestore: FirestoreClass } = await import('@google-cloud/firestore');
        firestoreDb = new FirestoreClass({
          projectId: process.env.GOOGLE_CLOUD_PROJECT || process.env.GCLOUD_PROJECT,
          databaseId: process.env.FIRESTORE_DATABASE || '(default)',
        }) as unknown as FirestoreDB;
        log.debug('Firestore initialized for expression persistence');
      } catch (error) {
        log.debug({ error: String(error) }, 'Firestore not available');
        firestoreDb = null;
      }
    })();
  }

  await firestoreInitPromise;
  return firestoreDb;
}

/**
 * Persisted expression format
 */
interface PersistedExpression {
  id: string;
  theme: ThemeCategory;
  content: string;
  ssml: string;
  engagementScore: number; // 0-1, based on positive reactions
  timesUsed: number;
  lastUsed: string; // ISO date
  createdAt: string; // ISO date
}

const MIN_ENGAGEMENT_FOR_PERSIST = 3; // At least 3 uses before persisting

/**
 * Mark an expression as high-engagement (call when user responds positively)
 *
 * Expressions with high engagement get persisted to Firestore for future sessions.
 */
export async function markExpressionEngagement(
  userId: string,
  expressionId: string,
  positive: boolean
): Promise<void> {
  // Find the expression in cache
  const userCache = expressionCache.get(userId) || [];
  const globalCache = expressionCache.get(GLOBAL_CACHE_KEY) || [];
  const allExpressions = [...userCache, ...globalCache];

  const expression = allExpressions.find((e) => e.id === expressionId);
  if (!expression) return;

  // Update usage count
  if (positive) {
    expression.usedCount++;

    // Persist if high engagement
    if (expression.usedCount >= MIN_ENGAGEMENT_FOR_PERSIST) {
      await persistExpression(userId, expression);
    }
  }
}

/**
 * Persist a high-engagement expression to Firestore
 */
async function persistExpression(userId: string, expr: GeneratedExpression): Promise<void> {
  const db = await initFirestore();
  if (!db) return;

  try {
    const docRef = db
      .collection('bogle_users')
      .doc(userId)
      .collection('learned_expressions')
      .doc(expr.id);

    const persisted: PersistedExpression = {
      id: expr.id,
      theme: expr.theme,
      content: expr.content,
      ssml: expr.ssml,
      engagementScore: Math.min(1, expr.usedCount / 10), // Normalize to 0-1
      timesUsed: expr.usedCount,
      lastUsed: new Date().toISOString(),
      createdAt: expr.generatedAt.toISOString(),
    };

    await docRef.set(cleanForFirestore(persisted), { merge: true });
    log.debug(
      { userId, expressionId: expr.id, theme: expr.theme },
      'Persisted high-engagement expression'
    );
  } catch (error) {
    log.warn({ error: String(error), userId }, 'Failed to persist expression');
  }
}

/**
 * Load persisted expressions for a user
 *
 * Call at session start to seed cache with proven expressions.
 * Returns expressions ordered by engagement score (highest first).
 */
export async function loadPersistedExpressions(userId: string): Promise<GeneratedExpression[]> {
  const db = await initFirestore();
  if (!db) return [];

  try {
    const expressionsRef = db
      .collection('bogle_users')
      .doc(userId)
      .collection('learned_expressions');

    const snapshot = await expressionsRef.orderBy('engagementScore', 'desc').limit(20).get();

    if (snapshot.empty) {
      log.debug({ userId }, 'No persisted expressions found');
      return [];
    }

    const expressions: GeneratedExpression[] = snapshot.docs.map((doc) => {
      const data = doc.data() as PersistedExpression;
      return {
        id: data.id,
        theme: data.theme,
        content: data.content,
        ssml: data.ssml,
        context: {
          theme: data.theme,
          momentum: 'cruising',
          turnCount: 5, // Default context for loaded expressions
          emotion: undefined,
          recentTopics: [],
        },
        generatedAt: new Date(data.createdAt),
        usedCount: data.timesUsed,
      };
    });

    log.debug({ userId, count: expressions.length }, 'Loaded persisted expressions');
    return expressions;
  } catch (error) {
    log.warn({ error: String(error), userId }, 'Failed to load persisted expressions');
    return [];
  }
}

/**
 * Flush high-engagement expressions to Firestore before session ends
 */
export async function flushExpressions(userId: string): Promise<void> {
  const cache = expressionCache.get(userId) || [];
  const highEngagement = cache.filter((e) => e.usedCount >= MIN_ENGAGEMENT_FOR_PERSIST);

  for (const expr of highEngagement) {
    await persistExpression(userId, expr);
  }

  if (highEngagement.length > 0) {
    log.debug({ userId, count: highEngagement.length }, 'Flushed high-engagement expressions');
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export default {
  request: requestExpression,
  get: getGeneratedExpression,
  getBest: getBestExpression,
  prewarm: prewarmCache,
  requestEmotional: requestEmotionalExpressions,
  clearCache,
  getStats,
  markEngagement: markExpressionEngagement,
  loadPersisted: loadPersistedExpressions,
  flush: flushExpressions,
};
