#!/bin/bash
# Interactive setup for macOS code signing credentials
# Run this once to configure your signing environment

set -e

echo "═══════════════════════════════════════════════════════════════"
echo "🔐 Ferni macOS Signing Setup"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "This script will help you configure code signing credentials"
echo "for distributing the Ferni Voice macOS app."
echo ""

# Check for existing credentials
if [ -f ~/.ferni-signing ]; then
    echo "⚠️  Existing credentials found at ~/.ferni-signing"
    echo ""
    read -p "Do you want to reconfigure? (y/N): " RECONFIGURE
    if [[ ! "$RECONFIGURE" =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
fi

echo ""
echo "Step 1: Developer ID Certificate"
echo "─────────────────────────────────"
echo ""
echo "You need a 'Developer ID Application' certificate from Apple."
echo ""
echo "Available signing identities on this Mac:"
echo ""
security find-identity -v -p codesigning 2>/dev/null | grep "Developer ID Application" || echo "  (none found)"
echo ""

read -p "Enter your Developer ID (e.g., 'Developer ID Application: Your Name (TEAMID)'): " DEVELOPER_ID

if [ -z "$DEVELOPER_ID" ]; then
    echo ""
    echo "No Developer ID provided. You can get one from:"
    echo "  https://developer.apple.com/account/resources/certificates/list"
    echo ""
    echo "Create a 'Developer ID Application' certificate and install it in Keychain."
    DEVELOPER_ID='Developer ID Application: Your Name (TEAMID)'
fi

echo ""
echo "Step 2: Apple ID"
echo "─────────────────────────────────"
echo ""
echo "Your Apple ID email for notarization."
echo ""

read -p "Enter your Apple ID email: " APPLE_ID

if [ -z "$APPLE_ID" ]; then
    APPLE_ID='your@email.com'
fi

echo ""
echo "Step 3: Team ID"
echo "─────────────────────────────────"
echo ""
echo "Your Apple Developer Team ID (10 characters)."
echo "Find it at: https://developer.apple.com/account → Membership"
echo ""

read -p "Enter your Team ID [XT8W26YE9U]: " TEAM_ID

if [ -z "$TEAM_ID" ]; then
    TEAM_ID='XT8W26YE9U'
fi

echo ""
echo "Step 4: App-Specific Password"
echo "─────────────────────────────────"
echo ""
echo "Create an app-specific password for notarization:"
echo "  1. Go to https://appleid.apple.com"
echo "  2. Sign in → Security → App-Specific Passwords"
echo "  3. Click '+' to generate a new password"
echo "  4. Name it 'Ferni macOS Notarization'"
echo ""

read -sp "Enter your app-specific password (hidden): " APP_PASSWORD
echo ""

if [ -z "$APP_PASSWORD" ]; then
    APP_PASSWORD='xxxx-xxxx-xxxx-xxxx'
fi

# Write credentials file
cat > ~/.ferni-signing << EOF
# Ferni macOS Code Signing Credentials
# Generated by setup-signing.sh on $(date)
#
# Load with: source ~/.ferni-signing
# Then run: ./sign-and-notarize.sh

export FERNI_DEVELOPER_ID='$DEVELOPER_ID'
export FERNI_APPLE_ID='$APPLE_ID'
export FERNI_TEAM_ID='$TEAM_ID'
export FERNI_APP_PASSWORD='$APP_PASSWORD'
EOF

chmod 600 ~/.ferni-signing

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ Configuration saved to ~/.ferni-signing"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "To use these credentials:"
echo ""
echo "  source ~/.ferni-signing"
echo "  ./build.sh"
echo "  ./sign-and-notarize.sh"
echo ""
echo "Or add to your shell profile (~/.zshrc or ~/.bashrc):"
echo ""
echo "  echo 'source ~/.ferni-signing' >> ~/.zshrc"
echo ""

# Verify credentials (optional)
echo "─────────────────────────────────"
read -p "Would you like to verify the configuration? (y/N): " VERIFY

if [[ "$VERIFY" =~ ^[Yy]$ ]]; then
    source ~/.ferni-signing

    echo ""
    echo "Checking signing identity..."
    if security find-identity -v -p codesigning | grep -q "$FERNI_DEVELOPER_ID"; then
        echo "  ✅ Developer ID certificate found in Keychain"
    else
        echo "  ⚠️  Developer ID certificate not found in Keychain"
        echo "      Install it from Apple Developer Portal"
    fi

    echo ""
    echo "Testing notarization credentials..."
    if xcrun notarytool history --apple-id "$FERNI_APPLE_ID" --team-id "$FERNI_TEAM_ID" --password "$FERNI_APP_PASSWORD" &>/dev/null; then
        echo "  ✅ Notarization credentials valid"
    else
        echo "  ⚠️  Notarization credentials may be invalid"
        echo "      Check your Apple ID and app-specific password"
    fi
fi

echo ""
echo "Setup complete! 🎉"
echo ""
