#!/usr/bin/env npx tsx
/**
 * Enable All Feature Flags for E2E Testing
 *
 * This script enables ALL feature flags across the system for comprehensive
 * end-to-end validation. Use with caution in production environments.
 *
 * Usage:
 *   npx tsx scripts/enable-all-flags.ts [options]
 *
 * Options:
 *   --dry-run    Show what would be enabled without making changes
 *   --report     Show current flag status
 *   --reset      Reset all flags to defaults
 *   --save-env   Generate .env.e2e-all-features file
 *
 * Examples:
 *   npm run flags:enable-all
 *   npm run flags:enable-all -- --dry-run
 *   npm run flags:report
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import {
  getFeatureFlags,
  reloadFeatureFlags,
  setFeatureFlagsForTesting,
  type FeatureFlags,
} from '../../../../../src/config/feature-flags.js';
import {
  getFlags as getVoiceFlags,
  resetFlags as resetVoiceFlags,
  updateFlags as updateVoiceFlags,
  type VoiceHumanizationFlags,
} from '../../../../../src/config/voice-humanization-flags.js';
import {
  enableAllTrustFlags,
  getAllFlags,
  resetToDefaults,
} from '../../../../../src/services/feature-flags.js';

// ============================================================================
// ALL FLAGS CONFIGURATION (Maximum E2E Coverage)
// ============================================================================

/**
 * Core feature flags - ALL enabled
 */
const ALL_CORE_FLAGS: FeatureFlags = {
  humanization: {
    enabled: true,
    disfluencies: true,
    backchannels: true,
    emotionMatching: true,
    activeListening: true,
    memoryCallbacks: true,
    followUpQuestions: true,
    speechNaturalization: true,
  },
  debug: {
    agent: true,
    humanizing: true,
    memory: true,
    tools: true,
    handoff: true,
    audio: true,
  },
  experimental: {
    sessionContext: true,
    abTesting: true,
    voiceEmotionDetection: true,
    crossSessionThreading: true,
    proactiveInsights: true,
  },
  audio: {
    musicEnabled: true,
    ambientSounds: true,
    voiceDucking: true,
  },
  integrations: {
    spotify: true,
    googleCalendar: true,
    email: true,
    pushNotifications: true,
  },
  evalops: {
    enabled: true,
    autoSampling: true,
    voiceChecks: true,
    llmEvaluation: true,
    scheduledSuites: true,
    alerting: true,
    sampleRate: 100, // 100% sampling for full coverage
  },
  lifeCoachDomains: {
    enabled: true,
    crisis: true,
    health: true,
    career: true,
    decisions: true,
    family: true,
    home: true,
    learning: true,
    creativity: true,
    community: true,
    legalAdmin: true,
    analytics: true,
  },
};

/**
 * Voice humanization flags - ALL enabled
 */
const ALL_VOICE_FLAGS: VoiceHumanizationFlags = {
  // Phase 1: Foundation
  enableProsodyTurnPrediction: true,
  enableMicroInterruptions: true,
  enableEmotionalArcTts: true,

  // Phase 2: Audio Intelligence
  enableLaughterDetection: true,
  enableAmbientAwareness: true,

  // Phase 3: Advanced
  enableRhythmMirroring: true,
  enableEmotionalContagion: true,
  enableEnhancedVoiceFingerprinting: true,
  enableVoiceAuthentication: true,

  // Phase 4: Advanced Audio Intelligence
  enableFftAnalysis: true,
  enableEnhancedTurnPrediction: true,
  enableMultiSignalLaughter: true,
  enableWordTimingRhythm: true,

  // Phase 5: Preemptive Generation
  enableResponseAnticipation: true,
  useCachedResponses: true, // Usually off in prod
  cacheConfidenceThreshold: 0.5, // Lower threshold for testing

  // Rollout controls
  rolloutPercentage: 100,
  enableVerboseLogging: true,
  enableMetrics: true,
};

// ============================================================================
// ENVIRONMENT FILE GENERATION
// ============================================================================

function generateEnvFile(): string {
  const lines: string[] = [
    '# =============================================================================',
    '# E2E Testing Environment - ALL FEATURES ENABLED',
    '# =============================================================================',
    '# Generated by: npx tsx scripts/enable-all-flags.ts --save-env',
    `# Generated at: ${new Date().toISOString()}`,
    '#',
    '# WARNING: This enables ALL features including experimental ones.',
    '# Use for comprehensive E2E testing only, not production.',
    '# =============================================================================',
    '',
    '# -----------------------------------------------------------------------------',
    '# HUMANIZATION FLAGS',
    '# -----------------------------------------------------------------------------',
    'HUMANIZATION_ENABLED=true',
    'ENABLE_DISFLUENCIES=true',
    'ENABLE_BACKCHANNELS=true',
    'ENABLE_EMOTION_MATCHING=true',
    '',
    '# -----------------------------------------------------------------------------',
    '# DEBUG FLAGS (Enable verbose logging for all systems)',
    '# -----------------------------------------------------------------------------',
    'DEBUG_AGENT=true',
    'DEBUG_HUMANIZING=true',
    'DEBUG_MEMORY=true',
    'DEBUG_TOOLS=true',
    'DEBUG_HANDOFF=true',
    'DEBUG_AUDIO=true',
    '',
    '# -----------------------------------------------------------------------------',
    '# EXPERIMENTAL FLAGS',
    '# -----------------------------------------------------------------------------',
    'EXPERIMENTAL_SESSION_CONTEXT=true',
    'ENABLE_AB_TESTING=true',
    'ENABLE_VOICE_EMOTION=true',
    '',
    '# -----------------------------------------------------------------------------',
    '# AUDIO FLAGS',
    '# -----------------------------------------------------------------------------',
    'ENABLE_MUSIC=true',
    'ENABLE_AMBIENT=true',
    '',
    '# -----------------------------------------------------------------------------',
    '# INTEGRATION FLAGS',
    '# -----------------------------------------------------------------------------',
    'ENABLE_SPOTIFY=true',
    'ENABLE_GOOGLE_CALENDAR=true',
    'ENABLE_EMAIL=true',
    'ENABLE_PUSH_NOTIFICATIONS=true',
    '',
    '# -----------------------------------------------------------------------------',
    '# EVALOPS FLAGS (Quality Evaluation)',
    '# -----------------------------------------------------------------------------',
    'EVALOPS_ENABLED=true',
    'EVALOPS_AUTO_SAMPLING=true',
    'EVALOPS_VOICE_CHECKS=true',
    'EVALOPS_LLM_EVALUATION=true',
    'EVALOPS_SCHEDULED_SUITES=true',
    'EVALOPS_ALERTING=true',
    'EVALOPS_SAMPLE_RATE=100',
    '',
    '# -----------------------------------------------------------------------------',
    '# LIFE COACH DOMAIN FLAGS',
    '# -----------------------------------------------------------------------------',
    'LIFE_COACH_DOMAINS_ENABLED=true',
    'LIFE_COACH_CRISIS=true',
    'LIFE_COACH_HEALTH=true',
    'LIFE_COACH_CAREER=true',
    'LIFE_COACH_DECISIONS=true',
    'LIFE_COACH_FAMILY=true',
    'LIFE_COACH_HOME=true',
    'LIFE_COACH_LEARNING=true',
    'LIFE_COACH_CREATIVITY=true',
    'LIFE_COACH_COMMUNITY=true',
    'LIFE_COACH_LEGAL_ADMIN=true',
    'LIFE_COACH_ANALYTICS=true',
    '',
    '# -----------------------------------------------------------------------------',
    '# VOICE HUMANIZATION FLAGS',
    '# -----------------------------------------------------------------------------',
    '# Phase 1: Foundation',
    'VOICE_HUMANIZATION_ENABLE_PROSODY_TURN_PREDICTION=true',
    'VOICE_HUMANIZATION_ENABLE_MICRO_INTERRUPTIONS=true',
    'VOICE_HUMANIZATION_ENABLE_EMOTIONAL_ARC_TTS=true',
    '',
    '# Phase 2: Audio Intelligence',
    'VOICE_HUMANIZATION_ENABLE_LAUGHTER_DETECTION=true',
    'VOICE_HUMANIZATION_ENABLE_AMBIENT_AWARENESS=true',
    '',
    '# Phase 3: Advanced',
    'VOICE_HUMANIZATION_ENABLE_RHYTHM_MIRRORING=true',
    'VOICE_HUMANIZATION_ENABLE_EMOTIONAL_CONTAGION=true',
    'VOICE_HUMANIZATION_ENABLE_ENHANCED_VOICE_FINGERPRINTING=true',
    'VOICE_HUMANIZATION_ENABLE_VOICE_AUTHENTICATION=true',
    '',
    '# Phase 4: Advanced Audio Intelligence',
    'VOICE_HUMANIZATION_ENABLE_FFT_ANALYSIS=true',
    'VOICE_HUMANIZATION_ENABLE_ENHANCED_TURN_PREDICTION=true',
    'VOICE_HUMANIZATION_ENABLE_MULTI_SIGNAL_LAUGHTER=true',
    'VOICE_HUMANIZATION_ENABLE_WORD_TIMING_RHYTHM=true',
    '',
    '# Phase 5: Preemptive Generation',
    'VOICE_HUMANIZATION_ENABLE_RESPONSE_ANTICIPATION=true',
    'VOICE_HUMANIZATION_USE_CACHED_RESPONSES=true',
    '',
    '# Rollout',
    'VOICE_HUMANIZATION_ROLLOUT_PERCENTAGE=100',
    'VOICE_HUMANIZATION_ENABLE_VERBOSE_LOGGING=true',
    'VOICE_HUMANIZATION_ENABLE_METRICS=true',
    '',
    '# =============================================================================',
    '# USAGE:',
    '#   1. Copy to .env: cp .env.e2e-all-features .env',
    '#   2. Or source before running: source .env.e2e-all-features && npm run dev',
    '#   3. Or use dotenv: node -r dotenv/config --dotenv-path=.env.e2e-all-features',
    '# =============================================================================',
  ];

  return lines.join('\n');
}

// ============================================================================
// REPORTING
// ============================================================================

function printFlagReport(): void {
  console.log('\n📊 CURRENT FEATURE FLAG STATUS\n');
  console.log('═'.repeat(70));

  // Core flags
  const coreFlags = getFeatureFlags();
  console.log('\n🔧 CORE FEATURE FLAGS:\n');

  const printCategory = (name: string, flags: Record<string, boolean | number>) => {
    console.log(`  ${name}:`);
    for (const [key, value] of Object.entries(flags)) {
      const status = value === true ? '✅' : value === false ? '❌' : `📊 ${value}`;
      console.log(`    ${status} ${key}`);
    }
  };

  printCategory('Humanization', coreFlags.humanization);
  printCategory('Debug', coreFlags.debug);
  printCategory('Experimental', coreFlags.experimental);
  printCategory('Audio', coreFlags.audio);
  printCategory('Integrations', coreFlags.integrations);
  printCategory('EvalOps', coreFlags.evalops);
  printCategory('Life Coach Domains', coreFlags.lifeCoachDomains);

  // Trust flags
  console.log('\n\n🤝 TRUST SYSTEM FLAGS:\n');
  const trustFlags = getAllFlags();
  for (const [id, config] of Object.entries(trustFlags)) {
    const status = config.enabled ? '✅' : '❌';
    const pct = config.percentage || 0;
    console.log(`  ${status} ${id} (${pct}%): ${config.description}`);
  }

  // Voice humanization flags
  console.log('\n\n🎙️ VOICE HUMANIZATION FLAGS:\n');
  const voiceFlags = getVoiceFlags();
  for (const [key, value] of Object.entries(voiceFlags)) {
    const status = value === true ? '✅' : value === false ? '❌' : `📊 ${value}`;
    console.log(`  ${status} ${key}`);
  }

  console.log('\n' + '═'.repeat(70));

  // Summary counts
  let enabledCount = 0;
  let disabledCount = 0;

  const countFlags = (obj: Record<string, any>) => {
    for (const value of Object.values(obj)) {
      if (typeof value === 'object' && value !== null) {
        countFlags(value);
      } else if (value === true) {
        enabledCount++;
      } else if (value === false) {
        disabledCount++;
      }
    }
  };

  countFlags(coreFlags);
  countFlags(voiceFlags);

  console.log(`\n📈 SUMMARY: ${enabledCount} enabled, ${disabledCount} disabled\n`);
}

// ============================================================================
// MAIN
// ============================================================================

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const isDryRun = args.includes('--dry-run');
  const isReport = args.includes('--report');
  const isReset = args.includes('--reset');
  const isSaveEnv = args.includes('--save-env');

  console.log('\n🚀 FERNI FEATURE FLAGS MANAGER\n');

  // Report mode
  if (isReport) {
    printFlagReport();
    return;
  }

  // Reset mode
  if (isReset) {
    console.log('🔄 Resetting all flags to defaults...\n');
    if (!isDryRun) {
      await resetToDefaults();
      resetVoiceFlags();
      reloadFeatureFlags();
    }
    console.log(isDryRun ? '(dry run - no changes made)' : '✅ All flags reset to defaults');
    return;
  }

  // Save env mode
  if (isSaveEnv) {
    const envContent = generateEnvFile();
    const envPath = join(process.cwd(), '.env.e2e-all-features');

    if (isDryRun) {
      console.log('📄 Would generate .env.e2e-all-features:\n');
      console.log(envContent);
    } else {
      writeFileSync(envPath, envContent);
      console.log(`✅ Generated: ${envPath}`);
      console.log('\nUsage:');
      console.log('  cp .env.e2e-all-features .env');
      console.log('  # or');
      console.log('  source .env.e2e-all-features && npm run dev');
    }
    return;
  }

  // Enable all mode (default)
  console.log('🔓 ENABLING ALL FEATURE FLAGS FOR E2E TESTING\n');
  console.log('═'.repeat(70));

  if (isDryRun) {
    console.log('\n⚠️  DRY RUN MODE - No changes will be made\n');
  }

  // Count what we're enabling
  const flagCounts = {
    core: 0,
    trust: 0,
    voice: 0,
  };

  // Core flags
  console.log('\n📦 Core Feature Flags:');
  const countAndPrint = (category: string, flags: Record<string, any>) => {
    for (const [key, value] of Object.entries(flags)) {
      if (typeof value === 'boolean' && value === true) {
        flagCounts.core++;
        console.log(`  ✅ ${category}.${key}`);
      } else if (typeof value === 'number') {
        flagCounts.core++;
        console.log(`  📊 ${category}.${key} = ${value}`);
      }
    }
  };

  countAndPrint('humanization', ALL_CORE_FLAGS.humanization);
  countAndPrint('debug', ALL_CORE_FLAGS.debug);
  countAndPrint('experimental', ALL_CORE_FLAGS.experimental);
  countAndPrint('audio', ALL_CORE_FLAGS.audio);
  countAndPrint('integrations', ALL_CORE_FLAGS.integrations);
  countAndPrint('evalops', ALL_CORE_FLAGS.evalops);
  countAndPrint('lifeCoachDomains', ALL_CORE_FLAGS.lifeCoachDomains);

  // Trust flags
  console.log('\n🤝 Trust System Flags:');
  const trustFlagIds = Object.keys(getAllFlags());
  flagCounts.trust = trustFlagIds.length;
  for (const id of trustFlagIds) {
    console.log(`  ✅ ${id} → 100%`);
  }

  // Voice humanization flags
  console.log('\n🎙️ Voice Humanization Flags:');
  for (const [key, value] of Object.entries(ALL_VOICE_FLAGS)) {
    if (typeof value === 'boolean' && value === true) {
      flagCounts.voice++;
      console.log(`  ✅ ${key}`);
    } else if (typeof value === 'number') {
      flagCounts.voice++;
      console.log(`  📊 ${key} = ${value}`);
    }
  }

  console.log('\n' + '═'.repeat(70));
  console.log(
    `\n📈 TOTAL: ${flagCounts.core + flagCounts.trust + flagCounts.voice} flags to enable`
  );
  console.log(`   • Core: ${flagCounts.core}`);
  console.log(`   • Trust: ${flagCounts.trust}`);
  console.log(`   • Voice: ${flagCounts.voice}`);

  if (!isDryRun) {
    console.log('\n⏳ Applying changes...\n');

    // Apply core flags
    setFeatureFlagsForTesting(ALL_CORE_FLAGS);
    console.log('  ✅ Core feature flags enabled');

    // Apply trust flags
    await enableAllTrustFlags();
    console.log('  ✅ Trust system flags enabled (100%)');

    // Apply voice flags
    updateVoiceFlags(ALL_VOICE_FLAGS);
    console.log('  ✅ Voice humanization flags enabled');

    console.log('\n🎉 ALL FLAGS ENABLED FOR E2E TESTING!\n');
    console.log('💡 Tip: Run with --report to verify current status');
    console.log('💡 Tip: Run with --save-env to generate .env file\n');
  } else {
    console.log('\n(dry run complete - no changes made)\n');
  }
}

main().catch((error) => {
  console.error('❌ Error:', error);
  process.exit(1);
});
