/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Library information */
export interface LibraryInfo {
  version: string
  bufferPoolSize: number
  maxFrameSize: number
  defaultSampleRate: number
}
/** Get library information */
export declare function getLibraryInfo(): LibraryInfo
/** Prosody analysis result from a single frame */
export interface NativeProsodyResult {
  /** Current pitch estimate (Hz) */
  pitchHz: number
  /** Pitch confidence (0-1) */
  pitchConfidence: number
  /** Energy in dB */
  energyDb: number
  /** Short-term energy variance */
  energyVariance: number
  /** Zero crossing rate */
  zcr: number
  /** Is speech detected? */
  isSpeech: boolean
  /** Is voiced speech? */
  isVoiced: boolean
  /** Current silence duration (ms) */
  silenceMs: number
  /** Pitch trend: "rising", "falling", "stable" */
  pitchTrend: string
  /** Timestamp of analysis (ms) */
  timestampMs: number
}
/** Full prosody features for end-of-utterance analysis */
export interface NativeFullProsodyFeatures {
  /** Mean pitch (Hz) */
  pitchMean: number
  /** Pitch variance */
  pitchVariance: number
  /** Pitch range (max - min) */
  pitchRange: number
  /** Mean energy (dB) */
  energyMean: number
  /** Energy variance */
  energyVariance: number
  /** Estimated speech rate (syllables/sec approximation) */
  speechRate: number
  /** Total utterance duration (ms) */
  durationMs: number
  /** Speaking ratio (speech time / total time) */
  speakingRatio: number
  /** Number of pauses detected */
  pauseCount: number
}
/** Processor statistics */
export interface NativeProcessorStats {
  totalSamples: number
  analysisCount: number
  bufferFillLevel: number
  isInSpeech: boolean
  currentSilenceMs: number
}
/**
 * Get or create a processor for a session (global registry)
 *
 * Use this for simpler session management where you don't want
 * to hold a reference to the NativeAudioProcessor object.
 */
export declare function getOrCreateProcessor(sessionId: string, sampleRate?: number | undefined | null): boolean
/** Process a frame using the session registry */
export declare function processSessionFrame(sessionId: string, samples: Int16Array, timestampMs: number): NativeProsodyResult | null
/** Get full features from session registry */
export declare function getSessionFullFeatures(sessionId: string): NativeFullProsodyFeatures | null
/** Reset a session processor */
export declare function resetSessionProcessor(sessionId: string): boolean
/** Remove a session processor */
export declare function removeSessionProcessor(sessionId: string): boolean
/** Get count of active session processors */
export declare function getActiveProcessorCount(): number
/** Clear all session processors (for emergency cleanup) */
export declare function clearAllProcessors(): number
/**
 * Convert Int16 samples to Float32 (standalone function)
 *
 * For when you just need conversion without full processing.
 */
export declare function convertI16ToF32(samples: Int16Array): Float32Array
/** Compute energy in dB for a Float32 audio buffer */
export declare function computeEnergyDb(samples: Float32Array): number
/** Check if audio contains speech (simple threshold check) */
export declare function isSpeech(samples: Float32Array, thresholdDb?: number | undefined | null): boolean
/**
 * Compute RMS (Root Mean Square) energy for a Float32 audio buffer
 *
 * Returns linear scale RMS (not dB). Use this for breath detection
 * and energy analysis where linear comparison is needed.
 */
export declare function computeRms(samples: Float32Array): number
/**
 * Compute Zero Crossing Rate for a Float32 audio buffer
 *
 * Returns a value between 0 and 1 indicating how often the signal
 * crosses zero. High ZCR often indicates unvoiced/breathy sounds,
 * low ZCR indicates voiced speech.
 */
export declare function computeZcr(samples: Float32Array): number
/**
 * Compute variance of a Float32 array
 *
 * Useful for pitch variance, energy variance calculations.
 */
export declare function computeVariance(values: Float32Array): number
/** Compute mean of a Float32 array */
export declare function computeMean(values: Float32Array): number
/** Compute standard deviation of a Float32 array */
export declare function computeStdDev(values: Float32Array): number
/** Pitch estimation result */
export interface PitchEstimateResult {
  /** Estimated pitch in Hz (0 if no voiced speech detected) */
  pitchHz: number
  /** Confidence of pitch estimate (0-1) */
  confidence: number
}
/**
 * Estimate pitch using autocorrelation
 *
 * Standalone pitch estimation for single audio frames.
 * Uses autocorrelation with normalized confidence.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples (normalized -1 to 1)
 * * `sample_rate` - Sample rate in Hz (typically 16000)
 * * `min_pitch` - Minimum pitch to detect in Hz (default: 50)
 * * `max_pitch` - Maximum pitch to detect in Hz (default: 500)
 *
 * # Returns
 * Pitch estimate with confidence, or { pitch_hz: 0, confidence: 0 } if no pitch detected
 */
export declare function estimatePitch(samples: Float32Array, sampleRate: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): PitchEstimateResult
/**
 * Extract full prosody features from a single frame
 *
 * Combines pitch, energy, and ZCR analysis.
 * More efficient than calling individual functions separately.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples
 * * `sample_rate` - Sample rate in Hz
 * * `timestamp_ms` - Current timestamp in milliseconds
 */
export interface FrameFeaturesResult {
  pitchHz: number
  pitchConfidence: number
  energyDb: number
  energyRms: number
  zcr: number
  isSpeech: boolean
  isVoiced: boolean
  timestampMs: number
}
export declare function extractFrameFeatures(samples: Float32Array, sampleRate: number, timestampMs: number): FrameFeaturesResult
/** FFT result containing real and imaginary parts */
export interface FftResult {
  real: Array<number>
  imaginary: Array<number>
  size: number
}
/**
 * Apply FFT to a Float32Array signal
 *
 * Returns complex frequency domain representation.
 * Signal is zero-padded to next power of 2 if needed.
 */
export declare function fftF32(samples: Float32Array): FftResult
/** Apply Hanning window to reduce spectral leakage */
export declare function applyHanningWindow(samples: Float32Array): Float32Array
/**
 * Get magnitude spectrum from FFT result
 *
 * Only returns first half (up to Nyquist frequency)
 */
export declare function getMagnitudeSpectrum(real: Array<number>, imaginary: Array<number>): Float32Array
/** Get power spectrum in dB */
export declare function getPowerSpectrumDb(real: Array<number>, imaginary: Array<number>, reference?: number | undefined | null): Float32Array
/**
 * Spectral analysis result
 * Field names match TypeScript NativeSpectralFeatures interface for seamless integration
 */
export interface SpectralFeatures {
  /** Spectral centroid (brightness) in Hz */
  centroid: number
  /** Spectral rolloff (85%) in Hz */
  rolloff: number
  /** Dominant frequency in Hz */
  dominantFrequency: number
  /** Magnitude at dominant frequency */
  dominantMagnitude: number
  /** Band energies (sub-bass, bass, low-mid, mid, high-mid, presence, brilliance) */
  bandEnergies: Array<number>
}
/**
 * Analyze spectral features of an audio signal
 *
 * Performs FFT and computes spectral centroid, rolloff, dominant frequency, and band energies.
 */
export declare function analyzeSpectrum(samples: Float32Array, sampleRate: number, minFreq?: number | undefined | null, maxFreq?: number | undefined | null): SpectralFeatures
/** Clear FFT caches (for memory management) */
export declare function clearFftCaches(): void
/** Configuration for post-TTS audio enhancement */
export interface PostTtsEnhancementConfig {
  /** Sample rate (typically 24000 or 44100 for Cartesia) */
  sampleRate: number
  /** Enable breath injection at phrase starts */
  enableBreath: boolean
  /** Enable spectral warmth enhancement */
  enableWarmth: boolean
  /** Enable micro-pitch modulation */
  enableMicroPitch: boolean
  /** Enable soft attack/release on phrases */
  enableSoftEdges: boolean
  /** Enable light compression */
  enableCompression: boolean
  /** Enable presence EQ boost (2-4kHz clarity) */
  enablePresence: boolean
  /** Breath injection probability (0.0-1.0, default 0.3) */
  breathProbability: number
  /** Warmth amount (0.0-1.0, default 0.15) */
  warmthAmount: number
  /** Pitch modulation depth in cents (default 8) */
  pitchModulationCents: number
  /** Soft edge duration in ms (default 20) */
  softEdgeMs: number
  /** Compression ratio (default 2.0) */
  compressionRatio: number
  /** Compression threshold in dB (default -20) */
  compressionThresholdDb: number
  /** Presence boost in dB (default 2.5) */
  presenceBoostDb: number
}
/** Result of post-TTS enhancement */
export interface PostTtsEnhancementResult {
  /** Number of breaths injected */
  breathsInjected: number
  /** Number of phrase edges softened */
  edgesSoftened: number
  /** Was warmth applied */
  warmthApplied: boolean
  /** Was pitch modulation applied */
  pitchModApplied: boolean
  /** Was compression applied */
  compressionApplied: boolean
  /** Was presence boost applied */
  presenceApplied: boolean
}
/** Get default post-TTS enhancement configuration */
export declare function getDefaultPostTtsConfig(): PostTtsEnhancementConfig
/**
 * Apply full post-TTS enhancement pipeline to TTS output
 *
 * This is the main entry point for "Better Than Human" audio processing.
 * Applies breath injection, spectral warmth, micro-pitch modulation,
 * soft attack/release, compression, and presence boost.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples from Cartesia TTS
 * * `config` - Enhancement configuration
 *
 * # Returns
 * Enhancement result with stats about what was applied
 */
export declare function enhanceTtsAudio(samples: Float32Array, config: PostTtsEnhancementConfig): PostTtsEnhancementResult
/**
 * Apply full post-TTS enhancement and return enhanced audio
 *
 * Same as enhance_tts_audio but returns the modified samples.
 * Use this when you need the enhanced audio data back.
 */
export declare function enhanceTtsAudioInplace(samples: Float32Array, config: PostTtsEnhancementConfig): Float32Array
/**
 * Apply soft attack (fade-in) to audio start
 *
 * Creates a smooth, natural-sounding start instead of abrupt onset.
 */
export declare function applySoftAttack(samples: Float32Array, attackMs: number, sampleRate: number): Float32Array
/**
 * Apply soft release (fade-out) to audio end
 *
 * Creates a smooth, natural-sounding end instead of abrupt cutoff.
 */
export declare function applySoftRelease(samples: Float32Array, releaseMs: number, sampleRate: number): Float32Array
/**
 * Apply spectral warmth enhancement
 *
 * Boosts low frequencies for a warmer, more intimate voice quality.
 */
export declare function applyWarmth(samples: Float32Array, sampleRate: number, amount: number): Float32Array
/**
 * Apply presence boost (2-4kHz)
 *
 * Enhances clarity and intelligibility without harshness.
 */
export declare function applyPresence(samples: Float32Array, sampleRate: number, boostDb: number): Float32Array
/**
 * Apply light dynamic compression
 *
 * Evens out volume dynamics for consistent listening experience.
 */
export declare function applyCompression(samples: Float32Array, sampleRate: number, thresholdDb: number, ratio: number): Float32Array
/**
 * Inject breath sounds at phrase boundaries
 *
 * Returns the number of breaths injected.
 */
export declare function injectBreathSounds(samples: Float32Array, sampleRate: number, probability: number): number
/**
 * Native audio processor for real-time voice analysis
 *
 * Pre-allocates all buffers at construction for zero per-frame allocations.
 */
export declare class NativeAudioProcessor {
  /**
   * Create a new audio processor for a session
   *
   * # Arguments
   * * `session_id` - Unique session identifier for debugging
   * * `sample_rate` - Audio sample rate (default: 16000)
   */
  constructor(sessionId: string, sampleRate?: number | undefined | null)
  /**
   * Process an Int16 audio frame
   *
   * This is the main entry point for LiveKit audio frames.
   * Uses pre-allocated buffers for zero per-frame allocations.
   *
   * # Arguments
   * * `samples` - Int16Array audio samples from LiveKit
   * * `timestamp_ms` - Current timestamp in milliseconds
   *
   * # Returns
   * Prosody features if enough data is available, None otherwise
   */
  processFrame(samples: Int16Array, timestampMs: number): NativeProsodyResult | null
  /**
   * Process a Float32 audio frame
   *
   * Use this if samples are already normalized floats.
   */
  processFrameF32(samples: Float32Array, timestampMs: number): NativeProsodyResult | null
  /** Get full prosody features for end-of-utterance analysis */
  getFullFeatures(): NativeFullProsodyFeatures
  /** Get processor statistics */
  getStats(): NativeProcessorStats
  /**
   * Reset processor for reuse
   *
   * Clears all state but keeps pre-allocated buffers.
   */
  reset(): void
  /** Get session ID */
  get sessionId(): string
}
