/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'ferni-audio.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.android-arm64.node')
          } else {
            nativeBinding = require('@ferni/audio-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'ferni-audio.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.android-arm-eabi.node')
          } else {
            nativeBinding = require('@ferni/audio-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-audio.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@ferni/audio-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-audio.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@ferni/audio-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-audio.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@ferni/audio-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'ferni-audio.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./ferni-audio.darwin-universal.node')
      } else {
        nativeBinding = require('@ferni/audio-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'ferni-audio.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.darwin-x64.node')
          } else {
            nativeBinding = require('@ferni/audio-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-audio.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.darwin-arm64.node')
          } else {
            nativeBinding = require('@ferni/audio-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'ferni-audio.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./ferni-audio.freebsd-x64.node')
      } else {
        nativeBinding = require('@ferni/audio-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-x64-musl.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-audio.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-audio.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@ferni/audio-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-audio.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-audio.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@ferni/audio-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { NativeWhisperStt, transcribeWhisper, estimatePitchYin, batchEstimatePitchYin, getLibraryInfo, NativeAudioProcessor, getOrCreateProcessor, processSessionFrame, getSessionFullFeatures, resetSessionProcessor, removeSessionProcessor, getActiveProcessorCount, clearAllProcessors, convertI16ToF32, resampleF32, computeEnergyDb, isSpeech, computeRms, computeZcr, computeVariance, computeMean, computeStdDev, estimatePitch, extractFrameFeatures, fftF32, applyHanningWindow, getMagnitudeSpectrum, getPowerSpectrumDb, analyzeSpectrum, clearFftCaches, getDefaultPostTtsConfig, enhanceTtsAudio, enhanceTtsAudioInplace, applySoftAttack, applySoftRelease, applyWarmth, applyPresence, applyCompression, injectBreathSounds, NativePostTtsProcessor, NativePreSttProcessor, applyAgc, resetAgc, removeAgc } = nativeBinding

module.exports.NativeWhisperStt = NativeWhisperStt
module.exports.transcribeWhisper = transcribeWhisper
module.exports.estimatePitchYin = estimatePitchYin
module.exports.batchEstimatePitchYin = batchEstimatePitchYin
module.exports.getLibraryInfo = getLibraryInfo
module.exports.NativeAudioProcessor = NativeAudioProcessor
module.exports.getOrCreateProcessor = getOrCreateProcessor
module.exports.processSessionFrame = processSessionFrame
module.exports.getSessionFullFeatures = getSessionFullFeatures
module.exports.resetSessionProcessor = resetSessionProcessor
module.exports.removeSessionProcessor = removeSessionProcessor
module.exports.getActiveProcessorCount = getActiveProcessorCount
module.exports.clearAllProcessors = clearAllProcessors
module.exports.convertI16ToF32 = convertI16ToF32
module.exports.resampleF32 = resampleF32
module.exports.computeEnergyDb = computeEnergyDb
module.exports.isSpeech = isSpeech
module.exports.computeRms = computeRms
module.exports.computeZcr = computeZcr
module.exports.computeVariance = computeVariance
module.exports.computeMean = computeMean
module.exports.computeStdDev = computeStdDev
module.exports.estimatePitch = estimatePitch
module.exports.extractFrameFeatures = extractFrameFeatures
module.exports.fftF32 = fftF32
module.exports.applyHanningWindow = applyHanningWindow
module.exports.getMagnitudeSpectrum = getMagnitudeSpectrum
module.exports.getPowerSpectrumDb = getPowerSpectrumDb
module.exports.analyzeSpectrum = analyzeSpectrum
module.exports.clearFftCaches = clearFftCaches
module.exports.getDefaultPostTtsConfig = getDefaultPostTtsConfig
module.exports.enhanceTtsAudio = enhanceTtsAudio
module.exports.enhanceTtsAudioInplace = enhanceTtsAudioInplace
module.exports.applySoftAttack = applySoftAttack
module.exports.applySoftRelease = applySoftRelease
module.exports.applyWarmth = applyWarmth
module.exports.applyPresence = applyPresence
module.exports.applyCompression = applyCompression
module.exports.injectBreathSounds = injectBreathSounds
module.exports.NativePostTtsProcessor = NativePostTtsProcessor
module.exports.NativePreSttProcessor = NativePreSttProcessor
module.exports.applyAgc = applyAgc
module.exports.resetAgc = resetAgc
module.exports.removeAgc = removeAgc
