/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** YIN pitch estimation result for NAPI */
export interface NativeYinResult {
  /** Estimated pitch in Hz (0 if no voiced speech detected) */
  pitchHz: number
  /** Confidence of pitch estimate (0-1) */
  confidence: number
  /** Best period in samples */
  periodSamples: number
}
/**
 * Estimate pitch using YIN algorithm (standalone function)
 *
 * This is ~40x faster than naive autocorrelation for pitch detection.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples (normalized -1 to 1)
 * * `sample_rate` - Sample rate in Hz
 * * `min_pitch` - Minimum pitch to detect (default: 50 Hz)
 * * `max_pitch` - Maximum pitch to detect (default: 500 Hz)
 *
 * # Returns
 * Pitch estimate with frequency, confidence, and period
 */
export declare function estimatePitchYin(samples: Float32Array, sampleRate: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): NativeYinResult
/**
 * Batch pitch estimation using YIN
 *
 * Process multiple frames efficiently for utterance-level analysis
 */
export declare function batchEstimatePitchYin(samples: Float32Array, sampleRate: number, frameSize: number, hopSize: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): Array<NativeYinResult>
/** Library information */
export interface LibraryInfo {
  version: string
  bufferPoolSize: number
  maxFrameSize: number
  defaultSampleRate: number
}
/** Get library information */
export declare function getLibraryInfo(): LibraryInfo
/** Prosody analysis result from a single frame */
export interface NativeProsodyResult {
  /** Current pitch estimate (Hz) */
  pitchHz: number
  /** Pitch confidence (0-1) */
  pitchConfidence: number
  /** Energy in dB */
  energyDb: number
  /** Short-term energy variance */
  energyVariance: number
  /** Zero crossing rate */
  zcr: number
  /** Is speech detected? */
  isSpeech: boolean
  /** Is voiced speech? */
  isVoiced: boolean
  /** Current silence duration (ms) */
  silenceMs: number
  /** Pitch trend: "rising", "falling", "stable" */
  pitchTrend: string
  /** Timestamp of analysis (ms) */
  timestampMs: number
}
/** Full prosody features for end-of-utterance analysis */
export interface NativeFullProsodyFeatures {
  /** Mean pitch (Hz) */
  pitchMean: number
  /** Pitch variance */
  pitchVariance: number
  /** Pitch range (max - min) */
  pitchRange: number
  /** Mean energy (dB) */
  energyMean: number
  /** Energy variance */
  energyVariance: number
  /** Estimated speech rate (syllables/sec approximation) */
  speechRate: number
  /** Total utterance duration (ms) */
  durationMs: number
  /** Speaking ratio (speech time / total time) */
  speakingRatio: number
  /** Number of pauses detected */
  pauseCount: number
}
/** Processor statistics */
export interface NativeProcessorStats {
  totalSamples: number
  analysisCount: number
  bufferFillLevel: number
  isInSpeech: boolean
  currentSilenceMs: number
}
/**
 * Get or create a processor for a session (global registry)
 *
 * Use this for simpler session management where you don't want
 * to hold a reference to the NativeAudioProcessor object.
 */
export declare function getOrCreateProcessor(sessionId: string, sampleRate?: number | undefined | null): boolean
/** Process a frame using the session registry */
export declare function processSessionFrame(sessionId: string, samples: Int16Array, timestampMs: number): NativeProsodyResult | null
/** Get full features from session registry */
export declare function getSessionFullFeatures(sessionId: string): NativeFullProsodyFeatures | null
/** Reset a session processor */
export declare function resetSessionProcessor(sessionId: string): boolean
/** Remove a session processor */
export declare function removeSessionProcessor(sessionId: string): boolean
/** Get count of active session processors */
export declare function getActiveProcessorCount(): number
/** Clear all session processors (for emergency cleanup) */
export declare function clearAllProcessors(): number
/**
 * Convert Int16 samples to Float32 (standalone function)
 *
 * SIMD-accelerated: processes 8 samples at a time using f32x8.
 * For when you just need conversion without full processing.
 */
export declare function convertI16ToF32(samples: Int16Array): Float32Array
/**
 * Compute energy in dB for a Float32 audio buffer
 *
 * SIMD-accelerated: processes 8 samples at a time for sum-of-squares.
 */
export declare function computeEnergyDb(samples: Float32Array): number
/** Check if audio contains speech (simple threshold check) */
export declare function isSpeech(samples: Float32Array, thresholdDb?: number | undefined | null): boolean
/**
 * Compute RMS (Root Mean Square) energy for a Float32 audio buffer
 *
 * SIMD-accelerated: processes 8 samples at a time for sum-of-squares.
 * Returns linear scale RMS (not dB). Use this for breath detection
 * and energy analysis where linear comparison is needed.
 */
export declare function computeRms(samples: Float32Array): number
/**
 * Compute Zero Crossing Rate for a Float32 audio buffer
 *
 * Returns a value between 0 and 1 indicating how often the signal
 * crosses zero. High ZCR often indicates unvoiced/breathy sounds,
 * low ZCR indicates voiced speech.
 */
export declare function computeZcr(samples: Float32Array): number
/**
 * Compute variance of a Float32 array
 *
 * SIMD-accelerated: uses two-pass algorithm with SIMD sum and squared-diff.
 * Useful for pitch variance, energy variance calculations.
 */
export declare function computeVariance(values: Float32Array): number
/**
 * Compute mean of a Float32 array
 *
 * SIMD-accelerated: processes 8 samples at a time.
 */
export declare function computeMean(values: Float32Array): number
/** Compute standard deviation of a Float32 array */
export declare function computeStdDev(values: Float32Array): number
/** Pitch estimation result */
export interface PitchEstimateResult {
  /** Estimated pitch in Hz (0 if no voiced speech detected) */
  pitchHz: number
  /** Confidence of pitch estimate (0-1) */
  confidence: number
}
/**
 * Estimate pitch using autocorrelation
 *
 * Standalone pitch estimation for single audio frames.
 * Uses autocorrelation with normalized confidence.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples (normalized -1 to 1)
 * * `sample_rate` - Sample rate in Hz (typically 16000)
 * * `min_pitch` - Minimum pitch to detect in Hz (default: 50)
 * * `max_pitch` - Maximum pitch to detect in Hz (default: 500)
 *
 * # Returns
 * Pitch estimate with confidence, or { pitch_hz: 0, confidence: 0 } if no pitch detected
 */
export declare function estimatePitch(samples: Float32Array, sampleRate: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): PitchEstimateResult
/**
 * Extract full prosody features from a single frame
 *
 * Combines pitch, energy, and ZCR analysis.
 * More efficient than calling individual functions separately.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples
 * * `sample_rate` - Sample rate in Hz
 * * `timestamp_ms` - Current timestamp in milliseconds
 */
export interface FrameFeaturesResult {
  pitchHz: number
  pitchConfidence: number
  energyDb: number
  energyRms: number
  zcr: number
  isSpeech: boolean
  isVoiced: boolean
  timestampMs: number
}
export declare function extractFrameFeatures(samples: Float32Array, sampleRate: number, timestampMs: number): FrameFeaturesResult
/** FFT result containing real and imaginary parts */
export interface FftResult {
  real: Array<number>
  imaginary: Array<number>
  size: number
}
/**
 * Apply FFT to a Float32Array signal
 *
 * Returns complex frequency domain representation.
 * Signal is zero-padded to next power of 2 if needed.
 */
export declare function fftF32(samples: Float32Array): FftResult
/** Apply Hanning window to reduce spectral leakage */
export declare function applyHanningWindow(samples: Float32Array): Float32Array
/**
 * Get magnitude spectrum from FFT result
 *
 * Only returns first half (up to Nyquist frequency)
 */
export declare function getMagnitudeSpectrum(real: Array<number>, imaginary: Array<number>): Float32Array
/** Get power spectrum in dB */
export declare function getPowerSpectrumDb(real: Array<number>, imaginary: Array<number>, reference?: number | undefined | null): Float32Array
/**
 * Spectral analysis result
 * Field names match TypeScript NativeSpectralFeatures interface for seamless integration
 */
export interface SpectralFeatures {
  /** Spectral centroid (brightness) in Hz */
  centroid: number
  /** Spectral rolloff (85%) in Hz */
  rolloff: number
  /** Dominant frequency in Hz */
  dominantFrequency: number
  /** Magnitude at dominant frequency */
  dominantMagnitude: number
  /** Band energies (sub-bass, bass, low-mid, mid, high-mid, presence, brilliance) */
  bandEnergies: Array<number>
}
/**
 * Analyze spectral features of an audio signal
 *
 * Performs FFT and computes spectral centroid, rolloff, dominant frequency, and band energies.
 */
export declare function analyzeSpectrum(samples: Float32Array, sampleRate: number, minFreq?: number | undefined | null, maxFreq?: number | undefined | null): SpectralFeatures
/** Clear FFT caches (for memory management) */
export declare function clearFftCaches(): void
/** Configuration for post-TTS audio enhancement */
export interface PostTtsEnhancementConfig {
  /** Sample rate (typically 24000 or 44100 for Cartesia) */
  sampleRate: number
  /** Enable breath injection at phrase starts */
  enableBreath: boolean
  /** Enable spectral warmth enhancement */
  enableWarmth: boolean
  /** Enable micro-pitch modulation */
  enableMicroPitch: boolean
  /** Enable soft attack/release on phrases */
  enableSoftEdges: boolean
  /** Enable light compression */
  enableCompression: boolean
  /** Enable presence EQ boost (2-4kHz clarity) */
  enablePresence: boolean
  /** Breath injection probability (0.0-1.0, default 0.3) */
  breathProbability: number
  /** Warmth amount (0.0-1.0, default 0.15) */
  warmthAmount: number
  /** Pitch modulation depth in cents (default 8) */
  pitchModulationCents: number
  /** Soft edge duration in ms (default 20) */
  softEdgeMs: number
  /** Compression ratio (default 2.0) */
  compressionRatio: number
  /** Compression threshold in dB (default -20) */
  compressionThresholdDb: number
  /** Presence boost in dB (default 2.5) */
  presenceBoostDb: number
}
/** Result of post-TTS enhancement */
export interface PostTtsEnhancementResult {
  /** Number of breaths injected */
  breathsInjected: number
  /** Number of phrase edges softened */
  edgesSoftened: number
  /** Was warmth applied */
  warmthApplied: boolean
  /** Was pitch modulation applied */
  pitchModApplied: boolean
  /** Was compression applied */
  compressionApplied: boolean
  /** Was presence boost applied */
  presenceApplied: boolean
}
/** Get default post-TTS enhancement configuration */
export declare function getDefaultPostTtsConfig(): PostTtsEnhancementConfig
/**
 * Apply full post-TTS enhancement pipeline to TTS output
 *
 * This is the main entry point for "Better Than Human" audio processing.
 * Applies breath injection, spectral warmth, micro-pitch modulation,
 * soft attack/release, compression, and presence boost.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples from Cartesia TTS
 * * `config` - Enhancement configuration
 *
 * # Returns
 * Enhancement result with stats about what was applied
 */
export declare function enhanceTtsAudio(samples: Float32Array, config: PostTtsEnhancementConfig): PostTtsEnhancementResult
/**
 * Apply full post-TTS enhancement and return enhanced audio
 *
 * Same as enhance_tts_audio but returns the modified samples.
 * Use this when you need the enhanced audio data back.
 */
export declare function enhanceTtsAudioInplace(samples: Float32Array, config: PostTtsEnhancementConfig): Float32Array
/**
 * Apply soft attack (fade-in) to audio start
 *
 * Creates a smooth, natural-sounding start instead of abrupt onset.
 */
export declare function applySoftAttack(samples: Float32Array, attackMs: number, sampleRate: number): Float32Array
/**
 * Apply soft release (fade-out) to audio end
 *
 * Creates a smooth, natural-sounding end instead of abrupt cutoff.
 */
export declare function applySoftRelease(samples: Float32Array, releaseMs: number, sampleRate: number): Float32Array
/**
 * Apply spectral warmth enhancement
 *
 * Boosts low frequencies for a warmer, more intimate voice quality.
 */
export declare function applyWarmth(samples: Float32Array, sampleRate: number, amount: number): Float32Array
/**
 * Apply presence boost (2-4kHz)
 *
 * Enhances clarity and intelligibility without harshness.
 */
export declare function applyPresence(samples: Float32Array, sampleRate: number, boostDb: number): Float32Array
/**
 * Apply light dynamic compression
 *
 * Evens out volume dynamics for consistent listening experience.
 */
export declare function applyCompression(samples: Float32Array, sampleRate: number, thresholdDb: number, ratio: number): Float32Array
/**
 * Inject breath sounds at phrase boundaries
 *
 * Returns the number of breaths injected.
 */
export declare function injectBreathSounds(samples: Float32Array, sampleRate: number, probability: number): number
/**
 * JavaScript-compatible phrase boundary for adaptive breath timing
 *
 * Represents a location in the audio where a breath could naturally be injected.
 */
export interface NativePhraseBoundary {
  /** Sample index (absolute position in the utterance) */
  sampleIndex: number
  /** Boundary type: 0=SentenceEnd, 1=ClauseBreak, 2=EmphasisBefore, 3=EmotionalRelease */
  boundaryType: number
}
/** Configuration for the stateful post-TTS processor */
export interface NativePostTtsConfig {
  /** Sample rate in Hz (default: 24000) */
  sampleRate?: number
  /** Enable warmth (low-shelf EQ boost) */
  enableWarmth?: boolean
  /** Warmth frequency in Hz (default: 300) */
  warmthFreq?: number
  /** Warmth gain in dB (default: 2.5) */
  warmthGainDb?: number
  /** Enable presence (peak EQ boost) */
  enablePresence?: boolean
  /** Presence frequency in Hz (default: 3000) */
  presenceFreq?: number
  /** Presence gain in dB (default: 2.0) */
  presenceGainDb?: number
  /** Enable compression */
  enableCompression?: boolean
  /** Compression threshold in dB (default: -18) */
  compThresholdDb?: number
  /** Compression ratio (default: 2.0) */
  compRatio?: number
  /** Compression attack in ms (default: 10) */
  compAttackMs?: number
  /** Compression release in ms (default: 100) */
  compReleaseMs?: number
  /** Enable de-esser (legacy wideband - DEPRECATED) */
  enableDeesser?: boolean
  /** De-esser frequency in Hz (default: 6000) */
  deesserFreq?: number
  /** De-esser threshold in dB (default: -20) */
  deesserThresholdDb?: number
  /** Enable split-band de-esser (NEW - professional quality) */
  enableSplitbandDeesser?: boolean
  /** Split-band crossover frequency in Hz (default: 5000) */
  splitbandCrossoverFreq?: number
  /** Split-band threshold in dB (default: -20) */
  splitbandThresholdDb?: number
  /** Split-band ratio (default: 4.0) */
  splitbandRatio?: number
  /** Enable limiter */
  enableLimiter?: boolean
  /** Limiter threshold in dB (default: -1) */
  limiterThresholdDb?: number
  /** Enable crossfade between frames */
  enableCrossfade?: boolean
  /** Crossfade length in ms (default: 2) */
  crossfadeMs?: number
  /** Soft attack duration in ms (default: 15) */
  softAttackMs?: number
  /** Soft release duration in ms (default: 15) */
  softReleaseMs?: number
  /** Enable breath injection at utterance start */
  enableBreath?: boolean
  /** Breath injection probability (0-1) */
  breathProbability?: number
  /** Enable micro-pitch modulation (~5Hz wobble) */
  enableMicroPitch?: boolean
  /** Micro-pitch modulation depth in cents */
  microPitchCents?: number
  /** Enable noise floor (subtle room tone) */
  enableNoiseFloor?: boolean
  /** Noise floor level in dB (typically -60 to -50) */
  noiseFloorDb?: number
  /** Enable amplitude jitter (volume micro-variations) */
  enableAmplitudeJitter?: boolean
  /** Amplitude jitter depth (0-1, typically 0.015) */
  amplitudeJitterDepth?: number
  /** Enable pitch drift (slow pitch wandering) */
  enablePitchDrift?: boolean
  /** Pitch drift max in cents */
  pitchDriftCents?: number
  /**
   * Use SOLA-based pitch shifting (artifact-free)
   * When true (default), uses proper overlap-add algorithm instead of
   * frame-by-frame resampling. This eliminates clicks/crackles from pitch features.
   */
  useSolaPitch?: boolean
  /**
   * Enable emotion-aware prosody (affects vibrato, pitch drift, breath, pacing)
   * When true (default), the processor adapts all humanization features based on
   * the emotional context of the utterance.
   */
  enableEmotionProsody?: boolean
  /**
   * Current emotional state (0-8)
   * 0=Neutral, 1=Happy, 2=Sad, 3=Excited, 4=Calm, 5=Tense, 6=Empathetic, 7=Curious, 8=Supportive
   * This affects vibrato rate/depth, pitch drift direction, breath likelihood, and tempo.
   */
  emotion?: number
  /**
   * Enable adaptive pacing (time-stretch based on content complexity)
   * When true, speech rate adjusts to help comprehension of complex content.
   */
  enableAdaptivePacing?: boolean
  /**
   * Content complexity (0.0-1.0)
   * 0.0 = simple content (slightly faster pace)
   * 0.5 = moderate complexity (normal pace)
   * 1.0 = complex content (slower pace for comprehension)
   */
  contentComplexity?: number
  /**
   * Enable vocal fry (creaky voice at phrase endings)
   * Creates natural trailing-off quality like human speakers
   */
  enableVocalFry?: boolean
  /**
   * Vocal fry depth (0-1, default: 0.4)
   * How pronounced the creaky modulation is
   */
  vocalFryDepth?: number
  /**
   * Vocal fry duration in ms (default: 200)
   * How long the creaky effect lasts at phrase end
   */
  vocalFryDurationMs?: number
  /**
   * Enable lip smacks (mouth sounds between phrases)
   * Adds realistic mouth noises at natural pause points
   */
  enableLipSmacks?: boolean
  /**
   * Lip smack probability (0-1, default: 0.3)
   * Probability of triggering at each phrase boundary
   */
  lipSmackProbability?: number
  /**
   * Enable tempo micro-variation (subtle speed changes)
   * Creates natural rhythm variations within utterances
   */
  enableTempoVariation?: boolean
  /**
   * Tempo variation depth (0-1, default: 0.03)
   * How much the tempo can vary (3% typical for natural speech)
   */
  tempoVariationDepth?: number
  /**
   * Enable onset softening (micro-fades on hard glottal attacks)
   * Reduces harsh vowel-initial sounds for more natural speech
   */
  enableOnsetSoftening?: boolean
}
/** Statistics from processing a frame */
export interface NativeProcessingStats {
  frameNumber: number
  crossfadeApplied: boolean
  softAttackApplied: boolean
  softReleaseApplied: boolean
  warmthApplied: boolean
  presenceApplied: boolean
  compressionReductionDb: number
  deesserReductionDb: number
  limiterReductionDb: number
}
/** Configuration for Pre-STT audio processing */
export interface NativePreSttConfig {
  /** Sample rate of input audio (default: 16000) */
  sampleRate?: number
  /** Enable AGC (Automatic Gain Control) */
  enableAgc?: boolean
  /** Enable noise suppression */
  enableNoiseSuppression?: boolean
  /** Enable high-pass filter (DC removal) */
  enableHighpass?: boolean
  /** High-pass cutoff frequency in Hz (default: 80) */
  highpassCutoffHz?: number
  /** Enable bandwidth extension (for 8kHz input) */
  enableBandwidthExtension?: boolean
  /** Input is 8kHz (Twilio) - enables bandwidth extension */
  inputIs8Khz?: boolean
}
/** Statistics from Pre-STT processing */
export interface NativePreSttStats {
  /** Number of frames processed */
  framesProcessed: number
  /** Current AGC gain (1.0 = no change) */
  agcGain: number
  /** Whether noise suppression is ready (has noise floor estimate) */
  noiseSuppressionReady: boolean
  /** Whether bandwidth extension was applied this frame */
  bandwidthExtended: boolean
}
/**
 * Apply AGC to audio samples (standalone function)
 *
 * Creates/reuses a session-scoped AGC instance.
 *
 * @param sessionId - Session identifier for state management
 * @param samples - Float32Array to process (modified in place)
 * @returns Current AGC gain
 */
export declare function applyAgc(sessionId: string, samples: Float32Array): number
/** Reset AGC state for a session */
export declare function resetAgc(sessionId: string): boolean
/** Remove AGC instance for a session */
export declare function removeAgc(sessionId: string): boolean
/**
 * Native audio processor for real-time voice analysis
 *
 * Pre-allocates all buffers at construction for zero per-frame allocations.
 */
export declare class NativeAudioProcessor {
  /**
   * Create a new audio processor for a session
   *
   * # Arguments
   * * `session_id` - Unique session identifier for debugging
   * * `sample_rate` - Audio sample rate (default: 16000)
   */
  constructor(sessionId: string, sampleRate?: number | undefined | null)
  /**
   * Process an Int16 audio frame
   *
   * This is the main entry point for LiveKit audio frames.
   * Uses pre-allocated buffers for zero per-frame allocations.
   *
   * # Arguments
   * * `samples` - Int16Array audio samples from LiveKit
   * * `timestamp_ms` - Current timestamp in milliseconds
   *
   * # Returns
   * Prosody features if enough data is available, None otherwise
   */
  processFrame(samples: Int16Array, timestampMs: number): NativeProsodyResult | null
  /**
   * Process a Float32 audio frame
   *
   * Use this if samples are already normalized floats.
   */
  processFrameF32(samples: Float32Array, timestampMs: number): NativeProsodyResult | null
  /** Get full prosody features for end-of-utterance analysis */
  getFullFeatures(): NativeFullProsodyFeatures
  /** Get processor statistics */
  getStats(): NativeProcessorStats
  /**
   * Reset processor for reuse
   *
   * Clears all state but keeps pre-allocated buffers.
   */
  reset(): void
  /** Get session ID */
  get sessionId(): string
}
export type NativePostTTSProcessor = NativePostTtsProcessor
/**
 * Stateful Post-TTS Audio Processor
 *
 * This processor maintains state between frames for seamless audio enhancement.
 * Create one instance per session and call `processFrame()` for each audio frame.
 *
 * Features:
 * - Stateful biquad filters (no clicks at frame boundaries)
 * - Stateful compressor (no pumping/breathing)
 * - De-esser (reduces harsh sibilance)
 * - Look-ahead soft limiter (prevents clipping)
 * - Crossfade overlap-add (eliminates frame discontinuities)
 *
 * Usage:
 * ```javascript
 * const processor = new NativePostTTSProcessor({
 *   sampleRate: 24000,
 *   enableWarmth: true,
 *   enablePresence: true,
 *   enableCompression: true,
 *   enableDeesser: true,
 *   enableLimiter: true,
 *   enableCrossfade: true,
 * });
 *
 * // Process frames
 * for (const frame of audioFrames) {
 *   const isLast = isLastFrame(frame);
 *   const stats = processor.processFrame(frame.samples, isLast);
 *   // frame.samples is modified in place
 * }
 *
 * // Reset for new utterance
 * processor.startUtterance();
 * ```
 */
export declare class NativePostTtsProcessor {
  /** Create a new processor with the given configuration */
  constructor(config?: NativePostTtsConfig | undefined | null)
  /** Create with default configuration (all features enabled) */
  static withDefaults(): NativePostTtsProcessor
  /**
   * Process a frame of audio samples in-place
   *
   * Call this for each audio frame. The processor maintains state between calls
   * for seamless audio without artifacts.
   *
   * @param samples - Float32Array of audio samples (modified in place)
   * @param isLastFrame - Set to true for the last frame of an utterance
   * @returns Processing statistics
   */
  processFrame(samples: Float32Array, isLastFrame: boolean): NativeProcessingStats
  /**
   * Mark the start of a new utterance
   *
   * Resets crossfade buffer but keeps filter state for continuity.
   * Call this at the start of each new TTS utterance.
   */
  startUtterance(): void
  /**
   * Fully reset all state
   *
   * Use this when switching personas or at session end.
   */
  reset(): void
  /** Get the number of frames processed */
  frameCount(): number
  /**
   * Set the emotional state (can be called mid-utterance for dynamic expression)
   *
   * The emotion smoothly transitions to affect vibrato, pitch drift, and pacing.
   * Valid values: 0=Neutral, 1=Happy, 2=Sad, 3=Excited, 4=Calm, 5=Tense,
   *               6=Empathetic, 7=Curious, 8=Supportive
   *
   * @param emotion - Emotion state (0-8)
   */
  setEmotion(emotion: number): void
  /**
   * Set content complexity for adaptive pacing
   *
   * 0.0 = simple content (normal/slightly faster pace)
   * 0.5 = moderate complexity (normal pace)
   * 1.0 = complex content (slower pace for comprehension)
   *
   * @param complexity - Complexity value (0.0 - 1.0)
   */
  setContentComplexity(complexity: number): void
  /**
   * Get the current emotional state
   *
   * @returns Current emotion state (0-8)
   */
  getEmotion(): number
  /**
   * Set phrase boundaries for adaptive breath placement
   *
   * This enables intelligent breath injection at natural pause points (sentence ends,
   * clause breaks, emphasis points). The processor will probabilistically inject
   * breaths based on boundary type and emotional context.
   *
   * @param boundaries - Array of phrase boundaries with sample positions and types
   *
   * Example:
   * ```javascript
   * processor.setPhraseBoundaries([
   *   { sampleIndex: 24000, boundaryType: 0 },  // Sentence end at 1 second
   *   { sampleIndex: 12000, boundaryType: 1 },  // Clause break at 0.5 seconds
   * ]);
   * ```
   */
  setPhraseBoundaries(boundaries: Array<NativePhraseBoundary>): void
  /**
   * Add a single phrase boundary
   *
   * Boundary types:
   * - 0 = SentenceEnd (80% breath likelihood)
   * - 1 = ClauseBreak (40% breath likelihood)
   * - 2 = EmphasisBefore (20% breath likelihood)
   * - 3 = EmotionalRelease (60% breath likelihood)
   *
   * @param sampleIndex - Absolute sample position in the utterance
   * @param boundaryType - Type of boundary (0-3)
   */
  addPhraseBoundary(sampleIndex: number, boundaryType: number): void
  /**
   * Clear all phrase boundaries
   *
   * Call this when starting a new utterance if you want to disable adaptive
   * breath timing and only use the standard breath injection.
   */
  clearPhraseBoundaries(): void
  /** Get the number of phrase boundaries currently set */
  phraseBoundaryCount(): number
}
export type NativePreSTTProcessor = NativePreSttProcessor
/**
 * Pre-STT Audio Processor
 *
 * Enhances inbound user audio before sending to STT (Gemini/Google).
 *
 * Features:
 * - **AGC** - Normalizes levels from quiet/loud speakers
 * - **Noise Suppression** - Removes background noise (fans, AC, etc.)
 * - **Bandwidth Extension** - Enhances 8kHz Twilio audio to 16kHz
 * - **DC Removal** - Removes DC offset and low-frequency rumble
 *
 * Usage:
 * ```javascript
 * const processor = new NativePreSTTProcessor({
 *   enableAgc: true,
 *   enableNoiseSuppression: true,
 *   enableHighpass: true,
 * });
 *
 * // For each audio frame from LiveKit
 * const enhanced = processor.processFrame(samples, isSpeech);
 * // Send enhanced audio to Gemini STT
 * ```
 */
export declare class NativePreSttProcessor {
  /** Create a new Pre-STT processor with configuration */
  constructor(config?: NativePreSttConfig | undefined | null)
  /** Create with default configuration (all features enabled for 16kHz) */
  static withDefaults(): NativePreSttProcessor
  /** Create configured for Twilio (8kHz → 16kHz with bandwidth extension) */
  static forTwilio(): NativePreSttProcessor
  /**
   * Process a frame of Float32 audio
   *
   * @param samples - Float32Array audio samples (normalized -1 to 1)
   * @param isSpeech - VAD result (true if speech detected in this frame)
   * @returns Enhanced audio samples (may be longer if bandwidth extended)
   */
  processFrame(samples: Float32Array, isSpeech: boolean): Float32Array
  /**
   * Process a frame of Int16 audio (common LiveKit format)
   *
   * @param samples - Int16Array audio samples
   * @param isSpeech - VAD result
   * @returns Enhanced audio as Float32Array (normalized -1 to 1)
   */
  processFrameI16(samples: Int16Array, isSpeech: boolean): Float32Array
  /** Get processing statistics */
  getStats(): NativePreSttStats
  /** Reset noise estimation (call when entering a new environment) */
  resetNoiseEstimate(): void
  /** Full reset (call when starting a new session) */
  reset(): void
}
