/**
 * Speech Module
 *
 * Provides adaptive speech synthesis capabilities.
 * Tracks user speaking patterns and adapts SSML accordingly.
 *
 * This module includes:
 * - Voice management for persona switching
 * - Adaptive SSML generation
 * - Audio prosody analysis for emotion detection
 * - Backchanneling (standard and live)
 * - Response naturalness (acknowledgments, fillers)
 * - Emotion matching for TTS
 * - Cognitive speech integration
 * - Pronunciation memory
 * - TTS context for prosody continuity
 * - Session cleanup utilities
 */
export { cleanupAllSpeechSessions, cleanupSpeechSession, emergencySpeechCleanup, getActiveSpeechSessionCount, getActiveSpeechSessions, registerSpeechSession, } from './session-cleanup.js';
export { advanceTurn, canAddFeedback, getFeedbackStats, recordFeedback, resetAllFeedbackCoordinators, resetFeedbackCoordinator, type FeedbackType, } from './feedback-coordinator.js';
export { checkForLeaks, cleanupSessionTracking, getAllSessionsDebugInfo, getSessionDebugInfo, getSpeechModuleDebugInfo, logModuleState, trackBackchannel, trackEmotionDetected, trackProsodyAnalysis, trackSessionStart, trackTurnPrediction, type SpeechModuleDebugInfo, type SpeechSessionDebugInfo, } from './session-debug.js';
export { cleanupRegisteredServices, createSessionManager, getRegisteredManagerCount, registerSessionManager, type ServiceFactory, type SessionService, type SessionServiceManager, } from './session-service.js';
export { ACKNOWLEDGMENT_PREFIXES, BACKCHANNEL_LIBRARY, PERSONA_BACKCHANNEL_STYLE, PERSONA_CATCHPHRASES, SOFT_BACKCHANNELS, getAcknowledgmentPrefix, getBackchannelPhrase, getCatchphraseWithSsml, getPersonaBackchannelStyle, getSoftBackchannel, getContextAwareThinkingFiller, // Context-aware ProcessingIntelligence integration
normalizePersonaId, type AcknowledgmentMood, type BackchannelCategory, type BackchannelEmotionType, type CatchphraseConfig, type PersonaBackchannelStyle, type PersonaId, } from './persona-phrases.js';
export { BackchannelEngine, BreathPauseDetector, DEFAULT_BREATH_PAUSE_CONFIG, ENHANCED_TIMING, LIVE_TIMING, STANDARD_TIMING, SessionBackchannelManager, adjustTimingForTopic, createBackchannelEngine, getActiveBackchannelSessionCount, getBackchannelEngine, getBackchannelManager, getSessionBreathPauseDetector, getTimingForMode, resetAllBackchanneling, resetBackchanneling, signalNewTurn, type BackchannelEngineOptions, type BackchannelMode, type BackchannelTiming, type BreathPauseConfig, type BreathPauseStats, type BackchannelContext as UnifiedBackchannelContext, type BackchannelDecision as UnifiedBackchannelDecision, } from './backchanneling/index.js';
export type * from './types/index.js';
export { DEFAULT_SPEECH_CHARACTERISTICS, WPMTracker, buildSpeechContext, deriveSpeechCharacteristicsFromEnergy, detectEnergyLevel, determineTopicWeight, getSessionWPMTracker, resetSessionWPMTracker, type EnergyLevel, type SpeechContext, type TopicWeight, } from './speech-context.js';
export { applyPhasePersonality, clearCognitiveSpeechState, getCognitiveSpeechStats, tagAdvice, tagAdviceWithPersonality, tagGreeting, tagGreetingWithPersonality, tagStory, tagSupportResponse, tagSupportWithPersonality, tagTextWithCognitiveSsml, tagTextWithSsmlAdaptive, tagWrapUp, tagWrapUpWithPersonality, type CognitiveSsmlOptions, } from './adaptive-ssml.js';
export { sanitizeSsml, tagTextWithSsml, tagTextWithSsmlPersonaAware } from '../ssml/index.js';
export { CatchphraseTracker, determineAcknowledgmentMood, getResponseEnhancements, getSessionCatchphraseTracker, resetAllCatchphraseTrackers, resetCatchphraseTracking, resetSessionCatchphraseTracker, shouldAddPrefix, shouldInjectCatchphrase, type ResponseEnhancement, type ResponseEnhancementOptions, } from './response-naturalness.js';
export { AudioProsodyAnalyzer, clearProsodyMetrics, getProsodyMetrics, getSessionAudioProsodyAnalyzer, recordProsodyAnalysis, resetSessionAudioProsodyAnalyzer, type ProsodyFeatures, type ProsodyMetrics, type VoiceEmotion, type VoiceEmotionResult, } from './audio-prosody.js';
export { EMOTION_RESPONSES, adjustTTSSpeed, getEmotionGuidance, getEmotionModulation, getRegisteredEmotions, isEmotionRegistered, registerEmotionResponse, wrapWithEmotionProsody, type VoiceEmotionModulation, } from './emotion-matching.js';
export { BackchannelingSystem, getSessionBackchannelingSystem, resetSessionBackchannelingSystem, type BackchannelContext, type BackchannelResult, } from './backchanneling.js';
export { LiveBackchannelingService, getBreathPauseDetector, getLiveBackchannelingService, resetLiveBackchanneling, type AudioFrameData, type LiveBackchannelContext, type LiveBackchannelResult, type SimpleEmotion, } from './live-backchanneling.js';
export { applyCognitiveAdjustments, buildPauseSSML, calculateCognitiveSpeechAdjustments, getCognitiveThinkingSound, getPauseDuration, type CognitiveSpeechContext, type SpeechAdjustments, } from './cognitive-speech.js';
export { applyCognitiveSpeechAdjustments, buildCognitiveSSML, getReasoningStyleSpeechPreset, type CognitiveSpeechInput, type CognitiveSpeechResult, } from './cognitive-speech-integration.js';
export { analyzeQuestionComplexity, calculateThinkingPause, createThinkingContext, generateThinkingSSML, personaThinkingPhrases, wrapWithThinkingPause, type ThinkingContext, type ThinkingPause, } from './authentic-thinking.js';
export { TtsContextService, getTtsContextService, resetTtsContextService, type ProsodyGuidance, type TtsContextState, type TurnProsodyRecord, } from './tts-context.js';
export { PronunciationMemoryService, analyzePronunciationNeeds, getPronunciationMemory, resetAllPronunciationMemory, resetPronunciationMemory, type PronunciationEntry, type PronunciationMemoryState, type PronunciationSource, } from './pronunciation-memory.js';
export { applyConsonantSmoothing, detectDifficultClusters, getClusterStats, type ClusterPattern, } from './consonant-smoothing.js';
export { DynamicTTS, PersonaAwareTTS, VOICES, createDynamicTTS, createPersonaAwareTTS, getSessionVoiceManager, getSessionVoiceManagerCount, getVoiceManager, resetAllSessionVoiceManagers, resetSessionVoiceManager, resetVoiceManager, type VoiceAgentId, type VoiceConfig, } from './voice-manager.js';
export { createTurnPredictionContext, getIntonationFromVoiceEmotion, mapPitchContourToIntonation, predictTurnWithVoice, voiceSuggestsTurnComplete, type EnhancedTurnPrediction, type Intonation, } from './prosody-turn-bridge.js';
export { getAirDJMoment, getDancingComment, getExcitedMusicReaction, getFunDJMoment, getGenreReaction, getMoodMusicReaction, getMusicReaction, getPlayfulMusicComment, getPlayfulMusicIntro, shouldReactToMusic, } from './music-reactions.js';
export { clearAllContexts, clearSessionContextId, generateContextId, getActiveContextCount, getAllSessionContexts, getCartesiaContextOptions, getOrCreateContextId, getSessionContextId, setSessionContextId, type CartesiaContextOptions, } from './cartesia-context-patch.js';
export { HumanListeningPipeline, getHumanListeningPipeline, resetAllHumanListeningPipelines, resetHumanListeningPipeline, type AudioAnalysis, type ConversationAnalysis, type EmotionalUndercurrent, type HumanListeningContext, type HumanListeningResult, type TextAnalysis, } from './human-listening-pipeline.js';
export { BreathDetector, getBreathDetector, resetAllBreathDetectors, resetBreathDetector, type BreathCharacteristics, type BreathEvent, type BreathPatternResult, type BreathType, } from './breath-detection.js';
export { VoiceTremorDetector, getVoiceTremorDetector, resetAllVoiceTremorDetectors, resetVoiceTremorDetector, type TremorEvent, type TremorIntensity, type TremorType, type VoiceStabilityProfile, type VoiceTremorResult, } from './voice-tremor.js';
export { VolumeDynamicsTracker, getVolumeDynamicsTracker, resetAllVolumeDynamicsTrackers, resetVolumeDynamicsTracker, type VolumeDynamicsState, type VolumeLevel, type VolumeObservation, type VolumePattern, type VolumeTrend, } from './volume-dynamics.js';
export { EnergyDynamicsTracker, getEnergyDynamicsTracker, resetAllEnergyDynamicsTrackers, resetEnergyDynamicsTracker, type EnergyDynamicsResult, type EnergyFadeEvent, type EnergyFadeReason, type EnergySegment, type EnergyTrajectory, } from './energy-dynamics.js';
export { FluencyAnalyzer, getFluencyAnalyzer, resetAllFluencyAnalyzers, resetFluencyAnalyzer, type Disfluency, type DisfluencyCounts, type DisfluencyType, type FluencyAnalysisResult, type FluencyPattern, } from './fluency-analysis.js';
export { FillerAnalyzer, getFillerAnalyzer, resetAllFillerAnalyzers, resetFillerAnalyzer, type FillerAnalysisResult, type FillerInstance, type FillerMeaning, type FillerPattern, type FillerPosition, type FillerType, } from './filler-analysis.js';
export { FFTAnalyzerService, analyzeLaughterSpectral, analyzeSpectrum, classifyEnvironment, getFFTAnalyzer, resetFFTAnalyzer, type LaughterSpectralFeatures, type SpectralAnalysis, type SpectralEnvironment, } from './fft-analyzer.js';
export { ALL_CARTESIA_EMOTIONS, CARTESIA_EMOTIONS, addBreathGroupPauses, analyzeRhythm, applyRhythmVariations, getEmotionTransition, humanizeText, injectNaturalFillers, mapContextToEmotion, getEmotionProfile, PERSONA_EMOTION_PROFILES, type BreathGroupConfig, type CartesiaEmotion, type EmotionContext, type FillerConfig, type HumanizationOptions as AdvancedHumanizationOptions, type PersonaEmotionProfile, type RhythmVariation, } from './advanced-humanization.js';
export { EnhancedBackchannelingEngine, getEnhancedBackchannelingEngine, getQuickBackchannel, resetEnhancedBackchannelingEngine, type BackchannelType, type EnhancedBackchannelContext, // Preferred naming alias
type BackchannelDecision as EnhancedBackchannelDecision, } from './enhanced-backchanneling.js';
export { DEFAULT_SPEED_CONFIG, applyDynamicSpeedSsml, calculateDynamicSpeed, getSpeedControlSession, getSpeedTrend, recordSpeedDecision, resetAllSpeedControlSessions, resetSpeedControlSession, type SpeedControlConfig, type SpeedControlContext, type SpeedControlResult, } from './adaptive-ssml/dynamic-speed-control.js';
export { DEFAULT_REALTIME_CONFIG, RealTimeAudioAnalyzer, getActiveRealTimeAnalyzerCount, getRealTimeAnalyzer, resetAllRealTimeAnalyzers, resetRealTimeAnalyzer, type AnalyzerState, type PartialProsodyFeatures, type RealTimeAnalyzerConfig, } from './audio-prosody/real-time-analyzer.js';
export { getLatencyMetrics, getQualityMetrics, getSpeechMetrics, getSpeechMetricsSnapshot, getUsageMetrics, recordBackchannelTiming, recordEmotionConfidence, recordLatency, recordOperation, recordSessionEnd, recordSessionStart, recordTurnPredictionAccuracy, resetSpeechMetrics, withTiming, withTimingSync, type LatencyMetrics, type MetricsSnapshot, type OperationMetrics, type QualityMetrics, type SpeechPipelineMetrics, type UsageMetrics, } from './metrics/index.js';
export { COMPOUND_REACTIONS, DISFLUENCY_PATTERNS, MICRO_REACTIONS, addContextualPause, addExcitedInterruption, addRealizationMoment, addThinkingStart, addTrailingOff, anticipateResponse, applyProsodyRecommendation, calculateTrajectory, detectContext, detectContexts, detectTrajectory, detectTrajectoryType, enhanceResponseWithSesame, findInjectionPoints, getActiveAnticipatorySessionCount, getActiveConversationStateCount, getActiveDisfluencySessionCount, getActiveMicroReactionSessionCount, getActiveSesamePipelineSessionCount, getAnticipatorySession, getCompoundReaction, getConversationState, getDisfluenciesForEmotion, getDisfluencySession, getImmediateMicroReaction, getLastAnticipation, getMicroReaction, getMicroReactionSession, getPreparedResponse, getProsodyRecommendation, getRandomSsmlPattern, getReactionsForContext, getSesamePipelineMetrics, getSessionMicroReaction, getSessionProsodyRecommendation, injectDisfluency, isHeavyTopic, processPartialTranscript, quickEnhance, recordReaction, resetAnticipatorySession, resetConversationState, resetDisfluencySession, resetMicroReactionSession, resetSesamePipeline, selectMicroReaction, selectWeightedDisfluency, shouldAnticipate, shouldUseReaction, smartInjectDisfluency, startNewTurn, updateAnticipation, updateConversationState, type AnticipatedResponse, type ConversationEmotionalState, type ConversationProsodyRecommendation, type DisfluencyInjection, type DisfluencyPattern, // Aliased to avoid conflict with fluency-analysis
type EmotionalTrajectory as SesameEmotionalTrajectory, type MicroReaction, type MicroReactionContext, type MicroReactionType, type PartialTranscript, type PreparedResponse, type DisfluencyType as SesameDisfluencyType, type SesameEnhancedResult, } from './sesame-inspired/index.js';
export { SpeechOrchestrator, getActiveOrchestratorCount, getOrchestrator, resetAllOrchestrators, resetOrchestrator, type AnticipatedResult, type AnticipationContext, type BackchannelRequest, type BackchannelResponse, type HumanizationOptions, type HumanizedResponse, type ListeningAnalysisOptions, type ListeningAnalysisResult, type SpeechOrchestratorContext, } from './orchestrator/index.js';
export { ANTICIPATION_CONFIG, BACKCHANNELING_CONFIG, BREATH_DETECTION_CONFIG, EMOTION_DETECTION_CONFIG, FEEDBACK_COORDINATION_CONFIG, FFT_CONFIG, HUMANIZATION_CONFIG, LATENCY_TARGETS_MS, TURN_PREDICTION_CONFIG, adjustTimingForTopicWeight, getBackchannelConfig, type BackchannelMode as ConfigBackchannelMode, type EmotionType as ConfigEmotionType, type TopicWeight as ConfigTopicWeight, } from './config/index.js';
export { clearVoiceDataCache, getBackchannelByCategorySync, getBackchannelSync, getCatchphraseSync, getExpressionSync, getLoadedPersonaCount, getSilenceFillerSync, hasVoiceDataLoaded, loadPersonaVoiceData, preloadCommonPersonaVoice, type PersonaBackchannels, type PersonaCatchphrases, type PersonaExpressions, type PersonaVoiceData, } from './persona-voice-loader.js';
export { AnticipationPipeline, EmotionPredictor, IntentPredictor, getActiveAnticipationPipelineCount, getAnticipationPipeline, resetAllAnticipationPipelines, resetAnticipationPipeline, DEFAULT_ANTICIPATION_OPTIONS, type AnticipationContext as UnifiedAnticipationContext, type AnticipationOptions, type AnticipationResult, type EmotionalPrediction, type EmotionalTrajectory as AnticipationEmotionalTrajectory, type IntentCategory, type IntentPrediction, } from './anticipation/index.js';
export { getInterruptState, resetInterruptState, addCushioning, senseInterrupt, getTrailingSsml, getRecoverySsml, endRecovery, wrapWithInterruptAwareness, wrapSpeechWithInterruptAwareness, createInterruptAwareTransform, markRecoveryComplete, isInRecoveryPhase, CUSHION_TIMING, TRAILING_TRIGGERS, type InterruptPhase, type InterruptState, type CushionedResponse, type RecoveryOptions, type RecoverySsml, type InterruptContext, type WrappedSpeech, } from './graceful-interrupt/index.js';
export { TTSBulkhead, TimeoutError, getTTSBulkhead, resetTTSBulkhead, executeWithBulkhead, canAcceptTTSRequest, isTTSUnderPressure, getTTSBulkheadStats, cleanupTTSSession, type TTSBulkheadConfig, type TTSRequest, type TTSBulkheadResult, type TTSBulkheadStats, } from './tts-bulkhead.js';
export { humanizeSpeech, quickHumanize, getAvailableCategories, quickHumanizeSync, loadSpeechProfile, clearSpeechProfileCache, preloadAllSpeechProfiles, selectImperfection, selectThinkingSound, selectBackchannel, selectBreathSound, getInjectionConfig, getSpeechProfileSync, areSpeechProfilesPreloaded, selectThinkingSoundSync, selectImperfectionSync, selectBreathSoundSync, type BehaviorSelectionContext, type EmotionalSelectionContext, type ContentSelectionContext, type SelectedBehavior, type HumanizedSpeechResult, type SpeechImperfectionsSchema, type ThinkingSoundsSchema, type BackchannelsSchema, type BreathSoundsSchema, type PersonaSpeechProfile, type ImperfectionCategory, type CoreImperfectionCategory, type ExtendedImperfectionCategory, type InjectionConfig, } from './humanization/index.js';
//# sourceMappingURL=index.d.ts.map