
import type { PersonaId } from '../types/index.js';

// TYPES

export type CapabilityCategory =
  | 'life-coaching'
  | 'emotional-support'
  | 'relationships'
  | 'productivity'
  | 'growth'
  | 'practical'
  | 'wellness'
  | 'entertainment'
  | 'communication'
  | 'superhuman';

export type CapabilityPriority = 'essential' | 'high' | 'medium' | 'low';

export interface Capability {
  id: string;
  name?: string;
  nameKey: string;
  description?: string;
  descriptionKey: string;
  details?: string;
  detailsKey?: string;
  voiceTriggers: string[];
  persona: PersonaId;
  category: CapabilityCategory;
  priority: CapabilityPriority;
  icon: string;
  hasUI: boolean;
  uiPanel?: string;
  tags: string[];
  isBetterThanHuman?: boolean;
  humanLimitation?: string;
  humanLimitationKey?: string;
}

export interface CapabilityGroup {
  id: string;
  name?: string;
  nameKey: string;
  description?: string;
  descriptionKey: string;
  icon: string;
  capabilities: Capability[];
}

// CAPABILITY DEFINITIONS

export const CAPABILITIES: Capability[] = [
] = [
  // LIFE COACHING - Grief, Loss, Transitions
  {
    id: 'grief-support',
    nameKey: 'capabilityRegistry.griefSupport.name',
    description: "I'm here when you're processing loss",
    details: 'Whether you\'ve lost a loved one, a pet, a relationship, or a dream, I can hold space for your grief without trying to fix it.',
    detailsKey: 'capabilityRegistry.griefSupport.details',
    voiceTriggers: ['Help me process grief', 'I lost someone', 'I\'m grieving'],
    persona: 'nayan-patel',
    category: 'life-coaching',
    priority: 'high',
    icon: 'heart',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['grief', 'loss', 'death', 'mourning', 'bereavement'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.griefSupport.humanLimitation',
  },
  {
    id: 'breakup-recovery',
    nameKey: 'capabilityRegistry.breakupRecovery.name',
    descriptionKey: 'capabilityRegistry.breakupRecovery.description',
    details: 'Process the end of a relationship without judgment. I won\'t tell you to "get over it" or rush your healing.',
    detailsKey: 'capabilityRegistry.breakupRecovery.details',
    voiceTriggers: ['Help me get over my ex', 'We just broke up', 'I\'m heartbroken'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'high',
    icon: 'heart-crack',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['breakup', 'heartbreak', 'ex', 'relationship end', 'divorce'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.breakupRecovery.humanLimitation',
  },
  {
    id: 'divorce-support',
    nameKey: 'capabilityRegistry.divorceSupport.name',
    descriptionKey: 'capabilityRegistry.divorceSupport.description',
    detailsKey: 'capabilityRegistry.divorceSupport.details',
    voiceTriggers: ['Help me with my divorce', 'I\'m getting divorced', 'Co-parenting help'],
    persona: 'ferni',
    category: 'life-coaching',
    priority: 'high',
    icon: 'users',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['divorce', 'separation', 'co-parenting', 'custody'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.divorceSupport.humanLimitation',
  },
  {
    id: 'job-loss',
    nameKey: 'capabilityRegistry.jobLoss.name',
    descriptionKey: 'capabilityRegistry.jobLoss.description',
    detailsKey: 'capabilityRegistry.jobLoss.details',
    voiceTriggers: ['I lost my job', 'I got fired', 'Help me with unemployment'],
    persona: 'peter-john',
    category: 'life-coaching',
    priority: 'high',
    icon: 'briefcase',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['job loss', 'fired', 'laid off', 'unemployment', 'career'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.jobLoss.humanLimitation',
  },
  {
    id: 'health-diagnosis',
    nameKey: 'capabilityRegistry.healthDiagnosis.name',
    descriptionKey: 'capabilityRegistry.healthDiagnosis.description',
    detailsKey: 'capabilityRegistry.healthDiagnosis.details',
    voiceTriggers: ['I just got diagnosed', 'Help me with my diagnosis', 'I have bad health news'],
    persona: 'nayan-patel',
    category: 'life-coaching',
    priority: 'high',
    icon: 'stethoscope',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['diagnosis', 'illness', 'health', 'chronic', 'disease'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.healthDiagnosis.humanLimitation',
  },
  {
    id: 'chronic-conditions',
    nameKey: 'capabilityRegistry.chronicConditions.name',
    descriptionKey: 'capabilityRegistry.chronicConditions.description',
    detailsKey: 'capabilityRegistry.chronicConditions.details',
    voiceTriggers: ['Help with chronic pain', 'Living with chronic illness', 'Spoon theory help'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'high',
    icon: 'activity',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['chronic', 'pain', 'disability', 'illness', 'fatigue'],
    isBetterThanHuman: true,
    humanLimitation: 'Healthy people don\'t understand the daily reality',
  },
  {
    id: 'caregiver-support',
    nameKey: 'capabilityRegistry.caregiverSupport.name',
    descriptionKey: 'capabilityRegistry.caregiverSupport.description',
    detailsKey: 'capabilityRegistry.caregiverSupport.details',
    voiceTriggers: ['Caregiver burnout', 'Taking care of my parents', 'I\'m a caregiver'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'high',
    icon: 'hand-heart',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['caregiver', 'aging parents', 'elder care', 'caregiving'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.caregiverSupport.humanLimitation',
  },
  {
    id: 'sobriety-support',
    nameKey: 'capabilityRegistry.sobrietySupport.name',
    descriptionKey: 'capabilityRegistry.sobrietySupport.description',
    details: 'Whether you\'re newly sober or years into recovery, I\'m here for check-ins, cravings, and celebrating milestones.',
    detailsKey: 'capabilityRegistry.sobrietySupport.details',
    voiceTriggers: ['Help with sobriety', 'I\'m in recovery', 'Craving support'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'high',
    icon: 'flower-2',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['sobriety', 'recovery', 'addiction', 'sober', 'AA'],
    isBetterThanHuman: true,
    humanLimitation: 'Sponsors aren\'t always available at 2am',
  },
  {
    id: 'burnout-recovery',
    nameKey: 'capabilityRegistry.burnoutRecovery.name',
    descriptionKey: 'capabilityRegistry.burnoutRecovery.description',
    details: 'Burnout isn\'t just being tired—it\'s a deep depletion. I can help you recognize it, recover from it, and prevent it.',
    detailsKey: 'capabilityRegistry.burnoutRecovery.details',
    voiceTriggers: ['I\'m burned out', 'Help with burnout', 'I can\'t keep going'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'high',
    icon: 'battery-low',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['burnout', 'exhaustion', 'overwork', 'stress', 'recovery'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.burnoutRecovery.humanLimitation',
  },
  {
    id: 'new-parent',
    nameKey: 'capabilityRegistry.newParent.name',
    descriptionKey: 'capabilityRegistry.newParent.description',
    detailsKey: 'capabilityRegistry.newParent.details',
    voiceTriggers: ['Help as a new parent', 'New baby support', 'Postpartum help'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'medium',
    icon: 'baby',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['parenting', 'new parent', 'baby', 'postpartum', 'motherhood'],
  },
  {
    id: 'empty-nest',
    nameKey: 'capabilityRegistry.emptyNest.name',
    descriptionKey: 'capabilityRegistry.emptyNest.description',
    detailsKey: 'capabilityRegistry.emptyNest.details',
    voiceTriggers: ['Kids left for college', 'Empty nest feelings', 'Kids moved out'],
    persona: 'nayan-patel',
    category: 'life-coaching',
    priority: 'medium',
    icon: 'home',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['empty nest', 'kids leaving', 'midlife', 'identity'],
  },
  {
    id: 'midlife-transition',
    nameKey: 'capabilityRegistry.midlifeTransition.name',
    descriptionKey: 'capabilityRegistry.midlifeTransition.description',
    details: 'Midlife isn\'t a crisis—it\'s an invitation to reassess what matters. I can help you find renewed purpose.',
    detailsKey: 'capabilityRegistry.midlifeTransition.details',
    voiceTriggers: ['Midlife crisis help', 'What am I doing with my life', 'Is this it?'],
    persona: 'nayan-patel',
    category: 'life-coaching',
    priority: 'medium',
    icon: 'sunrise',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['midlife', 'meaning', 'purpose', 'crisis', 'transition'],
  },

  // EMOTIONAL SUPPORT - Processing Difficult Emotions
  {
    id: 'anger-processing',
    nameKey: 'capabilityRegistry.angerProcessing.name',
    descriptionKey: 'capabilityRegistry.angerProcessing.description',
    details: 'Anger isn\'t bad—it\'s information. I can help you understand what your anger is telling you and express it healthily.',
    detailsKey: 'capabilityRegistry.angerProcessing.details',
    voiceTriggers: ['I\'m so angry', 'Help me with anger', 'I want to scream'],
    persona: 'maya-santos',
    category: 'emotional-support',
    priority: 'high',
    icon: 'flame',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['anger', 'rage', 'frustration', 'mad'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.angerProcessing.humanLimitation',
  },
  {
    id: 'shame-healing',
    nameKey: 'capabilityRegistry.shameHealing.name',
    descriptionKey: 'capabilityRegistry.shameHealing.description',
    detailsKey: 'capabilityRegistry.shameHealing.details',
    voiceTriggers: ['I feel so ashamed', 'Help with shame', 'I hate myself'],
    persona: 'nayan-patel',
    category: 'emotional-support',
    priority: 'high',
    icon: 'shield',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['shame', 'guilt', 'embarrassment', 'self-worth'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.shameHealing.humanLimitation',
  },
  {
    id: 'self-compassion',
    nameKey: 'capabilityRegistry.selfCompassion.name',
    descriptionKey: 'capabilityRegistry.selfCompassion.description',
    details: 'Learn to treat yourself with the kindness you\'d give a good friend. I can guide you through self-compassion practices.',
    detailsKey: 'capabilityRegistry.selfCompassion.details',
    voiceTriggers: ['Help with self-criticism', 'I\'m too hard on myself', 'Inner critic help'],
    persona: 'maya-santos',
    category: 'emotional-support',
    priority: 'high',
    icon: 'heart-handshake',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['self-compassion', 'inner critic', 'self-kindness', 'self-love'],
    isBetterThanHuman: true,
    humanLimitation: 'Hard to model when you\'re in the pattern',
  },
  {
    id: 'trauma-support',
    nameKey: 'capabilityRegistry.traumaSupport.name',
    descriptionKey: 'capabilityRegistry.traumaSupport.description',
    detailsKey: 'capabilityRegistry.traumaSupport.details',
    voiceTriggers: ['I\'m having a flashback', 'Help me ground', 'Trauma response help'],
    persona: 'maya-santos',
    category: 'emotional-support',
    priority: 'high',
    icon: 'anchor',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['trauma', 'PTSD', 'flashback', 'grounding', 'safety'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.traumaSupport.humanLimitation',
  },
  {
    id: 'anxiety-support',
    nameKey: 'capabilityRegistry.anxietySupport.name',
    descriptionKey: 'capabilityRegistry.anxietySupport.description',
    detailsKey: 'capabilityRegistry.anxietySupport.details',
    voiceTriggers: ['I\'m anxious', 'Help with anxiety', 'Can\'t stop worrying'],
    persona: 'maya-santos',
    category: 'emotional-support',
    priority: 'high',
    icon: 'cloud',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['anxiety', 'worry', 'panic', 'nervous', 'stress'],
  },
  {
    id: 'vulnerability-practice',
    nameKey: 'capabilityRegistry.vulnerabilityPractice.name',
    descriptionKey: 'capabilityRegistry.vulnerabilityPractice.description',
    detailsKey: 'capabilityRegistry.vulnerabilityPractice.details',
    voiceTriggers: ['Help me be more vulnerable', 'I\'m scared to open up', 'Vulnerability practice'],
    persona: 'nayan-patel',
    category: 'emotional-support',
    priority: 'medium',
    icon: 'eye',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['vulnerability', 'authenticity', 'courage', 'connection'],
  },
  {
    id: 'envy-processing',
    nameKey: 'capabilityRegistry.envyProcessing.name',
    descriptionKey: 'capabilityRegistry.envyProcessing.description',
    detailsKey: 'capabilityRegistry.envyProcessing.details',
    voiceTriggers: ['I\'m jealous of', 'Help with envy', 'Why can\'t I have that'],
    persona: 'nayan-patel',
    category: 'emotional-support',
    priority: 'medium',
    icon: 'sparkles',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['envy', 'jealousy', 'comparison', 'wanting'],
  },
  {
    id: 'resentment-release',
    nameKey: 'capabilityRegistry.resentmentRelease.name',
    descriptionKey: 'capabilityRegistry.resentmentRelease.description',
    detailsKey: 'capabilityRegistry.resentmentRelease.details',
    voiceTriggers: ['I can\'t forgive them', 'Help with resentment', 'I\'m holding a grudge'],
    persona: 'nayan-patel',
    category: 'emotional-support',
    priority: 'medium',
    icon: 'scale',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['resentment', 'forgiveness', 'grudge', 'letting go'],
  },

  // GROWTH & DEVELOPMENT
  {
    id: 'decisions-toolkit',
    nameKey: 'capabilityRegistry.decisionsToolkit.name',
    descriptionKey: 'capabilityRegistry.decisionsToolkit.description',
    details: 'When you\'re stuck on a decision, I can help you explore options, identify values, and find clarity.',
    detailsKey: 'capabilityRegistry.decisionsToolkit.details',
    voiceTriggers: ['Help me decide', 'I can\'t make this decision', 'Pros and cons'],
    persona: 'peter-john',
    category: 'growth',
    priority: 'high',
    icon: 'git-branch',
    hasUI: true,
    uiPanel: 'decisions-toolkit',
    tags: ['decisions', 'choices', 'options', 'dilemma'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.decisionsToolkit.humanLimitation',
  },
  {
    id: 'boundaries-toolkit',
    nameKey: 'capabilityRegistry.boundariesToolkit.name',
    descriptionKey: 'capabilityRegistry.boundariesToolkit.description',
    detailsKey: 'capabilityRegistry.boundariesToolkit.details',
    voiceTriggers: ['Help me set boundaries', 'I need to say no', 'Boundary scripts'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'high',
    icon: 'shield-check',
    hasUI: true,
    uiPanel: 'decisions-toolkit',
    tags: ['boundaries', 'saying no', 'limits', 'self-protection'],
    isBetterThanHuman: true,
    humanLimitation: 'People with bad boundaries can\'t help you set yours',
  },
  {
    id: 'difficult-conversations',
    nameKey: 'capabilityRegistry.difficultConversations.name',
    descriptionKey: 'capabilityRegistry.difficultConversations.description',
    details: 'Practice that conversation you\'ve been dreading. I can roleplay, help you prepare, and debrief after.',
    detailsKey: 'capabilityRegistry.difficultConversations.details',
    voiceTriggers: ['Help me prepare for a conversation', 'Practice a hard talk', 'What should I say'],
    persona: 'alex-chen',
    category: 'growth',
    priority: 'high',
    icon: 'message-circle',
    hasUI: true,
    uiPanel: 'decisions-toolkit',
    tags: ['conversation', 'conflict', 'talking', 'communication'],
    isBetterThanHuman: true,
    humanLimitation: 'Can\'t practice infinitely with a human',
  },
  {
    id: 'meaning-purpose',
    nameKey: 'capabilityRegistry.meaningPurpose.name',
    descriptionKey: 'capabilityRegistry.meaningPurpose.description',
    details: 'When life feels meaningless or you\'re questioning your purpose, I can help you explore what truly matters to you.',
    detailsKey: 'capabilityRegistry.meaningPurpose.details',
    voiceTriggers: ['What\'s my purpose', 'Life feels meaningless', 'Why am I here'],
    persona: 'nayan-patel',
    category: 'growth',
    priority: 'high',
    icon: 'compass',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['meaning', 'purpose', 'existential', 'why'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.meaningPurpose.humanLimitation',
  },
  {
    id: 'dreams-aspirations',
    nameKey: 'capabilityRegistry.dreamsAspirations.name',
    descriptionKey: 'capabilityRegistry.dreamsAspirations.description',
    detailsKey: 'capabilityRegistry.dreamsAspirations.details',
    voiceTriggers: ['What were my dreams', 'Help me dream bigger', 'I forgot what I wanted'],
    persona: 'jordan-taylor',
    category: 'growth',
    priority: 'high',
    icon: 'star',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['dreams', 'aspirations', 'goals', 'ambitions', 'bucket list'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.dreamsAspirations.humanLimitation',
  },
  {
    id: 'quiet-growth',
    nameKey: 'capabilityRegistry.quietGrowth.name',
    descriptionKey: 'capabilityRegistry.quietGrowth.description',
    detailsKey: 'capabilityRegistry.quietGrowth.details',
    voiceTriggers: ['I feel like I\'m not progressing', 'Is it okay to rest', 'Celebrate my maintenance'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'high',
    icon: 'leaf',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['rest', 'growth', 'maintenance', 'seasons', 'hustle'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.quietGrowth.humanLimitation',
  },
  {
    id: 'life-transitions',
    nameKey: 'capabilityRegistry.lifeTransitions.name',
    descriptionKey: 'capabilityRegistry.lifeTransitions.description',
    details: 'Big life changes affect your identity. I can help you honor both what you\'re leaving and where you\'re going.',
    detailsKey: 'capabilityRegistry.lifeTransitions.details',
    voiceTriggers: ['I\'m going through a transition', 'Everything is changing', 'Identity shift'],
    persona: 'nayan-patel',
    category: 'growth',
    priority: 'high',
    icon: 'arrow-right-circle',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['transition', 'change', 'identity', 'transformation'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.lifeTransitions.humanLimitation',
  },
  {
    id: 'second-chances',
    nameKey: 'capabilityRegistry.secondChances.name',
    descriptionKey: 'capabilityRegistry.secondChances.description',
    details: 'Whether you\'re rebuilding after failure or starting over, I believe in second chances and can help you begin again.',
    detailsKey: 'capabilityRegistry.secondChances.details',
    voiceTriggers: ['Help me start over', 'I need a fresh start', 'Second chance support'],
    persona: 'ferni',
    category: 'growth',
    priority: 'high',
    icon: 'refresh-cw',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['second chance', 'fresh start', 'reinvention', 'rebuilding'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.secondChances.humanLimitation',
  },
  {
    id: 'connection-loneliness',
    nameKey: 'capabilityRegistry.connectionLoneliness.name',
    description: 'You\'re not alone',
    descriptionKey: 'capabilityRegistry.connectionLoneliness.description',
    detailsKey: 'capabilityRegistry.connectionLoneliness.details',
    voiceTriggers: ['I\'m so lonely', 'Help with loneliness', 'I feel alone'],
    persona: 'ferni',
    category: 'growth',
    priority: 'high',
    icon: 'users',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['loneliness', 'connection', 'isolation', 'belonging'],
    isBetterThanHuman: true,
    humanLimitation: 'Humans aren\'t available at 2am every night',
  },
  {
    id: 'presence-mindfulness',
    nameKey: 'capabilityRegistry.presenceMindfulness.name',
    descriptionKey: 'capabilityRegistry.presenceMindfulness.description',
    detailsKey: 'capabilityRegistry.presenceMindfulness.details',
    voiceTriggers: ['Help me be present', 'Grounding exercise', 'I can\'t stop thinking'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'high',
    icon: 'wind',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['mindfulness', 'presence', 'grounding', 'breathing', 'meditation'],
  },
  {
    id: 'perfectionism-recovery',
    nameKey: 'capabilityRegistry.perfectionismRecovery.name',
    descriptionKey: 'capabilityRegistry.perfectionismRecovery.description',
    detailsKey: 'capabilityRegistry.perfectionismRecovery.details',
    voiceTriggers: ['Help with perfectionism', 'I\'m never good enough', 'Imposter syndrome'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'medium',
    icon: 'check-circle',
    hasUI: true,
    uiPanel: 'emotional-toolkit',
    tags: ['perfectionism', 'imposter syndrome', 'good enough', 'standards'],
  },
  {
    id: 'procrastination',
    nameKey: 'capabilityRegistry.procrastination.name',
    descriptionKey: 'capabilityRegistry.procrastination.description',
    details: 'Procrastination isn\'t laziness—it\'s often fear or overwhelm in disguise. I can help you understand and overcome it.',
    detailsKey: 'capabilityRegistry.procrastination.details',
    voiceTriggers: ['Help with procrastination', 'I keep putting things off', 'Why can\'t I start'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'medium',
    icon: 'clock',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['procrastination', 'avoidance', 'productivity', 'starting'],
  },
  {
    id: 'neurodiversity',
    nameKey: 'capabilityRegistry.neurodiversity.name',
    descriptionKey: 'capabilityRegistry.neurodiversity.description',
    detailsKey: 'capabilityRegistry.neurodiversity.details',
    voiceTriggers: ['ADHD help', 'Autism support', 'Neurodivergent strategies'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'high',
    icon: 'brain',
    hasUI: true,
    uiPanel: 'growth-dashboard',
    tags: ['ADHD', 'autism', 'neurodiversity', 'executive function'],
    isBetterThanHuman: true,
    humanLimitation: 'Many people don\'t understand neurodivergent needs',
  },

  // RELATIONSHIPS
  {
    id: 'dating-support',
    nameKey: 'capabilityRegistry.datingSupport.name',
    descriptionKey: 'capabilityRegistry.datingSupport.description',
    detailsKey: 'capabilityRegistry.datingSupport.details',
    voiceTriggers: ['Dating advice', 'Help with dating', 'Should I text them'],
    persona: 'alex-chen',
    category: 'relationships',
    priority: 'medium',
    icon: 'heart',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['dating', 'relationships', 'love', 'romance'],
  },
  {
    id: 'infidelity-recovery',
    nameKey: 'capabilityRegistry.infidelityRecovery.name',
    descriptionKey: 'capabilityRegistry.infidelityRecovery.description',
    details: 'Whether you\'ve been betrayed or made a mistake, I can help you process and decide your path forward.',
    detailsKey: 'capabilityRegistry.infidelityRecovery.details',
    voiceTriggers: ['They cheated on me', 'I cheated', 'Betrayal recovery'],
    persona: 'nayan-patel',
    category: 'relationships',
    priority: 'medium',
    icon: 'heart-off',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['infidelity', 'cheating', 'betrayal', 'trust'],
  },
  {
    id: 'coming-out',
    nameKey: 'capabilityRegistry.comingOut.name',
    descriptionKey: 'capabilityRegistry.comingOut.description',
    detailsKey: 'capabilityRegistry.comingOut.details',
    voiceTriggers: ['Coming out help', 'I think I\'m gay', 'LGBTQ support'],
    persona: 'nayan-patel',
    category: 'relationships',
    priority: 'medium',
    icon: 'rainbow',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['LGBTQ', 'coming out', 'identity', 'queer'],
  },
  {
    id: 'faith-transition',
    nameKey: 'capabilityRegistry.faithTransition.name',
    descriptionKey: 'capabilityRegistry.faithTransition.description',
    details: 'Whether you\'re leaving a religion, finding a new one, or questioning everything, I can hold space for your journey.',
    detailsKey: 'capabilityRegistry.faithTransition.details',
    voiceTriggers: ['Faith crisis', 'Leaving my religion', 'Spiritual journey'],
    persona: 'nayan-patel',
    category: 'relationships',
    priority: 'medium',
    icon: 'sparkle',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['faith', 'religion', 'spiritual', 'belief', 'atheism'],
  },
  {
    id: 'blended-family',
    nameKey: 'capabilityRegistry.blendedFamily.name',
    descriptionKey: 'capabilityRegistry.blendedFamily.description',
    detailsKey: 'capabilityRegistry.blendedFamily.details',
    voiceTriggers: ['Step-parenting help', 'Blended family support', 'His kids hate me'],
    persona: 'maya-santos',
    category: 'relationships',
    priority: 'medium',
    icon: 'users',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['blended family', 'step-parent', 'remarriage', 'kids'],
  },
  {
    id: 'sandwich-generation',
    nameKey: 'capabilityRegistry.sandwichGeneration.name',
    descriptionKey: 'capabilityRegistry.sandwichGeneration.description',
    detailsKey: 'capabilityRegistry.sandwichGeneration.details',
    voiceTriggers: ['Sandwich generation help', 'Caring for parents and kids', 'Pulled in both directions'],
    persona: 'maya-santos',
    category: 'relationships',
    priority: 'medium',
    icon: 'layers',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['sandwich generation', 'caregiving', 'parents', 'children'],
  },

  // SUPERHUMAN SERVICES - Better than Human
  {
    id: 'predictive-coaching',
    nameKey: 'capabilityRegistry.predictiveCoaching.name',
    descriptionKey: 'capabilityRegistry.predictiveCoaching.description',
    details: 'Based on patterns I\'ve noticed, I can predict when you might struggle and check in proactively.',
    detailsKey: 'capabilityRegistry.predictiveCoaching.details',
    voiceTriggers: ['What patterns do you see', 'Predict my struggles', 'What should I watch for'],
    persona: 'ferni',
    category: 'superhuman',
    priority: 'high',
    icon: 'eye',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['patterns', 'prediction', 'anticipation', 'coaching'],
    isBetterThanHuman: true,
    humanLimitation: 'Humans can\'t track patterns objectively',
  },
  {
    id: 'capacity-guardian',
    nameKey: 'capabilityRegistry.capacityGuardian.name',
    descriptionKey: 'capabilityRegistry.capacityGuardian.description',
    detailsKey: 'capabilityRegistry.capacityGuardian.details',
    voiceTriggers: ['Check my capacity', 'Am I overcommitted', 'Energy check'],
    persona: 'maya-santos',
    category: 'superhuman',
    priority: 'high',
    icon: 'battery-charging',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['capacity', 'energy', 'burnout', 'commitments'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.capacityGuardian.humanLimitation',
  },
  {
    id: 'values-alignment',
    nameKey: 'capabilityRegistry.valuesAlignment.name',
    descriptionKey: 'capabilityRegistry.valuesAlignment.description',
    detailsKey: 'capabilityRegistry.valuesAlignment.details',
    voiceTriggers: ['Am I living my values', 'Values check', 'Am I being hypocritical'],
    persona: 'nayan-patel',
    category: 'superhuman',
    priority: 'high',
    icon: 'compass',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['values', 'alignment', 'integrity', 'authentic'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.valuesAlignment.humanLimitation',
  },
  {
    id: 'commitment-keeper',
    nameKey: 'capabilityRegistry.commitmentKeeper.name',
    descriptionKey: 'capabilityRegistry.commitmentKeeper.description',
    details: 'Every commitment you\'ve made to yourself or others—I remember and can help you keep them.',
    detailsKey: 'capabilityRegistry.commitmentKeeper.details',
    voiceTriggers: ['What commitments have I made', 'Did I promise something', 'Check my commitments'],
    persona: 'ferni',
    category: 'superhuman',
    priority: 'high',
    icon: 'check-square',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['commitments', 'promises', 'accountability', 'follow-through'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.commitmentKeeper.humanLimitation',
  },
  {
    id: 'life-narrative',
    nameKey: 'capabilityRegistry.lifeNarrative.name',
    descriptionKey: 'capabilityRegistry.lifeNarrative.description',
    detailsKey: 'capabilityRegistry.lifeNarrative.details',
    voiceTriggers: ['Tell me my story', 'What\'s my narrative', 'How far have I come'],
    persona: 'nayan-patel',
    category: 'superhuman',
    priority: 'high',
    icon: 'book-open',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['narrative', 'story', 'journey', 'growth', 'history'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.lifeNarrative.humanLimitation',
  },
  {
    id: 'dream-keeper',
    nameKey: 'capabilityRegistry.dreamKeeper.name',
    descriptionKey: 'capabilityRegistry.dreamKeeper.description',
    detailsKey: 'capabilityRegistry.dreamKeeper.details',
    voiceTriggers: ['What were my dreams', 'Remind me of my goals', 'What did I want'],
    persona: 'jordan-taylor',
    category: 'superhuman',
    priority: 'high',
    icon: 'star',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['dreams', 'aspirations', 'goals', 'ambitions'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.dreamKeeper.humanLimitation',
  },

  // PRACTICAL LIFE - Voice-only domains needing UI discovery
  {
    id: 'weather',
    nameKey: 'capabilityRegistry.weather.name',
    descriptionKey: 'capabilityRegistry.weather.description',
    voiceTriggers: ['What\'s the weather', 'Will it rain', 'Weather forecast'],
    persona: 'ferni',
    category: 'practical',
    priority: 'medium',
    icon: 'cloud',
    hasUI: false,
    tags: ['weather', 'forecast', 'rain', 'temperature'],
  },
  {
    id: 'reminders',
    nameKey: 'capabilityRegistry.reminders.name',
    descriptionKey: 'capabilityRegistry.reminders.description',
    voiceTriggers: ['Remind me to', 'Set a reminder', 'Don\'t let me forget'],
    persona: 'ferni',
    category: 'practical',
    priority: 'high',
    icon: 'bell',
    hasUI: false,
    tags: ['reminders', 'todo', 'remember', 'forget'],
  },
  {
    id: 'travel-planning',
    nameKey: 'capabilityRegistry.travelPlanning.name',
    descriptionKey: 'capabilityRegistry.travelPlanning.description',
    voiceTriggers: ['Help me plan a trip', 'Travel to', 'Vacation ideas'],
    persona: 'jordan-taylor',
    category: 'practical',
    priority: 'medium',
    icon: 'map',
    hasUI: false,
    tags: ['travel', 'vacation', 'trip', 'adventure'],
  },
  {
    id: 'local-search',
    nameKey: 'capabilityRegistry.localSearch.name',
    descriptionKey: 'capabilityRegistry.localSearch.description',
    voiceTriggers: ['Find a restaurant', 'Coffee shop near me', 'Best pizza'],
    persona: 'ferni',
    category: 'practical',
    priority: 'medium',
    icon: 'map-pin',
    hasUI: false,
    tags: ['restaurants', 'local', 'nearby', 'places'],
  },
  {
    id: 'learning',
    nameKey: 'capabilityRegistry.learning.name',
    descriptionKey: 'capabilityRegistry.learning.description',
    voiceTriggers: ['Help me learn', 'Study tips', 'How do I get better at'],
    persona: 'peter-john',
    category: 'practical',
    priority: 'medium',
    icon: 'book',
    hasUI: false,
    tags: ['learning', 'skills', 'study', 'improve'],
  },
  {
    id: 'finance-basics',
    nameKey: 'capabilityRegistry.financeBasics.name',
    descriptionKey: 'capabilityRegistry.financeBasics.description',
    voiceTriggers: ['Help with budgeting', 'Should I save or invest', 'Money advice'],
    persona: 'peter-john',
    category: 'practical',
    priority: 'medium',
    icon: 'dollar-sign',
    hasUI: false,
    tags: ['money', 'finance', 'budget', 'savings'],
  },
  {
    id: 'digital-wellness',
    nameKey: 'capabilityRegistry.digitalWellness.name',
    descriptionKey: 'capabilityRegistry.digitalWellness.description',
    voiceTriggers: ['Screen time help', 'Digital detox', 'Phone addiction'],
    persona: 'maya-santos',
    category: 'practical',
    priority: 'medium',
    icon: 'smartphone',
    hasUI: false,
    tags: ['screen time', 'digital', 'phone', 'tech'],
  },
  {
    id: 'home-management',
    nameKey: 'capabilityRegistry.homeManagement.name',
    descriptionKey: 'capabilityRegistry.homeManagement.description',
    voiceTriggers: ['Moving checklist', 'Home maintenance', 'Organize my space'],
    persona: 'jordan-taylor',
    category: 'practical',
    priority: 'low',
    icon: 'home',
    hasUI: false,
    tags: ['home', 'organize', 'moving', 'maintenance'],
  },
  {
    id: 'social-skills',
    nameKey: 'capabilityRegistry.socialSkills.name',
    descriptionKey: 'capabilityRegistry.socialSkills.description',
    voiceTriggers: ['Small talk help', 'How to make friends', 'Social anxiety'],
    persona: 'alex-chen',
    category: 'practical',
    priority: 'medium',
    icon: 'users',
    hasUI: false,
    tags: ['social', 'friends', 'networking', 'anxiety'],
  },
  {
    id: 'curiosity-wonder',
    nameKey: 'capabilityRegistry.curiosityWonder.name',
    descriptionKey: 'capabilityRegistry.curiosityWonder.description',
    voiceTriggers: ['I\'m curious about', 'Tell me something interesting', 'Explore with me'],
    persona: 'nayan-patel',
    category: 'growth',
    priority: 'medium',
    icon: 'sparkles',
    hasUI: false,
    tags: ['curiosity', 'wonder', 'explore', 'learn'],
  },
  {
    id: 'play-joy',
    nameKey: 'capabilityRegistry.playJoy.name',
    descriptionKey: 'capabilityRegistry.playJoy.description',
    voiceTriggers: ['Help me have more fun', 'I forgot how to play', 'Joy practice'],
    persona: 'jordan-taylor',
    category: 'growth',
    priority: 'medium',
    icon: 'smile',
    hasUI: false,
    tags: ['play', 'fun', 'joy', 'happiness'],
  },
  {
    id: 'body-relationship',
    nameKey: 'capabilityRegistry.bodyRelationship.name',
    descriptionKey: 'capabilityRegistry.bodyRelationship.description',
    voiceTriggers: ['Body image help', 'Accept my body', 'Body neutrality'],
    persona: 'maya-santos',
    category: 'emotional-support',
    priority: 'medium',
    icon: 'heart',
    hasUI: false,
    tags: ['body', 'image', 'acceptance', 'weight'],
  },

  // GROWTH & DEVELOPMENT - Additional domains
  {
    id: 'perfectionism',
    nameKey: 'capabilityRegistry.perfectionism.name',
    descriptionKey: 'capabilityRegistry.perfectionism.description',
    detailsKey: 'capabilityRegistry.perfectionism.details',
    voiceTriggers: ['Help with perfectionism', 'I can\'t stop criticizing myself', 'Nothing is ever good enough'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'medium',
    icon: 'check-circle',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['perfectionism', 'good enough', 'self-criticism'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.perfectionism.humanLimitation',
  },
  {
    id: 'procrastination',
    nameKey: 'capabilityRegistry.procrastination.name',
    descriptionKey: 'capabilityRegistry.procrastination.description',
    details: 'Procrastination often protects us from something. Let\'s explore what\'s underneath.',
    detailsKey: 'capabilityRegistry.procrastination.details',
    voiceTriggers: ['Help me stop procrastinating', 'I keep putting things off', 'Why can\'t I start'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'medium',
    icon: 'clock',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['procrastination', 'avoidance', 'motivation'],
  },
  {
    id: 'burnout-recovery',
    nameKey: 'capabilityRegistry.burnoutRecovery.name',
    descriptionKey: 'capabilityRegistry.burnoutRecovery.description',
    details: 'Burnout isn\'t weakness - it\'s a sign you cared too much. I can help you recover sustainably.',
    detailsKey: 'capabilityRegistry.burnoutRecovery.details',
    voiceTriggers: ['I\'m burned out', 'Help me recover from burnout', 'I have nothing left'],
    persona: 'maya-santos',
    category: 'growth',
    priority: 'high',
    icon: 'battery-low',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['burnout', 'exhaustion', 'recovery', 'rest'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.burnoutRecovery.humanLimitation',
  },
  {
    id: 'neurodiversity',
    nameKey: 'capabilityRegistry.neurodiversity.name',
    descriptionKey: 'capabilityRegistry.neurodiversity.description',
    details: 'ADHD, autism, and other neurotypes aren\'t disorders - they\'re different operating systems. I can help you work with your brain, not against it.',
    detailsKey: 'capabilityRegistry.neurodiversity.details',
    voiceTriggers: ['ADHD help', 'Autism support', 'My brain works differently'],
    persona: 'peter-john',
    category: 'growth',
    priority: 'high',
    icon: 'brain',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['adhd', 'autism', 'neurodivergent', 'different'],
    isBetterThanHuman: true,
    humanLimitation: 'Neurotypical friends often don\'t understand',
  },

  // RELATIONSHIPS - Additional domains
  {
    id: 'dating',
    nameKey: 'capabilityRegistry.dating.name',
    descriptionKey: 'capabilityRegistry.dating.description',
    detailsKey: 'capabilityRegistry.dating.details',
    voiceTriggers: ['Dating advice', 'Help me with dating', 'I hate dating apps'],
    persona: 'alex-chen',
    category: 'relationships',
    priority: 'medium',
    icon: 'heart',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['dating', 'apps', 'relationships', 'single'],
  },
  {
    id: 'infidelity',
    nameKey: 'capabilityRegistry.infidelity.name',
    descriptionKey: 'capabilityRegistry.infidelity.description',
    details: 'Whether you were betrayed or did the betraying, trust can be rebuilt. I\'m here for the long journey.',
    detailsKey: 'capabilityRegistry.infidelity.details',
    voiceTriggers: ['Help me trust again', 'I was cheated on', 'Recovering from infidelity'],
    persona: 'nayan-patel',
    category: 'relationships',
    priority: 'medium',
    icon: 'heart-handshake',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['infidelity', 'betrayal', 'trust', 'cheating'],
    isBetterThanHuman: true,
    humanLimitation: 'Friends take sides and can\'t stay neutral',
  },
  {
    id: 'coming-out',
    nameKey: 'capabilityRegistry.comingOut.name',
    descriptionKey: 'capabilityRegistry.comingOut.description',
    details: 'Coming out - to others or to yourself - is a profound journey. I\'m here without judgment.',
    detailsKey: 'capabilityRegistry.comingOut.details',
    voiceTriggers: ['Coming out support', 'I think I might be', 'Help with my identity'],
    persona: 'ferni',
    category: 'relationships',
    priority: 'medium',
    icon: 'rainbow',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['lgbtq', 'identity', 'coming out', 'sexuality'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.comingOut.humanLimitation',
  },
  {
    id: 'faith-transition',
    nameKey: 'capabilityRegistry.faithTransition.name',
    descriptionKey: 'capabilityRegistry.faithTransition.description',
    details: 'Whether you\'re finding faith, losing it, or changing it - spiritual transitions shake everything. I can hold space.',
    detailsKey: 'capabilityRegistry.faithTransition.details',
    voiceTriggers: ['Losing my faith', 'Spiritual crisis', 'I don\'t know what I believe'],
    persona: 'nayan-patel',
    category: 'relationships',
    priority: 'medium',
    icon: 'sunrise',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['faith', 'religion', 'spiritual', 'belief'],
  },

  // SPECIALTY - Better Than Human domains
  {
    id: 'reflection-games',
    nameKey: 'capabilityRegistry.reflectionGames.name',
    descriptionKey: 'capabilityRegistry.reflectionGames.description',
    detailsKey: 'capabilityRegistry.reflectionGames.details',
    voiceTriggers: ['Play a reflection game', 'Help me reflect', 'Deep questions'],
    persona: 'nayan-patel',
    category: 'growth',
    priority: 'medium',
    icon: 'sparkle',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['reflection', 'games', 'insight', 'questions'],
  },
  {
    id: 'midlife',
    nameKey: 'capabilityRegistry.midlife.name',
    descriptionKey: 'capabilityRegistry.midlife.description',
    details: 'Midlife isn\'t a crisis - it\'s an invitation to go deeper. I can help you find meaning in this transition.',
    detailsKey: 'capabilityRegistry.midlife.details',
    voiceTriggers: ['Midlife crisis', 'I\'m turning 40', 'What\'s the point'],
    persona: 'nayan-patel',
    category: 'growth',
    priority: 'medium',
    icon: 'compass',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['midlife', 'meaning', 'aging', 'purpose'],
  },
  {
    id: 'chronic-conditions',
    nameKey: 'capabilityRegistry.chronicConditions.name',
    descriptionKey: 'capabilityRegistry.chronicConditions.description',
    detailsKey: 'capabilityRegistry.chronicConditions.details',
    voiceTriggers: ['Living with chronic illness', 'Spoon theory', 'Managing my condition'],
    persona: 'maya-santos',
    category: 'life-coaching',
    priority: 'high',
    icon: 'activity',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['chronic', 'illness', 'spoons', 'pacing'],
    isBetterThanHuman: true,
    humanLimitation: 'Healthy people often don\'t understand invisible illness',
  },
  {
    id: 'trauma-support',
    nameKey: 'capabilityRegistry.traumaSupport.name',
    descriptionKey: 'capabilityRegistry.traumaSupport.description',
    details: 'I won\'t push you to relive anything. I can offer grounding, safety, and steady presence as you heal.',
    detailsKey: 'capabilityRegistry.traumaSupport.details',
    voiceTriggers: ['Trauma support', 'I need grounding', 'Help me feel safe'],
    persona: 'nayan-patel',
    category: 'emotional-support',
    priority: 'high',
    icon: 'shield-check',
    hasUI: true,
    uiPanel: 'life-coaching-hub',
    tags: ['trauma', 'grounding', 'safety', 'healing'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.traumaSupport.humanLimitation',
  },
  {
    id: 'community',
    nameKey: 'capabilityRegistry.community.name',
    descriptionKey: 'capabilityRegistry.community.description',
    details: 'Want to give back but don\'t know where to start? I can help you find your way to meaningful contribution.',
    detailsKey: 'capabilityRegistry.community.details',
    voiceTriggers: ['How can I give back', 'Volunteer ideas', 'Community service'],
    persona: 'jordan-taylor',
    category: 'practical',
    priority: 'low',
    icon: 'users',
    hasUI: false,
    tags: ['community', 'volunteer', 'giving', 'impact'],
  },

  // PERSONA MASTERY - Specialist domains
  {
    id: 'pattern-mastery',
    nameKey: 'capabilityRegistry.patternMastery.name',
    descriptionKey: 'capabilityRegistry.patternMastery.description',
    detailsKey: 'capabilityRegistry.patternMastery.details',
    voiceTriggers: ['Show me my patterns', 'What patterns do you see', 'Talk to Peter about patterns'],
    persona: 'peter-john',
    category: 'superhuman',
    priority: 'medium',
    icon: 'git-branch',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['patterns', 'analytics', 'insights', 'peter'],
    isBetterThanHuman: true,
    humanLimitation: 'Humans can\'t track patterns across hundreds of conversations',
  },
  {
    id: 'workflow-mastery',
    nameKey: 'capabilityRegistry.workflowMastery.name',
    descriptionKey: 'capabilityRegistry.workflowMastery.description',
    detailsKey: 'capabilityRegistry.workflowMastery.details',
    voiceTriggers: ['Help me work better', 'Optimize my workflow', 'Talk to Alex about productivity'],
    persona: 'alex-chen',
    category: 'superhuman',
    priority: 'medium',
    icon: 'layers',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['workflow', 'productivity', 'communication', 'alex'],
  },
  {
    id: 'milestone-mastery',
    nameKey: 'capabilityRegistry.milestoneMastery.name',
    descriptionKey: 'capabilityRegistry.milestoneMastery.description',
    detailsKey: 'capabilityRegistry.milestoneMastery.details',
    voiceTriggers: ['Help me plan a celebration', 'What milestones are coming', 'Talk to Jordan about events'],
    persona: 'jordan-taylor',
    category: 'superhuman',
    priority: 'medium',
    icon: 'star',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['milestones', 'celebrations', 'events', 'jordan'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.milestoneMastery.humanLimitation',
  },
  {
    id: 'habit-mastery',
    nameKey: 'capabilityRegistry.habitMastery.name',
    descriptionKey: 'capabilityRegistry.habitMastery.description',
    detailsKey: 'capabilityRegistry.habitMastery.details',
    voiceTriggers: ['Help me build a habit', 'Talk to Maya about habits', 'I keep failing at habits'],
    persona: 'maya-santos',
    category: 'superhuman',
    priority: 'medium',
    icon: 'activity',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['habits', 'coaching', 'behavior', 'maya'],
  },
  {
    id: 'wisdom-archive',
    nameKey: 'capabilityRegistry.wisdomArchive.name',
    descriptionKey: 'capabilityRegistry.wisdomArchive.description',
    detailsKey: 'capabilityRegistry.wisdomArchive.details',
    voiceTriggers: ['Share some wisdom', 'What would the ancients say', 'Talk to Nayan about life'],
    persona: 'nayan-patel',
    category: 'superhuman',
    priority: 'medium',
    icon: 'book-open',
    hasUI: true,
    uiPanel: 'superhuman-dashboard',
    tags: ['wisdom', 'philosophy', 'spiritual', 'nayan'],
    isBetterThanHuman: true,
    humanLimitationKey: 'capabilityRegistry.wisdomArchive.humanLimitation',
  },

];

// CAPABILITY GROUPS

export const CAPABILITY_GROUPS: CapabilityGroup[] = [
  {
    id: 'life-coaching',
    nameKey: 'capabilityRegistry.group.lifeCoaching.name',
    description: 'Support through life\'s biggest challenges',
    descriptionKey: 'capabilityRegistry.group.lifeCoaching.description',
    icon: 'heart',
    capabilities: CAPABILITIES.filter(c => c.category === 'life-coaching'),
  },
  {
    id: 'emotional-support',
    nameKey: 'capabilityRegistry.group.emotionalSupport.name',
    descriptionKey: 'capabilityRegistry.group.emotionalSupport.description',
    icon: 'shield',
    capabilities: CAPABILITIES.filter(c => c.category === 'emotional-support'),
  },
  {
    id: 'growth',
    nameKey: 'capabilityRegistry.group.growth.name',
    descriptionKey: 'capabilityRegistry.group.growth.description',
    icon: 'trending-up',
    capabilities: CAPABILITIES.filter(c => c.category === 'growth'),
  },
  {
    id: 'relationships',
    nameKey: 'capabilityRegistry.group.relationships.name',
    descriptionKey: 'capabilityRegistry.group.relationships.description',
    icon: 'users',
    capabilities: CAPABILITIES.filter(c => c.category === 'relationships'),
  },
  {
    id: 'practical',
    nameKey: 'capabilityRegistry.group.practical.name',
    descriptionKey: 'capabilityRegistry.group.practical.description',
    icon: 'map-pin',
    capabilities: CAPABILITIES.filter(c => c.category === 'practical'),
  },
  {
    id: 'superhuman',
    nameKey: 'capabilityRegistry.group.superhuman.name',
    description: 'What Ferni does that humans can\'t',
    descriptionKey: 'capabilityRegistry.group.superhuman.description',
    icon: 'sparkles',
    capabilities: CAPABILITIES.filter(c => c.category === 'superhuman'),
  },
];

// HELPERS

export function getCapability(id: string): Capability | undefined {
  return CAPABILITIES.find(c => c.id === id);
}

export function getCapabilitiesForPersona(personaId: PersonaId): Capability[] {
  return CAPABILITIES.filter(c => c.persona === personaId);
}

export function getCapabilitiesByCategory(category: CapabilityCategory): Capability[] {
  return CAPABILITIES.filter(c => c.category === category);
}

export function getBetterThanHumanCapabilities(): Capability[] {
  return CAPABILITIES.filter(c => c.isBetterThanHuman);
}

export function searchCapabilities(query: string): Capability[] {
  const lowerQuery = query.toLowerCase();
  return CAPABILITIES.filter(c =>
    c.name.toLowerCase().includes(lowerQuery) ||
    c.description.toLowerCase().includes(lowerQuery) ||
    c.tags.some(t => t.toLowerCase().includes(lowerQuery)) ||
    c.voiceTriggers.some(v => v.toLowerCase().includes(lowerQuery))
  );
}

export function getContextualCapabilities(context: {
  emotion?: string;
  topics?: string[];
}): Capability[] {
  const relevant: Capability[] = [];
  
  // Emotion-based suggestions
  if (context.emotion) {
    const emotionMap: Record<string, string[]> = {
      'sad': ['grief-support', 'breakup-recovery', 'connection-loneliness'],
      'angry': ['anger-processing', 'resentment-release', 'boundaries-toolkit'],
      'anxious': ['anxiety-support', 'trauma-support', 'presence-mindfulness'],
      'stressed': ['burnout-recovery', 'capacity-guardian', 'presence-mindfulness'],
      'lost': ['meaning-purpose', 'life-transitions', 'second-chances'],
    };
    
    const ids = emotionMap[context.emotion] || [];
    ids.forEach(id => {
      const cap = getCapability(id);
      if (cap) relevant.push(cap);
    });
  }
  
  // Topic-based suggestions
  if (context.topics) {
    context.topics.forEach(topic => {
      const matches = CAPABILITIES.filter(c => 
        c.tags.some(t => t.toLowerCase().includes(topic.toLowerCase()))
      );
      relevant.push(...matches);
    });
  }
  
  // Deduplicate
  return [...new Set(relevant)];
}
