/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ToolPrediction {
  toolId: string
  confidence: number
}
export interface RouterPredictResult {
  predictions: Array<ToolPrediction>
  latencyMs: number
}
export interface RouterConfig {
  modelPath: string
  tokenizerPath: string
  labelMapPath: string
  maxLength: number
  threshold: number
  topK: number
  /** Number of threads for inference (0 = auto-detect based on CPU cores) */
  numThreads?: number
}
/**
 * Quick prediction without creating a router instance
 * (useful for one-off predictions, but slower due to model loading)
 */
export declare function quickPredict(modelPath: string, tokenizerPath: string, labelMapPath: string, query: string): RouterPredictResult
/**
 * Compute cosine similarity between two embedding vectors.
 * Uses SIMD instructions when available (AVX2/SSE/NEON).
 *
 * Returns a value between -1.0 and 1.0.
 */
export declare function cosineSimilarity(a: Array<number>, b: Array<number>): number
/**
 * Batch cosine similarity: compare one query vector against many candidates.
 * Returns similarity scores in the same order as candidates.
 * Uses parallel processing via Rayon.
 */
export declare function batchCosineSimilarity(query: Array<number>, candidates: Array<Array<number>>): Array<number>
/**
 * Compute Euclidean distance between two embedding vectors.
 * Returns the L2 distance (sqrt of sum of squared differences).
 */
export declare function euclideanDistance(a: Array<number>, b: Array<number>): number
/**
 * Batch euclidean distance: compare one query vector against many candidates.
 * Returns distance values in the same order as candidates.
 * Uses parallel processing via Rayon.
 */
export declare function batchEuclideanDistance(query: Array<number>, candidates: Array<Array<number>>): Array<number>
/**
 * Batch cosine similarity with F32 embeddings for maximum performance.
 * Takes flat arrays for zero-copy transfer from JavaScript.
 *
 * # Arguments
 * * `query` - Query embedding (1536 floats for OpenAI embeddings)
 * * `candidates` - Flat array of candidate embeddings (n * dim floats)
 * * `candidate_count` - Number of candidates
 *
 * # Returns
 * Array of similarity scores
 */
export declare function batchCosineSimilarityF32(query: Float32Array, candidates: Float32Array, candidateCount: number): Float32Array
/**
 * Euclidean distance with F32 embeddings for maximum performance.
 * Takes flat arrays for zero-copy transfer from JavaScript.
 *
 * # Arguments
 * * `a` - First embedding (Float32Array)
 * * `b` - Second embedding (Float32Array)
 *
 * # Returns
 * Euclidean distance (L2 norm of difference)
 */
export declare function euclideanDistanceF32(a: Float32Array, b: Float32Array): number
/**
 * Batch Euclidean distance with F32 embeddings for maximum performance.
 * Takes flat arrays for zero-copy transfer from JavaScript.
 *
 * # Arguments
 * * `query` - Query embedding (dim floats)
 * * `candidates` - Flat array of candidate embeddings (n * dim floats)
 * * `candidate_count` - Number of candidates
 *
 * # Returns
 * Array of distance values
 */
export declare function batchEuclideanDistanceF32(query: Float32Array, candidates: Float32Array, candidateCount: number): Float32Array
/**
 * Normalize a vector to unit length (L2 normalization).
 * Returns a new Float32Array with the normalized vector.
 *
 * # Arguments
 * * `v` - Vector to normalize (Float32Array)
 *
 * # Returns
 * Normalized vector with L2 norm = 1
 */
export declare function normalizeVectorF32(v: Float32Array): Float32Array
/**
 * Batch normalize multiple vectors to unit length.
 * Takes flat array of embeddings and normalizes each in-place.
 *
 * # Arguments
 * * `embeddings` - Flat array of embeddings (n * dim floats)
 * * `embedding_count` - Number of embeddings
 *
 * # Returns
 * Flat array of normalized embeddings
 */
export declare function batchNormalizeVectorsF32(embeddings: Float32Array, embeddingCount: number): Float32Array
/**
 * Compute L2 norm (magnitude) of a vector.
 * Uses SIMD-accelerated dot product.
 */
export declare function vectorNormF32(v: Float32Array): number
/**
 * Compute centroid (mean vector) of multiple embeddings.
 * Useful for clustering and averaging embeddings.
 *
 * # Arguments
 * * `embeddings` - Flat array of embeddings (n * dim floats)
 * * `embedding_count` - Number of embeddings
 *
 * # Returns
 * Centroid vector (dim floats)
 */
export declare function computeCentroidF32(embeddings: Float32Array, embeddingCount: number): Float32Array
/** Result for similar pairs search. */
export interface SimilarPair {
  firstIdx: number
  secondIdx: number
  similarity: number
}
/**
 * Find all pairs of embeddings with similarity above threshold.
 * Optimized for O(n²) pairwise comparison in memory deduplication.
 *
 * # Arguments
 * * `embeddings` - Flat array of embeddings (n * dim floats)
 * * `embedding_count` - Number of embeddings
 * * `dim` - Embedding dimension (e.g., 1536 for OpenAI)
 * * `threshold` - Minimum similarity threshold (0-1)
 *
 * # Returns
 * Array of SimilarPair objects for all pairs above threshold
 */
export declare function findSimilarPairsF32(embeddings: Float32Array, embeddingCount: number, dim: number, threshold: number): Array<SimilarPair>
/** Result for top-K similarity search. */
export interface TopKResult {
  indices: Array<number>
  similarities: Array<number>
}
/**
 * Find top-K most similar embeddings to a query.
 * Uses parallel computation with local top-K per thread.
 *
 * # Arguments
 * * `query` - Query embedding (dim floats)
 * * `candidates` - Flat array of candidate embeddings (n * dim floats)
 * * `candidate_count` - Number of candidates
 * * `k` - Number of top results to return
 * * `min_similarity` - Minimum similarity threshold (0-1)
 *
 * # Returns
 * TopKResult with indices and similarity scores
 */
export declare function topKSimilarF32(query: Float32Array, candidates: Float32Array, candidateCount: number, k: number, minSimilarity: number): TopKResult
/**
 * Compute Jaccard similarity between two texts using k-shingles.
 * Returns a value between 0.0 and 1.0.
 */
export declare function textSimilarity(text1: string, text2: string, shingleSize?: number | undefined | null): number
/**
 * Batch text similarity: compare one query text against many candidates.
 * Returns similarity scores in the same order as candidates.
 */
export declare function batchTextSimilarity(query: string, candidates: Array<string>, shingleSize?: number | undefined | null): Array<number>
/** MinHash signature for LSH. */
export interface MinHashSignature {
  id: string
  signature: Array<number>
}
/**
 * Generate MinHash signature for a text.
 * Uses xxhash for fast hashing with different seeds.
 */
export declare function computeMinhash(text: string, numHashes: number, shingleSize?: number | undefined | null): MinHashSignature
/**
 * Estimate Jaccard similarity from MinHash signatures.
 * Returns a value between 0.0 and 1.0.
 */
export declare function estimateSimilarityFromMinhash(sig1: Array<number>, sig2: Array<number>): number
/**
 * Find duplicate pairs from a batch of texts using LSH.
 * Returns pairs of indices with their similarity scores.
 */
export interface DuplicatePair {
  firstIdx: number
  secondIdx: number
  similarity: number
}
export declare function findDuplicatesLsh(texts: Array<string>, threshold: number, numHashes?: number | undefined | null, numBands?: number | undefined | null): Array<DuplicatePair>
/** Input for a single tool profile to be scored */
export interface ToolProfileInput {
  toolId: string
  /** Regex patterns as strings (will be compiled in Rust) */
  patterns: Array<string>
  /** Keywords with their weights: [keyword, weight, keyword, weight, ...] */
  keywordsFlat: Array<string>
  keywordWeightsFlat: Array<number>
  /** Whether this tool has an embedding (index in embeddings array) */
  hasEmbedding: boolean
  embeddingIndex?: number
}
/** Output for a scored tool */
export interface ToolScoringResult {
  toolId: string
  score: number
  patternScore: number
  keywordScore: number
  embeddingScore: number
  matchedPatternCount: number
  matchedKeywordCount: number
}
/** Configuration for batch scoring */
export interface BatchScoringConfig {
  patternWeight: number
  keywordWeight: number
  embeddingWeight: number
  earlyTerminationThreshold: number
  minScoreThreshold: number
}
/**
 * Batch score all tools against a query with parallel processing and early termination.
 *
 * This is the main optimization function for the semantic router.
 * It compiles regex patterns once, scores all tools in parallel using Rayon,
 * and supports early termination when a high-confidence match is found.
 *
 * # Arguments
 * * `query` - The user query to match against tools
 * * `profiles` - Array of tool profiles with patterns and keywords
 * * `query_embedding` - Optional query embedding (flat f32 array)
 * * `tool_embeddings` - Flat array of all tool embeddings (n * dim)
 * * `embedding_dim` - Dimension of embeddings (e.g., 1536 for OpenAI)
 * * `config` - Scoring configuration (weights, thresholds)
 *
 * # Returns
 * Array of scoring results, sorted by score descending
 */
export declare function batchScoreTools(query: string, profiles: Array<ToolProfileInput>, queryEmbedding?: Float32Array | undefined | null, toolEmbeddings?: Float32Array | undefined | null, embeddingDim?: number | undefined | null, config?: BatchScoringConfig | undefined | null): Array<ToolScoringResult>
/** Get library version and capabilities. */
export interface LibraryInfo {
  version: string
  simdAvailable: boolean
  parallelThreads: number
}
export declare function getLibraryInfo(): LibraryInfo
/** Parsed function call from TTS stream */
export interface NativeFunctionCall {
  /** Tool name */
  fnName: string
  /** Arguments as JSON string */
  argsJson: string
  /** Start position in original text */
  startPos: number
  /** End position in original text */
  endPos: number
}
/** Result of scanning text for function calls */
export interface NativeScanResult {
  /** All detected function calls */
  calls: Array<NativeFunctionCall>
  /** Text with function calls removed */
  cleanText: string
  /** Whether any function calls were found */
  hasCalls: boolean
}
/**
 * Fast check if text likely contains a JSON function call
 *
 * Uses SIMD-accelerated byte searching before regex
 */
export declare function likelyContainsFunctionCall(text: string): boolean
/**
 * Extract function calls from TTS text using SIMD-accelerated parsing
 *
 * Returns all function calls and the cleaned text
 */
export declare function extractFunctionCalls(text: string): NativeScanResult
/**
 * Parse a single JSON function call string
 *
 * Expected format: {"fn":"toolName","args":{...}}
 */
export declare function parseFunctionCall(jsonStr: string): NativeFunctionCall | null
/** Register known tool names for faster detection */
export declare function registerToolNames(names: Array<string>): void
/** Clear all registered tool names */
export declare function clearToolNames(): void
/** Check if a tool name is registered */
export declare function isKnownTool(name: string): boolean
/** Validate JSON string quickly using SIMD */
export declare function isValidJson(jsonStr: string): boolean
/** Get count of registered tools */
export declare function getToolCount(): number
/**
 * Parse JSON to a value (returns JSON string of parsed result)
 * Uses SIMD-accelerated simd-json for 2-5x faster parsing
 */
export declare function parseJsonFast(jsonStr: string): string | null
/** Extracted SSML tag */
export interface NativeSsmlTag {
  /** Tag type (break, emotion, speed, etc.) */
  tagType: string
  /** Full match text */
  fullMatch: string
  /** Start position */
  startPos: number
  /** End position */
  endPos: number
}
/** SSML analysis result */
export interface NativeSsmlAnalysis {
  /** Number of tags found */
  tagCount: number
  /** Plain text with SSML removed */
  plainText: string
  /** Total break time in milliseconds */
  totalBreakMs: number
  /** Detected emotions */
  emotions: Array<string>
  /** Speed modifiers found */
  speeds: Array<number>
  /** Has any SSML tags */
  hasSsml: boolean
}
/** Fast check if text contains any SSML tags */
export declare function containsSsml(text: string): boolean
/** Strip all SSML tags from text */
export declare function stripSsml(text: string): string
/** Analyze SSML in text and extract all tags */
export declare function analyzeSsml(text: string): NativeSsmlAnalysis
/** Batch analyze multiple texts in parallel */
export declare function batchAnalyzeSsml(texts: Array<string>): Array<NativeSsmlAnalysis>
/** Extract break tags and their durations */
export declare function extractBreaks(text: string): Array<number>
/** Extract emotion tags */
export declare function extractEmotions(text: string): Array<string>
/** Insert break tag at specified position */
export declare function insertBreak(text: string, position: number, durationMs: number): string
/** Insert emotion tag at specified position */
export declare function insertEmotion(text: string, position: number, emotion: string): string
/** Wrap text with speed modifier */
export declare function wrapWithSpeed(text: string, speedRatio: number): string
/** Register custom regex pattern for matching */
export declare function registerCustomPattern(name: string, pattern: string): boolean
/** Match custom pattern and return matches */
export declare function matchCustomPattern(name: string, text: string): Array<string>
/** Clear all custom patterns */
export declare function clearCustomPatterns(): void
/** Statistics result for time-series data */
export interface TimeSeriesStats {
  mean: number
  variance: number
  stdDev: number
  min: number
  max: number
  count: number
}
/**
 * SIMD-accelerated single-pass statistics calculation.
 * Computes mean, variance, min, max in one pass through the data.
 */
export declare function calculateStatisticsF32(values: Float32Array): TimeSeriesStats
/**
 * SIMD-accelerated linear regression (least squares).
 * Returns the slope of the best-fit line.
 */
export declare function calculateLinearTrendF32(values: Float32Array): number
/** Holt's double exponential smoothing result */
export interface ExponentialSmoothingResult {
  /** Smoothed level */
  level: number
  /** Trend component */
  trend: number
  /** Forecast (level + trend) */
  forecast: number
}
/**
 * SIMD-accelerated Holt's double exponential smoothing.
 * Returns the final smoothed values for forecasting.
 */
export declare function exponentialSmoothingF32(values: Float32Array, alpha: number, beta: number): ExponentialSmoothingResult
/** Seasonality analysis result */
export interface SeasonalityResult {
  /** Detected seasonality strength (0-1) */
  strength: number
  /** Detected period (if any) */
  period: number
  /** Seasonal indices for each period position */
  indices: Array<number>
}
/**
 * SIMD-accelerated seasonality detection.
 * Analyzes data for periodic patterns.
 */
export declare function calculateSeasonalityF32(values: Float32Array, maxPeriod: number): SeasonalityResult
/** Batch statistics for multiple time series in parallel */
export declare function batchCalculateStatisticsF32(seriesFlat: Float32Array, seriesLengths: Array<number>): Array<TimeSeriesStats>
/** Build the guidance block automaton (call once at startup) */
export declare function buildGuidanceAutomaton(): boolean
/**
 * Strip guidance blocks from text using pre-built automaton.
 * Returns cleaned text with all guidance blocks removed.
 */
export declare function stripGuidanceBlocks(text: string): string
/** Check if text contains any guidance blocks (fast check) */
export declare function containsGuidanceBlocks(text: string): boolean
/** Clear the guidance automaton */
export declare function clearGuidanceAutomaton(): void
/** Input injection for deduplication */
export interface InjectionInput {
  id: string
  content: string
  priority: number
  source: string
}
/** Result of deduplication - which injections to keep */
export interface DeduplicationResult {
  /** IDs of injections to keep (in order) */
  keepIds: Array<string>
  /** IDs of duplicates that were removed */
  removedIds: Array<string>
  /** Number of comparisons made */
  comparisons: number
}
/**
 * Deduplicate injections based on semantic similarity.
 * Returns IDs of injections to keep and those removed.
 *
 * # Arguments
 * * `injections` - Array of injection inputs
 * * `similarity_threshold` - Threshold for considering duplicates (0-1), default 0.7
 *
 * # Algorithm
 * 1. Extract keywords from each injection
 * 2. For each pair, compute semantic similarity
 * 3. When duplicates found, keep the one with higher priority (or first if equal)
 */
export declare function deduplicateInjections(injections: Array<InjectionInput>, similarityThreshold?: number | undefined | null): DeduplicationResult
/** Compute Jaccard similarity between two texts using keywords */
export declare function keywordJaccardSimilarity(text1: string, text2: string): number
/** Compute semantic similarity between two texts (accounts for related words) */
export declare function textSemanticSimilarity(text1: string, text2: string): number
/** Result of message analysis */
export interface MessageAnalysisResult {
  /** Whether the message is a wrap-up signal */
  isWrapUp: boolean
  /** Confidence in wrap-up detection (0-1) */
  wrapUpConfidence: number
  /** Whether the message is a question */
  isQuestion: boolean
  /** Whether the message is a greeting */
  isGreeting: boolean
  /** Detected sentiment (-1 to 1) */
  sentiment: number
  /** Dominant emotion category */
  emotionCategory: string
  /** Word count */
  wordCount: number
  /** Character count */
  charCount: number
  /** Keywords extracted */
  keywords: Array<string>
}
/**
 * Analyze a user message for various signals.
 *
 * Detects:
 * - Wrap-up signals (goodbye, thanks, etc.)
 * - Questions
 * - Greetings
 * - Sentiment/emotion
 * - Basic statistics
 */
export declare function analyzeMessage(text: string): MessageAnalysisResult
/** Batch analyze multiple messages in parallel */
export declare function batchAnalyzeMessages(messages: Array<string>): Array<MessageAnalysisResult>
/** Voice emotional indicators */
export interface VoiceEmotionInput {
  /** Speech rate relative to normal (1.0 = normal) */
  speechRate: number
  /** Volume level relative to normal (1.0 = normal) */
  volume: number
  /** Pitch variation (0-1, higher = more variation) */
  pitchVariation: number
  /** Pause frequency (pauses per 100 words) */
  pauseFrequency: number
}
/** Emotional state result */
export interface EmotionalStateResult {
  /** Primary detected emotion */
  primaryEmotion: string
  /** Confidence in primary emotion (0-1) */
  confidence: number
  /** Emotional intensity (0-1) */
  intensity: number
  /** Whether there's a voice-text mismatch */
  hasMismatch: boolean
  /** Description of mismatch if present */
  mismatchDescription: string
  /** Suggested response tone */
  suggestedTone: string
}
/**
 * Detect emotional state from text and optional voice indicators.
 *
 * Combines text sentiment with voice prosody to detect:
 * - Primary emotion
 * - Emotional intensity
 * - Voice-text mismatches (e.g., saying "I'm fine" with stressed voice)
 */
export declare function detectEmotionalState(text: string, voice?: VoiceEmotionInput | undefined | null): EmotionalStateResult
/** Input for tracking conversation dynamics */
export interface ConversationTurnInput {
  /** Turn number (0-indexed) */
  turnNumber: number
  /** Speaker: "user" or "agent" */
  speaker: string
  /** Word count of this turn */
  wordCount: number
  /** Duration in seconds (if available) */
  durationSecs?: number
  /** Sentiment of this turn (-1 to 1) */
  sentiment: number
  /** Whether this turn had a question */
  hasQuestion: boolean
}
/** Conversation dynamics analysis result */
export interface ConversationDynamicsResult {
  /** Average words per turn (user) */
  avgUserWords: number
  /** Average words per turn (agent) */
  avgAgentWords: number
  /** Turn-taking ratio (user turns / total) */
  turnRatio: number
  /** Engagement score (0-1) */
  engagementScore: number
  /** Conversation arc phase */
  conversationPhase: string
  /** Sentiment trajectory (rising, falling, stable) */
  sentimentTrend: string
  /** Question density (questions per turn) */
  questionDensity: number
  /** Suggested pacing (faster, slower, maintain) */
  suggestedPacing: string
}
/**
 * Analyze conversation dynamics from turn history.
 *
 * Tracks:
 * - Engagement patterns
 * - Sentiment trajectory
 * - Turn-taking balance
 * - Conversation phase (opening, exploring, deepening, closing)
 */
export declare function analyzeConversationDynamics(turns: Array<ConversationTurnInput>): ConversationDynamicsResult
/** Result of a pattern match */
export interface AhoCorasickMatch {
  /** Index of the matched pattern */
  patternIdx: number
  /** Start position in text */
  start: number
  /** End position in text */
  end: number
  /** The matched text */
  matchedText: string
}
/** Result of scanning text for patterns */
export interface AhoCorasickScanResult {
  /** All matches found */
  matches: Array<AhoCorasickMatch>
  /** Whether any patterns matched */
  hasMatches: boolean
  /** Number of matches */
  matchCount: number
}
/**
 * Build an Aho-Corasick automaton from a list of patterns.
 *
 * This compiles the patterns into a single automaton that can match
 * all patterns simultaneously in O(n) time.
 *
 * # Arguments
 * * `patterns` - List of patterns to match (usually tool names)
 *
 * # Returns
 * True if automaton was built successfully
 */
export declare function buildToolNameAutomaton(patterns: Array<string>): boolean
/**
 * Scan text for tool names using the pre-built automaton.
 *
 * This is the main function for tool-call-sanitizer.ts to use.
 * It scans text in O(n) time for all registered tool names.
 *
 * # Arguments
 * * `text` - Text to scan for tool names
 *
 * # Returns
 * Scan result with all matches
 */
export declare function scanForToolNames(text: string): AhoCorasickScanResult
/**
 * Check if text contains any registered tool name.
 *
 * Fast early-exit check - stops at first match.
 */
export declare function containsAnyToolName(text: string): boolean
/** Get the tool name for a pattern index. */
export declare function getToolNameByIndex(index: number): string | null
/** Get the number of registered tool name patterns. */
export declare function getToolNamePatternCount(): number
/** Clear the tool name automaton. */
export declare function clearToolNameAutomaton(): void
/** NAPI-compatible disfluency counts */
export interface NapiDisfluencyCounts {
  repetitions: number
  prolongations: number
  interjections: number
  revisions: number
  restarts: number
  trailing: number
  pauseFillers: number
  hesitations: number
}
/** NAPI-compatible fluency analysis result */
export interface NapiFluencyAnalysisResult {
  counts: NapiDisfluencyCounts
  wordCount: number
  fluencyScore: number
  detectedInterjections: Array<string>
  detectedProlongations: Array<string>
  hasSignificantDisfluencies: boolean
}
/** Analyze text for speech disfluencies (repetitions, interjections, etc.) */
export declare function analyzeFluency(text: string): NapiFluencyAnalysisResult
/** Batch analyze multiple texts for fluency */
export declare function batchAnalyzeFluency(texts: Array<string>): Array<NapiFluencyAnalysisResult>
/** Quick check if text likely contains disfluencies */
export declare function likelyHasDisfluencies(text: string): boolean
/** Extract only interjections from text */
export interface NapiInterjectionMatch {
  text: string
  start: number
  end: number
}
export declare function extractInterjections(text: string): Array<NapiInterjectionMatch>
/** Count interjections in text (fast path returning count only) */
export declare function countInterjections(text: string): number
/** NAPI-compatible phrase match */
export interface NapiTurnPhraseMatch {
  phrase: string
  phraseType: string
  start: number
  end: number
}
/** NAPI-compatible turn analysis result */
export interface NapiTurnAnalysisResult {
  matches: Array<NapiTurnPhraseMatch>
  turnFinalCount: number
  continuationCount: number
  likelyTurnComplete: boolean
  likelyContinuing: boolean
}
/** Analyze text for turn boundary indicators */
export declare function analyzeTurn(text: string): NapiTurnAnalysisResult
/** Check if text contains turn-final phrases */
export declare function hasTurnFinal(text: string): boolean
/** Check if text contains continuation phrases */
export declare function hasContinuation(text: string): boolean
/** Get probability that turn is complete (0.0 to 1.0) */
export declare function turnCompleteProbability(text: string): number
/** Batch analyze multiple texts for turn boundaries */
export declare function batchAnalyzeTurn(texts: Array<string>): Array<NapiTurnAnalysisResult>
/** NAPI-compatible extracted signal */
export interface NapiExtractedSignal {
  signalType: string
  value: string
  context: string
  start: number
  end: number
  confidence: number
}
/** NAPI-compatible signal extraction result */
export interface NapiSignalExtractionResult {
  signals: Array<NapiExtractedSignal>
  hasSignals: boolean
  highValueCount: number
}
/** Extract human signals from text (dates, values, fears, etc.) */
export declare function extractSignals(text: string): NapiSignalExtractionResult
/** Batch extract signals from multiple texts */
export declare function batchExtractSignals(texts: Array<string>): Array<NapiSignalExtractionResult>
/** Quick check if text likely contains signals */
export declare function likelyHasSignals(text: string): boolean
/** Extract only date signals (optimized) */
export declare function extractDateSignals(text: string): Array<NapiExtractedSignal>
/** Extract only high-value signals (birthdays, anniversaries, relationships) */
export declare function extractHighValueSignals(text: string): Array<NapiExtractedSignal>
/** Quick check if text has memorable signals (alias for likely_has_signals) */
export declare function hasMemorableSignals(text: string): boolean
/** NAPI-compatible text statistics */
export interface NapiTextStats {
  words: number
  tokensApprox: number
  chars: number
  bytes: number
  sentences: number
  lines: number
  avgWordLength: number
}
/** Count words in text */
export declare function countWords(text: string): number
/** Count approximate tokens (OpenAI-style) */
export declare function countTokensApprox(text: string): number
/** Count characters */
export declare function countChars(text: string): number
/** Count sentences */
export declare function countSentences(text: string): number
/** Count bytes */
export declare function countBytes(text: string): number
/** Count lines */
export declare function countLines(text: string): number
/** Get comprehensive text statistics */
export declare function getTextStats(text: string): NapiTextStats
/** Batch count words for multiple texts */
export declare function batchCountWords(texts: Array<string>): Array<number>
/** Batch count tokens for multiple texts */
export declare function batchCountTokens(texts: Array<string>): Array<number>
/** Batch get text statistics for multiple texts */
export declare function batchGetStats(texts: Array<string>): Array<NapiTextStats>
/** Check if text exceeds token limit */
export declare function exceedsTokenLimit(text: string, limit: number): boolean
/** Truncate text to approximate token limit */
export declare function truncateToTokens(text: string, maxTokens: number): string
/** Audio features extracted from FFT analysis */
export interface NapiAudioFeatures {
  rmsEnergy: number
  zeroCrossingRate: number
  spectralCentroid: number
  spectralFlux: number
  spectralRolloff: number
  dominantBin: number
  dominantMagnitude: number
}
/** Get RMS energy of audio samples (SIMD-accelerated) */
export declare function getRmsEnergy(samples: Array<number>): number
/** Get zero crossing rate of audio samples */
export declare function getZeroCrossingRate(samples: Array<number>): number
/** Cache statistics */
export interface NapiCacheStats {
  size: number
  capacity: number
  utilization: number
}
/** Compute SHA256 hash of text (returns hex string) */
export declare function hashTextSha256(text: string): string
/** Batch compute SHA256 hashes for multiple texts */
export declare function batchHashTextsSha256(texts: Array<string>): Array<string>
/** ONNX Router for FTIS V3 inference */
export declare class OnnxRouter {
  /** Create a new ONNX router instance */
  constructor(config: RouterConfig)
  /** Predict tools for a query */
  predict(query: string): RouterPredictResult
  /** Get the number of supported tools */
  getNumTools(): number
  /** Get all tool labels */
  getLabels(): Array<string>
  /**
   * Warmup the model by running a dummy inference
   * Call this at startup to avoid cold-start latency on first real request
   */
  warmup(): number
}
/**
 * Pre-compiled pattern matcher for repeated scoring
 * Stores compiled regex patterns for efficient reuse across queries
 */
export declare class PatternMatcher {
  /** Create a new pattern matcher */
  constructor()
  /** Add patterns for a tool (compiles regex once) */
  addToolPatterns(toolId: string, patterns: Array<string>): void
  /**
   * Score a query against all registered tools
   * Returns: [tool_id, score, tool_id, score, ...]
   */
  scoreAllPatterns(query: string): Array<string>
  /** Get the number of registered tools */
  toolCount(): number
}
/**
 * Create an Aho-Corasick automaton without global state.
 *
 * Returns an opaque handle that can be used for matching.
 * This is useful when you need multiple independent matchers.
 */
export declare class AhoCorasickMatcher {
  /** Create a new matcher from patterns. */
  constructor(patterns: Array<string>)
  /** Scan text for matches. */
  scan(text: string): AhoCorasickScanResult
  /** Check if text contains any pattern (fast early-exit). */
  containsAny(text: string): boolean
  /** Get the pattern at an index. */
  getPattern(index: number): string | null
  /** Get the number of patterns. */
  patternCount(): number
  /**
   * Replace all matches with a replacement function result.
   * The replacement is indexed by pattern index.
   */
  replaceAll(text: string, replacements: Array<string>): string
}
/** FFT processor instance for session-scoped audio analysis */
export declare class NapiFftProcessor {
  /** Create a new FFT processor with specified size (typically 1024 or 2048) */
  constructor(fftSize: number)
  /** Process audio frame and return magnitude spectrum */
  processFrame(samples: Array<number>): Array<number>
  /** Compute spectral flux (change from previous frame) - higher = onset/transient */
  computeSpectralFlux(samples: Array<number>): number
  /** Get spectral centroid (brightness measure) */
  getSpectralCentroid(sampleRate: number): number
  /** Get spectral rolloff (frequency bin containing threshold% of energy) */
  getSpectralRolloff(threshold: number): number
  /** Extract all audio features from a frame */
  extractFeatures(samples: Array<number>, sampleRate: number): NapiAudioFeatures
  /** Get FFT size */
  fftSize(): number
  /** Get number of frequency bins */
  numBins(): number
  /** Reset processor (clear previous frame data) */
  reset(): void
}
/** Thread-safe embedding cache with SHA256 keys and LRU eviction */
export declare class NapiEmbeddingCache {
  /** Create a new embedding cache with specified capacity and TTL (ms) */
  constructor(maxSize: number, defaultTtlMs: number)
  /** Get an embedding from the cache (returns null if not found or expired) */
  get(text: string, currentTimeMs: number): Array<number> | null
  /** Put an embedding in the cache */
  put(text: string, embedding: Array<number>, currentTimeMs: number): void
  /** Put an embedding with custom TTL */
  putWithTtl(text: string, embedding: Array<number>, currentTimeMs: number, ttlMs: number): void
  /** Remove an entry from the cache */
  remove(text: string): boolean
  /** Clear all entries from the cache */
  clear(): void
  /** Get the current number of entries */
  len(): number
  /** Check if the cache is empty */
  isEmpty(): boolean
  /** Get cache capacity */
  capacity(): number
  /** Prune expired entries, returns count of entries removed */
  pruneExpired(currentTimeMs: number): number
  /** Get cache statistics */
  stats(): NapiCacheStats
}
