/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'ferni-perf.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.android-arm64.node')
          } else {
            nativeBinding = require('@ferni/perf-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'ferni-perf.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.android-arm-eabi.node')
          } else {
            nativeBinding = require('@ferni/perf-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-perf.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@ferni/perf-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-perf.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@ferni/perf-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-perf.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@ferni/perf-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'ferni-perf.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./ferni-perf.darwin-universal.node')
      } else {
        nativeBinding = require('@ferni/perf-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'ferni-perf.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.darwin-x64.node')
          } else {
            nativeBinding = require('@ferni/perf-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-perf.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.darwin-arm64.node')
          } else {
            nativeBinding = require('@ferni/perf-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'ferni-perf.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./ferni-perf.freebsd-x64.node')
      } else {
        nativeBinding = require('@ferni/perf-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-x64-musl.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ferni-perf.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ferni-perf.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@ferni/perf-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'ferni-perf.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ferni-perf.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@ferni/perf-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { OnnxRouter, quickPredict, cosineSimilarity, batchCosineSimilarity, euclideanDistance, batchEuclideanDistance, batchCosineSimilarityF32, euclideanDistanceF32, batchEuclideanDistanceF32, normalizeVectorF32, batchNormalizeVectorsF32, vectorNormF32, computeCentroidF32, findSimilarPairsF32, topKSimilarF32, textSimilarity, batchTextSimilarity, computeMinhash, estimateSimilarityFromMinhash, findDuplicatesLsh, batchScoreTools, PatternMatcher, getLibraryInfo, likelyContainsFunctionCall, extractFunctionCalls, parseFunctionCall, registerToolNames, clearToolNames, isKnownTool, isValidJson, getToolCount, parseJsonFast, containsSsml, stripSsml, analyzeSsml, batchAnalyzeSsml, extractBreaks, extractEmotions, insertBreak, insertEmotion, wrapWithSpeed, registerCustomPattern, matchCustomPattern, clearCustomPatterns, calculateStatisticsF32, calculateLinearTrendF32, exponentialSmoothingF32, calculateSeasonalityF32, batchCalculateStatisticsF32, buildGuidanceAutomaton, stripGuidanceBlocks, containsGuidanceBlocks, clearGuidanceAutomaton, deduplicateInjections, keywordJaccardSimilarity, textSemanticSimilarity, analyzeMessage, batchAnalyzeMessages, detectEmotionalState, analyzeConversationDynamics, buildToolNameAutomaton, scanForToolNames, containsAnyToolName, getToolNameByIndex, getToolNamePatternCount, clearToolNameAutomaton, AhoCorasickMatcher, analyzeFluency, batchAnalyzeFluency, likelyHasDisfluencies, extractInterjections, countInterjections, analyzeTurn, hasTurnFinal, hasContinuation, turnCompleteProbability, batchAnalyzeTurn, extractSignals, batchExtractSignals, likelyHasSignals, extractDateSignals, extractHighValueSignals, hasMemorableSignals, countWords, countTokensApprox, countChars, countSentences, countBytes, countLines, getTextStats, batchCountWords, batchCountTokens, batchGetStats, exceedsTokenLimit, truncateToTokens, NapiFftProcessor, getRmsEnergy, getZeroCrossingRate, NapiEmbeddingCache, hashTextSha256, batchHashTextsSha256 } = nativeBinding

module.exports.OnnxRouter = OnnxRouter
module.exports.quickPredict = quickPredict
module.exports.cosineSimilarity = cosineSimilarity
module.exports.batchCosineSimilarity = batchCosineSimilarity
module.exports.euclideanDistance = euclideanDistance
module.exports.batchEuclideanDistance = batchEuclideanDistance
module.exports.batchCosineSimilarityF32 = batchCosineSimilarityF32
module.exports.euclideanDistanceF32 = euclideanDistanceF32
module.exports.batchEuclideanDistanceF32 = batchEuclideanDistanceF32
module.exports.normalizeVectorF32 = normalizeVectorF32
module.exports.batchNormalizeVectorsF32 = batchNormalizeVectorsF32
module.exports.vectorNormF32 = vectorNormF32
module.exports.computeCentroidF32 = computeCentroidF32
module.exports.findSimilarPairsF32 = findSimilarPairsF32
module.exports.topKSimilarF32 = topKSimilarF32
module.exports.textSimilarity = textSimilarity
module.exports.batchTextSimilarity = batchTextSimilarity
module.exports.computeMinhash = computeMinhash
module.exports.estimateSimilarityFromMinhash = estimateSimilarityFromMinhash
module.exports.findDuplicatesLsh = findDuplicatesLsh
module.exports.batchScoreTools = batchScoreTools
module.exports.PatternMatcher = PatternMatcher
module.exports.getLibraryInfo = getLibraryInfo
module.exports.likelyContainsFunctionCall = likelyContainsFunctionCall
module.exports.extractFunctionCalls = extractFunctionCalls
module.exports.parseFunctionCall = parseFunctionCall
module.exports.registerToolNames = registerToolNames
module.exports.clearToolNames = clearToolNames
module.exports.isKnownTool = isKnownTool
module.exports.isValidJson = isValidJson
module.exports.getToolCount = getToolCount
module.exports.parseJsonFast = parseJsonFast
module.exports.containsSsml = containsSsml
module.exports.stripSsml = stripSsml
module.exports.analyzeSsml = analyzeSsml
module.exports.batchAnalyzeSsml = batchAnalyzeSsml
module.exports.extractBreaks = extractBreaks
module.exports.extractEmotions = extractEmotions
module.exports.insertBreak = insertBreak
module.exports.insertEmotion = insertEmotion
module.exports.wrapWithSpeed = wrapWithSpeed
module.exports.registerCustomPattern = registerCustomPattern
module.exports.matchCustomPattern = matchCustomPattern
module.exports.clearCustomPatterns = clearCustomPatterns
module.exports.calculateStatisticsF32 = calculateStatisticsF32
module.exports.calculateLinearTrendF32 = calculateLinearTrendF32
module.exports.exponentialSmoothingF32 = exponentialSmoothingF32
module.exports.calculateSeasonalityF32 = calculateSeasonalityF32
module.exports.batchCalculateStatisticsF32 = batchCalculateStatisticsF32
module.exports.buildGuidanceAutomaton = buildGuidanceAutomaton
module.exports.stripGuidanceBlocks = stripGuidanceBlocks
module.exports.containsGuidanceBlocks = containsGuidanceBlocks
module.exports.clearGuidanceAutomaton = clearGuidanceAutomaton
module.exports.deduplicateInjections = deduplicateInjections
module.exports.keywordJaccardSimilarity = keywordJaccardSimilarity
module.exports.textSemanticSimilarity = textSemanticSimilarity
module.exports.analyzeMessage = analyzeMessage
module.exports.batchAnalyzeMessages = batchAnalyzeMessages
module.exports.detectEmotionalState = detectEmotionalState
module.exports.analyzeConversationDynamics = analyzeConversationDynamics
module.exports.buildToolNameAutomaton = buildToolNameAutomaton
module.exports.scanForToolNames = scanForToolNames
module.exports.containsAnyToolName = containsAnyToolName
module.exports.getToolNameByIndex = getToolNameByIndex
module.exports.getToolNamePatternCount = getToolNamePatternCount
module.exports.clearToolNameAutomaton = clearToolNameAutomaton
module.exports.AhoCorasickMatcher = AhoCorasickMatcher
module.exports.analyzeFluency = analyzeFluency
module.exports.batchAnalyzeFluency = batchAnalyzeFluency
module.exports.likelyHasDisfluencies = likelyHasDisfluencies
module.exports.extractInterjections = extractInterjections
module.exports.countInterjections = countInterjections
module.exports.analyzeTurn = analyzeTurn
module.exports.hasTurnFinal = hasTurnFinal
module.exports.hasContinuation = hasContinuation
module.exports.turnCompleteProbability = turnCompleteProbability
module.exports.batchAnalyzeTurn = batchAnalyzeTurn
module.exports.extractSignals = extractSignals
module.exports.batchExtractSignals = batchExtractSignals
module.exports.likelyHasSignals = likelyHasSignals
module.exports.extractDateSignals = extractDateSignals
module.exports.extractHighValueSignals = extractHighValueSignals
module.exports.hasMemorableSignals = hasMemorableSignals
module.exports.countWords = countWords
module.exports.countTokensApprox = countTokensApprox
module.exports.countChars = countChars
module.exports.countSentences = countSentences
module.exports.countBytes = countBytes
module.exports.countLines = countLines
module.exports.getTextStats = getTextStats
module.exports.batchCountWords = batchCountWords
module.exports.batchCountTokens = batchCountTokens
module.exports.batchGetStats = batchGetStats
module.exports.exceedsTokenLimit = exceedsTokenLimit
module.exports.truncateToTokens = truncateToTokens
module.exports.NapiFftProcessor = NapiFftProcessor
module.exports.getRmsEnergy = getRmsEnergy
module.exports.getZeroCrossingRate = getZeroCrossingRate
module.exports.NapiEmbeddingCache = NapiEmbeddingCache
module.exports.hashTextSha256 = hashTextSha256
module.exports.batchHashTextsSha256 = batchHashTextsSha256
