/**
 * Quant Tools Firestore Persistence
 *
 * Stores and retrieves user financial data for Peter's quant tools.
 *
 * Schema:
 * - bogle_users/{userId}/financial_profile/current    → FinancialProfile
 * - bogle_users/{userId}/portfolio/holdings           → PortfolioHoldings
 * - bogle_users/{userId}/behavioral_finance/tracking  → BehavioralTracking
 * - bogle_users/{userId}/fire_progress/snapshots      → FIRESnapshot[]
 * - bogle_users/{userId}/quant_insights/history       → QuantInsight[]
 *
 * @module tools/domains/research/quant-firestore
 */

import { getLogger } from '../../../utils/safe-logger.js';

const log = getLogger();

// ============================================================================
// TYPES
// ============================================================================

/**
 * User's financial profile - income, expenses, savings
 */
export interface FinancialProfile {
  userId: string;
  monthlyIncome: number;
  monthlyExpenses: number;
  monthlyDebtPayments: number;
  emergencyFundMonths: number;
  retirementContribution: number;
  currentAge: number;
  targetRetirementAge: number;
  currentRetirementSavings: number;
  riskTolerance: 'conservative' | 'moderate' | 'aggressive';
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Individual stock/fund holding
 */
export interface Holding {
  symbol: string;
  shares: number;
  costBasis: number;
  purchaseDate: Date;
  accountType: 'taxable' | 'ira' | '401k' | 'roth' | 'other';
  notes?: string;
}

/**
 * User's complete portfolio
 */
export interface PortfolioHoldings {
  userId: string;
  holdings: Holding[];
  lastUpdated: Date;
  totalValue?: number;
  totalCostBasis?: number;
}

/**
 * Behavioral finance tracking - tracks financial psychology over time
 */
export interface BehavioralTracking {
  userId: string;
  // Negative behaviors to minimize
  panicSells: BehaviorEvent[];
  timingAttempts: BehaviorEvent[];
  impulsePurchases: BehaviorEvent[];
  // Positive metrics
  budgetAdherence: MonthlyMetric[];
  savingsConsistency: MonthlyMetric[];
  debtPaymentConsistency: MonthlyMetric[];
  // Scores
  currentEmotionalControlScore: number;
  currentDisciplineScore: number;
  currentPatienceScore: number;
  lastCalculated: Date;
}

export interface BehaviorEvent {
  date: Date;
  description: string;
  amount?: number;
  symbol?: string;
  emotion?: string;
}

export interface MonthlyMetric {
  month: string; // YYYY-MM format
  value: number; // 0-100 percentage
}

/**
 * FIRE progress snapshot
 */
export interface FIRESnapshot {
  date: Date;
  netWorth: number;
  fireNumber: number;
  percentToFire: number;
  projectedFireDate: Date | null;
  savingsRate: number;
  monthlyPassiveIncome: number;
}

/**
 * Individual quant insight generated by Peter
 */
export interface QuantInsight {
  id: string;
  date: Date;
  type: 'technical' | 'risk' | 'behavioral' | 'fire' | 'portfolio' | 'market';
  title: string;
  summary: string;
  details: string;
  actionable: boolean;
  priority: 'low' | 'medium' | 'high';
  symbols?: string[];
  metrics?: Record<string, number>;
  acknowledged: boolean;
}

// ============================================================================
// FIRESTORE INTERFACE (minimal typing to avoid hard dependency)
// ============================================================================

interface Firestore {
  collection: (path: string) => CollectionReference;
}

interface CollectionReference {
  doc: (id: string) => DocumentReference;
  add: (data: Record<string, unknown>) => Promise<DocumentReference>;
  where: (field: string, op: string, value: unknown) => Query;
  orderBy: (field: string, direction?: 'asc' | 'desc') => Query;
  limit: (n: number) => Query;
  get: () => Promise<QuerySnapshot>;
}

interface DocumentReference {
  collection: (path: string) => CollectionReference;
  get: () => Promise<DocumentSnapshot>;
  set: (data: Record<string, unknown>, options?: { merge?: boolean }) => Promise<void>;
  update: (data: Record<string, unknown>) => Promise<void>;
  delete: () => Promise<void>;
}

interface DocumentSnapshot {
  exists: boolean;
  data: () => Record<string, unknown> | undefined;
  id: string;
}

interface Query {
  get: () => Promise<QuerySnapshot>;
  limit: (n: number) => Query;
  orderBy: (field: string, direction?: 'asc' | 'desc') => Query;
}

interface QuerySnapshot {
  docs: DocumentSnapshot[];
  empty: boolean;
}

// ============================================================================
// QUANT FIRESTORE SERVICE
// ============================================================================

export class QuantFirestoreService {
  private db: Firestore | null = null;
  private initPromise: Promise<void> | null = null;
  private readonly USERS_COLLECTION = 'bogle_users';

  constructor() {
    // Lazy initialization
  }

  /**
   * Initialize Firestore connection
   */
  async initialize(): Promise<void> {
    if (this.db) return;
    if (this.initPromise) return this.initPromise;

    this.initPromise = this.doInitialize();
    return this.initPromise;
  }

  private async doInitialize(): Promise<void> {
    try {
      const { Firestore } = await import('@google-cloud/firestore');
      this.db = new Firestore({
        projectId: process.env.GOOGLE_CLOUD_PROJECT || process.env.GCLOUD_PROJECT,
        databaseId: process.env.FIRESTORE_DATABASE || '(default)',
      }) as unknown as Firestore;
      log.info('Quant Firestore service initialized');
    } catch (error) {
      log.error({ error: String(error) }, 'Failed to initialize Firestore for quant tools');
      this.db = null;
    }
  }

  // ============================================================================
  // FINANCIAL PROFILE
  // ============================================================================

  /**
   * Save or update user's financial profile
   */
  async saveFinancialProfile(profile: FinancialProfile): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(profile.userId)
        .collection('financial_profile')
        .doc('current');

      await docRef.set(this.serializeProfile(profile), { merge: true });
      log.info({ userId: profile.userId }, 'Financial profile saved');
    } catch (error) {
      log.error(
        { error: String(error), userId: profile.userId },
        'Failed to save financial profile'
      );
    }
  }

  /**
   * Load user's financial profile
   */
  async loadFinancialProfile(userId: string): Promise<FinancialProfile | null> {
    await this.initialize();
    if (!this.db) return null;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('financial_profile')
        .doc('current');

      const doc = await docRef.get();
      if (!doc.exists) return null;

      return this.deserializeProfile(doc.data()!, userId);
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to load financial profile');
      return null;
    }
  }

  /**
   * Update specific financial profile fields
   */
  async updateFinancialProfile(userId: string, updates: Partial<FinancialProfile>): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('financial_profile')
        .doc('current');

      await docRef.update({
        ...updates,
        updatedAt: new Date().toISOString(),
      });
      log.debug({ userId, fields: Object.keys(updates) }, 'Financial profile updated');
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to update financial profile');
    }
  }

  // ============================================================================
  // PORTFOLIO HOLDINGS
  // ============================================================================

  /**
   * Save user's portfolio holdings
   */
  async savePortfolio(portfolio: PortfolioHoldings): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(portfolio.userId)
        .collection('portfolio')
        .doc('holdings');

      await docRef.set(this.serializePortfolio(portfolio), { merge: true });
      log.info(
        { userId: portfolio.userId, holdingCount: portfolio.holdings.length },
        'Portfolio saved'
      );
    } catch (error) {
      log.error({ error: String(error), userId: portfolio.userId }, 'Failed to save portfolio');
    }
  }

  /**
   * Load user's portfolio
   */
  async loadPortfolio(userId: string): Promise<PortfolioHoldings | null> {
    await this.initialize();
    if (!this.db) return null;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('portfolio')
        .doc('holdings');

      const doc = await docRef.get();
      if (!doc.exists) return null;

      return this.deserializePortfolio(doc.data()!, userId);
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to load portfolio');
      return null;
    }
  }

  /**
   * Add a holding to the portfolio
   */
  async addHolding(userId: string, holding: Holding): Promise<void> {
    const portfolio = await this.loadPortfolio(userId);
    const holdings = portfolio?.holdings || [];
    holdings.push(holding);

    await this.savePortfolio({
      userId,
      holdings,
      lastUpdated: new Date(),
    });
  }

  /**
   * Update a specific holding
   */
  async updateHolding(userId: string, symbol: string, updates: Partial<Holding>): Promise<void> {
    const portfolio = await this.loadPortfolio(userId);
    if (!portfolio) return;

    const holdingIndex = portfolio.holdings.findIndex((h) => h.symbol === symbol);
    if (holdingIndex === -1) return;

    portfolio.holdings[holdingIndex] = { ...portfolio.holdings[holdingIndex], ...updates };
    portfolio.lastUpdated = new Date();

    await this.savePortfolio(portfolio);
  }

  /**
   * Remove a holding from the portfolio
   */
  async removeHolding(userId: string, symbol: string): Promise<void> {
    const portfolio = await this.loadPortfolio(userId);
    if (!portfolio) return;

    portfolio.holdings = portfolio.holdings.filter((h) => h.symbol !== symbol);
    portfolio.lastUpdated = new Date();

    await this.savePortfolio(portfolio);
  }

  // ============================================================================
  // BEHAVIORAL TRACKING
  // ============================================================================

  /**
   * Save behavioral tracking data
   */
  async saveBehavioralTracking(tracking: BehavioralTracking): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(tracking.userId)
        .collection('behavioral_finance')
        .doc('tracking');

      await docRef.set(this.serializeBehavioral(tracking), { merge: true });
      log.info({ userId: tracking.userId }, 'Behavioral tracking saved');
    } catch (error) {
      log.error(
        { error: String(error), userId: tracking.userId },
        'Failed to save behavioral tracking'
      );
    }
  }

  /**
   * Load behavioral tracking data
   */
  async loadBehavioralTracking(userId: string): Promise<BehavioralTracking | null> {
    await this.initialize();
    if (!this.db) return null;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('behavioral_finance')
        .doc('tracking');

      const doc = await docRef.get();
      if (!doc.exists) return null;

      return this.deserializeBehavioral(doc.data()!, userId);
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to load behavioral tracking');
      return null;
    }
  }

  /**
   * Record a behavioral event (panic sell, timing attempt, etc.)
   */
  async recordBehaviorEvent(
    userId: string,
    eventType: 'panicSell' | 'timingAttempt' | 'impulsePurchase',
    event: Omit<BehaviorEvent, 'date'>
  ): Promise<void> {
    const tracking =
      (await this.loadBehavioralTracking(userId)) || this.createEmptyTracking(userId);

    const newEvent: BehaviorEvent = {
      ...event,
      date: new Date(),
    };

    switch (eventType) {
      case 'panicSell':
        tracking.panicSells.push(newEvent);
        break;
      case 'timingAttempt':
        tracking.timingAttempts.push(newEvent);
        break;
      case 'impulsePurchase':
        tracking.impulsePurchases.push(newEvent);
        break;
    }

    // Recalculate scores
    tracking.currentEmotionalControlScore = this.calculateEmotionalControl(tracking);
    tracking.currentDisciplineScore = this.calculateDiscipline(tracking);
    tracking.lastCalculated = new Date();

    await this.saveBehavioralTracking(tracking);
  }

  /**
   * Record monthly metric (budget adherence, savings consistency, etc.)
   */
  async recordMonthlyMetric(
    userId: string,
    metricType: 'budgetAdherence' | 'savingsConsistency' | 'debtPaymentConsistency',
    value: number
  ): Promise<void> {
    const tracking =
      (await this.loadBehavioralTracking(userId)) || this.createEmptyTracking(userId);

    const month = new Date().toISOString().slice(0, 7); // YYYY-MM
    const metric: MonthlyMetric = { month, value };

    const existingIndex = tracking[metricType].findIndex((m) => m.month === month);
    if (existingIndex >= 0) {
      tracking[metricType][existingIndex] = metric;
    } else {
      tracking[metricType].push(metric);
    }

    // Recalculate scores
    tracking.currentDisciplineScore = this.calculateDiscipline(tracking);
    tracking.lastCalculated = new Date();

    await this.saveBehavioralTracking(tracking);
  }

  // ============================================================================
  // FIRE PROGRESS
  // ============================================================================

  /**
   * Save a FIRE progress snapshot
   */
  async saveFIRESnapshot(userId: string, snapshot: FIRESnapshot): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const colRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('fire_progress');

      await colRef.add(this.serializeFIRESnapshot(snapshot));
      log.info({ userId, percentToFire: snapshot.percentToFire }, 'FIRE snapshot saved');
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to save FIRE snapshot');
    }
  }

  /**
   * Load FIRE progress history
   */
  async loadFIREHistory(userId: string, limit: number = 12): Promise<FIRESnapshot[]> {
    await this.initialize();
    if (!this.db) return [];

    try {
      const colRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('fire_progress');

      const querySnapshot = await colRef.orderBy('date', 'desc').limit(limit).get();

      return querySnapshot.docs.map((doc) => this.deserializeFIRESnapshot(doc.data()!));
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to load FIRE history');
      return [];
    }
  }

  /**
   * Get latest FIRE snapshot
   */
  async getLatestFIRESnapshot(userId: string): Promise<FIRESnapshot | null> {
    const history = await this.loadFIREHistory(userId, 1);
    return history[0] || null;
  }

  // ============================================================================
  // QUANT INSIGHTS
  // ============================================================================

  /**
   * Save a quant insight
   */
  async saveInsight(userId: string, insight: QuantInsight): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const colRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('quant_insights');

      await colRef.doc(insight.id).set(this.serializeInsight(insight));
      log.debug({ userId, insightId: insight.id, type: insight.type }, 'Quant insight saved');
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to save quant insight');
    }
  }

  /**
   * Load recent insights
   */
  async loadRecentInsights(userId: string, limit: number = 10): Promise<QuantInsight[]> {
    await this.initialize();
    if (!this.db) return [];

    try {
      const colRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('quant_insights');

      const querySnapshot = await colRef.orderBy('date', 'desc').limit(limit).get();

      return querySnapshot.docs.map((doc) => this.deserializeInsight(doc.data()!));
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to load recent insights');
      return [];
    }
  }

  /**
   * Get unacknowledged high-priority insights
   */
  async getActionableInsights(userId: string): Promise<QuantInsight[]> {
    await this.initialize();
    if (!this.db) return [];

    try {
      const colRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('quant_insights');

      // Note: Firestore doesn't support multiple inequality filters,
      // so we filter in memory for complex queries
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      let query: any = colRef;
      query = query.where('acknowledged', '==', false);
      query = query.where('actionable', '==', true);
      query = query.orderBy('date', 'desc');
      query = query.limit(20);

      const querySnapshot = await query.get();

      return querySnapshot.docs
        .map((doc: { data: () => Record<string, unknown> }) => this.deserializeInsight(doc.data()))
        .filter((i: QuantInsight) => i.priority === 'high' || i.priority === 'medium');
    } catch (error) {
      log.error({ error: String(error), userId }, 'Failed to load actionable insights');
      return [];
    }
  }

  /**
   * Mark an insight as acknowledged
   */
  async acknowledgeInsight(userId: string, insightId: string): Promise<void> {
    await this.initialize();
    if (!this.db) return;

    try {
      const docRef = this.db
        .collection(this.USERS_COLLECTION)
        .doc(userId)
        .collection('quant_insights')
        .doc(insightId);

      await docRef.update({ acknowledged: true });
    } catch (error) {
      log.error({ error: String(error), userId, insightId }, 'Failed to acknowledge insight');
    }
  }

  // ============================================================================
  // HELPER METHODS
  // ============================================================================

  private createEmptyTracking(userId: string): BehavioralTracking {
    return {
      userId,
      panicSells: [],
      timingAttempts: [],
      impulsePurchases: [],
      budgetAdherence: [],
      savingsConsistency: [],
      debtPaymentConsistency: [],
      currentEmotionalControlScore: 100,
      currentDisciplineScore: 100,
      currentPatienceScore: 100,
      lastCalculated: new Date(),
    };
  }

  private calculateEmotionalControl(tracking: BehavioralTracking): number {
    // Fewer panic sells and timing attempts = higher score
    const recentPanicSells = tracking.panicSells.filter(
      (e) => new Date(e.date) > new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)
    ).length;
    const recentTimingAttempts = tracking.timingAttempts.filter(
      (e) => new Date(e.date) > new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)
    ).length;

    // Start at 100, deduct for each negative event
    let score = 100;
    score -= recentPanicSells * 15;
    score -= recentTimingAttempts * 10;

    return Math.max(0, Math.min(100, score));
  }

  private calculateDiscipline(tracking: BehavioralTracking): number {
    // Average of recent monthly metrics
    const recentMonths = 6;
    const getRecentAverage = (metrics: MonthlyMetric[]): number => {
      const recent = metrics.slice(-recentMonths);
      if (recent.length === 0) return 100;
      return recent.reduce((sum, m) => sum + m.value, 0) / recent.length;
    };

    const budgetScore = getRecentAverage(tracking.budgetAdherence);
    const savingsScore = getRecentAverage(tracking.savingsConsistency);
    const debtScore = getRecentAverage(tracking.debtPaymentConsistency);

    // Deduct for impulse purchases
    const recentImpulse = tracking.impulsePurchases.filter(
      (e) => new Date(e.date) > new Date(Date.now() - 180 * 24 * 60 * 60 * 1000)
    ).length;

    const impulseDeduction = recentImpulse * 5;

    return Math.max(
      0,
      Math.min(100, (budgetScore + savingsScore + debtScore) / 3 - impulseDeduction)
    );
  }

  // ============================================================================
  // SERIALIZATION
  // ============================================================================

  private serializeProfile(profile: FinancialProfile): Record<string, unknown> {
    return {
      ...profile,
      createdAt: profile.createdAt.toISOString(),
      updatedAt: profile.updatedAt.toISOString(),
    };
  }

  private deserializeProfile(data: Record<string, unknown>, userId: string): FinancialProfile {
    return {
      userId,
      monthlyIncome: (data.monthlyIncome as number) || 0,
      monthlyExpenses: (data.monthlyExpenses as number) || 0,
      monthlyDebtPayments: (data.monthlyDebtPayments as number) || 0,
      emergencyFundMonths: (data.emergencyFundMonths as number) || 0,
      retirementContribution: (data.retirementContribution as number) || 0,
      currentAge: (data.currentAge as number) || 30,
      targetRetirementAge: (data.targetRetirementAge as number) || 65,
      currentRetirementSavings: (data.currentRetirementSavings as number) || 0,
      riskTolerance: ((data.riskTolerance as string) ||
        'moderate') as FinancialProfile['riskTolerance'],
      createdAt: new Date((data.createdAt as string) || Date.now()),
      updatedAt: new Date((data.updatedAt as string) || Date.now()),
    };
  }

  private serializePortfolio(portfolio: PortfolioHoldings): Record<string, unknown> {
    return {
      ...portfolio,
      holdings: portfolio.holdings.map((h) => ({
        ...h,
        purchaseDate: h.purchaseDate.toISOString(),
      })),
      lastUpdated: portfolio.lastUpdated.toISOString(),
    };
  }

  private deserializePortfolio(data: Record<string, unknown>, userId: string): PortfolioHoldings {
    const holdings = (data.holdings as Array<Record<string, unknown>>) || [];
    return {
      userId,
      holdings: holdings.map((h) => ({
        symbol: h.symbol as string,
        shares: h.shares as number,
        costBasis: h.costBasis as number,
        purchaseDate: new Date(h.purchaseDate as string),
        accountType: ((h.accountType as string) || 'taxable') as Holding['accountType'],
        notes: h.notes as string | undefined,
      })),
      lastUpdated: new Date((data.lastUpdated as string) || Date.now()),
      totalValue: data.totalValue as number | undefined,
      totalCostBasis: data.totalCostBasis as number | undefined,
    };
  }

  private serializeBehavioral(tracking: BehavioralTracking): Record<string, unknown> {
    const serializeEvents = (events: BehaviorEvent[]) =>
      events.map((e) => ({ ...e, date: e.date.toISOString() }));

    return {
      ...tracking,
      panicSells: serializeEvents(tracking.panicSells),
      timingAttempts: serializeEvents(tracking.timingAttempts),
      impulsePurchases: serializeEvents(tracking.impulsePurchases),
      lastCalculated: tracking.lastCalculated.toISOString(),
    };
  }

  private deserializeBehavioral(data: Record<string, unknown>, userId: string): BehavioralTracking {
    const deserializeEvents = (events: Array<Record<string, unknown>>): BehaviorEvent[] =>
      events.map((e) => ({ ...e, date: new Date(e.date as string) })) as BehaviorEvent[];

    return {
      userId,
      panicSells: deserializeEvents((data.panicSells as Array<Record<string, unknown>>) || []),
      timingAttempts: deserializeEvents(
        (data.timingAttempts as Array<Record<string, unknown>>) || []
      ),
      impulsePurchases: deserializeEvents(
        (data.impulsePurchases as Array<Record<string, unknown>>) || []
      ),
      budgetAdherence: (data.budgetAdherence as MonthlyMetric[]) || [],
      savingsConsistency: (data.savingsConsistency as MonthlyMetric[]) || [],
      debtPaymentConsistency: (data.debtPaymentConsistency as MonthlyMetric[]) || [],
      currentEmotionalControlScore: (data.currentEmotionalControlScore as number) || 100,
      currentDisciplineScore: (data.currentDisciplineScore as number) || 100,
      currentPatienceScore: (data.currentPatienceScore as number) || 100,
      lastCalculated: new Date((data.lastCalculated as string) || Date.now()),
    };
  }

  private serializeFIRESnapshot(snapshot: FIRESnapshot): Record<string, unknown> {
    return {
      ...snapshot,
      date: snapshot.date.toISOString(),
      projectedFireDate: snapshot.projectedFireDate?.toISOString() || null,
    };
  }

  private deserializeFIRESnapshot(data: Record<string, unknown>): FIRESnapshot {
    return {
      date: new Date(data.date as string),
      netWorth: data.netWorth as number,
      fireNumber: data.fireNumber as number,
      percentToFire: data.percentToFire as number,
      projectedFireDate: data.projectedFireDate ? new Date(data.projectedFireDate as string) : null,
      savingsRate: data.savingsRate as number,
      monthlyPassiveIncome: data.monthlyPassiveIncome as number,
    };
  }

  private serializeInsight(insight: QuantInsight): Record<string, unknown> {
    return {
      ...insight,
      date: insight.date.toISOString(),
    };
  }

  private deserializeInsight(data: Record<string, unknown>): QuantInsight {
    return {
      id: data.id as string,
      date: new Date(data.date as string),
      type: data.type as QuantInsight['type'],
      title: data.title as string,
      summary: data.summary as string,
      details: data.details as string,
      actionable: data.actionable as boolean,
      priority: data.priority as QuantInsight['priority'],
      symbols: data.symbols as string[] | undefined,
      metrics: data.metrics as Record<string, number> | undefined,
      acknowledged: data.acknowledged as boolean,
    };
  }
}

// ============================================================================
// SINGLETON INSTANCE
// ============================================================================

let quantFirestoreInstance: QuantFirestoreService | null = null;

export function getQuantFirestore(): QuantFirestoreService {
  if (!quantFirestoreInstance) {
    quantFirestoreInstance = new QuantFirestoreService();
  }
  return quantFirestoreInstance;
}

export default getQuantFirestore;
