/**
 * Quant Tools Firestore Persistence
 *
 * Stores and retrieves user financial data for Peter's quant tools.
 *
 * Schema:
 * - bogle_users/{userId}/financial_profile/current    → FinancialProfile
 * - bogle_users/{userId}/portfolio/holdings           → PortfolioHoldings
 * - bogle_users/{userId}/behavioral_finance/tracking  → BehavioralTracking
 * - bogle_users/{userId}/fire_progress/snapshots      → FIRESnapshot[]
 * - bogle_users/{userId}/quant_insights/history       → QuantInsight[]
 *
 * @module tools/domains/research/quant-firestore
 */
/**
 * User's financial profile - income, expenses, savings
 */
export interface FinancialProfile {
    userId: string;
    monthlyIncome: number;
    monthlyExpenses: number;
    monthlyDebtPayments: number;
    emergencyFundMonths: number;
    retirementContribution: number;
    currentAge: number;
    targetRetirementAge: number;
    currentRetirementSavings: number;
    riskTolerance: 'conservative' | 'moderate' | 'aggressive';
    createdAt: Date;
    updatedAt: Date;
}
/**
 * Individual stock/fund holding
 */
export interface Holding {
    symbol: string;
    shares: number;
    costBasis: number;
    purchaseDate: Date;
    accountType: 'taxable' | 'ira' | '401k' | 'roth' | 'other';
    notes?: string;
}
/**
 * User's complete portfolio
 */
export interface PortfolioHoldings {
    userId: string;
    holdings: Holding[];
    lastUpdated: Date;
    totalValue?: number;
    totalCostBasis?: number;
}
/**
 * Behavioral finance tracking - tracks financial psychology over time
 */
export interface BehavioralTracking {
    userId: string;
    panicSells: BehaviorEvent[];
    timingAttempts: BehaviorEvent[];
    impulsePurchases: BehaviorEvent[];
    budgetAdherence: MonthlyMetric[];
    savingsConsistency: MonthlyMetric[];
    debtPaymentConsistency: MonthlyMetric[];
    currentEmotionalControlScore: number;
    currentDisciplineScore: number;
    currentPatienceScore: number;
    lastCalculated: Date;
}
export interface BehaviorEvent {
    date: Date;
    description: string;
    amount?: number;
    symbol?: string;
    emotion?: string;
}
export interface MonthlyMetric {
    month: string;
    value: number;
}
/**
 * FIRE progress snapshot
 */
export interface FIRESnapshot {
    date: Date;
    netWorth: number;
    fireNumber: number;
    percentToFire: number;
    projectedFireDate: Date | null;
    savingsRate: number;
    monthlyPassiveIncome: number;
}
/**
 * Individual quant insight generated by Peter
 */
export interface QuantInsight {
    id: string;
    date: Date;
    type: 'technical' | 'risk' | 'behavioral' | 'fire' | 'portfolio' | 'market';
    title: string;
    summary: string;
    details: string;
    actionable: boolean;
    priority: 'low' | 'medium' | 'high';
    symbols?: string[];
    metrics?: Record<string, number>;
    acknowledged: boolean;
}
export declare class QuantFirestoreService {
    private db;
    private initPromise;
    private readonly USERS_COLLECTION;
    constructor();
    /**
     * Initialize Firestore connection
     */
    initialize(): Promise<void>;
    private doInitialize;
    /**
     * Save or update user's financial profile
     */
    saveFinancialProfile(profile: FinancialProfile): Promise<void>;
    /**
     * Load user's financial profile
     */
    loadFinancialProfile(userId: string): Promise<FinancialProfile | null>;
    /**
     * Update specific financial profile fields
     */
    updateFinancialProfile(userId: string, updates: Partial<FinancialProfile>): Promise<void>;
    /**
     * Save user's portfolio holdings
     */
    savePortfolio(portfolio: PortfolioHoldings): Promise<void>;
    /**
     * Load user's portfolio
     */
    loadPortfolio(userId: string): Promise<PortfolioHoldings | null>;
    /**
     * Add a holding to the portfolio
     */
    addHolding(userId: string, holding: Holding): Promise<void>;
    /**
     * Update a specific holding
     */
    updateHolding(userId: string, symbol: string, updates: Partial<Holding>): Promise<void>;
    /**
     * Remove a holding from the portfolio
     */
    removeHolding(userId: string, symbol: string): Promise<void>;
    /**
     * Save behavioral tracking data
     */
    saveBehavioralTracking(tracking: BehavioralTracking): Promise<void>;
    /**
     * Load behavioral tracking data
     */
    loadBehavioralTracking(userId: string): Promise<BehavioralTracking | null>;
    /**
     * Record a behavioral event (panic sell, timing attempt, etc.)
     */
    recordBehaviorEvent(userId: string, eventType: 'panicSell' | 'timingAttempt' | 'impulsePurchase', event: Omit<BehaviorEvent, 'date'>): Promise<void>;
    /**
     * Record monthly metric (budget adherence, savings consistency, etc.)
     */
    recordMonthlyMetric(userId: string, metricType: 'budgetAdherence' | 'savingsConsistency' | 'debtPaymentConsistency', value: number): Promise<void>;
    /**
     * Save a FIRE progress snapshot
     */
    saveFIRESnapshot(userId: string, snapshot: FIRESnapshot): Promise<void>;
    /**
     * Load FIRE progress history
     */
    loadFIREHistory(userId: string, limit?: number): Promise<FIRESnapshot[]>;
    /**
     * Get latest FIRE snapshot
     */
    getLatestFIRESnapshot(userId: string): Promise<FIRESnapshot | null>;
    /**
     * Save a quant insight
     */
    saveInsight(userId: string, insight: QuantInsight): Promise<void>;
    /**
     * Load recent insights
     */
    loadRecentInsights(userId: string, limit?: number): Promise<QuantInsight[]>;
    /**
     * Get unacknowledged high-priority insights
     */
    getActionableInsights(userId: string): Promise<QuantInsight[]>;
    /**
     * Mark an insight as acknowledged
     */
    acknowledgeInsight(userId: string, insightId: string): Promise<void>;
    private createEmptyTracking;
    private calculateEmotionalControl;
    private calculateDiscipline;
    private serializeProfile;
    private deserializeProfile;
    private serializePortfolio;
    private deserializePortfolio;
    private serializeBehavioral;
    private deserializeBehavioral;
    private serializeFIRESnapshot;
    private deserializeFIRESnapshot;
    private serializeInsight;
    private deserializeInsight;
}
export declare function getQuantFirestore(): QuantFirestoreService;
export default getQuantFirestore;
//# sourceMappingURL=quant-firestore.d.ts.map