/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** NAPI: Optional STT config */
export interface WhisperSttConfig {
  /** Path to GGML model (e.g. ggml-base.en.bin) */
  modelPath: string
}
/**
 * One-shot transcribe: load model, transcribe, return text.
 * Prefer NativeWhisperStt when transcribing multiple chunks.
 */
export declare function transcribeWhisper(modelPath: string, pcm: Float32Array): string
/** YIN pitch estimation result for NAPI */
export interface NativeYinResult {
  /** Estimated pitch in Hz (0 if no voiced speech detected) */
  pitchHz: number
  /** Confidence of pitch estimate (0-1) */
  confidence: number
  /** Best period in samples */
  periodSamples: number
}
/**
 * Estimate pitch using YIN algorithm (standalone function)
 *
 * This is ~40x faster than naive autocorrelation for pitch detection.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples (normalized -1 to 1)
 * * `sample_rate` - Sample rate in Hz
 * * `min_pitch` - Minimum pitch to detect (default: 50 Hz)
 * * `max_pitch` - Maximum pitch to detect (default: 500 Hz)
 *
 * # Returns
 * Pitch estimate with frequency, confidence, and period
 */
export declare function estimatePitchYin(samples: Float32Array, sampleRate: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): NativeYinResult
/**
 * Batch pitch estimation using YIN
 *
 * Process multiple frames efficiently for utterance-level analysis
 */
export declare function batchEstimatePitchYin(samples: Float32Array, sampleRate: number, frameSize: number, hopSize: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): Array<NativeYinResult>
/** Library information */
export interface LibraryInfo {
  version: string
  bufferPoolSize: number
  maxFrameSize: number
  defaultSampleRate: number
}
/** Get library information */
export declare function getLibraryInfo(): LibraryInfo
/** Prosody analysis result from a single frame */
export interface NativeProsodyResult {
  /** Current pitch estimate (Hz) */
  pitchHz: number
  /** Pitch confidence (0-1) */
  pitchConfidence: number
  /** Energy in dB */
  energyDb: number
  /** Short-term energy variance */
  energyVariance: number
  /** Zero crossing rate */
  zcr: number
  /** Is speech detected? */
  isSpeech: boolean
  /** Is voiced speech? */
  isVoiced: boolean
  /** Current silence duration (ms) */
  silenceMs: number
  /** Pitch trend: "rising", "falling", "stable" */
  pitchTrend: string
  /** Timestamp of analysis (ms) */
  timestampMs: number
}
/** Full prosody features for end-of-utterance analysis */
export interface NativeFullProsodyFeatures {
  /** Mean pitch (Hz) */
  pitchMean: number
  /** Pitch variance */
  pitchVariance: number
  /** Pitch range (max - min) */
  pitchRange: number
  /** Mean energy (dB) */
  energyMean: number
  /** Energy variance */
  energyVariance: number
  /** Estimated speech rate (syllables/sec approximation) */
  speechRate: number
  /** Total utterance duration (ms) */
  durationMs: number
  /** Speaking ratio (speech time / total time) */
  speakingRatio: number
  /** Number of pauses detected */
  pauseCount: number
}
/** Processor statistics */
export interface NativeProcessorStats {
  totalSamples: number
  analysisCount: number
  bufferFillLevel: number
  isInSpeech: boolean
  currentSilenceMs: number
}
/**
 * Get or create a processor for a session (global registry)
 *
 * Use this for simpler session management where you don't want
 * to hold a reference to the NativeAudioProcessor object.
 */
export declare function getOrCreateProcessor(sessionId: string, sampleRate?: number | undefined | null): boolean
/** Process a frame using the session registry */
export declare function processSessionFrame(sessionId: string, samples: Int16Array, timestampMs: number): NativeProsodyResult | null
/** Get full features from session registry */
export declare function getSessionFullFeatures(sessionId: string): NativeFullProsodyFeatures | null
/** Reset a session processor */
export declare function resetSessionProcessor(sessionId: string): boolean
/** Remove a session processor */
export declare function removeSessionProcessor(sessionId: string): boolean
/** Get count of active session processors */
export declare function getActiveProcessorCount(): number
/** Clear all session processors (for emergency cleanup) */
export declare function clearAllProcessors(): number
/**
 * Convert Int16 samples to Float32 (standalone function)
 *
 * SIMD-accelerated: processes 8 samples at a time using f32x8.
 * For when you just need conversion without full processing.
 */
export declare function convertI16ToF32(samples: Int16Array): Float32Array
/**
 * Compute energy in dB for a Float32 audio buffer
 *
 * SIMD-accelerated: processes 8 samples at a time for sum-of-squares.
 */
export declare function computeEnergyDb(samples: Float32Array): number
/** Check if audio contains speech (simple threshold check) */
export declare function isSpeech(samples: Float32Array, thresholdDb?: number | undefined | null): boolean
/**
 * Compute RMS (Root Mean Square) energy for a Float32 audio buffer
 *
 * SIMD-accelerated: processes 8 samples at a time for sum-of-squares.
 * Returns linear scale RMS (not dB). Use this for breath detection
 * and energy analysis where linear comparison is needed.
 */
export declare function computeRms(samples: Float32Array): number
/**
 * Compute Zero Crossing Rate for a Float32 audio buffer
 *
 * Returns a value between 0 and 1 indicating how often the signal
 * crosses zero. High ZCR often indicates unvoiced/breathy sounds,
 * low ZCR indicates voiced speech.
 */
export declare function computeZcr(samples: Float32Array): number
/**
 * Compute variance of a Float32 array
 *
 * SIMD-accelerated: uses two-pass algorithm with SIMD sum and squared-diff.
 * Useful for pitch variance, energy variance calculations.
 */
export declare function computeVariance(values: Float32Array): number
/**
 * Compute mean of a Float32 array
 *
 * SIMD-accelerated: processes 8 samples at a time.
 */
export declare function computeMean(values: Float32Array): number
/** Compute standard deviation of a Float32 array */
export declare function computeStdDev(values: Float32Array): number
/** Pitch estimation result */
export interface PitchEstimateResult {
  /** Estimated pitch in Hz (0 if no voiced speech detected) */
  pitchHz: number
  /** Confidence of pitch estimate (0-1) */
  confidence: number
}
/**
 * Estimate pitch using autocorrelation
 *
 * Standalone pitch estimation for single audio frames.
 * Uses autocorrelation with normalized confidence.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples (normalized -1 to 1)
 * * `sample_rate` - Sample rate in Hz (typically 16000)
 * * `min_pitch` - Minimum pitch to detect in Hz (default: 50)
 * * `max_pitch` - Maximum pitch to detect in Hz (default: 500)
 *
 * # Returns
 * Pitch estimate with confidence, or { pitch_hz: 0, confidence: 0 } if no pitch detected
 */
export declare function estimatePitch(samples: Float32Array, sampleRate: number, minPitch?: number | undefined | null, maxPitch?: number | undefined | null): PitchEstimateResult
/**
 * Extract full prosody features from a single frame
 *
 * Combines pitch, energy, and ZCR analysis.
 * More efficient than calling individual functions separately.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples
 * * `sample_rate` - Sample rate in Hz
 * * `timestamp_ms` - Current timestamp in milliseconds
 */
export interface FrameFeaturesResult {
  pitchHz: number
  pitchConfidence: number
  energyDb: number
  energyRms: number
  zcr: number
  isSpeech: boolean
  isVoiced: boolean
  timestampMs: number
}
export declare function extractFrameFeatures(samples: Float32Array, sampleRate: number, timestampMs: number): FrameFeaturesResult
/** FFT result containing real and imaginary parts */
export interface FftResult {
  real: Array<number>
  imaginary: Array<number>
  size: number
}
/**
 * Apply FFT to a Float32Array signal
 *
 * Returns complex frequency domain representation.
 * Signal is zero-padded to next power of 2 if needed.
 */
export declare function fftF32(samples: Float32Array): FftResult
/** Apply Hanning window to reduce spectral leakage */
export declare function applyHanningWindow(samples: Float32Array): Float32Array
/**
 * Get magnitude spectrum from FFT result
 *
 * Only returns first half (up to Nyquist frequency)
 */
export declare function getMagnitudeSpectrum(real: Array<number>, imaginary: Array<number>): Float32Array
/** Get power spectrum in dB */
export declare function getPowerSpectrumDb(real: Array<number>, imaginary: Array<number>, reference?: number | undefined | null): Float32Array
/**
 * Spectral analysis result
 * Field names match TypeScript NativeSpectralFeatures interface for seamless integration
 */
export interface SpectralFeatures {
  /** Spectral centroid (brightness) in Hz */
  centroid: number
  /** Spectral rolloff (85%) in Hz */
  rolloff: number
  /** Dominant frequency in Hz */
  dominantFrequency: number
  /** Magnitude at dominant frequency */
  dominantMagnitude: number
  /** Band energies (sub-bass, bass, low-mid, mid, high-mid, presence, brilliance) */
  bandEnergies: Array<number>
}
/**
 * Analyze spectral features of an audio signal
 *
 * Performs FFT and computes spectral centroid, rolloff, dominant frequency, and band energies.
 */
export declare function analyzeSpectrum(samples: Float32Array, sampleRate: number, minFreq?: number | undefined | null, maxFreq?: number | undefined | null): SpectralFeatures
/** Clear FFT caches (for memory management) */
export declare function clearFftCaches(): void
/** Configuration for post-TTS audio enhancement */
export interface PostTtsEnhancementConfig {
  /** Sample rate (typically 24000 or 44100 for Cartesia) */
  sampleRate: number
  /** Enable breath injection at phrase starts */
  enableBreath: boolean
  /** Enable spectral warmth enhancement */
  enableWarmth: boolean
  /** Enable micro-pitch modulation */
  enableMicroPitch: boolean
  /** Enable soft attack/release on phrases */
  enableSoftEdges: boolean
  /** Enable light compression */
  enableCompression: boolean
  /** Enable presence EQ boost (2-4kHz clarity) */
  enablePresence: boolean
  /** Breath injection probability (0.0-1.0, default 0.3) */
  breathProbability: number
  /** Warmth amount (0.0-1.0, default 0.15) */
  warmthAmount: number
  /** Pitch modulation depth in cents (default 8) */
  pitchModulationCents: number
  /** Soft edge duration in ms (default 20) */
  softEdgeMs: number
  /** Compression ratio (default 2.0) */
  compressionRatio: number
  /** Compression threshold in dB (default -20) */
  compressionThresholdDb: number
  /** Presence boost in dB (default 2.5) */
  presenceBoostDb: number
}
/** Result of post-TTS enhancement */
export interface PostTtsEnhancementResult {
  /** Number of breaths injected */
  breathsInjected: number
  /** Number of phrase edges softened */
  edgesSoftened: number
  /** Was warmth applied */
  warmthApplied: boolean
  /** Was pitch modulation applied */
  pitchModApplied: boolean
  /** Was compression applied */
  compressionApplied: boolean
  /** Was presence boost applied */
  presenceApplied: boolean
}
/** Get default post-TTS enhancement configuration */
export declare function getDefaultPostTtsConfig(): PostTtsEnhancementConfig
/**
 * Apply full post-TTS enhancement pipeline to TTS output
 *
 * This is the main entry point for "Better Than Human" audio processing.
 * Applies breath injection, spectral warmth, micro-pitch modulation,
 * soft attack/release, compression, and presence boost.
 *
 * # Arguments
 * * `samples` - Float32Array audio samples from Cartesia TTS
 * * `config` - Enhancement configuration
 *
 * # Returns
 * Enhancement result with stats about what was applied
 */
export declare function enhanceTtsAudio(samples: Float32Array, config: PostTtsEnhancementConfig): PostTtsEnhancementResult
/**
 * Apply full post-TTS enhancement and return enhanced audio
 *
 * Same as enhance_tts_audio but returns the modified samples.
 * Use this when you need the enhanced audio data back.
 */
export declare function enhanceTtsAudioInplace(samples: Float32Array, config: PostTtsEnhancementConfig): Float32Array
/**
 * Apply soft attack (fade-in) to audio start
 *
 * Creates a smooth, natural-sounding start instead of abrupt onset.
 */
export declare function applySoftAttack(samples: Float32Array, attackMs: number, sampleRate: number): Float32Array
/**
 * Apply soft release (fade-out) to audio end
 *
 * Creates a smooth, natural-sounding end instead of abrupt cutoff.
 */
export declare function applySoftRelease(samples: Float32Array, releaseMs: number, sampleRate: number): Float32Array
/**
 * Apply spectral warmth enhancement
 *
 * Boosts low frequencies for a warmer, more intimate voice quality.
 */
export declare function applyWarmth(samples: Float32Array, sampleRate: number, amount: number): Float32Array
/**
 * Apply presence boost (2-4kHz)
 *
 * Enhances clarity and intelligibility without harshness.
 */
export declare function applyPresence(samples: Float32Array, sampleRate: number, boostDb: number): Float32Array
/**
 * Apply light dynamic compression
 *
 * Evens out volume dynamics for consistent listening experience.
 */
export declare function applyCompression(samples: Float32Array, sampleRate: number, thresholdDb: number, ratio: number): Float32Array
/**
 * Inject breath sounds at phrase boundaries
 *
 * Returns the number of breaths injected.
 */
export declare function injectBreathSounds(samples: Float32Array, sampleRate: number, probability: number): number
/**
 * JavaScript-compatible phrase boundary for adaptive breath timing
 *
 * Represents a location in the audio where a breath could naturally be injected.
 */
export interface NativePhraseBoundary {
  /** Sample index (absolute position in the utterance) */
  sampleIndex: number
  /** Boundary type: 0=SentenceEnd, 1=ClauseBreak, 2=EmphasisBefore, 3=EmotionalRelease */
  boundaryType: number
}
/** Configuration for the stateful post-TTS processor */
export interface NativePostTtsConfig {
  /** Sample rate in Hz (default: 24000) */
  sampleRate?: number
  /** Enable warmth (low-shelf EQ boost) */
  enableWarmth?: boolean
  /** Warmth frequency in Hz (default: 300) */
  warmthFreq?: number
  /** Warmth gain in dB (default: 2.5) */
  warmthGainDb?: number
  /** Enable presence (peak EQ boost) */
  enablePresence?: boolean
  /** Presence frequency in Hz (default: 3000) */
  presenceFreq?: number
  /** Presence gain in dB (default: 2.0) */
  presenceGainDb?: number
  /** Enable compression */
  enableCompression?: boolean
  /** Compression threshold in dB (default: -18) */
  compThresholdDb?: number
  /** Compression ratio (default: 2.0) */
  compRatio?: number
  /** Compression attack in ms (default: 10) */
  compAttackMs?: number
  /** Compression release in ms (default: 100) */
  compReleaseMs?: number
  /** Enable de-esser (legacy wideband - DEPRECATED) */
  enableDeesser?: boolean
  /** De-esser frequency in Hz (default: 6000) */
  deesserFreq?: number
  /** De-esser threshold in dB (default: -20) */
  deesserThresholdDb?: number
  /** Enable split-band de-esser (NEW - professional quality) */
  enableSplitbandDeesser?: boolean
  /** Split-band crossover frequency in Hz (default: 5000) */
  splitbandCrossoverFreq?: number
  /** Split-band threshold in dB (default: -20) */
  splitbandThresholdDb?: number
  /** Split-band ratio (default: 4.0) */
  splitbandRatio?: number
  /** Enable limiter */
  enableLimiter?: boolean
  /** Limiter threshold in dB (default: -1) */
  limiterThresholdDb?: number
  /** Enable crossfade between frames */
  enableCrossfade?: boolean
  /** Crossfade length in ms (default: 2) */
  crossfadeMs?: number
  /** Soft attack duration in ms (default: 15) */
  softAttackMs?: number
  /** Soft release duration in ms (default: 15) */
  softReleaseMs?: number
  /** Enable breath injection at utterance start */
  enableBreath?: boolean
  /** Breath injection probability (0-1) */
  breathProbability?: number
  /** Enable micro-pitch modulation (~5Hz wobble) */
  enableMicroPitch?: boolean
  /** Micro-pitch modulation depth in cents */
  microPitchCents?: number
  /** Enable noise floor (subtle room tone) */
  enableNoiseFloor?: boolean
  /** Noise floor level in dB (typically -60 to -50) */
  noiseFloorDb?: number
  /** Enable amplitude jitter (volume micro-variations) */
  enableAmplitudeJitter?: boolean
  /** Amplitude jitter depth (0-1, typically 0.015) */
  amplitudeJitterDepth?: number
  /** Enable pitch drift (slow pitch wandering) */
  enablePitchDrift?: boolean
  /** Pitch drift max in cents */
  pitchDriftCents?: number
  /**
   * Use SOLA-based pitch shifting (artifact-free)
   * When true (default), uses proper overlap-add algorithm instead of
   * frame-by-frame resampling. This eliminates clicks/crackles from pitch features.
   */
  useSolaPitch?: boolean
  /**
   * Enable emotion-aware prosody (affects vibrato, pitch drift, breath, pacing)
   * When true (default), the processor adapts all humanization features based on
   * the emotional context of the utterance.
   */
  enableEmotionProsody?: boolean
  /**
   * Current emotional state (0-8)
   * 0=Neutral, 1=Happy, 2=Sad, 3=Excited, 4=Calm, 5=Tense, 6=Empathetic, 7=Curious, 8=Supportive
   * This affects vibrato rate/depth, pitch drift direction, breath likelihood, and tempo.
   */
  emotion?: number
  /**
   * Enable adaptive pacing (time-stretch based on content complexity)
   * When true, speech rate adjusts to help comprehension of complex content.
   */
  enableAdaptivePacing?: boolean
  /**
   * Content complexity (0.0-1.0)
   * 0.0 = simple content (slightly faster pace)
   * 0.5 = moderate complexity (normal pace)
   * 1.0 = complex content (slower pace for comprehension)
   */
  contentComplexity?: number
  /**
   * Enable vocal fry (creaky voice at phrase endings)
   * Creates natural trailing-off quality like human speakers
   */
  enableVocalFry?: boolean
  /**
   * Vocal fry depth (0-1, default: 0.4)
   * How pronounced the creaky modulation is
   */
  vocalFryDepth?: number
  /**
   * Vocal fry duration in ms (default: 200)
   * How long the creaky effect lasts at phrase end
   */
  vocalFryDurationMs?: number
  /**
   * Enable lip smacks (mouth sounds between phrases)
   * Adds realistic mouth noises at natural pause points
   */
  enableLipSmacks?: boolean
  /**
   * Lip smack probability (0-1, default: 0.3)
   * Probability of triggering at each phrase boundary
   */
  lipSmackProbability?: number
  /**
   * Enable tempo micro-variation (subtle speed changes)
   * Creates natural rhythm variations within utterances
   */
  enableTempoVariation?: boolean
  /**
   * Tempo variation depth (0-1, default: 0.03)
   * How much the tempo can vary (3% typical for natural speech)
   */
  tempoVariationDepth?: number
  /**
   * Enable onset softening (micro-fades on hard glottal attacks)
   * Reduces harsh vowel-initial sounds for more natural speech
   */
  enableOnsetSoftening?: boolean
}
/** Statistics from processing a frame */
export interface NativeProcessingStats {
  frameNumber: number
  crossfadeApplied: boolean
  softAttackApplied: boolean
  softReleaseApplied: boolean
  warmthApplied: boolean
  presenceApplied: boolean
  compressionReductionDb: number
  deesserReductionDb: number
  limiterReductionDb: number
}
/** Configuration for Pre-STT audio processing */
export interface NativePreSttConfig {
  /** Sample rate of input audio (default: 16000) */
  sampleRate?: number
  /** Enable AGC (Automatic Gain Control) */
  enableAgc?: boolean
  /** Enable noise suppression */
  enableNoiseSuppression?: boolean
  /** Enable high-pass filter (DC removal) */
  enableHighpass?: boolean
  /** High-pass cutoff frequency in Hz (default: 80) */
  highpassCutoffHz?: number
  /** Enable bandwidth extension (for 8kHz input) */
  enableBandwidthExtension?: boolean
  /** Input is 8kHz (Twilio) - enables bandwidth extension */
  inputIs8Khz?: boolean
}
/** Statistics from Pre-STT processing */
export interface NativePreSttStats {
  /** Number of frames processed */
  framesProcessed: number
  /** Current AGC gain (1.0 = no change) */
  agcGain: number
  /** Whether noise suppression is ready (has noise floor estimate) */
  noiseSuppressionReady: boolean
  /** Whether bandwidth extension was applied this frame */
  bandwidthExtended: boolean
}
/**
 * Apply AGC to audio samples (standalone function)
 *
 * Creates/reuses a session-scoped AGC instance.
 *
 * @param sessionId - Session identifier for state management
 * @param samples - Float32Array to process (modified in place)
 * @returns Current AGC gain
 */
export declare function applyAgc(sessionId: string, samples: Float32Array): number
/** Reset AGC state for a session */
export declare function resetAgc(sessionId: string): boolean
/** Remove AGC instance for a session */
export declare function removeAgc(sessionId: string): boolean
export interface ToolPrediction {
  toolId: string
  confidence: number
}
export interface RouterPredictResult {
  predictions: Array<ToolPrediction>
  latencyMs: number
}
export interface RouterConfig {
  modelPath: string
  tokenizerPath: string
  labelMapPath: string
  maxLength: number
  threshold: number
  topK: number
  /** Number of threads for inference (0 = auto-detect based on CPU cores) */
  numThreads?: number
}
/**
 * Quick prediction without creating a router instance
 * (useful for one-off predictions, but slower due to model loading)
 */
export declare function quickPredict(modelPath: string, tokenizerPath: string, labelMapPath: string, query: string): RouterPredictResult
export interface CandleToolPrediction {
  toolId: string
  confidence: number
}
export interface CandleRouterResult {
  predictions: Array<CandleToolPrediction>
  latencyMs: number
  device: string
}
export interface CandleRouterConfig {
  modelPath: string
  tokenizerPath: string
  labelMapPath: string
  maxLength: number
  threshold: number
  topK: number
}
export interface CandleThinkerConfig {
  modelPath: string
  tokenizerPath: string
  maxNewTokens?: number
  temperature?: number
}
/**
 * Compute cosine similarity between two embedding vectors.
 * Uses SIMD instructions when available (AVX2/SSE/NEON).
 *
 * Returns a value between -1.0 and 1.0.
 */
export declare function cosineSimilarity(a: Array<number>, b: Array<number>): number
/**
 * Batch cosine similarity: compare one query vector against many candidates.
 * Returns similarity scores in the same order as candidates.
 * Uses parallel processing via Rayon.
 */
export declare function batchCosineSimilarity(query: Array<number>, candidates: Array<Array<number>>): Array<number>
/**
 * Compute Euclidean distance between two embedding vectors.
 * Returns the L2 distance (sqrt of sum of squared differences).
 */
export declare function euclideanDistance(a: Array<number>, b: Array<number>): number
/**
 * Batch euclidean distance: compare one query vector against many candidates.
 * Returns distance values in the same order as candidates.
 * Uses parallel processing via Rayon.
 */
export declare function batchEuclideanDistance(query: Array<number>, candidates: Array<Array<number>>): Array<number>
/**
 * Batch cosine similarity with F32 embeddings for maximum performance.
 * Takes flat arrays for zero-copy transfer from JavaScript.
 *
 * # Arguments
 * * `query` - Query embedding (1536 floats for OpenAI embeddings)
 * * `candidates` - Flat array of candidate embeddings (n * dim floats)
 * * `candidate_count` - Number of candidates
 *
 * # Returns
 * Array of similarity scores
 */
export declare function batchCosineSimilarityF32(query: Float32Array, candidates: Float32Array, candidateCount: number): Float32Array
/**
 * Euclidean distance with F32 embeddings for maximum performance.
 * Takes flat arrays for zero-copy transfer from JavaScript.
 *
 * # Arguments
 * * `a` - First embedding (Float32Array)
 * * `b` - Second embedding (Float32Array)
 *
 * # Returns
 * Euclidean distance (L2 norm of difference)
 */
export declare function euclideanDistanceF32(a: Float32Array, b: Float32Array): number
/**
 * Batch Euclidean distance with F32 embeddings for maximum performance.
 * Takes flat arrays for zero-copy transfer from JavaScript.
 *
 * # Arguments
 * * `query` - Query embedding (dim floats)
 * * `candidates` - Flat array of candidate embeddings (n * dim floats)
 * * `candidate_count` - Number of candidates
 *
 * # Returns
 * Array of distance values
 */
export declare function batchEuclideanDistanceF32(query: Float32Array, candidates: Float32Array, candidateCount: number): Float32Array
/**
 * Normalize a vector to unit length (L2 normalization).
 * Returns a new Float32Array with the normalized vector.
 *
 * # Arguments
 * * `v` - Vector to normalize (Float32Array)
 *
 * # Returns
 * Normalized vector with L2 norm = 1
 */
export declare function normalizeVectorF32(v: Float32Array): Float32Array
/**
 * Batch normalize multiple vectors to unit length.
 * Takes flat array of embeddings and normalizes each in-place.
 *
 * # Arguments
 * * `embeddings` - Flat array of embeddings (n * dim floats)
 * * `embedding_count` - Number of embeddings
 *
 * # Returns
 * Flat array of normalized embeddings
 */
export declare function batchNormalizeVectorsF32(embeddings: Float32Array, embeddingCount: number): Float32Array
/**
 * Compute L2 norm (magnitude) of a vector.
 * Uses SIMD-accelerated dot product.
 */
export declare function vectorNormF32(v: Float32Array): number
/**
 * Compute centroid (mean vector) of multiple embeddings.
 * Useful for clustering and averaging embeddings.
 *
 * # Arguments
 * * `embeddings` - Flat array of embeddings (n * dim floats)
 * * `embedding_count` - Number of embeddings
 *
 * # Returns
 * Centroid vector (dim floats)
 */
export declare function computeCentroidF32(embeddings: Float32Array, embeddingCount: number): Float32Array
/** Result for similar pairs search. */
export interface SimilarPair {
  firstIdx: number
  secondIdx: number
  similarity: number
}
/**
 * Find all pairs of embeddings with similarity above threshold.
 * Optimized for O(n²) pairwise comparison in memory deduplication.
 *
 * # Arguments
 * * `embeddings` - Flat array of embeddings (n * dim floats)
 * * `embedding_count` - Number of embeddings
 * * `dim` - Embedding dimension (e.g., 1536 for OpenAI)
 * * `threshold` - Minimum similarity threshold (0-1)
 *
 * # Returns
 * Array of SimilarPair objects for all pairs above threshold
 */
export declare function findSimilarPairsF32(embeddings: Float32Array, embeddingCount: number, dim: number, threshold: number): Array<SimilarPair>
/** Result for top-K similarity search. */
export interface TopKResult {
  indices: Array<number>
  similarities: Array<number>
}
/**
 * Find top-K most similar embeddings to a query.
 * Uses parallel computation with local top-K per thread.
 *
 * # Arguments
 * * `query` - Query embedding (dim floats)
 * * `candidates` - Flat array of candidate embeddings (n * dim floats)
 * * `candidate_count` - Number of candidates
 * * `k` - Number of top results to return
 * * `min_similarity` - Minimum similarity threshold (0-1)
 *
 * # Returns
 * TopKResult with indices and similarity scores
 */
export declare function topKSimilarF32(query: Float32Array, candidates: Float32Array, candidateCount: number, k: number, minSimilarity: number): TopKResult
/**
 * Compute Jaccard similarity between two texts using k-shingles.
 * Returns a value between 0.0 and 1.0.
 */
export declare function textSimilarity(text1: string, text2: string, shingleSize?: number | undefined | null): number
/**
 * Batch text similarity: compare one query text against many candidates.
 * Returns similarity scores in the same order as candidates.
 */
export declare function batchTextSimilarity(query: string, candidates: Array<string>, shingleSize?: number | undefined | null): Array<number>
/** MinHash signature for LSH. */
export interface MinHashSignature {
  id: string
  signature: Array<number>
}
/**
 * Generate MinHash signature for a text.
 * Uses xxhash for fast hashing with different seeds.
 */
export declare function computeMinhash(text: string, numHashes: number, shingleSize?: number | undefined | null): MinHashSignature
/**
 * Estimate Jaccard similarity from MinHash signatures.
 * Returns a value between 0.0 and 1.0.
 */
export declare function estimateSimilarityFromMinhash(sig1: Array<number>, sig2: Array<number>): number
/**
 * Find duplicate pairs from a batch of texts using LSH.
 * Returns pairs of indices with their similarity scores.
 */
export interface DuplicatePair {
  firstIdx: number
  secondIdx: number
  similarity: number
}
export declare function findDuplicatesLsh(texts: Array<string>, threshold: number, numHashes?: number | undefined | null, numBands?: number | undefined | null): Array<DuplicatePair>
/** Input for a single tool profile to be scored */
export interface ToolProfileInput {
  toolId: string
  /** Regex patterns as strings (will be compiled in Rust) */
  patterns: Array<string>
  /** Keywords with their weights: [keyword, weight, keyword, weight, ...] */
  keywordsFlat: Array<string>
  keywordWeightsFlat: Array<number>
  /** Whether this tool has an embedding (index in embeddings array) */
  hasEmbedding: boolean
  embeddingIndex?: number
}
/** Output for a scored tool */
export interface ToolScoringResult {
  toolId: string
  score: number
  patternScore: number
  keywordScore: number
  embeddingScore: number
  matchedPatternCount: number
  matchedKeywordCount: number
}
/** Configuration for batch scoring */
export interface BatchScoringConfig {
  patternWeight: number
  keywordWeight: number
  embeddingWeight: number
  earlyTerminationThreshold: number
  minScoreThreshold: number
}
/**
 * Batch score all tools against a query with parallel processing and early termination.
 *
 * This is the main optimization function for the semantic router.
 * It compiles regex patterns once, scores all tools in parallel using Rayon,
 * and supports early termination when a high-confidence match is found.
 *
 * # Arguments
 * * `query` - The user query to match against tools
 * * `profiles` - Array of tool profiles with patterns and keywords
 * * `query_embedding` - Optional query embedding (flat f32 array)
 * * `tool_embeddings` - Flat array of all tool embeddings (n * dim)
 * * `embedding_dim` - Dimension of embeddings (e.g., 1536 for OpenAI)
 * * `config` - Scoring configuration (weights, thresholds)
 *
 * # Returns
 * Array of scoring results, sorted by score descending
 */
export declare function batchScoreTools(query: string, profiles: Array<ToolProfileInput>, queryEmbedding?: Float32Array | undefined | null, toolEmbeddings?: Float32Array | undefined | null, embeddingDim?: number | undefined | null, config?: BatchScoringConfig | undefined | null): Array<ToolScoringResult>
/** Get library version and capabilities. */
export interface LibraryInfo {
  version: string
  simdAvailable: boolean
  parallelThreads: number
}
export declare function getLibraryInfo(): LibraryInfo
/** Parsed function call from TTS stream */
export interface NativeFunctionCall {
  /** Tool name */
  fnName: string
  /** Arguments as JSON string */
  argsJson: string
  /** Start position in original text */
  startPos: number
  /** End position in original text */
  endPos: number
}
/** Result of scanning text for function calls */
export interface NativeScanResult {
  /** All detected function calls */
  calls: Array<NativeFunctionCall>
  /** Text with function calls removed */
  cleanText: string
  /** Whether any function calls were found */
  hasCalls: boolean
}
/**
 * Fast check if text likely contains a JSON function call
 *
 * Uses SIMD-accelerated byte searching before regex
 */
export declare function likelyContainsFunctionCall(text: string): boolean
/**
 * Extract function calls from TTS text using SIMD-accelerated parsing
 *
 * Returns all function calls and the cleaned text
 */
export declare function extractFunctionCalls(text: string): NativeScanResult
/**
 * Parse a single JSON function call string
 *
 * Expected format: {"fn":"toolName","args":{...}}
 */
export declare function parseFunctionCall(jsonStr: string): NativeFunctionCall | null
/** Register known tool names for faster detection */
export declare function registerToolNames(names: Array<string>): void
/** Clear all registered tool names */
export declare function clearToolNames(): void
/** Check if a tool name is registered */
export declare function isKnownTool(name: string): boolean
/** Validate JSON string quickly using SIMD */
export declare function isValidJson(jsonStr: string): boolean
/** Get count of registered tools */
export declare function getToolCount(): number
/**
 * Parse JSON to a value (returns JSON string of parsed result)
 * Uses SIMD-accelerated simd-json for 2-5x faster parsing
 */
export declare function parseJsonFast(jsonStr: string): string | null
/** Extracted SSML tag */
export interface NativeSsmlTag {
  /** Tag type (break, emotion, speed, etc.) */
  tagType: string
  /** Full match text */
  fullMatch: string
  /** Start position */
  startPos: number
  /** End position */
  endPos: number
}
/** SSML analysis result */
export interface NativeSsmlAnalysis {
  /** Number of tags found */
  tagCount: number
  /** Plain text with SSML removed */
  plainText: string
  /** Total break time in milliseconds */
  totalBreakMs: number
  /** Detected emotions */
  emotions: Array<string>
  /** Speed modifiers found */
  speeds: Array<number>
  /** Has any SSML tags */
  hasSsml: boolean
}
/** Fast check if text contains any SSML tags */
export declare function containsSsml(text: string): boolean
/** Strip all SSML tags from text */
export declare function stripSsml(text: string): string
/** Analyze SSML in text and extract all tags */
export declare function analyzeSsml(text: string): NativeSsmlAnalysis
/** Batch analyze multiple texts in parallel */
export declare function batchAnalyzeSsml(texts: Array<string>): Array<NativeSsmlAnalysis>
/** Extract break tags and their durations */
export declare function extractBreaks(text: string): Array<number>
/** Extract emotion tags */
export declare function extractEmotions(text: string): Array<string>
/** Insert break tag at specified position */
export declare function insertBreak(text: string, position: number, durationMs: number): string
/** Insert emotion tag at specified position */
export declare function insertEmotion(text: string, position: number, emotion: string): string
/** Wrap text with speed modifier */
export declare function wrapWithSpeed(text: string, speedRatio: number): string
/** Register custom regex pattern for matching */
export declare function registerCustomPattern(name: string, pattern: string): boolean
/** Match custom pattern and return matches */
export declare function matchCustomPattern(name: string, text: string): Array<string>
/** Clear all custom patterns */
export declare function clearCustomPatterns(): void
/** Statistics result for time-series data */
export interface TimeSeriesStats {
  mean: number
  variance: number
  stdDev: number
  min: number
  max: number
  count: number
}
/**
 * SIMD-accelerated single-pass statistics calculation.
 * Computes mean, variance, min, max in one pass through the data.
 */
export declare function calculateStatisticsF32(values: Float32Array): TimeSeriesStats
/**
 * SIMD-accelerated linear regression (least squares).
 * Returns the slope of the best-fit line.
 */
export declare function calculateLinearTrendF32(values: Float32Array): number
/** Holt's double exponential smoothing result */
export interface ExponentialSmoothingResult {
  /** Smoothed level */
  level: number
  /** Trend component */
  trend: number
  /** Forecast (level + trend) */
  forecast: number
}
/**
 * SIMD-accelerated Holt's double exponential smoothing.
 * Returns the final smoothed values for forecasting.
 */
export declare function exponentialSmoothingF32(values: Float32Array, alpha: number, beta: number): ExponentialSmoothingResult
/** Seasonality analysis result */
export interface SeasonalityResult {
  /** Detected seasonality strength (0-1) */
  strength: number
  /** Detected period (if any) */
  period: number
  /** Seasonal indices for each period position */
  indices: Array<number>
}
/**
 * SIMD-accelerated seasonality detection.
 * Analyzes data for periodic patterns.
 */
export declare function calculateSeasonalityF32(values: Float32Array, maxPeriod: number): SeasonalityResult
/** Batch statistics for multiple time series in parallel */
export declare function batchCalculateStatisticsF32(seriesFlat: Float32Array, seriesLengths: Array<number>): Array<TimeSeriesStats>
/** Build the guidance block automaton (call once at startup) */
export declare function buildGuidanceAutomaton(): boolean
/**
 * Strip guidance blocks from text using pre-built automaton.
 * Returns cleaned text with all guidance blocks removed.
 */
export declare function stripGuidanceBlocks(text: string): string
/** Check if text contains any guidance blocks (fast check) */
export declare function containsGuidanceBlocks(text: string): boolean
/** Clear the guidance automaton */
export declare function clearGuidanceAutomaton(): void
/** Input injection for deduplication */
export interface InjectionInput {
  id: string
  content: string
  priority: number
  source: string
}
/** Result of deduplication - which injections to keep */
export interface DeduplicationResult {
  /** IDs of injections to keep (in order) */
  keepIds: Array<string>
  /** IDs of duplicates that were removed */
  removedIds: Array<string>
  /** Number of comparisons made */
  comparisons: number
}
/**
 * Deduplicate injections based on semantic similarity.
 * Returns IDs of injections to keep and those removed.
 *
 * # Arguments
 * * `injections` - Array of injection inputs
 * * `similarity_threshold` - Threshold for considering duplicates (0-1), default 0.7
 *
 * # Algorithm
 * 1. Extract keywords from each injection
 * 2. For each pair, compute semantic similarity
 * 3. When duplicates found, keep the one with higher priority (or first if equal)
 */
export declare function deduplicateInjections(injections: Array<InjectionInput>, similarityThreshold?: number | undefined | null): DeduplicationResult
/** Compute Jaccard similarity between two texts using keywords */
export declare function keywordJaccardSimilarity(text1: string, text2: string): number
/** Compute semantic similarity between two texts (accounts for related words) */
export declare function textSemanticSimilarity(text1: string, text2: string): number
/** Result of message analysis */
export interface MessageAnalysisResult {
  /** Whether the message is a wrap-up signal */
  isWrapUp: boolean
  /** Confidence in wrap-up detection (0-1) */
  wrapUpConfidence: number
  /** Whether the message is a question */
  isQuestion: boolean
  /** Whether the message is a greeting */
  isGreeting: boolean
  /** Detected sentiment (-1 to 1) */
  sentiment: number
  /** Dominant emotion category */
  emotionCategory: string
  /** Word count */
  wordCount: number
  /** Character count */
  charCount: number
  /** Keywords extracted */
  keywords: Array<string>
}
/**
 * Analyze a user message for various signals.
 *
 * Detects:
 * - Wrap-up signals (goodbye, thanks, etc.)
 * - Questions
 * - Greetings
 * - Sentiment/emotion
 * - Basic statistics
 */
export declare function analyzeMessage(text: string): MessageAnalysisResult
/** Batch analyze multiple messages in parallel */
export declare function batchAnalyzeMessages(messages: Array<string>): Array<MessageAnalysisResult>
/** Voice emotional indicators */
export interface VoiceEmotionInput {
  /** Speech rate relative to normal (1.0 = normal) */
  speechRate: number
  /** Volume level relative to normal (1.0 = normal) */
  volume: number
  /** Pitch variation (0-1, higher = more variation) */
  pitchVariation: number
  /** Pause frequency (pauses per 100 words) */
  pauseFrequency: number
}
/** Emotional state result */
export interface EmotionalStateResult {
  /** Primary detected emotion */
  primaryEmotion: string
  /** Confidence in primary emotion (0-1) */
  confidence: number
  /** Emotional intensity (0-1) */
  intensity: number
  /** Whether there's a voice-text mismatch */
  hasMismatch: boolean
  /** Description of mismatch if present */
  mismatchDescription: string
  /** Suggested response tone */
  suggestedTone: string
}
/**
 * Detect emotional state from text and optional voice indicators.
 *
 * Combines text sentiment with voice prosody to detect:
 * - Primary emotion
 * - Emotional intensity
 * - Voice-text mismatches (e.g., saying "I'm fine" with stressed voice)
 */
export declare function detectEmotionalState(text: string, voice?: VoiceEmotionInput | undefined | null): EmotionalStateResult
/** Input for tracking conversation dynamics */
export interface ConversationTurnInput {
  /** Turn number (0-indexed) */
  turnNumber: number
  /** Speaker: "user" or "agent" */
  speaker: string
  /** Word count of this turn */
  wordCount: number
  /** Duration in seconds (if available) */
  durationSecs?: number
  /** Sentiment of this turn (-1 to 1) */
  sentiment: number
  /** Whether this turn had a question */
  hasQuestion: boolean
}
/** Conversation dynamics analysis result */
export interface ConversationDynamicsResult {
  /** Average words per turn (user) */
  avgUserWords: number
  /** Average words per turn (agent) */
  avgAgentWords: number
  /** Turn-taking ratio (user turns / total) */
  turnRatio: number
  /** Engagement score (0-1) */
  engagementScore: number
  /** Conversation arc phase */
  conversationPhase: string
  /** Sentiment trajectory (rising, falling, stable) */
  sentimentTrend: string
  /** Question density (questions per turn) */
  questionDensity: number
  /** Suggested pacing (faster, slower, maintain) */
  suggestedPacing: string
}
/**
 * Analyze conversation dynamics from turn history.
 *
 * Tracks:
 * - Engagement patterns
 * - Sentiment trajectory
 * - Turn-taking balance
 * - Conversation phase (opening, exploring, deepening, closing)
 */
export declare function analyzeConversationDynamics(turns: Array<ConversationTurnInput>): ConversationDynamicsResult
/** Result of a pattern match */
export interface AhoCorasickMatch {
  /** Index of the matched pattern */
  patternIdx: number
  /** Start position in text */
  start: number
  /** End position in text */
  end: number
  /** The matched text */
  matchedText: string
}
/** Result of scanning text for patterns */
export interface AhoCorasickScanResult {
  /** All matches found */
  matches: Array<AhoCorasickMatch>
  /** Whether any patterns matched */
  hasMatches: boolean
  /** Number of matches */
  matchCount: number
}
/**
 * Build an Aho-Corasick automaton from a list of patterns.
 *
 * This compiles the patterns into a single automaton that can match
 * all patterns simultaneously in O(n) time.
 *
 * # Arguments
 * * `patterns` - List of patterns to match (usually tool names)
 *
 * # Returns
 * True if automaton was built successfully
 */
export declare function buildToolNameAutomaton(patterns: Array<string>): boolean
/**
 * Scan text for tool names using the pre-built automaton.
 *
 * This is the main function for tool-call-sanitizer.ts to use.
 * It scans text in O(n) time for all registered tool names.
 *
 * # Arguments
 * * `text` - Text to scan for tool names
 *
 * # Returns
 * Scan result with all matches
 */
export declare function scanForToolNames(text: string): AhoCorasickScanResult
/**
 * Check if text contains any registered tool name.
 *
 * Fast early-exit check - stops at first match.
 */
export declare function containsAnyToolName(text: string): boolean
/** Get the tool name for a pattern index. */
export declare function getToolNameByIndex(index: number): string | null
/** Get the number of registered tool name patterns. */
export declare function getToolNamePatternCount(): number
/** Clear the tool name automaton. */
export declare function clearToolNameAutomaton(): void
/** NAPI-compatible disfluency counts */
export interface NapiDisfluencyCounts {
  repetitions: number
  prolongations: number
  interjections: number
  revisions: number
  restarts: number
  trailing: number
  pauseFillers: number
  hesitations: number
}
/** NAPI-compatible fluency analysis result */
export interface NapiFluencyAnalysisResult {
  counts: NapiDisfluencyCounts
  wordCount: number
  fluencyScore: number
  detectedInterjections: Array<string>
  detectedProlongations: Array<string>
  hasSignificantDisfluencies: boolean
}
/** Analyze text for speech disfluencies (repetitions, interjections, etc.) */
export declare function analyzeFluency(text: string): NapiFluencyAnalysisResult
/** Batch analyze multiple texts for fluency */
export declare function batchAnalyzeFluency(texts: Array<string>): Array<NapiFluencyAnalysisResult>
/** Quick check if text likely contains disfluencies */
export declare function likelyHasDisfluencies(text: string): boolean
/** Extract only interjections from text */
export interface NapiInterjectionMatch {
  text: string
  start: number
  end: number
}
export declare function extractInterjections(text: string): Array<NapiInterjectionMatch>
/** Count interjections in text (fast path returning count only) */
export declare function countInterjections(text: string): number
/** NAPI-compatible phrase match */
export interface NapiTurnPhraseMatch {
  phrase: string
  phraseType: string
  start: number
  end: number
}
/** NAPI-compatible turn analysis result */
export interface NapiTurnAnalysisResult {
  matches: Array<NapiTurnPhraseMatch>
  turnFinalCount: number
  continuationCount: number
  likelyTurnComplete: boolean
  likelyContinuing: boolean
}
/** Analyze text for turn boundary indicators */
export declare function analyzeTurn(text: string): NapiTurnAnalysisResult
/** Check if text contains turn-final phrases */
export declare function hasTurnFinal(text: string): boolean
/** Check if text contains continuation phrases */
export declare function hasContinuation(text: string): boolean
/** Get probability that turn is complete (0.0 to 1.0) */
export declare function turnCompleteProbability(text: string): number
/** Batch analyze multiple texts for turn boundaries */
export declare function batchAnalyzeTurn(texts: Array<string>): Array<NapiTurnAnalysisResult>
/** NAPI-compatible extracted signal */
export interface NapiExtractedSignal {
  signalType: string
  value: string
  context: string
  start: number
  end: number
  confidence: number
}
/** NAPI-compatible signal extraction result */
export interface NapiSignalExtractionResult {
  signals: Array<NapiExtractedSignal>
  hasSignals: boolean
  highValueCount: number
}
/** Extract human signals from text (dates, values, fears, etc.) */
export declare function extractSignals(text: string): NapiSignalExtractionResult
/** Batch extract signals from multiple texts */
export declare function batchExtractSignals(texts: Array<string>): Array<NapiSignalExtractionResult>
/** Quick check if text likely contains signals */
export declare function likelyHasSignals(text: string): boolean
/** Extract only date signals (optimized) */
export declare function extractDateSignals(text: string): Array<NapiExtractedSignal>
/** Extract only high-value signals (birthdays, anniversaries, relationships) */
export declare function extractHighValueSignals(text: string): Array<NapiExtractedSignal>
/** Quick check if text has memorable signals (alias for likely_has_signals) */
export declare function hasMemorableSignals(text: string): boolean
/** NAPI-compatible text statistics */
export interface NapiTextStats {
  words: number
  tokensApprox: number
  chars: number
  bytes: number
  sentences: number
  lines: number
  avgWordLength: number
}
/** Count words in text */
export declare function countWords(text: string): number
/** Count approximate tokens (OpenAI-style) */
export declare function countTokensApprox(text: string): number
/** Count characters */
export declare function countChars(text: string): number
/** Count sentences */
export declare function countSentences(text: string): number
/** Count bytes */
export declare function countBytes(text: string): number
/** Count lines */
export declare function countLines(text: string): number
/** Get comprehensive text statistics */
export declare function getTextStats(text: string): NapiTextStats
/** Batch count words for multiple texts */
export declare function batchCountWords(texts: Array<string>): Array<number>
/** Batch count tokens for multiple texts */
export declare function batchCountTokens(texts: Array<string>): Array<number>
/** Batch get text statistics for multiple texts */
export declare function batchGetStats(texts: Array<string>): Array<NapiTextStats>
/** Check if text exceeds token limit */
export declare function exceedsTokenLimit(text: string, limit: number): boolean
/** Truncate text to approximate token limit */
export declare function truncateToTokens(text: string, maxTokens: number): string
/** Audio features extracted from FFT analysis */
export interface NapiAudioFeatures {
  rmsEnergy: number
  zeroCrossingRate: number
  spectralCentroid: number
  spectralFlux: number
  spectralRolloff: number
  dominantBin: number
  dominantMagnitude: number
}
/** Get RMS energy of audio samples (SIMD-accelerated) */
export declare function getRmsEnergy(samples: Array<number>): number
/** Get zero crossing rate of audio samples */
export declare function getZeroCrossingRate(samples: Array<number>): number
/** Cache statistics */
export interface NapiCacheStats {
  size: number
  capacity: number
  utilization: number
}
/** Compute SHA256 hash of text (returns hex string) */
export declare function hashTextSha256(text: string): string
/** Batch compute SHA256 hashes for multiple texts */
export declare function batchHashTextsSha256(texts: Array<string>): Array<string>
/** Per-stage timing metrics for the Omni pipeline. */
export interface OmniTimings {
  melMs: number
  encoderMs: number
  thinkerMs: number
  talkerMs: number
  code2WavMs: number
  totalMs: number
}
/**
 * Configuration for the Omni engine.
 * Optional paths: omit to disable STT or Thinker; TTS always uses Mock.
 */
export interface OmniConfig {
  /** Path to Whisper GGML model (e.g. ggml-base.en.bin). Omit to disable STT. */
  whisperModelPath?: string
  /** Path to Thinker model directory (safetensors + config). Omit to disable Thinker. */
  thinkerModelPath?: string
  /** Path to Thinker tokenizer (tokenizer.json). Omit to disable Thinker. */
  thinkerTokenizerPath?: string
  /** Max new tokens for Thinker generation (default 256). */
  thinkerMaxTokens?: number
  /** Temperature for Thinker (default 0.6). */
  thinkerTemperature?: number
  /** If true, load full Qwen3-Omni pipeline and enable process_audio_omni (audio→audio, no Whisper/TTS). */
  useFullOmni?: boolean
  /** When true, build full Omni pipeline with zero weights (no checkpoint). For tests and shape validation. */
  testMode?: boolean
}
/**
 * NAPI: Whisper STT engine for Node.js
 * Load once, then call transcribe() with Float32Array (16 kHz mono).
 */
export declare class NativeWhisperStt {
  constructor(config: WhisperSttConfig)
  /** Transcribe Float32Array PCM (16 kHz, mono). Returns transcript text. */
  transcribe(pcm: Float32Array): string
}
/**
 * Native audio processor for real-time voice analysis
 *
 * Pre-allocates all buffers at construction for zero per-frame allocations.
 */
export declare class NativeAudioProcessor {
  /**
   * Create a new audio processor for a session
   *
   * # Arguments
   * * `session_id` - Unique session identifier for debugging
   * * `sample_rate` - Audio sample rate (default: 16000)
   */
  constructor(sessionId: string, sampleRate?: number | undefined | null)
  /**
   * Process an Int16 audio frame
   *
   * This is the main entry point for LiveKit audio frames.
   * Uses pre-allocated buffers for zero per-frame allocations.
   *
   * # Arguments
   * * `samples` - Int16Array audio samples from LiveKit
   * * `timestamp_ms` - Current timestamp in milliseconds
   *
   * # Returns
   * Prosody features if enough data is available, None otherwise
   */
  processFrame(samples: Int16Array, timestampMs: number): NativeProsodyResult | null
  /**
   * Process a Float32 audio frame
   *
   * Use this if samples are already normalized floats.
   */
  processFrameF32(samples: Float32Array, timestampMs: number): NativeProsodyResult | null
  /** Get full prosody features for end-of-utterance analysis */
  getFullFeatures(): NativeFullProsodyFeatures
  /** Get processor statistics */
  getStats(): NativeProcessorStats
  /**
   * Reset processor for reuse
   *
   * Clears all state but keeps pre-allocated buffers.
   */
  reset(): void
  /** Get session ID */
  get sessionId(): string
}
export type NativePostTTSProcessor = NativePostTtsProcessor
/**
 * Stateful Post-TTS Audio Processor
 *
 * This processor maintains state between frames for seamless audio enhancement.
 * Create one instance per session and call `processFrame()` for each audio frame.
 *
 * Features:
 * - Stateful biquad filters (no clicks at frame boundaries)
 * - Stateful compressor (no pumping/breathing)
 * - De-esser (reduces harsh sibilance)
 * - Look-ahead soft limiter (prevents clipping)
 * - Crossfade overlap-add (eliminates frame discontinuities)
 *
 * Usage:
 * ```javascript
 * const processor = new NativePostTTSProcessor({
 *   sampleRate: 24000,
 *   enableWarmth: true,
 *   enablePresence: true,
 *   enableCompression: true,
 *   enableDeesser: true,
 *   enableLimiter: true,
 *   enableCrossfade: true,
 * });
 *
 * // Process frames
 * for (const frame of audioFrames) {
 *   const isLast = isLastFrame(frame);
 *   const stats = processor.processFrame(frame.samples, isLast);
 *   // frame.samples is modified in place
 * }
 *
 * // Reset for new utterance
 * processor.startUtterance();
 * ```
 */
export declare class NativePostTtsProcessor {
  /** Create a new processor with the given configuration */
  constructor(config?: NativePostTtsConfig | undefined | null)
  /** Create with default configuration (all features enabled) */
  static withDefaults(): NativePostTtsProcessor
  /**
   * Process a frame of audio samples in-place
   *
   * Call this for each audio frame. The processor maintains state between calls
   * for seamless audio without artifacts.
   *
   * @param samples - Float32Array of audio samples (modified in place)
   * @param isLastFrame - Set to true for the last frame of an utterance
   * @returns Processing statistics
   */
  processFrame(samples: Float32Array, isLastFrame: boolean): NativeProcessingStats
  /**
   * Mark the start of a new utterance
   *
   * Resets crossfade buffer but keeps filter state for continuity.
   * Call this at the start of each new TTS utterance.
   */
  startUtterance(): void
  /**
   * Fully reset all state
   *
   * Use this when switching personas or at session end.
   */
  reset(): void
  /** Get the number of frames processed */
  frameCount(): number
  /**
   * Set the emotional state (can be called mid-utterance for dynamic expression)
   *
   * The emotion smoothly transitions to affect vibrato, pitch drift, and pacing.
   * Valid values: 0=Neutral, 1=Happy, 2=Sad, 3=Excited, 4=Calm, 5=Tense,
   *               6=Empathetic, 7=Curious, 8=Supportive
   *
   * @param emotion - Emotion state (0-8)
   */
  setEmotion(emotion: number): void
  /**
   * Set content complexity for adaptive pacing
   *
   * 0.0 = simple content (normal/slightly faster pace)
   * 0.5 = moderate complexity (normal pace)
   * 1.0 = complex content (slower pace for comprehension)
   *
   * @param complexity - Complexity value (0.0 - 1.0)
   */
  setContentComplexity(complexity: number): void
  /**
   * Get the current emotional state
   *
   * @returns Current emotion state (0-8)
   */
  getEmotion(): number
  /**
   * Set phrase boundaries for adaptive breath placement
   *
   * This enables intelligent breath injection at natural pause points (sentence ends,
   * clause breaks, emphasis points). The processor will probabilistically inject
   * breaths based on boundary type and emotional context.
   *
   * @param boundaries - Array of phrase boundaries with sample positions and types
   *
   * Example:
   * ```javascript
   * processor.setPhraseBoundaries([
   *   { sampleIndex: 24000, boundaryType: 0 },  // Sentence end at 1 second
   *   { sampleIndex: 12000, boundaryType: 1 },  // Clause break at 0.5 seconds
   * ]);
   * ```
   */
  setPhraseBoundaries(boundaries: Array<NativePhraseBoundary>): void
  /**
   * Add a single phrase boundary
   *
   * Boundary types:
   * - 0 = SentenceEnd (80% breath likelihood)
   * - 1 = ClauseBreak (40% breath likelihood)
   * - 2 = EmphasisBefore (20% breath likelihood)
   * - 3 = EmotionalRelease (60% breath likelihood)
   *
   * @param sampleIndex - Absolute sample position in the utterance
   * @param boundaryType - Type of boundary (0-3)
   */
  addPhraseBoundary(sampleIndex: number, boundaryType: number): void
  /**
   * Clear all phrase boundaries
   *
   * Call this when starting a new utterance if you want to disable adaptive
   * breath timing and only use the standard breath injection.
   */
  clearPhraseBoundaries(): void
  /** Get the number of phrase boundaries currently set */
  phraseBoundaryCount(): number
}
export type NativePreSTTProcessor = NativePreSttProcessor
/**
 * Pre-STT Audio Processor
 *
 * Enhances inbound user audio before sending to STT (Gemini/Google).
 *
 * Features:
 * - **AGC** - Normalizes levels from quiet/loud speakers
 * - **Noise Suppression** - Removes background noise (fans, AC, etc.)
 * - **Bandwidth Extension** - Enhances 8kHz Twilio audio to 16kHz
 * - **DC Removal** - Removes DC offset and low-frequency rumble
 *
 * Usage:
 * ```javascript
 * const processor = new NativePreSTTProcessor({
 *   enableAgc: true,
 *   enableNoiseSuppression: true,
 *   enableHighpass: true,
 * });
 *
 * // For each audio frame from LiveKit
 * const enhanced = processor.processFrame(samples, isSpeech);
 * // Send enhanced audio to Gemini STT
 * ```
 */
export declare class NativePreSttProcessor {
  /** Create a new Pre-STT processor with configuration */
  constructor(config?: NativePreSttConfig | undefined | null)
  /** Create with default configuration (all features enabled for 16kHz) */
  static withDefaults(): NativePreSttProcessor
  /** Create configured for Twilio (8kHz → 16kHz with bandwidth extension) */
  static forTwilio(): NativePreSttProcessor
  /**
   * Process a frame of Float32 audio
   *
   * @param samples - Float32Array audio samples (normalized -1 to 1)
   * @param isSpeech - VAD result (true if speech detected in this frame)
   * @returns Enhanced audio samples (may be longer if bandwidth extended)
   */
  processFrame(samples: Float32Array, isSpeech: boolean): Float32Array
  /**
   * Process a frame of Int16 audio (common LiveKit format)
   *
   * @param samples - Int16Array audio samples
   * @param isSpeech - VAD result
   * @returns Enhanced audio as Float32Array (normalized -1 to 1)
   */
  processFrameI16(samples: Int16Array, isSpeech: boolean): Float32Array
  /** Get processing statistics */
  getStats(): NativePreSttStats
  /** Reset noise estimation (call when entering a new environment) */
  resetNoiseEstimate(): void
  /** Full reset (call when starting a new session) */
  reset(): void
}
/** ONNX Router for FTIS V3 inference */
export declare class OnnxRouter {
  /** Create a new ONNX router instance */
  constructor(config: RouterConfig)
  /** Predict tools for a query */
  predict(query: string): RouterPredictResult
  /** Get the number of supported tools */
  getNumTools(): number
  /** Get all tool labels */
  getLabels(): Array<string>
  /**
   * Warmup the model by running a dummy inference
   * Call this at startup to avoid cold-start latency on first real request
   */
  warmup(): number
}
/** Metal GPU-accelerated FTIS V3 Router using Candle */
export declare class CandleRouter {
  /** Create a new Candle router with Metal GPU acceleration */
  constructor(config: CandleRouterConfig)
  /** Predict tools for a query using Metal GPU */
  predict(query: string): CandleRouterResult
  /** Get the number of supported tools */
  getNumTools(): number
  /** Get all tool labels */
  getLabels(): Array<string>
  /** Get the device being used (Metal GPU or CPU) */
  getDevice(): string
  /** Warmup the model by running a dummy inference */
  warmup(): number
}
export declare class CandleThinker {
  constructor(config: CandleThinkerConfig)
  generate(prompt: string): string
}
/**
 * Pre-compiled pattern matcher for repeated scoring
 * Stores compiled regex patterns for efficient reuse across queries
 */
export declare class PatternMatcher {
  /** Create a new pattern matcher */
  constructor()
  /** Add patterns for a tool (compiles regex once) */
  addToolPatterns(toolId: string, patterns: Array<string>): void
  /**
   * Score a query against all registered tools
   * Returns: [tool_id, score, tool_id, score, ...]
   */
  scoreAllPatterns(query: string): Array<string>
  /** Get the number of registered tools */
  toolCount(): number
}
/**
 * Create an Aho-Corasick automaton without global state.
 *
 * Returns an opaque handle that can be used for matching.
 * This is useful when you need multiple independent matchers.
 */
export declare class AhoCorasickMatcher {
  /** Create a new matcher from patterns. */
  constructor(patterns: Array<string>)
  /** Scan text for matches. */
  scan(text: string): AhoCorasickScanResult
  /** Check if text contains any pattern (fast early-exit). */
  containsAny(text: string): boolean
  /** Get the pattern at an index. */
  getPattern(index: number): string | null
  /** Get the number of patterns. */
  patternCount(): number
  /**
   * Replace all matches with a replacement function result.
   * The replacement is indexed by pattern index.
   */
  replaceAll(text: string, replacements: Array<string>): string
}
/** FFT processor instance for session-scoped audio analysis */
export declare class NapiFftProcessor {
  /** Create a new FFT processor with specified size (typically 1024 or 2048) */
  constructor(fftSize: number)
  /** Process audio frame and return magnitude spectrum */
  processFrame(samples: Array<number>): Array<number>
  /** Compute spectral flux (change from previous frame) - higher = onset/transient */
  computeSpectralFlux(samples: Array<number>): number
  /** Get spectral centroid (brightness measure) */
  getSpectralCentroid(sampleRate: number): number
  /** Get spectral rolloff (frequency bin containing threshold% of energy) */
  getSpectralRolloff(threshold: number): number
  /** Extract all audio features from a frame */
  extractFeatures(samples: Array<number>, sampleRate: number): NapiAudioFeatures
  /** Get FFT size */
  fftSize(): number
  /** Get number of frequency bins */
  numBins(): number
  /** Reset processor (clear previous frame data) */
  reset(): void
}
/** Thread-safe embedding cache with SHA256 keys and LRU eviction */
export declare class NapiEmbeddingCache {
  /** Create a new embedding cache with specified capacity and TTL (ms) */
  constructor(maxSize: number, defaultTtlMs: number)
  /** Get an embedding from the cache (returns null if not found or expired) */
  get(text: string, currentTimeMs: number): Array<number> | null
  /** Put an embedding in the cache */
  put(text: string, embedding: Array<number>, currentTimeMs: number): void
  /** Put an embedding with custom TTL */
  putWithTtl(text: string, embedding: Array<number>, currentTimeMs: number, ttlMs: number): void
  /** Remove an entry from the cache */
  remove(text: string): boolean
  /** Clear all entries from the cache */
  clear(): void
  /** Get the current number of entries */
  len(): number
  /** Check if the cache is empty */
  isEmpty(): boolean
  /** Get cache capacity */
  capacity(): number
  /** Prune expired entries, returns count of entries removed */
  pruneExpired(currentTimeMs: number): number
  /** Get cache statistics */
  stats(): NapiCacheStats
}
/**
 * Unified Omni engine: STT (Whisper) + Thinker (Candle MoE) + TTS (Mock); optional full audio→audio.
 * Call transcribe() → generate() → speak() for full pipeline, or process_audio_omni() when use_full_omni.
 */
export declare class OmniEngine {
  constructor(config: OmniConfig)
  /** Transcribe audio (Float32Array, 16 kHz mono) to text via Whisper. */
  transcribe(audio: Float32Array): string
  /** Generate text from prompt via Candle Thinker (MoE). */
  generate(prompt: string): string
  /** Synthesize text to speech (Float32Array) via TTS core (Mock). */
  speak(text: string): Float32Array
  /**
   * Full Qwen3-Omni: raw audio (16 kHz mono f32) → waveform (24 kHz f32). No Whisper, no external TTS.
   * Requires use_full_omni true and thinker_model_path + thinker_tokenizer_path set (or test_mode true).
   */
  processAudioOmni(audio: Float32Array): Float32Array
  /**
   * Streaming: run pipeline and invoke callback for each audio chunk (24 kHz f32).
   * Returns per-stage timings when done.
   */
  processAudioOmniStreaming(audio: Float32Array, callback: (...args: any[]) => any): OmniTimings
  /** Same as process_audio_omni but returns per-stage timing metrics. */
  processAudioOmniTimed(audio: Float32Array): OmniTimings
  /** Input sample rate for the Omni pipeline (16 kHz). */
  get sampleRateIn(): number
  /** Output sample rate for the Omni pipeline (24 kHz). */
  get sampleRateOut(): number
  /** True if the full Omni pipeline is loaded and ready for process_audio_omni. */
  get isReady(): boolean
}
