/**
 * Insight Store - Persistent storage for generated insights
 *
 * Stores and manages insights generated by the pattern detection system:
 * - Behavioral patterns ("You tend to X when Y")
 * - Temporal patterns ("This happens every Sunday")
 * - Correlations ("X and Y seem connected")
 * - Predictions ("You might feel X soon")
 * - Growth observations ("You've grown in X")
 *
 * Features:
 * - Surfacing scheduling (cooldown, max attempts)
 * - User feedback tracking
 * - Insight expiration
 * - Priority-based retrieval
 *
 * @module memory/knowledge-graph/storage/insight-store
 */

import { v4 as uuidv4 } from 'uuid';
import { createLogger } from '../../../utils/safe-logger.js';
import { cleanForFirestore } from '../../../utils/firestore-utils.js';
import type { Insight, InsightType } from '../types.js';

const log = createLogger({ module: 'InsightStore' });

// ============================================================================
// CONSTANTS
// ============================================================================

const COLLECTION = 'knowledge_graph';
const INSIGHTS_SUBCOLLECTION = 'insights';

// Default surfacing configuration
const DEFAULT_COOLDOWN_HOURS = 48; // Wait 2 days between surfacing same insight
const DEFAULT_MAX_SURFACE_ATTEMPTS = 3;
const DEFAULT_RECEPTIVITY_THRESHOLD = 0.5;

// ============================================================================
// FIRESTORE ACCESS
// ============================================================================

let firestoreInstance: FirebaseFirestore.Firestore | null = null;

async function getFirestore(): Promise<FirebaseFirestore.Firestore | null> {
  if (firestoreInstance) return firestoreInstance;

  try {
    const { Firestore } = await import('@google-cloud/firestore');
    firestoreInstance = new Firestore({
      projectId: process.env.GOOGLE_CLOUD_PROJECT || process.env.GCLOUD_PROJECT,
      databaseId: process.env.FIRESTORE_DATABASE || '(default)',
    });
    return firestoreInstance;
  } catch (error) {
    log.warn({ error: String(error) }, 'Firestore not available for insight store');
    return null;
  }
}

async function getInsightsRef(userId: string) {
  const db = await getFirestore();
  if (!db) return null;
  return db.collection(COLLECTION).doc(userId).collection(INSIGHTS_SUBCOLLECTION);
}

// ============================================================================
// CREATE & UPDATE
// ============================================================================

/**
 * Create a new insight
 */
export async function createInsight(
  userId: string,
  insight: Omit<Insight, 'id' | 'createdAt' | 'surfacedCount' | 'userFeedback'>
): Promise<Insight | null> {
  const ref = await getInsightsRef(userId);
  if (!ref) return null;

  const id = uuidv4();
  const now = new Date();

  const fullInsight: Insight = {
    ...insight,
    id,
    createdAt: now,
    surfacedCount: 0,
    receptivityThreshold: insight.receptivityThreshold || DEFAULT_RECEPTIVITY_THRESHOLD,
  };

  await ref.doc(id).set(cleanForFirestore(fullInsight));

  log.info(
    { userId, insightId: id, type: insight.insightType },
    '✨ Created insight'
  );

  return fullInsight;
}

/**
 * Update an existing insight
 */
export async function updateInsight(
  userId: string,
  insightId: string,
  updates: Partial<Insight>
): Promise<Insight | null> {
  const ref = await getInsightsRef(userId);
  if (!ref) return null;

  const docRef = ref.doc(insightId);
  const doc = await docRef.get();

  if (!doc.exists) {
    log.warn({ userId, insightId }, 'Insight not found for update');
    return null;
  }

  const cleanedUpdates = cleanForFirestore({
    ...updates,
    updatedAt: new Date(),
  });

  await docRef.update(cleanedUpdates);

  const updated = await docRef.get();
  return updated.data() as Insight;
}

/**
 * Record that an insight was surfaced to the user
 */
export async function recordInsightSurfaced(
  userId: string,
  insightId: string
): Promise<void> {
  const ref = await getInsightsRef(userId);
  if (!ref) return;

  await ref.doc(insightId).update({
    surfacedCount: (await import('firebase-admin/firestore')).FieldValue.increment(1),
    lastSurfacedAt: new Date(),
  });

  log.debug({ userId, insightId }, 'Recorded insight surfacing');
}

/**
 * Record user feedback on an insight
 */
export async function recordInsightFeedback(
  userId: string,
  insightId: string,
  feedback: 'helpful' | 'not_helpful' | 'wrong'
): Promise<void> {
  const ref = await getInsightsRef(userId);
  if (!ref) return;

  await ref.doc(insightId).update({
    userFeedback: feedback,
    feedbackAt: new Date(),
  });

  log.info({ userId, insightId, feedback }, 'Recorded insight feedback');
}

// ============================================================================
// RETRIEVE
// ============================================================================

/**
 * Get a single insight by ID
 */
export async function getInsight(userId: string, insightId: string): Promise<Insight | null> {
  const ref = await getInsightsRef(userId);
  if (!ref) return null;

  const doc = await ref.doc(insightId).get();
  return doc.exists ? (doc.data() as Insight) : null;
}

/**
 * Get all insights for a user
 */
export async function getAllInsights(
  userId: string,
  options?: {
    types?: InsightType[];
    entityIds?: string[];
    minConfidence?: number;
    limit?: number;
  }
): Promise<Insight[]> {
  const ref = await getInsightsRef(userId);
  if (!ref) return [];

  let query: FirebaseFirestore.Query = ref;

  // Filter by type
  if (options?.types && options.types.length > 0) {
    query = query.where('insightType', 'in', options.types);
  }

  // Order by salience
  query = query.orderBy('salience', 'desc');

  // Apply limit
  if (options?.limit) {
    query = query.limit(options.limit);
  }

  const snapshot = await query.get();
  let insights = snapshot.docs.map((doc) => doc.data() as Insight);

  // Filter by entity (post-query since Firestore can't do array-contains with in)
  if (options?.entityIds && options.entityIds.length > 0) {
    insights = insights.filter((i) =>
      i.entityIds.some((eid) => options.entityIds!.includes(eid))
    );
  }

  // Filter by confidence (post-query)
  if (options?.minConfidence !== undefined) {
    insights = insights.filter((i) => i.confidence >= options.minConfidence!);
  }

  return insights;
}

/**
 * Get insights ready to surface (not on cooldown, not maxed out)
 */
export async function getInsightsReadyToSurface(
  userId: string,
  options?: {
    types?: InsightType[];
    minSalience?: number;
    limit?: number;
  }
): Promise<Insight[]> {
  const allInsights = await getAllInsights(userId, {
    types: options?.types,
    limit: (options?.limit || 10) * 2, // Get more to filter
  });

  const now = Date.now();
  const cooldownMs = DEFAULT_COOLDOWN_HOURS * 60 * 60 * 1000;

  return allInsights
    .filter((insight) => {
      // Not maxed out
      if (insight.surfacedCount >= DEFAULT_MAX_SURFACE_ATTEMPTS) {
        return false;
      }

      // Not on cooldown
      if (insight.lastSurfacedAt) {
        const lastSurfaced = new Date(insight.lastSurfacedAt).getTime();
        if (now - lastSurfaced < cooldownMs) {
          return false;
        }
      }

      // Not already given negative feedback
      if (insight.userReaction === 'unhelpful') {
        return false;
      }

      // Not expired
      if (insight.validUntil && new Date(insight.validUntil).getTime() < now) {
        return false;
      }

      // Meets salience threshold
      if (options?.minSalience !== undefined && (insight.salience ?? 0) < options.minSalience) {
        return false;
      }

      return true;
    })
    .slice(0, options?.limit || 10);
}

/**
 * Get insights for specific entities
 */
export async function getInsightsForEntities(
  userId: string,
  entityIds: string[],
  options?: {
    types?: InsightType[];
    limit?: number;
  }
): Promise<Insight[]> {
  return getAllInsights(userId, {
    ...options,
    entityIds,
  });
}

// ============================================================================
// DELETE
// ============================================================================

/**
 * Delete an insight
 */
export async function deleteInsight(userId: string, insightId: string): Promise<boolean> {
  const ref = await getInsightsRef(userId);
  if (!ref) return false;

  await ref.doc(insightId).delete();
  log.info({ userId, insightId }, 'Deleted insight');
  return true;
}

/**
 * Delete expired insights
 */
export async function deleteExpiredInsights(userId: string): Promise<number> {
  const ref = await getInsightsRef(userId);
  if (!ref) return 0;

  const now = new Date();
  const snapshot = await ref.where('validUntil', '<', now).get();

  let deleted = 0;
  for (const doc of snapshot.docs) {
    await doc.ref.delete();
    deleted++;
  }

  if (deleted > 0) {
    log.info({ userId, deleted }, 'Deleted expired insights');
  }

  return deleted;
}

/**
 * Delete insights with negative feedback
 */
export async function deleteNegativeInsights(userId: string): Promise<number> {
  const ref = await getInsightsRef(userId);
  if (!ref) return 0;

  const snapshot = await ref
    .where('userFeedback', 'in', ['not_helpful', 'wrong'])
    .get();

  let deleted = 0;
  for (const doc of snapshot.docs) {
    await doc.ref.delete();
    deleted++;
  }

  if (deleted > 0) {
    log.info({ userId, deleted }, 'Deleted negative-feedback insights');
  }

  return deleted;
}

// ============================================================================
// BULK OPERATIONS
// ============================================================================

/**
 * Create multiple insights at once
 */
export async function createInsightsBatch(
  userId: string,
  insights: Array<Omit<Insight, 'id' | 'createdAt' | 'surfacedCount' | 'userFeedback'>>
): Promise<Insight[]> {
  const ref = await getInsightsRef(userId);
  if (!ref) return [];

  const db = await getFirestore();
  if (!db) return [];

  const batch = db.batch();
  const created: Insight[] = [];
  const now = new Date();

  for (const insight of insights) {
    const id = uuidv4();
    const fullInsight: Insight = {
      ...insight,
      id,
      createdAt: now,
      surfacedCount: 0,
      receptivityThreshold: insight.receptivityThreshold || DEFAULT_RECEPTIVITY_THRESHOLD,
    };

    batch.set(ref.doc(id), cleanForFirestore(fullInsight));
    created.push(fullInsight);
  }

  await batch.commit();

  log.info({ userId, count: created.length }, 'Created insights batch');

  return created;
}

/**
 * Get insight statistics for a user
 */
export async function getInsightStats(userId: string): Promise<{
  total: number;
  byType: Record<InsightType, number>;
  surfaced: number;
  withFeedback: number;
  averageSalience: number;
}> {
  const insights = await getAllInsights(userId, { limit: 1000 });

  const byType: Record<string, number> = {};
  let surfaced = 0;
  let withFeedback = 0;
  let totalSalience = 0;

  for (const insight of insights) {
    // Count by type
    const insightType = insight.type || insight.insightType;
    if (insightType) {
      byType[insightType] = (byType[insightType] || 0) + 1;
    }

    // Count surfaced
    if (insight.surfacedCount > 0) {
      surfaced++;
    }

    // Count with feedback
    if (insight.userFeedback && insight.userFeedback.length > 0) {
      withFeedback++;
    }

    // Sum salience
    totalSalience += insight.salience ?? 0;
  }

  return {
    total: insights.length,
    byType: byType as Record<InsightType, number>,
    surfaced,
    withFeedback,
    averageSalience: insights.length > 0 ? totalSalience / insights.length : 0,
  };
}

// ============================================================================
// EXPORTS
// ============================================================================

export {
  DEFAULT_COOLDOWN_HOURS,
  DEFAULT_MAX_SURFACE_ATTEMPTS,
  DEFAULT_RECEPTIVITY_THRESHOLD,
};
