/**
 * Cultural & Spiritual Pronunciations
 * Japanese, Mindfulness, and Eastern Philosophical Terms (Nayan's domain)
 *
 * @module ssml/constants/cultural
 */

import type { PronunciationEntry } from './types.js';

export const JAPANESE_PRONUNCIATIONS: PronunciationEntry[] = [
  // -------------------------------------------------------------------------
  // Japanese Food Terms
  // -------------------------------------------------------------------------
  { pattern: /\bramen\b/gi, replacement: 'RAH-men', description: 'Japanese noodle soup' },
  { pattern: /\bmatcha\b/gi, replacement: 'MAH-chah', description: 'Green tea powder' },
  { pattern: /\bwasabi\b/gi, replacement: 'wah-SAH-bee', description: 'Japanese horseradish' },
  { pattern: /\bsake\b(?=\s|$|[.,!?])/gi, replacement: 'SAH-kay', description: 'Japanese rice wine' },
  { pattern: /\bsushi\b/gi, replacement: 'SOO-shee', description: 'Japanese food' },
  { pattern: /\bsashimi\b/gi, replacement: 'sah-SHEE-mee', description: 'Raw fish slices' },
  { pattern: /\btempura\b/gi, replacement: 'tem-POO-rah', description: 'Fried food' },
  { pattern: /\bteriyaki\b/gi, replacement: 'teh-ree-YAH-kee', description: 'Grilled food' },
  { pattern: /\bmiso\b/gi, replacement: 'MEE-so', description: 'Fermented soybean paste' },
  { pattern: /\bedamame\b/gi, replacement: 'eh-dah-MAH-may', description: 'Young soybeans' },
  { pattern: /\budon\b/gi, replacement: 'OO-don', description: 'Thick noodles' },
  { pattern: /\bgyoza\b/gi, replacement: 'GYOH-zah', description: 'Dumplings' },
  { pattern: /\bkatsu\b/gi, replacement: 'KAHT-soo', description: 'Breaded cutlet' },
  { pattern: /\bbento\b/gi, replacement: 'BEN-toh', description: 'Lunch box' },
  { pattern: /\bonigiri\b/gi, replacement: 'oh-nee-GEE-ree', description: 'Rice ball' },
  
  // -------------------------------------------------------------------------
  // Common Japanese Terms
  // -------------------------------------------------------------------------
  { pattern: /\bsensei\b/gi, replacement: 'SEN-say', description: 'Teacher/master' },
  { pattern: /\bdojo\b/gi, replacement: 'DOH-joh', description: 'Training hall' },
  { pattern: /\bfuton\b/gi, replacement: 'FOO-ton', description: 'Japanese mattress' },
  { pattern: /\btsunami\b/gi, replacement: 'tsoo-NAH-mee', description: 'Tidal wave' },
  { pattern: /\bkaraoke\b/gi, replacement: 'kah-rah-OH-kay', description: 'Singing entertainment' },
  { pattern: /\borigami\b/gi, replacement: 'or-ih-GAH-mee', description: 'Paper folding' },
  { pattern: /\bsudoku\b/gi, replacement: 'soo-DOH-koo', description: 'Number puzzle' },
  { pattern: /\bkimono\b/gi, replacement: 'kee-MOH-no', description: 'Traditional garment' },
  { pattern: /\bsamurai\b/gi, replacement: 'SAH-moo-rye', description: 'Warrior class' },
  { pattern: /\bninja\b/gi, replacement: 'NIN-jah', description: 'Covert agent' },
  { pattern: /\bshogun\b/gi, replacement: 'SHO-gun', description: 'Military commander' },
  { pattern: /\bgeisha\b/gi, replacement: 'GAY-shah', description: 'Traditional entertainer' },
  { pattern: /\bsumo\b/gi, replacement: 'SOO-moh', description: 'Wrestling sport' },
  { pattern: /\bjudo\b/gi, replacement: 'JOO-doh', description: 'Martial art' },
  { pattern: /\bkarate\b/gi, replacement: 'kah-RAH-tay', description: 'Martial art' },
  { pattern: /\baikido\b/gi, replacement: 'eye-KEE-doh', description: 'Martial art' },
  { pattern: /\btaiko\b/gi, replacement: 'TY-koh', description: 'Japanese drums' },
  { pattern: /\bsake\b(?=.*rice|.*wine|.*drink)/gi, replacement: 'SAH-kay', description: 'Rice wine' },
  { pattern: /\bbonsai\b/gi, replacement: 'BON-sigh', description: 'Miniature tree art' },
  { pattern: /\bemoji\b/gi, replacement: 'ee-MOH-jee', description: 'Picture characters' },
  { pattern: /\bkawaii\b/gi, replacement: 'kah-WAH-ee', description: 'Cute' },
  { pattern: /\botaku\b/gi, replacement: 'oh-TAH-koo', description: 'Enthusiast/geek' },
  { pattern: /\banime\b/gi, replacement: 'AH-nee-may', description: 'Japanese animation' },
  { pattern: /\bmanga\b/gi, replacement: 'MAHN-gah', description: 'Japanese comics' },
  
  // -------------------------------------------------------------------------
  // Japanese Concepts & Philosophy (Nayan's domain)
  // -------------------------------------------------------------------------
  { pattern: /\bwabi[\s-]?sabi\b/gi, replacement: 'WAH-bee SAH-bee', description: 'Beauty of imperfection' },
  { pattern: /\bikigai\b/gi, replacement: 'ee-kee-GUY', description: 'Reason for being' },
  { pattern: /\bkintsugi\b/gi, replacement: 'kin-TSOO-gee', description: 'Gold repair art' },
  { pattern: /\bshinrin[\s-]?yoku\b/gi, replacement: 'SHIN-rin YO-koo', description: 'Forest bathing' },
  { pattern: /\bkaizen\b/gi, replacement: 'KY-zen', description: 'Continuous improvement' },
  { pattern: /\bkanban\b/gi, replacement: 'KAHN-bahn', description: 'Visual workflow' },
  { pattern: /\bhanami\b/gi, replacement: 'hah-NAH-mee', description: 'Flower viewing' },
  { pattern: /\bmono\s+no\s+aware\b/gi, replacement: 'MO-no no ah-WAH-reh', description: 'Pathos of things' },
  { pattern: /\byugen\b/gi, replacement: 'YOO-gen', description: 'Profound mystery' },
  { pattern: /\bma\b(?=\s+(space|concept|philosophy))/gi, replacement: 'mah', description: 'Negative space' },
  { pattern: /\bshoshin\b/gi, replacement: 'SHO-shin', description: 'Beginners mind' },
  { pattern: /\bmottainai\b/gi, replacement: 'mo-tie-NY', description: 'No waste philosophy' },
  { pattern: /\bganbatte\b/gi, replacement: 'gahn-BAH-teh', description: 'Do your best' },
  { pattern: /\bomoiyari\b/gi, replacement: 'oh-moy-YAH-ree', description: 'Empathic consideration' },
  { pattern: /\bnatsukashii\b/gi, replacement: 'nah-tsoo-KAH-shee', description: 'Nostalgic longing' },
  { pattern: /\bkomorebi\b/gi, replacement: 'ko-mo-REH-bee', description: 'Sunlight through leaves' },
  { pattern: /\btsundoku\b/gi, replacement: 'TSOON-doh-koo', description: 'Pile of unread books' },
  { pattern: /\bfurusato\b/gi, replacement: 'foo-roo-SAH-toh', description: 'Hometown/homeland' },
  { pattern: /\bokashi\b/gi, replacement: 'oh-KAH-shee', description: 'Charming/delightful' },
  { pattern: /\baware\b/gi, replacement: 'ah-WAH-reh', description: 'Gentle sadness/sensitivity' },
  { pattern: /\bshibui\b/gi, replacement: 'shee-BOO-ee', description: 'Simple refined beauty' },
  { pattern: /\bsuki\b/gi, replacement: 'SKEE', description: 'Aesthetic of gaps/voids' },
  { pattern: /\bwabisabi\b/gi, replacement: 'WAH-bee SAH-bee', description: 'Imperfect beauty' },
  { pattern: /\bgaman\b/gi, replacement: 'gah-MAHN', description: 'Dignified patience' },
  { pattern: /\benryo\b/gi, replacement: 'EN-ryoh', description: 'Polite restraint' },
  { pattern: /\bshoganai\b/gi, replacement: 'sho-gah-NY', description: 'It cant be helped' },
  { pattern: /\bnengajo\b/gi, replacement: 'nen-GAH-jo', description: 'New Year greeting cards' },

  // -------------------------------------------------------------------------
  // Japanese Poets & Writers (Nayan's domain)
  // -------------------------------------------------------------------------
  { pattern: /\bBasho\b/g, replacement: 'BAH-sho', description: 'Haiku master' },
  { pattern: /\bBashō\b/g, replacement: 'BAH-sho', description: 'Haiku master' },
  { pattern: /\bMatsuo\s+Bash[oō]\b/gi, replacement: 'maht-SOO-oh BAH-sho', description: 'Full name' },
  { pattern: /\bIssa\b/g, replacement: 'EE-sah', description: 'Haiku poet' },
  { pattern: /\bKobayashi\s+Issa\b/gi, replacement: 'ko-bah-YAH-shee EE-sah', description: 'Full name' },
  { pattern: /\bBuson\b/g, replacement: 'BOO-son', description: 'Haiku poet' },
  { pattern: /\bYosa\s+Buson\b/gi, replacement: 'YO-sah BOO-son', description: 'Full name' },
  { pattern: /\bShiki\b/g, replacement: 'SHEE-kee', description: 'Modern haiku master' },
  { pattern: /\bMasaoka\s+Shiki\b/gi, replacement: 'mah-sah-OH-kah SHEE-kee', description: 'Full name' },
  { pattern: /\bChiyo-?ni\b/gi, replacement: 'CHEE-yo-nee', description: 'Female haiku poet' },
  { pattern: /\bSantoka\b/gi, replacement: 'sahn-TOH-kah', description: 'Modern wandering poet' },
  { pattern: /\bTaneda\s+Santoka\b/gi, replacement: 'tah-NEH-dah sahn-TOH-kah', description: 'Full name' },
  { pattern: /\bRyokan\b/gi, replacement: 'RYOH-kahn', description: 'Zen poet-monk' },
  { pattern: /\bHosai\b/gi, replacement: 'HO-sigh', description: 'Free-verse haiku poet' },
  { pattern: /\bOzaki\s+Hosai\b/gi, replacement: 'oh-ZAH-kee HO-sigh', description: 'Full name' },
  { pattern: /\bKerouac\b/gi, replacement: 'KAIR-oh-ack', description: 'Beat generation writer' },
  { pattern: /\bMurakami\b/gi, replacement: 'moo-rah-KAH-mee', description: 'Japanese author' },

  // -------------------------------------------------------------------------
  // Japanese Poetry Terms (Nayan's domain)
  // -------------------------------------------------------------------------
  { pattern: /\bhaiku\b/gi, replacement: 'HY-koo', description: '5-7-5 poem form' },
  { pattern: /\btanka\b/gi, replacement: 'TAHN-kah', description: '31-syllable poem form' },
  { pattern: /\bsenryu\b/gi, replacement: 'SEN-ryoo', description: 'Comic haiku' },
  { pattern: /\brenku\b/gi, replacement: 'REN-koo', description: 'Linked verse' },
  { pattern: /\brenga\b/gi, replacement: 'REN-gah', description: 'Collaborative linked verse' },
  { pattern: /\bkigo\b/gi, replacement: 'KEE-go', description: 'Seasonal word' },
  { pattern: /\bkireji\b/gi, replacement: 'kee-REH-jee', description: 'Cutting word' },
  { pattern: /\bon\b(?=\s+(syllable|count|mora))/gi, replacement: 'own', description: 'Sound unit' },
  { pattern: /\bmora\b/gi, replacement: 'MOH-rah', description: 'Sound unit' },
  { pattern: /\bmorae\b/gi, replacement: 'MOH-rye', description: 'Sound units plural' },
  { pattern: /\bhonkadori\b/gi, replacement: 'hon-kah-DOH-ree', description: 'Allusive variation' },
  { pattern: /\bsaijiki\b/gi, replacement: 'sigh-JEE-kee', description: 'Seasonal almanac' },
  { pattern: /\bkukai\b/gi, replacement: 'KOO-ky', description: 'Haiku gathering' },
  { pattern: /\bginko\b/gi, replacement: 'GEEN-ko', description: 'Walking haiku composition' },
];

export const ZEN_BUDDHIST_PRONUNCIATIONS: PronunciationEntry[] = [
  // -------------------------------------------------------------------------
  // Zen Buddhism Terms
  // -------------------------------------------------------------------------
  { pattern: /\bzen\b/gi, replacement: 'zen', description: 'Japanese Buddhism' },
  { pattern: /\bzazen\b/gi, replacement: 'ZAH-zen', description: 'Seated meditation' },
  { pattern: /\bkinhin\b/gi, replacement: 'KIN-hin', description: 'Walking meditation' },
  { pattern: /\bsesshin\b/gi, replacement: 'SEH-shin', description: 'Meditation retreat' },
  { pattern: /\bkoan\b/gi, replacement: 'KO-ahn', description: 'Paradoxical riddle' },
  { pattern: /\bsatori\b/gi, replacement: 'sah-TOH-ree', description: 'Awakening/enlightenment' },
  { pattern: /\bkensho\b/gi, replacement: 'KEN-sho', description: 'Seeing true nature' },
  { pattern: /\bdokusan\b/gi, replacement: 'DOH-koo-sahn', description: 'Private interview' },
  { pattern: /\bteisho\b/gi, replacement: 'TAY-sho', description: 'Dharma talk' },
  { pattern: /\broshi\b/gi, replacement: 'RO-shee', description: 'Zen master' },
  { pattern: /\bsensei\b/gi, replacement: 'SEN-say', description: 'Teacher' },
  { pattern: /\bzendo\b/gi, replacement: 'ZEN-doh', description: 'Meditation hall' },
  { pattern: /\bkeisaku\b/gi, replacement: 'KAY-sah-koo', description: 'Encouragement stick' },
  { pattern: /\bkyosaku\b/gi, replacement: 'KYO-sah-koo', description: 'Wake-up stick' },
  { pattern: /\brakusu\b/gi, replacement: 'RAH-koo-soo', description: 'Small robe' },
  { pattern: /\bokesa\b/gi, replacement: 'oh-KEH-sah', description: 'Buddhist robe' },
  { pattern: /\bzafu\b/gi, replacement: 'ZAH-foo', description: 'Meditation cushion' },
  { pattern: /\bzabuton\b/gi, replacement: 'zah-BOO-ton', description: 'Floor mat' },
  { pattern: /\bmu\b(?=\s+(koan|response|answer))/gi, replacement: 'moo', description: 'Classic koan response' },
  { pattern: /\bgateless\s+gate\b/gi, replacement: 'GATE-less gate', description: 'Koan collection' },
  { pattern: /\bmumonkan\b/gi, replacement: 'moo-MON-kahn', description: 'Gateless Gate' },
  { pattern: /\bbodhi\b/gi, replacement: 'BO-dee', description: 'Awakening/enlightenment' },
  { pattern: /\bbodhisattva\b/gi, replacement: 'bo-dee-SAHT-vuh', description: 'Awakened being' },
  { pattern: /\bdharma\b/gi, replacement: 'DAR-muh', description: 'Teaching/truth/reality' },
  { pattern: /\bsangha\b/gi, replacement: 'SAHNG-guh', description: 'Community/group' },
  { pattern: /\bsutra\b/gi, replacement: 'SOO-truh', description: 'Sacred text' },
  { pattern: /\bsunyata\b/gi, replacement: 'shoon-YAH-tah', description: 'Emptiness' },
  { pattern: /\bnirvana\b/gi, replacement: 'nir-VAH-nuh', description: 'Liberation/awakening' },
  { pattern: /\bkarma\b/gi, replacement: 'KAR-muh', description: 'Action/consequence' },
  { pattern: /\bmudra\b/gi, replacement: 'MOO-druh', description: 'Hand gesture' },
  { pattern: /\bgassho\b/gi, replacement: 'GAH-sho', description: 'Palms together bow' },
  { pattern: /\banjali\b/gi, replacement: 'AHN-jah-lee', description: 'Prayer hands' },
  { pattern: /\bnamaste\b/gi, replacement: 'NAH-mah-stay', description: 'Greeting/bow' },
];

export const MINDFULNESS_PRONUNCIATIONS: PronunciationEntry[] = [
  // -------------------------------------------------------------------------
  // Sanskrit Terms
  // -------------------------------------------------------------------------
  { pattern: /\bprana\b/gi, replacement: 'PRAH-nah', description: 'Life force/breath' },
  { pattern: /\bpranayama\b/gi, replacement: 'prah-nah-YAH-mah', description: 'Breath control' },
  { pattern: /\byoga\b/gi, replacement: 'YO-guh', description: 'Union practice' },
  { pattern: /\byogi\b/gi, replacement: 'YO-gee', description: 'Yoga practitioner' },
  { pattern: /\byogini\b/gi, replacement: 'yo-GEE-nee', description: 'Female practitioner' },
  { pattern: /\basana\b/gi, replacement: 'AH-suh-nuh', description: 'Yoga posture' },
  { pattern: /\bsavasana\b/gi, replacement: 'shah-VAH-suh-nuh', description: 'Corpse pose' },
  { pattern: /\btadasana\b/gi, replacement: 'tah-DAH-suh-nuh', description: 'Mountain pose' },
  { pattern: /\bchakra\b/gi, replacement: 'CHAK-ruh', description: 'Energy center' },
  { pattern: /\bchakras\b/gi, replacement: 'CHAK-ruhz', description: 'Energy centers' },
  { pattern: /\bmantra\b/gi, replacement: 'MAHN-truh', description: 'Sacred sound/phrase' },
  { pattern: /\bmantras\b/gi, replacement: 'MAHN-truhz', description: 'Sacred sounds' },
  { pattern: /\bom\b(?=\s|$|[.,!?])/gi, replacement: 'ohm', description: 'Sacred syllable' },
  { pattern: /\baum\b/gi, replacement: 'ah-ohm', description: 'Sacred syllable' },
  { pattern: /\bahimsa\b/gi, replacement: 'ah-HIM-sah', description: 'Non-violence' },
  { pattern: /\bsatya\b/gi, replacement: 'SAHT-yuh', description: 'Truthfulness' },
  { pattern: /\basteya\b/gi, replacement: 'ah-STAY-uh', description: 'Non-stealing' },
  { pattern: /\bbrahmacharya\b/gi, replacement: 'brah-muh-CHAR-yuh', description: 'Moderation' },
  { pattern: /\baparigraha\b/gi, replacement: 'ah-pah-ree-GRAH-hah', description: 'Non-attachment' },
  { pattern: /\bdrishti\b/gi, replacement: 'DRISH-tee', description: 'Focused gaze' },
  { pattern: /\bbandha\b/gi, replacement: 'BAHN-dah', description: 'Energy lock' },
  { pattern: /\bkundali[ni]?\b/gi, replacement: 'koon-dah-LEE-nee', description: 'Coiled energy' },
  { pattern: /\bsamadhi\b/gi, replacement: 'suh-MAH-dee', description: 'Absorption/union' },
  { pattern: /\bsiddhi\b/gi, replacement: 'SID-dee', description: 'Spiritual power' },
  { pattern: /\bgunas?\b/gi, replacement: 'GOO-nuhz', description: 'Fundamental qualities' },
  { pattern: /\bsattva\b/gi, replacement: 'SAHT-vuh', description: 'Purity/harmony quality' },
  { pattern: /\brajas\b/gi, replacement: 'RAH-jus', description: 'Activity quality' },
  { pattern: /\btamas\b/gi, replacement: 'TAH-mus', description: 'Inertia quality' },
  { pattern: /\bguru\b/gi, replacement: 'GOO-roo', description: 'Spiritual teacher' },
  { pattern: /\bashram\b/gi, replacement: 'ASH-rum', description: 'Spiritual retreat' },
  { pattern: /\batman\b/gi, replacement: 'AHT-mun', description: 'True self/soul' },
  { pattern: /\bbrahman\b/gi, replacement: 'BRAH-mun', description: 'Ultimate reality' },
  { pattern: /\bmaya\b(?=.*illusion|.*veil)/gi, replacement: 'MAH-yuh', description: 'Illusion' },
  { pattern: /\bsamsara\b/gi, replacement: 'sahm-SAH-ruh', description: 'Cycle of rebirth' },
  { pattern: /\bmoksha\b/gi, replacement: 'MOHK-shuh', description: 'Liberation' },
  { pattern: /\bbhakti\b/gi, replacement: 'BAHK-tee', description: 'Devotional path' },
  { pattern: /\bjnana\b/gi, replacement: 'GYAH-nuh', description: 'Knowledge path' },
  { pattern: /\babhyasa\b/gi, replacement: 'ahb-YAH-suh', description: 'Consistent practice' },
  { pattern: /\bvairagya\b/gi, replacement: 'vy-RAHG-yuh', description: 'Non-attachment' },
  { pattern: /\bsantosha\b/gi, replacement: 'sahn-TOH-shuh', description: 'Contentment' },
  { pattern: /\btapas\b/gi, replacement: 'TAH-pus', description: 'Discipline/heat' },
  { pattern: /\bsvadhyaya\b/gi, replacement: 'svahd-YAH-yuh', description: 'Self-study' },
  { pattern: /\bishvara\b/gi, replacement: 'EESH-vah-ruh', description: 'Divine/higher power' },

  // -------------------------------------------------------------------------
  // Tibetan Buddhist Terms
  // -------------------------------------------------------------------------
  { pattern: /\bTibetan\b/g, replacement: 'tih-BET-un', description: 'From Tibet' },
  { pattern: /\bDalai\s+Lama\b/gi, replacement: 'DAH-lie LAH-mah', description: 'Tibetan leader' },
  { pattern: /\blama\b/gi, replacement: 'LAH-mah', description: 'Tibetan teacher' },
  { pattern: /\btulku\b/gi, replacement: 'TOOL-koo', description: 'Reincarnated teacher' },
  { pattern: /\brinpoche\b/gi, replacement: 'rin-PO-chay', description: 'Precious one' },
  { pattern: /\bgeshe\b/gi, replacement: 'GEH-shay', description: 'Learned teacher' },
  { pattern: /\btongle[n]?\b/gi, replacement: 'TONG-len', description: 'Giving and taking' },
  { pattern: /\bmetta\b/gi, replacement: 'MET-tuh', description: 'Loving-kindness' },
  { pattern: /\bvipassana\b/gi, replacement: 'vih-PAH-suh-nuh', description: 'Insight meditation' },
  { pattern: /\bsamatha\b/gi, replacement: 'shah-MAH-tuh', description: 'Calm abiding' },
  { pattern: /\bdzogchen\b/gi, replacement: 'ZOHG-chen', description: 'Great perfection' },
  { pattern: /\bmahamudra\b/gi, replacement: 'mah-hah-MOO-druh', description: 'Great seal' },
  { pattern: /\bbardo\b/gi, replacement: 'BAR-doh', description: 'Intermediate state' },
  { pattern: /\bthangka\b/gi, replacement: 'TAHNG-kah', description: 'Tibetan painting' },
  { pattern: /\bmala\b/gi, replacement: 'MAH-luh', description: 'Prayer beads' },
  { pattern: /\bstupa\b/gi, replacement: 'STOO-pah', description: 'Sacred monument' },
  { pattern: /\bmandala\b/gi, replacement: 'MAN-duh-luh', description: 'Sacred circle' },
  { pattern: /\bthanks?\s+giving\s+practice\b/gi, replacement: 'thanks giving practice', description: 'Gratitude meditation' },
];

export const THOUGHT_LEADER_PRONUNCIATIONS: PronunciationEntry[] = [
  // -------------------------------------------------------------------------
  // Authors & Thought Leaders (Nayan's domain)
  // -------------------------------------------------------------------------
  { pattern: /\bBren[eé]\s+Brown\b/gi, replacement: 'breh-NAY brown', description: 'Vulnerability researcher' },
  { pattern: /\bTara\s+Brach\b/gi, replacement: 'TAH-ruh brock', description: 'Meditation teacher' },
  { pattern: /\bPema\s+Ch[oö]dr[oö]n\b/gi, replacement: 'PEH-muh CHO-drun', description: 'Buddhist teacher' },
  { pattern: /\bThich\s+Nhat\s+Hanh\b/gi, replacement: 'tik NOT hahn', description: 'Buddhist teacher' },
  { pattern: /\bThich\b/g, replacement: 'tik', description: 'Vietnamese Buddhist title' },
  { pattern: /\bNhat\s+Hanh\b/gi, replacement: 'NOT hahn', description: 'Vietnamese name' },
  { pattern: /\bEckhart\s+Tolle\b/gi, replacement: 'ECK-hart TOL-lay', description: 'Spiritual author' },
  { pattern: /\bTolle\b/g, replacement: 'TOL-lay', description: 'Author surname' },
  { pattern: /\bJon\s+Kabat[\s-]?Zinn\b/gi, replacement: 'jon kuh-BAT zin', description: 'Mindfulness pioneer' },
  { pattern: /\bKabat[\s-]?Zinn\b/gi, replacement: 'kuh-BAT zin', description: 'Mindfulness surname' },
  { pattern: /\bRam\s+Dass\b/gi, replacement: 'rahm dahss', description: 'Spiritual teacher' },
  { pattern: /\bAlan\s+Watts\b/gi, replacement: 'AL-un wots', description: 'Philosopher' },
  { pattern: /\bJoseph\s+Campbell\b/gi, replacement: 'JO-suf CAM-bul', description: 'Mythologist' },
  { pattern: /\bCarl\s+Jung\b/gi, replacement: 'karl yoong', description: 'Psychologist' },
  { pattern: /\bJung\b(?=ian|\s)/g, replacement: 'yoong', description: 'Psychologist surname' },
  { pattern: /\bJungian\b/gi, replacement: 'YOONG-ee-un', description: 'Of Carl Jung' },
  { pattern: /\bViktor\s+Frankl\b/gi, replacement: 'VIK-tor FRAN-kul', description: 'Logotherapy founder' },
  { pattern: /\bFrankl\b/g, replacement: 'FRAN-kul', description: 'Author surname' },
  { pattern: /\bMihaly\s+Csikszentmihalyi\b/gi, replacement: 'mee-HIGH cheek-sent-mee-HIGH', description: 'Flow researcher' },
  { pattern: /\bCsikszentmihalyi\b/gi, replacement: 'cheek-sent-mee-HIGH', description: 'Researcher surname' },
  { pattern: /\bMartin\s+Seligman\b/gi, replacement: 'MAR-tin SEH-lig-mun', description: 'Positive psychology founder' },
  { pattern: /\bAngela\s+Duckworth\b/gi, replacement: 'AN-juh-luh DUCK-worth', description: 'Grit researcher' },
  { pattern: /\bCarol\s+Dweck\b/gi, replacement: 'KAIR-ul dwek', description: 'Mindset researcher' },
  { pattern: /\bDweck\b/g, replacement: 'dwek', description: 'Researcher surname' },
  { pattern: /\bBJ\s+Fogg\b/gi, replacement: 'B J fog', description: 'Tiny Habits author' },
  { pattern: /\bFogg\b/g, replacement: 'fog', description: 'Author surname' },
  { pattern: /\bJames\s+Clear\b/gi, replacement: 'james cleer', description: 'Atomic Habits author' },
  { pattern: /\bGretchen\s+Rubin\b/gi, replacement: 'GRETCH-un ROO-bin', description: 'Habits researcher' },
  { pattern: /\bCharles\s+Duhigg\b/gi, replacement: 'charlz doo-HIG', description: 'Power of Habit author' },
  { pattern: /\bDuhigg\b/g, replacement: 'doo-HIG', description: 'Author surname' },
  { pattern: /\bSimon\s+Sinek\b/gi, replacement: 'SY-mun SIN-ek', description: 'Leadership author' },
  { pattern: /\bSinek\b/g, replacement: 'SIN-ek', description: 'Author surname' },
  { pattern: /\bAdam\s+Grant\b/gi, replacement: 'AD-um grant', description: 'Organizational psychologist' },
  { pattern: /\bDaniel\s+Kahneman\b/gi, replacement: 'DAN-yul KAH-nuh-mun', description: 'Behavioral economist' },
  { pattern: /\bKahneman\b/g, replacement: 'KAH-nuh-mun', description: 'Economist surname' },
  { pattern: /\bAmos\s+Tversky\b/gi, replacement: 'AH-mos tuh-VER-skee', description: 'Cognitive psychologist' },
  { pattern: /\bTversky\b/g, replacement: 'tuh-VER-skee', description: 'Psychologist surname' },
  { pattern: /\bNassim\s+Taleb\b/gi, replacement: 'nah-SEEM tah-LEB', description: 'Black Swan author' },
  { pattern: /\bTaleb\b/g, replacement: 'tah-LEB', description: 'Author surname' },
  { pattern: /\bYuval\s+(Noah\s+)?Harari\b/gi, replacement: 'yoo-VAHL hah-RAH-ree', description: 'Sapiens author' },
  { pattern: /\bHarari\b/g, replacement: 'hah-RAH-ree', description: 'Author surname' },

  // -------------------------------------------------------------------------
  // Philosophers
  // -------------------------------------------------------------------------
  { pattern: /\bNietzsche\b/gi, replacement: 'NEE-chuh', description: 'German philosopher' },
  { pattern: /\bKierkegaard\b/gi, replacement: 'KEER-kuh-gard', description: 'Danish philosopher' },
  { pattern: /\bSartre\b/gi, replacement: 'SAR-truh', description: 'French philosopher' },
  { pattern: /\bCamus\b/gi, replacement: 'kah-MOO', description: 'French philosopher' },
  { pattern: /\bHeidegger\b/gi, replacement: 'HY-deh-gur', description: 'German philosopher' },
  { pattern: /\bSimone\s+de\s+Beauvoir\b/gi, replacement: 'see-MOHN duh bo-VWAHR', description: 'French philosopher' },
  { pattern: /\bFoucault\b/gi, replacement: 'foo-KOH', description: 'French philosopher' },
  { pattern: /\bDerrida\b/gi, replacement: 'deh-ree-DAH', description: 'French philosopher' },
  { pattern: /\bDescartes\b/gi, replacement: 'day-KART', description: 'French philosopher' },
  { pattern: /\bLao\s*[Tt]zu\b/gi, replacement: 'lao dzuh', description: 'Taoism founder' },
  { pattern: /\bConfucius\b/gi, replacement: 'kun-FYOO-shus', description: 'Chinese philosopher' },
  { pattern: /\bZhuangzi\b/gi, replacement: 'jwahng-dzuh', description: 'Taoist philosopher' },
  { pattern: /\bMencius\b/gi, replacement: 'MEN-shee-us', description: 'Chinese philosopher' },
  { pattern: /\bSeneca\b/gi, replacement: 'SEN-ih-kuh', description: 'Roman Stoic' },
  { pattern: /\bEpictetus\b/gi, replacement: 'ep-ik-TEE-tus', description: 'Roman Stoic' },
  { pattern: /\bMarcus\s+Aurelius\b/gi, replacement: 'MAR-kus aw-REE-lee-us', description: 'Roman Emperor/Stoic' },
  { pattern: /\bAurelius\b/g, replacement: 'aw-REE-lee-us', description: 'Roman name' },

  // -------------------------------------------------------------------------
  // Productivity Authors
  // -------------------------------------------------------------------------
  { pattern: /\bDavid\s+Allen\b/gi, replacement: 'DAY-vid AL-un', description: 'GTD author' },
  { pattern: /\bGTD\b/g, replacement: 'G T D', description: 'Getting Things Done' },
  { pattern: /\bCal\s+Newport\b/gi, replacement: 'kal NOO-port', description: 'Deep Work author' },
  { pattern: /\bTimothy\s+Ferriss\b/gi, replacement: 'TIM-uh-thee FAIR-is', description: '4-Hour author' },
  { pattern: /\bFerriss\b/g, replacement: 'FAIR-is', description: 'Author surname' },
  { pattern: /\bTim\s+Ferriss\b/gi, replacement: 'tim FAIR-is', description: '4-Hour author' },
  { pattern: /\bRyan\s+Holiday\b/gi, replacement: 'RY-un HOL-ih-day', description: 'Stoicism author' },
  { pattern: /\bPomodoro\b/gi, replacement: 'poh-moh-DOH-roh', description: 'Time technique' },
  { pattern: /\bEisenhower\b/gi, replacement: 'EYE-zen-how-er', description: 'Priority matrix' },
];

export const MISPRONOUNCED_WORDS: PronunciationEntry[] = [
  // -------------------------------------------------------------------------
  // Emotional/Coaching Words (commonly mispronounced)
  // -------------------------------------------------------------------------
  { pattern: /\bresilience\b/gi, replacement: 'rih-ZIL-yuns', description: 'Bouncing back' },
  { pattern: /\bvulnerability\b/gi, replacement: 'vul-ner-uh-BIL-ih-tee', description: 'Being open' },
  { pattern: /\bauthenticity\b/gi, replacement: 'aw-then-TIS-ih-tee', description: 'Being genuine' },
  { pattern: /\bequanimity\b/gi, replacement: 'ee-kwuh-NIM-ih-tee', description: 'Mental calmness' },
  { pattern: /\bself-compassion\b/gi, replacement: 'Self-kum-PASH-un', description: 'Self-kindness' },
  { pattern: /\bperseverance\b/gi, replacement: 'per-suh-VEER-uns', description: 'Persistence' },
  { pattern: /\bmischievous\b/gi, replacement: 'MIS-chih-vus', description: 'Commonly mispronounced' },
  { pattern: /\bawry\b/gi, replacement: 'uh-RYE', description: 'Gone wrong' },
  { pattern: /\bchasm\b/gi, replacement: 'KAZ-um', description: 'Deep gap' },
  { pattern: /\bdebut\b/gi, replacement: 'day-BYOO', description: 'First appearance' },
  { pattern: /\bdebris\b/gi, replacement: 'duh-BREE', description: 'Scattered fragments' },
  
  // -------------------------------------------------------------------------
  // Commonly Mispronounced Words
  // -------------------------------------------------------------------------
  { pattern: /\betc\.?\b/gi, replacement: 'et cetera', description: 'Latin abbreviation' },
  { pattern: /\bie\.?\b/gi, replacement: 'that is', description: 'Latin abbreviation' },
  { pattern: /\beg\.?\b/gi, replacement: 'for example', description: 'Latin abbreviation' },
  { pattern: /\be\.g\.?\b/gi, replacement: 'for example', description: 'Latin abbreviation' },
  { pattern: /\bi\.e\.?\b/gi, replacement: 'that is', description: 'Latin abbreviation' },
  { pattern: /\bvice\s+versa\b/gi, replacement: 'vice VER-suh', description: 'Latin phrase' },
  { pattern: /\bbona\s+fide\b/gi, replacement: 'BOH-nuh fide', description: 'Latin phrase' },
  { pattern: /\bper\s+se\b/gi, replacement: 'per SAY', description: 'Latin phrase' },
  { pattern: /\bad\s+hoc\b/gi, replacement: 'ad HOK', description: 'Latin phrase' },
  { pattern: /\bstatus\s+quo\b/gi, replacement: 'STAY-tus KWO', description: 'Latin phrase' },
  { pattern: /\bquid\s+pro\s+quo\b/gi, replacement: 'kwid pro KWO', description: 'Latin phrase' },
  { pattern: /\bpro\s+bono\b/gi, replacement: 'pro BO-no', description: 'Latin phrase' },
  { pattern: /\bcoup\s+de\s+gr[aâ]ce\b/gi, replacement: 'koo duh GRAHSS', description: 'French phrase' },
  { pattern: /\bfaux\s+pas\b/gi, replacement: 'foh PAH', description: 'French phrase' },
  { pattern: /\blaissez[\s-]?faire\b/gi, replacement: 'less-ay FAIR', description: 'French phrase' },
  { pattern: /\braison\s+d['']?[êe]tre\b/gi, replacement: 'ray-ZOHN DET-ruh', description: 'French phrase' },
  { pattern: /\bjoie\s+de\s+vivre\b/gi, replacement: 'zhwah duh VEEV-ruh', description: 'French phrase' },
  { pattern: /\bje\s+ne\s+sais\s+quoi\b/gi, replacement: 'zhuh nuh say KWAH', description: 'French phrase' },
  { pattern: /\bschadenfreude\b/gi, replacement: 'SHAH-den-froy-duh', description: 'German word' },
  { pattern: /\bzeitgeist\b/gi, replacement: 'TSITE-guyst', description: 'German word' },
  { pattern: /\bwanderlust\b/gi, replacement: 'WON-der-lust', description: 'German word' },
  { pattern: /\bgestalt\b/gi, replacement: 'guh-SHTALT', description: 'German word' },
  { pattern: /\bangst\b/gi, replacement: 'ahngst', description: 'German word' },
  { pattern: /\bkitsch\b/gi, replacement: 'kitch', description: 'German word' },
  { pattern: /\bubiquitous\b/gi, replacement: 'yoo-BIK-wih-tus', description: 'Commonly mispronounced' },
  { pattern: /\bnuance\b/gi, replacement: 'NOO-ahnce', description: 'Commonly mispronounced' },
  { pattern: /\bsegue\b/gi, replacement: 'SEG-way', description: 'Commonly mispronounced' },
  { pattern: /\bcache\b/gi, replacement: 'cash', description: 'Commonly mispronounced' },
  { pattern: /\bniche\b/gi, replacement: 'neesh', description: 'Commonly mispronounced' },
  { pattern: /\bepitome\b/gi, replacement: 'ih-PIT-uh-mee', description: 'Commonly mispronounced' },
  { pattern: /\bhyperbole\b/gi, replacement: 'hy-PER-buh-lee', description: 'Commonly mispronounced' },
  { pattern: /\bawry\b/gi, replacement: 'uh-RY', description: 'Commonly mispronounced' },
  { pattern: /\bmisc\.?\b/gi, replacement: 'miscellaneous', description: 'Abbreviation' },
  { pattern: /\bmiscellaneous\b/gi, replacement: 'miss-uh-LAY-nee-us', description: 'Commonly mispronounced' },
  { pattern: /\bquinoa\b/gi, replacement: 'KEEN-wah', description: 'Food grain' },
  { pattern: /\bacai\b/gi, replacement: 'ah-sah-EE', description: 'Food berry' },
  { pattern: /\bpho\b(?=\s|$)/gi, replacement: 'fuh', description: 'Vietnamese soup' },
  { pattern: /\bgyro\b/gi, replacement: 'YEE-roh', description: 'Greek food' },
  { pattern: /\bespresso\b/gi, replacement: 'ess-PRESS-oh', description: 'Coffee (not expresso)' },
  { pattern: /\bchipotle\b/gi, replacement: 'chih-POHT-lay', description: 'Mexican pepper' },
  { pattern: /\bjalape[nñ]o\b/gi, replacement: 'hah-luh-PAYN-yo', description: 'Mexican pepper' },
  { pattern: /\bquesadilla\b/gi, replacement: 'kay-suh-DEE-yuh', description: 'Mexican food' },
  { pattern: /\bcroissant\b/gi, replacement: 'kwah-SAHN', description: 'French pastry' },
  { pattern: /\bbruschetta\b/gi, replacement: 'broo-SKET-tuh', description: 'Italian appetizer' },
  { pattern: /\bgnocchi\b/gi, replacement: 'NYOH-kee', description: 'Italian pasta' },
  { pattern: /\brigatoni\b/gi, replacement: 'rig-uh-TOH-nee', description: 'Italian pasta' },
  { pattern: /\bprosciutto\b/gi, replacement: 'pro-SHOO-toh', description: 'Italian ham' },
];

