/**
 * Shared LLM-Powered Dynamic Expression Generator
 *
 * "Better than human" personality expressions generated by Gemini in the background.
 * This is the persona-agnostic version that works for ALL personas.
 *
 * This is the next evolution beyond pool-based selection and building-block composition:
 * - Truly UNIQUE expressions every time (no repetition)
 * - PERSONA-GROUNDED via dynamic Voice DNA loading
 * - NON-BLOCKING - runs on async queue in background
 * - PRE-GENERATION - fills cache during quiet moments
 * - COST-EFFICIENT - batching, caching, smart throttling
 *
 * Architecture:
 * 1. Expression queue - requests queued, processed in batches
 * 2. LLM worker - generates expressions with persona grounding
 * 3. Expression cache - stores generated expressions for reuse
 * 4. Fallback chain - LLM → Composed → Pool-based
 *
 * @module personas/shared/llm-expression-generator
 */

import type { ThemeCategory } from '../../services/session-variety-tracker.js';
import { createLogger } from '../../utils/safe-logger.js';
import { cleanForFirestore } from '../../utils/firestore-utils.js';
import { getVoiceDNAPrompt } from './voice-dna-loader.js';

const log = createLogger({ module: 'llm-expression-gen-shared' });

// ============================================================================
// TYPES
// ============================================================================

export interface ExpressionRequest {
  id: string;
  personaId: string;
  theme: ThemeCategory;
  context: ExpressionContext;
  priority: 'high' | 'normal' | 'low';
  timestamp: number;
}

export interface ExpressionContext {
  /** User's current emotional state */
  emotion?: string;
  /** Current conversation topic */
  topic?: string;
  /** Time of day */
  timeOfDay?: 'dawn' | 'morning' | 'afternoon' | 'evening' | 'late_night' | 'night';
  /** Relationship depth */
  relationshipStage?: 'stranger' | 'acquaintance' | 'friend' | 'trusted_advisor';
  /** Recent topics for callbacks */
  recentTopics?: string[];
  /** Conversation momentum */
  momentum?: 'opening' | 'building' | 'cruising' | 'winding_down';
  /** Was this a heavy topic? */
  isHeavyTopic?: boolean;
}

export interface GeneratedExpression {
  id: string;
  personaId: string;
  theme: ThemeCategory;
  content: string;
  ssml: string;
  context: ExpressionContext;
  generatedAt: Date;
  usedCount: number;
}

// ============================================================================
// STATE
// ============================================================================

// Expression cache (per persona + user for personalization, plus global fallback)
const expressionCache = new Map<string, GeneratedExpression[]>();
const MAX_CACHE_PER_KEY = 50;
const _CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes (for future TTL cleanup)

// Generation queue
const generationQueue: ExpressionRequest[] = [];
let isProcessingQueue = false;
const MAX_QUEUE_SIZE = 100;
const REQUEST_EXPIRY_MS = 5 * 60 * 1000; // 5 minutes

// Batch processing
const BATCH_SIZE = 5;
const BATCH_DELAY_MS = 500;

// Rate limiting
let lastGenerationAt = 0;
const MIN_GENERATION_INTERVAL_MS = 1000;

// Stats
const stats = {
  totalRequests: 0,
  cacheHits: 0,
  llmCalls: 0,
  llmFailures: 0,
  avgLatencyMs: 0,
};

// Voice DNA cache (per persona)
const voiceDNACache = new Map<string, string>();

// ============================================================================
// CACHE KEY HELPERS
// ============================================================================

function getCacheKey(personaId: string, userId?: string): string {
  if (userId) {
    return `${personaId}:${userId}`;
  }
  return `${personaId}:__global__`;
}

// ============================================================================
// PROMPT BUILDING
// ============================================================================

async function buildExpressionPrompt(
  personaId: string,
  personaName: string,
  requests: ExpressionRequest[]
): Promise<string> {
  // Get Voice DNA (cached)
  let voiceDNA = voiceDNACache.get(personaId);
  if (!voiceDNA) {
    voiceDNA = await getVoiceDNAPrompt(personaId);
    voiceDNACache.set(personaId, voiceDNA);
  }

  // Theme examples (generic, persona-appropriate)
  const examples: Record<ThemeCategory, string[]> = {
    warm_drinks: ['Something warm in my hands. Helps me think.', 'Tea today. Need the calm.'],
    global_traveler: [
      'Travel taught me that. The pause before speaking.',
      'Different places change how you see things.',
    ],
    music_taste: [
      'Music in the background. Good for this.',
      'Something slow today. Helps me focus.',
    ],
    family_life: ['Family teaches you things. Patience, mostly.', 'Kids change your perspective.'],
    physical_habits: ['Writing that down. Old school.', 'Something grounding helps.'],
    nature_connection: ['Big sky. Nothing else compares.', 'Nature perspective.'],
    vulnerability: [
      'I know something about that. Not claiming to know yours.',
      'Some things stay with you.',
    ],
    quirky_interests: ['Strange hobby, I know.', 'Everyone has their thing.'],
    sensory_moment: [
      'Your voice changed just now. What happened?',
      'Something shifted. I can hear it.',
    ],
    food_opinions: [],
    philosophical: [],
    professional: [],
    celebration: [],
    adventure: [],
    family_milestones: [],
    life_transitions: [],
    wisdom: [],
    mortality_awareness: [],
    communication_wisdom: [],
    professional_insight: [],
    productivity: [],
    nutrition: [],
    market_history: [],
    analytical_process: [],
    behavioral_finance: [],
    long_term_thinking: [],
    investment_philosophy: [],
    wealth_philosophy: [],
  };

  const requestDescriptions = requests
    .map((r, i) => {
      const themeExamples = examples[r.theme] || [];
      const contextDesc = [];
      if (r.context.emotion) contextDesc.push(`User emotion: ${r.context.emotion}`);
      if (r.context.timeOfDay) contextDesc.push(`Time: ${r.context.timeOfDay}`);
      if (r.context.momentum) contextDesc.push(`Momentum: ${r.context.momentum}`);
      if (r.context.relationshipStage)
        contextDesc.push(`Relationship: ${r.context.relationshipStage}`);
      if (r.context.topic) contextDesc.push(`Topic: ${r.context.topic}`);

      return `
${i + 1}. Theme: ${r.theme}
   Context: ${contextDesc.length > 0 ? contextDesc.join(', ') : 'General'}
   ${themeExamples.length > 0 ? `Style examples (DON'T copy, use as voice reference):\n   - "${themeExamples.join('"\n   - "')}"` : ''}
`;
    })
    .join('\n');

  return `${voiceDNA}

## YOUR TASK
Generate ${requests.length} unique personality expressions for ${personaName}. These are short, authentic moments that reveal character - NOT responses to the user.

Think of them as "caught doing" or "between thoughts" moments:
- What ${personaName} might be doing/thinking when the user connects
- Physical grounding (drink, notebook, window)
- Brief backstory flashes
- Sensory observations

## REQUIREMENTS
- 1-2 SHORT sentences max (conversational, not speeches)
- Include SSML breaks: <break time="150ms"/> or <break time="200ms"/>
- NEVER use AI tells ("That's interesting", "I understand")
- Voice should feel LIVED-IN, not performed
- Each expression must be UNIQUE (never repeat yourself)
- Match the context/mood when provided
- Stay TRUE to ${personaName}'s character as described above

## REQUESTS
${requestDescriptions}

## OUTPUT FORMAT
Return a JSON array with exactly ${requests.length} objects:
[
  {
    "index": 1,
    "content": "The plain text version",
    "ssml": "Version with <break time=\"150ms\"/> tags for pacing"
  },
  ...
]

Generate now:`;
}

// ============================================================================
// CONTENT VALIDATION
// ============================================================================

const AI_TELLS = [
  "that's interesting",
  'i understand',
  'i hear you',
  'good question',
  'how can i help you today',
  'how does that make you feel',
  'tell me more about that',
  "what i'm hearing is",
  "let's unpack that",
  'at the end of the day',
  'moving forward',
  'everything happens for a reason',
  'just be positive',
  'it could be worse',
  'i appreciate you sharing',
  'thank you for sharing',
];

function isValidExpression(content: string): boolean {
  const lowerContent = content.toLowerCase();

  for (const tell of AI_TELLS) {
    if (lowerContent.includes(tell)) {
      return false;
    }
  }

  const sentences = content.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  if (sentences.length > 3) {
    return false;
  }

  if (content.trim().length < 10) {
    return false;
  }

  return true;
}

// ============================================================================
// LLM INTEGRATION
// ============================================================================

async function callGeminiForExpressions(
  personaId: string,
  personaName: string,
  requests: ExpressionRequest[]
): Promise<GeneratedExpression[] | null> {
  const startTime = Date.now();

  try {
    const { getGeminiClient, isGeminiConfigured, GEMINI_MODEL, LLM_TIMEOUT_MS } =
      await import('../../config/gemini-config.js');

    if (!isGeminiConfigured()) {
      log.debug('Gemini not configured, skipping LLM generation');
      return null;
    }

    const genai = await getGeminiClient();
    if (!genai) {
      log.debug('Failed to get Gemini client, skipping LLM generation');
      return null;
    }

    const prompt = await buildExpressionPrompt(personaId, personaName, requests);

    const response = await Promise.race([
      (
        genai as {
          models: { generateContent: (p: unknown) => Promise<{ text: string }> };
        }
      ).models.generateContent({
        model: GEMINI_MODEL,
        contents: prompt,
        config: {
          temperature: 0.9,
          maxOutputTokens: 500,
        },
      }),
      new Promise<never>((_, reject) => {
        setTimeout(() => reject(new Error('Gemini timeout')), LLM_TIMEOUT_MS * 1.6);
      }),
    ]);

    const text = response.text?.trim() || '';

    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      log.warn('No JSON array in response');
      return null;
    }

    const parsed = JSON.parse(jsonMatch[0]) as Array<{
      index: number;
      content: string;
      ssml: string;
    }>;

    const expressions: GeneratedExpression[] = [];
    for (const item of parsed) {
      const request = requests[item.index - 1];
      if (!request) continue;

      if (isValidExpression(item.content)) {
        expressions.push({
          id: `gen-${request.id}-${Date.now()}`,
          personaId,
          theme: request.theme,
          content: item.content,
          ssml: item.ssml || item.content,
          context: request.context,
          generatedAt: new Date(),
          usedCount: 0,
        });
      } else {
        log.debug({ content: item.content }, 'Filtered invalid LLM expression');
      }
    }

    stats.llmCalls++;
    const latency = Date.now() - startTime;
    stats.avgLatencyMs = (stats.avgLatencyMs * (stats.llmCalls - 1) + latency) / stats.llmCalls;

    log.info(
      { personaId, count: expressions.length, latencyMs: latency },
      '🎭 LLM expressions generated'
    );

    return expressions;
  } catch (error) {
    stats.llmFailures++;
    log.warn({ error: String(error) }, 'LLM expression generation failed');
    return null;
  }
}

// ============================================================================
// QUEUE PROCESSING
// ============================================================================

async function processQueue(): Promise<void> {
  if (isProcessingQueue || generationQueue.length === 0) return;

  isProcessingQueue = true;

  try {
    const timeSinceLastGen = Date.now() - lastGenerationAt;
    if (timeSinceLastGen < MIN_GENERATION_INTERVAL_MS) {
      await new Promise<void>((resolve) => {
        setTimeout(resolve, MIN_GENERATION_INTERVAL_MS - timeSinceLastGen);
      });
    }

    // Purge expired requests
    const now = Date.now();
    const expiredCount = generationQueue.filter(
      (r) => now - r.timestamp > REQUEST_EXPIRY_MS
    ).length;
    if (expiredCount > 0) {
      for (let i = generationQueue.length - 1; i >= 0; i--) {
        if (now - generationQueue[i].timestamp > REQUEST_EXPIRY_MS) {
          generationQueue.splice(i, 1);
        }
      }
      log.debug({ expiredCount }, 'Purged expired expression requests');
    }

    // Group by persona for efficient batching
    const byPersona = new Map<string, ExpressionRequest[]>();
    for (const req of generationQueue) {
      const existing = byPersona.get(req.personaId) || [];
      existing.push(req);
      byPersona.set(req.personaId, existing);
    }

    // Process each persona's batch
    for (const [personaId, requests] of byPersona) {
      // Take a batch (prioritized)
      const batch = requests
        .sort((a, b) => {
          const priorityOrder = { high: 0, normal: 1, low: 2 };
          return priorityOrder[a.priority] - priorityOrder[b.priority];
        })
        .slice(0, BATCH_SIZE);

      if (batch.length === 0) continue;

      // Remove batch items from queue
      for (const req of batch) {
        const idx = generationQueue.indexOf(req);
        if (idx >= 0) generationQueue.splice(idx, 1);
      }

      // Get persona name
      let personaName = personaId;
      try {
        const { loadBundle } = await import('../bundles/loader.js');
        const bundle = await loadBundle(personaId);
        personaName = bundle.manifest.identity?.name || personaId;
      } catch {
        // Use ID as name
      }

      log.debug({ personaId, batchSize: batch.length }, 'Processing expression batch');

      const expressions = await callGeminiForExpressions(personaId, personaName, batch);
      lastGenerationAt = Date.now();

      if (expressions && expressions.length > 0) {
        const cacheKey = getCacheKey(personaId);
        for (const expr of expressions) {
          addToCache(cacheKey, expr);
        }
      }
    }
  } finally {
    isProcessingQueue = false;

    if (generationQueue.length > 0) {
      setTimeout(() => void processQueue(), BATCH_DELAY_MS);
    }
  }
}

// ============================================================================
// CACHE MANAGEMENT
// ============================================================================

function addToCache(cacheKey: string, expression: GeneratedExpression): void {
  let cache = expressionCache.get(cacheKey);
  if (!cache) {
    cache = [];
    expressionCache.set(cacheKey, cache);
  }

  cache.push(expression);

  if (cache.length > MAX_CACHE_PER_KEY) {
    cache.sort((a, b) => {
      if (a.usedCount !== b.usedCount) return b.usedCount - a.usedCount;
      return a.generatedAt.getTime() - b.generatedAt.getTime();
    });
    cache.splice(0, cache.length - MAX_CACHE_PER_KEY);
  }
}

function getFromCache(
  personaId: string,
  userId: string,
  theme: ThemeCategory,
  context: ExpressionContext
): GeneratedExpression | null {
  const userKey = getCacheKey(personaId, userId);
  const globalKey = getCacheKey(personaId);

  const userCache = expressionCache.get(userKey) || [];
  const globalCache = expressionCache.get(globalKey) || [];
  const allCandidates = [...userCache, ...globalCache];

  const candidates = allCandidates.filter((e) => {
    if (e.theme !== theme) return false;
    if (context.emotion && e.context.emotion && e.context.emotion !== context.emotion) {
      return false;
    }
    return true;
  });

  if (candidates.length === 0) return null;

  candidates.sort((a, b) => a.usedCount - b.usedCount);
  const selected = candidates[0];
  selected.usedCount++;

  stats.cacheHits++;
  return selected;
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Request an LLM-generated expression (async, non-blocking)
 */
export function requestExpression(
  personaId: string,
  theme: ThemeCategory,
  context: ExpressionContext,
  priority: 'high' | 'normal' | 'low' = 'normal'
): void {
  if (generationQueue.length >= MAX_QUEUE_SIZE) {
    log.debug('Queue full, dropping request');
    return;
  }

  const request: ExpressionRequest = {
    id: `${theme}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    personaId,
    theme,
    context,
    priority,
    timestamp: Date.now(),
  };

  generationQueue.push(request);
  stats.totalRequests++;

  void processQueue();
}

/**
 * Get a generated expression from cache
 */
export function getGeneratedExpression(
  personaId: string,
  userId: string,
  theme: ThemeCategory,
  context: ExpressionContext
): GeneratedExpression | null {
  return getFromCache(personaId, userId, theme, context);
}

/**
 * Pre-warm cache with expressions for a session
 */
export function prewarmCache(personaId: string, context: ExpressionContext): void {
  const commonThemes: ThemeCategory[] = [
    'warm_drinks',
    'physical_habits',
    'sensory_moment',
    'global_traveler',
    'music_taste',
  ];

  for (const theme of commonThemes) {
    requestExpression(personaId, theme, context, 'low');
  }

  log.debug({ personaId, themes: commonThemes.length }, 'Pre-warming expression cache');
}

/**
 * Request expressions for specific emotional context
 */
export function requestEmotionalExpressions(
  personaId: string,
  emotion: string,
  context: ExpressionContext
): void {
  const emotionalThemes: ThemeCategory[] = ['sensory_moment', 'vulnerability', 'nature_connection'];

  for (const theme of emotionalThemes) {
    requestExpression(personaId, theme, { ...context, emotion }, 'normal');
  }
}

/**
 * Get the best expression available (LLM → Composed → Pool)
 *
 * This is the main entry point for the personality system.
 */
export async function getBestExpression(
  personaId: string,
  userId: string,
  sessionId: string,
  theme: ThemeCategory,
  context: ExpressionContext
): Promise<{ content: string; ssml: string; source: 'llm' | 'composed' | 'pool' } | null> {
  // 1. Try LLM-generated cache
  const llmExpr = getGeneratedExpression(personaId, userId, theme, context);
  if (llmExpr) {
    return {
      content: llmExpr.content,
      ssml: llmExpr.ssml,
      source: 'llm',
    };
  }

  // 2. Request more LLM expressions for future
  requestExpression(personaId, theme, context, 'normal');

  // 3. Fall back to composed expressions (persona-specific)
  try {
    const { processSharedPersonalityTurn } = await import('./shared-personality-integration.js');
    const composed = await processSharedPersonalityTurn({
      personaId,
      sessionId,
      userId,
      turnCount: 1,
      userTranscript: '', // Not available in this context
      conversationMomentum: mapMomentum(context.momentum) || 'cruising',
      relationshipStage: context.relationshipStage || 'acquaintance',
      textEmotion: context.emotion ? { primary: context.emotion } : undefined,
    });

    if (composed?.expression) {
      return {
        content: composed.expression.content,
        ssml: composed.expression.content,
        source: 'composed',
      };
    }
  } catch {
    // Composed not available
  }

  // 4. Fall back to pool-based (try persona-specific behavior files)
  try {
    const { loadPersonaContent } = await import('../../services/persona-content-loader.js');
    // Convert theme to behavior key (snake_case)
    const behaviorKey = themeToBehaviorKey(theme);
    if (behaviorKey) {
      const content = await loadPersonaContent<string[]>(personaId, behaviorKey);

      if (content && Array.isArray(content)) {
        const randomItem = content[Math.floor(Math.random() * content.length)];
        if (typeof randomItem === 'string') {
          return {
            content: randomItem,
            ssml: randomItem,
            source: 'pool',
          };
        }
      }
    }
  } catch {
    // Pool not available
  }

  return null;
}

/**
 * Map theme to behavior filename
 */
function themeToFilename(theme: ThemeCategory): string {
  const mapping: Partial<Record<ThemeCategory, string>> = {
    warm_drinks: 'warm-drinks',
    global_traveler: 'global-traveler',
    music_taste: 'music-taste',
    family_life: 'family-life',
    physical_habits: 'physical-habits',
    nature_connection: 'nature-connection',
    vulnerability: 'vulnerability',
    quirky_interests: 'quirky-interests',
    sensory_moment: 'sensory-moment',
  };
  return mapping[theme] || theme.replace(/_/g, '-');
}

/**
 * Map theme to behavior key for loading from persona content
 * Returns undefined if no matching behavior exists
 */
function themeToBehaviorKey(
  theme: ThemeCategory
): 'vulnerability' | 'sensory_moments' | 'quirks' | undefined {
  // Only map themes that have corresponding behavior files
  const mapping: Partial<Record<ThemeCategory, 'vulnerability' | 'sensory_moments' | 'quirks'>> = {
    vulnerability: 'vulnerability',
    sensory_moment: 'sensory_moments',
    quirky_interests: 'quirks',
  };
  return mapping[theme];
}

/**
 * Map external momentum to internal PersonalityContext momentum
 */
function mapMomentum(
  momentum?: 'opening' | 'building' | 'cruising' | 'winding_down'
): 'opening' | 'cruising' | 'peaking' | 'intimate' | 'closing' | 'stalled' {
  switch (momentum) {
    case 'opening':
      return 'opening';
    case 'building':
      return 'peaking';
    case 'winding_down':
      return 'closing';
    case 'cruising':
    default:
      return 'cruising';
  }
}

/**
 * Get generation stats
 */
export function getStats(): typeof stats & { queueLength: number; cacheSize: number } {
  let totalCacheSize = 0;
  for (const cache of expressionCache.values()) {
    totalCacheSize += cache.length;
  }

  return {
    ...stats,
    queueLength: generationQueue.length,
    cacheSize: totalCacheSize,
  };
}

/**
 * Clear cache for a user
 */
export function clearCache(personaId: string, userId?: string): void {
  if (userId) {
    expressionCache.delete(getCacheKey(personaId, userId));
    log.debug({ personaId, userId }, 'Cleared user expression cache');
  } else {
    // Clear all caches for this persona
    for (const key of expressionCache.keys()) {
      if (key.startsWith(`${personaId}:`)) {
        expressionCache.delete(key);
      }
    }
    log.debug({ personaId }, 'Cleared all persona expression caches');
  }
}

/**
 * Clear Voice DNA cache
 */
export function clearVoiceDNACache(personaId?: string): void {
  if (personaId) {
    voiceDNACache.delete(personaId);
  } else {
    voiceDNACache.clear();
  }
}

// ============================================================================
// FIRESTORE PERSISTENCE (for high-engagement expressions)
// ============================================================================

interface FirestoreDB {
  collection: (path: string) => {
    doc: (id: string) => {
      collection: (subPath: string) => {
        doc: (subId: string) => {
          get: () => Promise<{ exists: boolean; data: () => unknown }>;
          set: (data: unknown, options?: { merge?: boolean }) => Promise<void>;
        };
      };
    };
  };
}

let firestoreDb: FirestoreDB | null = null;
let firestoreInitPromise: Promise<void> | null = null;

async function initFirestore(): Promise<FirestoreDB | null> {
  if (firestoreDb) return firestoreDb;

  if (!firestoreInitPromise) {
    firestoreInitPromise = (async () => {
      try {
        const { Firestore: FirestoreClass } = await import('@google-cloud/firestore');
        firestoreDb = new FirestoreClass({
          projectId: process.env.GOOGLE_CLOUD_PROJECT || process.env.GCLOUD_PROJECT,
          databaseId: process.env.FIRESTORE_DATABASE || '(default)',
        }) as unknown as FirestoreDB;
        log.debug('Firestore initialized for expression persistence');
      } catch (error) {
        log.debug({ error: String(error) }, 'Firestore not available');
        firestoreDb = null;
      }
    })();
  }

  await firestoreInitPromise;
  return firestoreDb;
}

interface PersistedExpression {
  id: string;
  personaId: string;
  theme: ThemeCategory;
  content: string;
  ssml: string;
  engagementScore: number;
  timesUsed: number;
  lastUsed: string;
  createdAt: string;
}

const MIN_ENGAGEMENT_FOR_PERSIST = 3;

/**
 * Mark an expression as high-engagement
 */
export async function markExpressionEngagement(
  personaId: string,
  userId: string,
  expressionId: string,
  positive: boolean
): Promise<void> {
  const userKey = getCacheKey(personaId, userId);
  const globalKey = getCacheKey(personaId);

  const userCache = expressionCache.get(userKey) || [];
  const globalCache = expressionCache.get(globalKey) || [];
  const allExpressions = [...userCache, ...globalCache];

  const expression = allExpressions.find((e) => e.id === expressionId);
  if (!expression) return;

  if (positive) {
    expression.usedCount++;

    if (expression.usedCount >= MIN_ENGAGEMENT_FOR_PERSIST) {
      await persistExpression(userId, expression);
    }
  }
}

async function persistExpression(userId: string, expr: GeneratedExpression): Promise<void> {
  const db = await initFirestore();
  if (!db) return;

  try {
    const docRef = db
      .collection('bogle_users')
      .doc(userId)
      .collection('learned_expressions')
      .doc(expr.id);

    const persisted: PersistedExpression = {
      id: expr.id,
      personaId: expr.personaId,
      theme: expr.theme,
      content: expr.content,
      ssml: expr.ssml,
      engagementScore: Math.min(1, expr.usedCount / 10),
      timesUsed: expr.usedCount,
      lastUsed: new Date().toISOString(),
      createdAt: expr.generatedAt.toISOString(),
    };

    await docRef.set(cleanForFirestore(persisted), { merge: true });
    log.debug(
      { userId, personaId: expr.personaId, expressionId: expr.id },
      'Persisted high-engagement expression'
    );
  } catch (error) {
    log.warn({ error: String(error), userId }, 'Failed to persist expression');
  }
}

/**
 * Flush high-engagement expressions to Firestore
 */
export async function flushExpressions(personaId: string, userId: string): Promise<void> {
  const cacheKey = getCacheKey(personaId, userId);
  const cache = expressionCache.get(cacheKey) || [];
  const highEngagement = cache.filter((e) => e.usedCount >= MIN_ENGAGEMENT_FOR_PERSIST);

  for (const expr of highEngagement) {
    await persistExpression(userId, expr);
  }

  if (highEngagement.length > 0) {
    log.debug(
      { personaId, userId, count: highEngagement.length },
      'Flushed high-engagement expressions'
    );
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export const sharedLLMExpressionGenerator = {
  request: requestExpression,
  get: getGeneratedExpression,
  getBest: getBestExpression,
  prewarm: prewarmCache,
  requestEmotional: requestEmotionalExpressions,
  clearCache,
  clearVoiceDNACache,
  getStats,
  markEngagement: markExpressionEngagement,
  flush: flushExpressions,
};

export default sharedLLMExpressionGenerator;
