// This file is @generated by prost-build.
/// Request for speech synthesis
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynthesisRequest {
    /// Text to synthesize (plain text or SSML)
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// Whether the text is SSML
    #[prost(bool, tag = "2")]
    pub is_ssml: bool,
    /// Voice ID to use
    #[prost(string, tag = "3")]
    pub voice_id: ::prost::alloc::string::String,
    /// Audio output configuration
    #[prost(message, optional, tag = "4")]
    pub audio_config: ::core::option::Option<AudioConfig>,
    /// Prosody configuration
    #[prost(message, optional, tag = "5")]
    pub prosody_config: ::core::option::Option<ProsodyConfig>,
    /// Superhuman context for enhanced prosody
    #[prost(message, optional, tag = "6")]
    pub superhuman_context: ::core::option::Option<SuperhumanContext>,
    /// Request ID for tracing
    #[prost(string, tag = "7")]
    pub request_id: ::prost::alloc::string::String,
}
/// Audio output configuration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioConfig {
    /// Sample rate in Hz (default: 24000)
    #[prost(uint32, tag = "1")]
    pub sample_rate: u32,
    /// Bits per sample (default: 16)
    #[prost(uint32, tag = "2")]
    pub bits_per_sample: u32,
    /// Number of channels (default: 1)
    #[prost(uint32, tag = "3")]
    pub channels: u32,
    /// Output format
    #[prost(enumeration = "AudioFormat", tag = "4")]
    pub format: i32,
}
/// Prosody configuration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProsodyConfig {
    /// Speaking rate multiplier (1.0 = normal)
    #[prost(float, tag = "1")]
    pub rate: f32,
    /// Pitch adjustment in semitones
    #[prost(float, tag = "2")]
    pub pitch: f32,
    /// Volume (0.0 - 1.0)
    #[prost(float, tag = "3")]
    pub volume: f32,
}
/// Superhuman context for enhanced prosody
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SuperhumanContext {
    /// User's local hour (0-23) for circadian adjustment
    #[prost(uint32, optional, tag = "1")]
    pub user_local_hour: ::core::option::Option<u32>,
    /// Relationship stage (0.0-1.0)
    #[prost(float, optional, tag = "2")]
    pub relationship_stage: ::core::option::Option<f32>,
    /// User's current energy level (0.0-1.0)
    #[prost(float, optional, tag = "3")]
    pub user_energy: ::core::option::Option<f32>,
    /// User's detected emotion
    #[prost(string, optional, tag = "4")]
    pub user_emotion: ::core::option::Option<::prost::alloc::string::String>,
    /// Emotion intensity (0.0-1.0)
    #[prost(float, optional, tag = "5")]
    pub emotion_intensity: ::core::option::Option<f32>,
    /// Topic sensitivity (0.0-1.0)
    #[prost(float, optional, tag = "6")]
    pub topic_sensitivity: ::core::option::Option<f32>,
    /// Emotional trajectory
    #[prost(string, optional, tag = "7")]
    pub emotional_trajectory: ::core::option::Option<::prost::alloc::string::String>,
    /// Remembered entities
    #[prost(message, repeated, tag = "8")]
    pub remembered_entities: ::prost::alloc::vec::Vec<MemoryEntity>,
    /// Turn number in conversation
    #[prost(uint32, optional, tag = "9")]
    pub turn_number: ::core::option::Option<u32>,
    /// User's speaking rate
    #[prost(float, optional, tag = "10")]
    pub user_speaking_rate: ::core::option::Option<f32>,
}
/// Memory entity for prosody emphasis
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryEntity {
    /// Entity name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Entity type (person, place, pet, etc.)
    #[prost(string, tag = "2")]
    pub entity_type: ::prost::alloc::string::String,
    /// Familiarity score (0.0-1.0)
    #[prost(float, tag = "3")]
    pub familiarity: f32,
    /// Emotional valence (-1.0 to 1.0)
    #[prost(float, optional, tag = "4")]
    pub emotional_valence: ::core::option::Option<f32>,
}
/// Synthesis response (non-streaming)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynthesisResponse {
    /// Synthesized audio data
    #[prost(bytes = "vec", tag = "1")]
    pub audio: ::prost::alloc::vec::Vec<u8>,
    /// Audio format used
    #[prost(message, optional, tag = "2")]
    pub audio_config: ::core::option::Option<AudioConfig>,
    /// Duration in milliseconds
    #[prost(uint64, tag = "3")]
    pub duration_ms: u64,
    /// Request ID for tracing
    #[prost(string, tag = "4")]
    pub request_id: ::prost::alloc::string::String,
    /// First byte latency in milliseconds
    #[prost(uint64, tag = "5")]
    pub latency_ms: u64,
    /// Transforms applied
    #[prost(string, repeated, tag = "6")]
    pub transforms_applied: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Streaming audio chunk
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioChunk {
    /// Audio data
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Chunk index
    #[prost(uint32, tag = "2")]
    pub index: u32,
    /// Is this the final chunk?
    #[prost(bool, tag = "3")]
    pub is_final: bool,
    /// Timestamp in milliseconds from start
    #[prost(uint64, tag = "4")]
    pub timestamp_ms: u64,
    /// Duration of this chunk in milliseconds
    #[prost(uint64, tag = "5")]
    pub duration_ms: u64,
}
/// Request to list available voices
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListVoicesRequest {
    /// Filter by language (optional)
    #[prost(string, optional, tag = "1")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
}
/// Response with available voices
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListVoicesResponse {
    #[prost(message, repeated, tag = "1")]
    pub voices: ::prost::alloc::vec::Vec<VoiceInfo>,
}
/// Voice information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoiceInfo {
    /// Voice ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Display name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Language code
    #[prost(string, tag = "3")]
    pub language: ::prost::alloc::string::String,
    /// Gender
    #[prost(enumeration = "VoiceGender", tag = "4")]
    pub gender: i32,
    /// Voice style/personality description
    #[prost(string, tag = "5")]
    pub style: ::prost::alloc::string::String,
    /// Whether voice supports cloning
    #[prost(bool, tag = "6")]
    pub supports_cloning: bool,
}
/// Health check request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {}
/// Health check response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    /// Service is healthy
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// Service version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Backend status
    #[prost(string, tag = "3")]
    pub backend_status: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AudioFormat {
    Unspecified = 0,
    Pcm = 1,
    Wav = 2,
    Mp3 = 3,
    Opus = 4,
}
impl AudioFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AudioFormat::Unspecified => "AUDIO_FORMAT_UNSPECIFIED",
            AudioFormat::Pcm => "AUDIO_FORMAT_PCM",
            AudioFormat::Wav => "AUDIO_FORMAT_WAV",
            AudioFormat::Mp3 => "AUDIO_FORMAT_MP3",
            AudioFormat::Opus => "AUDIO_FORMAT_OPUS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIO_FORMAT_UNSPECIFIED" => Some(Self::Unspecified),
            "AUDIO_FORMAT_PCM" => Some(Self::Pcm),
            "AUDIO_FORMAT_WAV" => Some(Self::Wav),
            "AUDIO_FORMAT_MP3" => Some(Self::Mp3),
            "AUDIO_FORMAT_OPUS" => Some(Self::Opus),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VoiceGender {
    Unspecified = 0,
    Male = 1,
    Female = 2,
    Neutral = 3,
}
impl VoiceGender {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            VoiceGender::Unspecified => "VOICE_GENDER_UNSPECIFIED",
            VoiceGender::Male => "VOICE_GENDER_MALE",
            VoiceGender::Female => "VOICE_GENDER_FEMALE",
            VoiceGender::Neutral => "VOICE_GENDER_NEUTRAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOICE_GENDER_UNSPECIFIED" => Some(Self::Unspecified),
            "VOICE_GENDER_MALE" => Some(Self::Male),
            "VOICE_GENDER_FEMALE" => Some(Self::Female),
            "VOICE_GENDER_NEUTRAL" => Some(Self::Neutral),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod synthesis_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// TTS Synthesis Service
    #[derive(Debug, Clone)]
    pub struct SynthesisServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SynthesisServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SynthesisServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SynthesisServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            SynthesisServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Synthesize speech from text (unary)
        pub async fn synthesize(
            &mut self,
            request: impl tonic::IntoRequest<super::SynthesisRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SynthesisResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferni.tts.SynthesisService/Synthesize",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferni.tts.SynthesisService", "Synthesize"));
            self.inner.unary(req, path, codec).await
        }
        /// Synthesize speech with streaming response
        pub async fn synthesize_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::SynthesisRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AudioChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferni.tts.SynthesisService/SynthesizeStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ferni.tts.SynthesisService", "SynthesizeStream"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// List available voices
        pub async fn list_voices(
            &mut self,
            request: impl tonic::IntoRequest<super::ListVoicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListVoicesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferni.tts.SynthesisService/ListVoices",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferni.tts.SynthesisService", "ListVoices"));
            self.inner.unary(req, path, codec).await
        }
        /// Health check
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ferni.tts.SynthesisService/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ferni.tts.SynthesisService", "HealthCheck"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod synthesis_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SynthesisServiceServer.
    #[async_trait]
    pub trait SynthesisService: Send + Sync + 'static {
        /// Synthesize speech from text (unary)
        async fn synthesize(
            &self,
            request: tonic::Request<super::SynthesisRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SynthesisResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the SynthesizeStream method.
        type SynthesizeStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AudioChunk, tonic::Status>,
            >
            + Send
            + 'static;
        /// Synthesize speech with streaming response
        async fn synthesize_stream(
            &self,
            request: tonic::Request<super::SynthesisRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SynthesizeStreamStream>,
            tonic::Status,
        >;
        /// List available voices
        async fn list_voices(
            &self,
            request: tonic::Request<super::ListVoicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListVoicesResponse>,
            tonic::Status,
        >;
        /// Health check
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
    }
    /// TTS Synthesis Service
    #[derive(Debug)]
    pub struct SynthesisServiceServer<T: SynthesisService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: SynthesisService> SynthesisServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SynthesisServiceServer<T>
    where
        T: SynthesisService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/ferni.tts.SynthesisService/Synthesize" => {
                    #[allow(non_camel_case_types)]
                    struct SynthesizeSvc<T: SynthesisService>(pub Arc<T>);
                    impl<
                        T: SynthesisService,
                    > tonic::server::UnaryService<super::SynthesisRequest>
                    for SynthesizeSvc<T> {
                        type Response = super::SynthesisResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SynthesisRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SynthesisService>::synthesize(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SynthesizeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ferni.tts.SynthesisService/SynthesizeStream" => {
                    #[allow(non_camel_case_types)]
                    struct SynthesizeStreamSvc<T: SynthesisService>(pub Arc<T>);
                    impl<
                        T: SynthesisService,
                    > tonic::server::ServerStreamingService<super::SynthesisRequest>
                    for SynthesizeStreamSvc<T> {
                        type Response = super::AudioChunk;
                        type ResponseStream = T::SynthesizeStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SynthesisRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SynthesisService>::synthesize_stream(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SynthesizeStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ferni.tts.SynthesisService/ListVoices" => {
                    #[allow(non_camel_case_types)]
                    struct ListVoicesSvc<T: SynthesisService>(pub Arc<T>);
                    impl<
                        T: SynthesisService,
                    > tonic::server::UnaryService<super::ListVoicesRequest>
                    for ListVoicesSvc<T> {
                        type Response = super::ListVoicesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListVoicesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SynthesisService>::list_voices(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ListVoicesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ferni.tts.SynthesisService/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: SynthesisService>(pub Arc<T>);
                    impl<
                        T: SynthesisService,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SynthesisService>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = HealthCheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: SynthesisService> Clone for SynthesisServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: SynthesisService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: SynthesisService> tonic::server::NamedService for SynthesisServiceServer<T> {
        const NAME: &'static str = "ferni.tts.SynthesisService";
    }
}
