#!/usr/bin/env npx tsx
/**
 * Sync GCP Secrets to Local Environment
 *
 * Pulls secrets from GCP Secret Manager and creates/updates a .env file
 * for local development and testing.
 *
 * Usage:
 *   npx tsx scripts/sync-secrets-to-env.ts
 *   npx tsx scripts/sync-secrets-to-env.ts --output .env.local
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

// Map of GCP Secret names to environment variable names
const SECRET_MAPPING: Record<string, string> = {
  // Communication
  'sendgrid-api-key': 'SENDGRID_API_KEY',
  'sendgrid-from-email': 'SENDGRID_FROM_EMAIL',
  'twilio-account-sid': 'TWILIO_ACCOUNT_SID',
  'twilio-auth-token': 'TWILIO_AUTH_TOKEN',
  'twilio-phone-number': 'TWILIO_PHONE_NUMBER',

  // Google APIs
  'google-api-key': 'GOOGLE_API_KEY',

  // LiveKit
  'livekit-url': 'LIVEKIT_URL',
  'livekit-api-key': 'LIVEKIT_API_KEY',
  'livekit-api-secret': 'LIVEKIT_API_SECRET',

  // TTS
  'cartesia-api-key': 'CARTESIA_API_KEY',

  // Banking
  'plaid-client-id': 'PLAID_CLIENT_ID',
  'plaid-secret': 'PLAID_SECRET',
  'plaid-env': 'PLAID_ENV',

  // Music
  'spotify-client-id': 'SPOTIFY_CLIENT_ID',
  'spotify-client-secret': 'SPOTIFY_CLIENT_SECRET',
  'spotify-refresh-token': 'SPOTIFY_REFRESH_TOKEN',

  // Research APIs
  'finnhub-api-key': 'FINNHUB_API_KEY',
  'alpha-vantage-key': 'ALPHA_VANTAGE_API_KEY',
  'fred-api-key': 'FRED_API_KEY',

  // Travel
  'amadeus-api-key': 'AMADEUS_API_KEY',
  'amadeus-api-secret': 'AMADEUS_API_SECRET',

  // Tracking
  'aftership-api-key': 'AFTERSHIP_API_KEY',

  // Admin
  'admin-api-key': 'ADMIN_API_KEY',
  'log-hash-secret': 'LOG_HASH_SECRET',
  'redis-url': 'REDIS_URL',

  // Observability
  'sentry-dsn': 'SENTRY_DSN',
};

const PROJECT_ID = 'johnb-2025';

function getSecret(secretName: string): string | null {
  try {
    const value = execSync(
      `gcloud secrets versions access latest --secret="${secretName}" --project="${PROJECT_ID}"`,
      { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    ).trim();
    return value;
  } catch (error) {
    return null;
  }
}

function main() {
  const args = process.argv.slice(2);
  const outputIndex = args.indexOf('--output');
  const outputFile = outputIndex >= 0 ? args[outputIndex + 1] : '.env';
  const outputPath = resolve(process.cwd(), outputFile);

  console.log('\n🔐 Syncing secrets from GCP Secret Manager...\n');
  console.log(`   Project: ${PROJECT_ID}`);
  console.log(`   Output:  ${outputFile}\n`);

  // Read existing .env if present
  let existingEnv: Record<string, string> = {};
  if (existsSync(outputPath)) {
    const content = readFileSync(outputPath, 'utf-8');
    for (const line of content.split('\n')) {
      const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
      if (match) {
        existingEnv[match[1]] = match[2];
      }
    }
    console.log(`   Found existing ${outputFile} with ${Object.keys(existingEnv).length} vars\n`);
  }

  const envVars: Record<string, string> = { ...existingEnv };
  let fetched = 0;
  let skipped = 0;
  let failed = 0;

  for (const [secretName, envVar] of Object.entries(SECRET_MAPPING)) {
    process.stdout.write(`   ${envVar.padEnd(30)}`);

    const value = getSecret(secretName);

    if (value) {
      envVars[envVar] = value;
      console.log('✅ fetched');
      fetched++;
    } else {
      console.log('⚠️  not found');
      failed++;
    }
  }

  // Add some defaults that aren't in secrets
  const defaults: Record<string, string> = {
    NODE_ENV: 'development',
    GCP_PROJECT_ID: PROJECT_ID,
    PERSONA_ID: 'ferni',
    SENDGRID_FROM_NAME: 'Ferni',
    PLAID_LINK_BASE_URL: 'https://app.ferni.ai/plaid-link',
  };

  for (const [key, value] of Object.entries(defaults)) {
    if (!envVars[key]) {
      envVars[key] = value;
    }
  }

  // Write the .env file
  const lines: string[] = [
    '# Auto-generated by scripts/sync-secrets-to-env.ts',
    `# Last updated: ${new Date().toISOString()}`,
    '#',
    '# DO NOT COMMIT THIS FILE',
    '',
    '# ═══════════════════════════════════════════════════════════════════',
    '# COMMUNICATION',
    '# ═══════════════════════════════════════════════════════════════════',
  ];

  const categories: Record<string, string[]> = {
    COMMUNICATION: ['SENDGRID_', 'TWILIO_'],
    GOOGLE: ['GOOGLE_'],
    LIVEKIT: ['LIVEKIT_'],
    TTS: ['CARTESIA_'],
    BANKING: ['PLAID_'],
    MUSIC: ['SPOTIFY_'],
    RESEARCH: ['FINNHUB_', 'ALPHA_VANTAGE_', 'FRED_'],
    TRAVEL: ['AMADEUS_'],
    TRACKING: ['AFTERSHIP_'],
    ADMIN: ['ADMIN_', 'LOG_HASH_'],
    OBSERVABILITY: ['SENTRY_'],
    OTHER: [],
  };

  const written = new Set<string>();

  for (const [category, prefixes] of Object.entries(categories)) {
    const categoryVars = Object.entries(envVars).filter(([key]) => {
      if (written.has(key)) return false;
      if (prefixes.length === 0) return !written.has(key);
      return prefixes.some((p) => key.startsWith(p));
    });

    if (categoryVars.length > 0) {
      lines.push('');
      lines.push(`# ═══════════════════════════════════════════════════════════════════`);
      lines.push(`# ${category}`);
      lines.push(`# ═══════════════════════════════════════════════════════════════════`);

      for (const [key, value] of categoryVars) {
        // Escape special characters
        const escapedValue =
          value.includes(' ') || value.includes('"') || value.includes("'")
            ? `"${value.replace(/"/g, '\\"')}"`
            : value;
        lines.push(`${key}=${escapedValue}`);
        written.add(key);
      }
    }
  }

  // Add any remaining vars
  const remaining = Object.entries(envVars).filter(([key]) => !written.has(key));
  if (remaining.length > 0) {
    lines.push('');
    lines.push('# ═══════════════════════════════════════════════════════════════════');
    lines.push('# OTHER');
    lines.push('# ═══════════════════════════════════════════════════════════════════');
    for (const [key, value] of remaining) {
      const escapedValue =
        value.includes(' ') || value.includes('"') ? `"${value.replace(/"/g, '\\"')}"` : value;
      lines.push(`${key}=${escapedValue}`);
    }
  }

  lines.push('');
  lines.push('# ═══════════════════════════════════════════════════════════════════');
  lines.push('# TESTING (Set these for validation tests)');
  lines.push('# ═══════════════════════════════════════════════════════════════════');
  lines.push('# TEST_EMAIL=your-email@example.com');
  lines.push('# TEST_PHONE_NUMBER=+1234567890');
  lines.push('');

  writeFileSync(outputPath, lines.join('\n'));

  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  console.log(`   ✅ Fetched: ${fetched}`);
  console.log(`   ⚠️  Not found: ${failed}`);
  console.log(`   📝 Written to: ${outputFile}`);
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);

  console.log('Next steps:');
  console.log('  1. Add TEST_EMAIL and TEST_PHONE_NUMBER to the .env file');
  console.log('  2. Run: source .env && npx tsx scripts/validate-integrations.ts --send-test');
  console.log('');
}

main();



















