/**
 * Proactive Intelligence Types
 *
 * Type definitions for proactive alerts and notifications.
 * This is the "Better Than Human" core - we reach out BEFORE you ask.
 */
/**
 * Categories of proactive alerts
 */
export type AlertCategory = 'weather' | 'traffic' | 'environmental' | 'finance' | 'sports' | 'health' | 'relationship' | 'calendar';
/**
 * Alert urgency levels
 */
export type AlertUrgency = 'low' | 'medium' | 'high' | 'critical';
/**
 * A proactive alert generated by the intelligence engine
 */
export interface ProactiveAlert {
    /** Unique identifier */
    id: string;
    /** Alert category */
    category: AlertCategory;
    /** Human-readable title */
    title: string;
    /** Full message content */
    message: string;
    /** Urgency level */
    urgency: AlertUrgency;
    /** When the alert was generated */
    generatedAt: Date;
    /** When the alert becomes relevant (e.g., 30 min before rain) */
    relevantAt: Date;
    /** When the alert expires (no longer relevant) */
    expiresAt: Date;
    /** Related data for follow-up actions */
    metadata: Record<string, unknown>;
    /** Suggested actions the user can take */
    suggestedActions?: AlertAction[];
    /** Has the user seen/acknowledged this? */
    acknowledged: boolean;
    /** Did the user find this helpful? (for learning) */
    wasHelpful?: boolean;
}
/**
 * An action the user can take in response to an alert
 */
export interface AlertAction {
    /** Action identifier */
    id: string;
    /** Display label */
    label: string;
    /** Action type */
    type: 'dismiss' | 'snooze' | 'act' | 'learn_more';
    /** Additional parameters */
    params?: Record<string, unknown>;
}
/**
 * Condition that triggers an alert
 */
export interface AlertTrigger {
    /** Trigger type */
    type: TriggerType;
    /** Parameters for the trigger */
    params: TriggerParams;
    /** How often to check this trigger */
    checkInterval: number;
    /** Is this trigger enabled? */
    enabled: boolean;
}
export type TriggerType = 'weather_change' | 'weather_calendar_conflict' | 'traffic_spike' | 'commute_alert' | 'air_quality_threshold' | 'pollen_threshold' | 'uv_threshold' | 'stock_movement' | 'game_day' | 'birthday_reminder' | 'calendar_reminder';
export type TriggerParams = WeatherTriggerParams | TrafficTriggerParams | EnvironmentalTriggerParams | FinanceTriggerParams | SportsTriggerParams | RelationshipTriggerParams;
export interface WeatherTriggerParams {
    type: 'weather_change' | 'weather_calendar_conflict';
    /** Threshold for significant temperature change (°F) */
    tempChangeThreshold?: number;
    /** Alert before rain starts (minutes) */
    rainLeadTime?: number;
    /** Alert for severe weather? */
    severeWeatherAlert?: boolean;
}
export interface TrafficTriggerParams {
    type: 'traffic_spike' | 'commute_alert';
    /** Threshold for traffic delay (minutes) */
    delayThreshold?: number;
    /** Alert before usual departure time (minutes) */
    alertLeadTime?: number;
}
export interface EnvironmentalTriggerParams {
    type: 'air_quality_threshold' | 'pollen_threshold' | 'uv_threshold';
    /** AQI threshold for alert */
    aqiThreshold?: number;
    /** Pollen level threshold */
    pollenLevel?: 'moderate' | 'high' | 'very_high';
    /** UV index threshold */
    uvThreshold?: number;
    /** User has allergies? */
    userHasAllergies?: boolean;
    /** User has respiratory conditions? */
    userHasRespiratoryConditions?: boolean;
}
export interface FinanceTriggerParams {
    type: 'stock_movement';
    /** Percentage change to trigger alert */
    percentageThreshold: number;
    /** Direction of movement */
    direction: 'up' | 'down' | 'both';
}
export interface SportsTriggerParams {
    type: 'game_day';
    /** Alert before game (hours) */
    alertBeforeGame: number;
    /** Alert for score updates during game? */
    inGameUpdates: boolean;
}
export interface RelationshipTriggerParams {
    type: 'birthday_reminder';
    /** Days before to remind */
    daysBeforeReminder: number;
    /** Include gift suggestions? */
    includeGiftSuggestions: boolean;
}
/**
 * Context used when generating alerts
 */
export interface AlertGenerationContext {
    userId: string;
    location?: {
        city: string;
        latitude: number;
        longitude: number;
    };
    calendarEvents?: CalendarEvent[];
    preferences?: AlertPreferences;
    healthContext?: HealthContext;
}
export interface CalendarEvent {
    id: string;
    title: string;
    startTime: Date;
    endTime: Date;
    location?: string;
    isOutdoor?: boolean;
}
export interface AlertPreferences {
    /** Categories user wants alerts for */
    enabledCategories: AlertCategory[];
    /** Quiet hours (no alerts) */
    quietHoursStart?: string;
    quietHoursEnd?: string;
    /** Max alerts per day */
    maxAlertsPerDay: number;
    /** Minimum urgency to alert */
    minimumUrgency: AlertUrgency;
}
export interface HealthContext {
    hasAllergies: boolean;
    allergyTypes?: string[];
    hasAsthma: boolean;
    skinType?: string;
}
export declare const DEFAULT_ALERT_PREFERENCES: AlertPreferences;
export declare const DEFAULT_CHECK_INTERVALS: Record<AlertCategory, number>;
//# sourceMappingURL=types.d.ts.map