/**
 * Persona Bundle Types - Main Entry Point
 *
 * Re-exports all types from modular files for backward compatibility.
 */
export type { PersonaBundleManifest, BundleIdentity, BundleLLMContext, BundleVoice, BundleSpeechCharacteristics, BundleHumanization, BundlePersonality, BundleRole, BundleTeam, BundleHandoffTransition, BundleCognitive, BundleToolDomain, BundleTools, BundleCapabilities, BundleContent, BundleMetadata, } from './core.js';
export type { BundleMarketplaceConfig } from './marketplace.js';
export type { BundleEmotionalConfig, EmotionalTone, ProgressiveLoadingConfig, ExtendedBundleManifest, BundleHooks, } from './emotional.js';
export type { BundleStory, StoryIndex, BundleStoryRef, BundleKnowledge, KnowledgeIndex, BundleKnowledgeRef, BundlePetPeeve, BundleGreetings, BundleBackchannels, BundleSilenceFillers, BundleCelebrations, BundleStorytelling, BundleCatchphrases, BundleThinkingSounds, BundleGoodbyes, BundleBehaviors, } from './content.js';
export type { BundleCognitiveProfile, BundleMusicPreferences } from './cognitive.js';
export type { BundleGoodbyesV2, BundleEntrancesV2, BundleGreetingsV2, BundleVulnerability, BundleCulturalMoments, BundleMicroMoments, BundleOffDuty, BundleSensoryMoments, BundleConflictHandling, UserPushbackResponse, PersonaDisagreementConfig, RepairConfig, BoundaryConfig, MisunderstandingConfig, BundleRelationshipTransitions, BundleVoiceExpressions, VoiceExpression, BundleSituationalResponses, SituationalResponse, DifficultMomentResponse, BundleRelationshipStages, RelationshipStage, ProgressionTrigger, RegressionTrigger, BundleMemoryPatterns, MemoryReferencePattern, NameUsageConfig, DetailCallback, BundlePersonaModes, PersonaMode, ModeTransition, BundleContextualNuances, TimeOfDayConfig, DayOfWeekConfig, SeasonalConfig, SpecialDateConfig, WeatherConfig, BundleMicroExpressions, PacingVariation, SilencePattern, BundleStoryGraph, StoryArc, StoryReference, ContextTrigger, StoryTimingRules, BundlePromptAssembly, ConditionalModule, DynamicInjection, InstructionPriority, TokenBudget, BundleQuirks, BundleEmotionalIntelligence, BundleEmotionDetection, BundlePhysicalPresence, BundleLateNightPresence, BundleSuperhumanInsights, BundleTrustPhrases, BundleINoticePower, BundleThinkingOfYou, BundleSelfDoubt, BundleSecretModes, BundleSecretFears, BundleAnticipation, BundleMortalityAwareness, BundleInnerWorld, BundleSensoryWorld, ExtendedBundleBehaviors, ExtendedBundleContent, } from './extensions.js';
export { isGoodbyesV2, isEntrancesV2, isGreetingsV2 } from './extensions.js';
export type { LoadedPersonaBundle, BundleLoadOptions, DiscoveredBundle, BundleDiscoveryResult, ExtendedLoadedBundle, } from './loaded.js';
export type { BundleCommand, BundleCommandArgument, BundleCommandIndex, BundleCommandRef, BundleCommandFrontmatter, CommandExecutionContext, CommandExecutionResult, BundleAgentHooks, BundleHook, HookEventType, HookExecutionContext, HookExecutionResult, BundleLocalTool, BundleLocalToolsIndex, BundleLocalToolRef, BundleTheme, BundleSounds, BundleAssets, BundleMCPConfig, BundleMCPServer, } from './commands.js';
//# sourceMappingURL=index.d.ts.map