#!/usr/bin/env npx tsx
/**
 * Bundle Agent Script
 * 
 * Creates a single-file bundle of the voice agent for instant child process startup.
 * 
 * WHY BUNDLE?
 * -----------
 * Node.js module loading is SLOW - each import() resolves dependencies recursively.
 * Our agent imports 200+ modules → 30-120 seconds on cold start!
 * 
 * By bundling into a single file:
 * - All imports resolved at BUILD time, not runtime
 * - Child process loads ONE file instead of 200+
 * - Startup: 30-120s → 1-3s
 * 
 * USAGE:
 *   npx tsx scripts/bundle-agent.ts
 *   # or
 *   npm run build:agent-bundle
 * 
 * OUTPUT:
 *   dist/agents/voice-agent-bundle.js  (single file, ~2-5MB)
 */

import * as esbuild from 'esbuild';
import * as path from 'path';
import * as fs from 'fs';

const ROOT = path.resolve(import.meta.dirname, '..');
const ENTRY = path.join(ROOT, 'src/agents/voice-agent-child.ts');
const OUTPUT = path.join(ROOT, 'dist/agents/voice-agent-bundle.js');

// Packages that MUST be external (native modules, dynamic requires)
const EXTERNAL_PACKAGES = [
  // Native modules - can't be bundled
  '@livekit/rtc-node',
  'better-sqlite3',
  'bufferutil',
  'utf-8-validate',
  
  // LiveKit packages - have native deps
  '@livekit/agents',
  '@livekit/agents-plugin-google',
  '@livekit/agents-plugin-silero', 
  '@livekit/agents-plugin-cartesia',
  '@livekit/rtc-node',
  
  // Google packages - complex native deps
  '@google-cloud/firestore',
  '@google-cloud/storage',
  '@google/genai',
  '@google/generative-ai',
  'firebase-admin',
  
  // Other native
  'sharp',
  'canvas',
  
  // Node built-ins
  'fs', 'path', 'url', 'http', 'https', 'crypto', 'stream', 'util', 'events',
  'child_process', 'os', 'net', 'tls', 'zlib', 'buffer', 'querystring',
  'assert', 'string_decoder', 'punycode', 'dns', 'dgram', 'cluster',
  'readline', 'repl', 'vm', 'v8', 'perf_hooks', 'async_hooks', 'worker_threads',
  'inspector', 'trace_events', 'constants', 'process', 'module', 'timers',
  'fs/promises', 'node:fs', 'node:path', 'node:url', 'node:http', 'node:https',
  'node:crypto', 'node:stream', 'node:util', 'node:events', 'node:child_process',
  'node:os', 'node:net', 'node:tls', 'node:zlib', 'node:buffer', 'node:querystring',
];

async function bundle() {
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║  BUNDLING VOICE AGENT                                        ║');
  console.log('╚══════════════════════════════════════════════════════════════╝');
  console.log('');
  console.log(`Entry: ${ENTRY}`);
  console.log(`Output: ${OUTPUT}`);
  console.log('');

  const startTime = Date.now();

  try {
    // Ensure output directory exists
    const outDir = path.dirname(OUTPUT);
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    const result = await esbuild.build({
      entryPoints: [ENTRY],
      bundle: true,
      outfile: OUTPUT,
      platform: 'node',
      target: 'node20',
      format: 'esm',
      
      // Keep external packages that can't be bundled
      external: EXTERNAL_PACKAGES,
      
      // Source maps for debugging
      sourcemap: true,
      
      // Don't minify - easier to debug
      minify: false,
      
      // Tree-shake unused code
      treeShaking: true,
      
      // Handle JSON imports
      loader: {
        '.json': 'json',
      },
      
      // Define process.env for dead code elimination
      define: {
        'process.env.NODE_ENV': '"production"',
      },
      
      // Banner for debugging - includes EARLY logging before any imports
      banner: {
        js: `
/**
 * BUNDLED VOICE AGENT
 * 
 * This file is auto-generated by scripts/bundle-agent.ts
 * DO NOT EDIT DIRECTLY - changes will be overwritten!
 * 
 * Generated: ${new Date().toISOString()}
 * Source: ${ENTRY}
 * 
 * All internal modules are bundled inline.
 * External packages (LiveKit, Google, etc.) are imported at runtime.
 */

// EARLY LOGGING - runs BEFORE any imports to verify file is being loaded
try {
  process.stderr.write('[BUNDLE] voice-agent-bundle.js loading at ' + new Date().toISOString() + '\\n');
  process.stderr.write('[BUNDLE] pid=' + process.pid + ', argv=' + JSON.stringify(process.argv) + '\\n');
  process.stderr.write('[BUNDLE] cwd=' + process.cwd() + '\\n');
} catch (e) {
  // Ignore logging errors
}
`.trim(),
      },
      
      // Log what's happening
      logLevel: 'info',
      
      // Analyze bundle size
      metafile: true,
    });

    const duration = Date.now() - startTime;
    
    // Get bundle size
    const stats = fs.statSync(OUTPUT);
    const sizeMB = (stats.size / 1024 / 1024).toFixed(2);
    
    console.log('');
    console.log('✅ Bundle created successfully!');
    console.log(`   Size: ${sizeMB} MB`);
    console.log(`   Time: ${duration}ms`);
    console.log(`   Output: ${OUTPUT}`);
    
    // Analyze what was bundled
    if (result.metafile) {
      const inputs = Object.keys(result.metafile.inputs);
      console.log(`   Modules bundled: ${inputs.length}`);
      
      // Show top 10 largest modules
      const sortedInputs = inputs
        .map(name => ({ name, size: result.metafile!.inputs[name].bytes }))
        .sort((a, b) => b.size - a.size)
        .slice(0, 10);
      
      console.log('');
      console.log('Top 10 largest bundled modules:');
      sortedInputs.forEach((m, i) => {
        const kb = (m.size / 1024).toFixed(1);
        console.log(`   ${i + 1}. ${m.name} (${kb} KB)`);
      });
    }
    
    console.log('');
    console.log('Next steps:');
    console.log('  1. Update voice-worker.ts to use voice-agent-bundle.js');
    console.log('  2. Deploy and test');
    
  } catch (error) {
    console.error('❌ Bundle failed:', error);
    process.exit(1);
  }
}

bundle();

