#!/usr/bin/env npx tsx
/**
 * Interactive Smart Home Setup Script
 *
 * Sets up direct integrations with:
 * - Ecobee (thermostat)
 * - Philips Hue (lights)
 * - LIFX (lights)
 *
 * Run: pnpm smart-home:setup
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const ENV_FILE = path.join(process.cwd(), '.env.local');

// =============================================================================
// UTILITIES
// =============================================================================

function createReadline(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

async function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

async function promptYesNo(rl: readline.Interface, question: string): Promise<boolean> {
  const answer = await prompt(rl, `${question} (y/n): `);
  return answer.toLowerCase().startsWith('y');
}

function loadEnvFile(): Record<string, string> {
  const env: Record<string, string> = {};
  if (fs.existsSync(ENV_FILE)) {
    const content = fs.readFileSync(ENV_FILE, 'utf-8');
    for (const line of content.split('\n')) {
      const match = line.match(/^([^#=]+)=(.*)$/);
      if (match) {
        env[match[1].trim()] = match[2].trim();
      }
    }
  }
  return env;
}

function saveEnvFile(env: Record<string, string>): void {
  const lines: string[] = [
    '# Smart Home Integration Configuration',
    '# Generated by pnpm smart-home:setup',
    '',
  ];

  // Group by category
  const categories = {
    'Test User': ['TEST_USER_ID'],
    'Ecobee': ['ECOBEE_API_KEY'],
    'Philips Hue': ['HUE_BRIDGE_IP', 'HUE_USERNAME'],
    'LIFX': ['LIFX_TOKEN'],
    'Home Assistant (Optional)': ['HOME_ASSISTANT_URL', 'HOME_ASSISTANT_TOKEN'],
    'Test Options': ['DRY_RUN', 'VERBOSE', 'SKIP_RESTORE'],
  };

  for (const [category, keys] of Object.entries(categories)) {
    const hasAny = keys.some((k) => env[k]);
    if (hasAny) {
      lines.push(`# ${category}`);
      for (const key of keys) {
        if (env[key]) {
          lines.push(`${key}=${env[key]}`);
        }
      }
      lines.push('');
    }
  }

  // Add any other keys not in categories
  const allCategoryKeys = Object.values(categories).flat();
  for (const [key, value] of Object.entries(env)) {
    if (!allCategoryKeys.includes(key) && value) {
      lines.push(`${key}=${value}`);
    }
  }

  fs.writeFileSync(ENV_FILE, lines.join('\n'));
  console.log(`\n✅ Saved to ${ENV_FILE}\n`);
}

// =============================================================================
// ECOBEE SETUP
// =============================================================================

async function setupEcobee(rl: readline.Interface, env: Record<string, string>): Promise<void> {
  console.log('\n' + '═'.repeat(60));
  console.log('🌡️  ECOBEE THERMOSTAT SETUP');
  console.log('═'.repeat(60));

  if (env.ECOBEE_API_KEY) {
    console.log(`\n✅ Already configured: ${env.ECOBEE_API_KEY.slice(0, 8)}...`);
    const reconfigure = await promptYesNo(rl, 'Reconfigure?');
    if (!reconfigure) return;
  }

  console.log('\n📋 Steps to get your Ecobee API Key:\n');
  console.log('   1. Go to: https://www.ecobee.com/developers/');
  console.log('   2. Sign in with your Ecobee account');
  console.log('   3. Click "Create New" to register an app');
  console.log('   4. Name: "Ferni" (or anything)');
  console.log('   5. Copy the API Key\n');

  const apiKey = await prompt(rl, 'Enter your Ecobee API Key (or press Enter to skip): ');

  if (apiKey) {
    env.ECOBEE_API_KEY = apiKey;
    console.log('\n✅ Ecobee API Key saved!');
    console.log('   Next step: Run "pnpm ecobee:auth" to complete authorization');
  } else {
    console.log('   Skipped Ecobee setup');
  }
}

// =============================================================================
// PHILIPS HUE SETUP
// =============================================================================

async function findHueBridge(): Promise<string | null> {
  console.log('\n🔍 Searching for Hue Bridge on your network...');

  try {
    // Try Hue discovery endpoint
    const response = await fetch('https://discovery.meethue.com/');
    if (response.ok) {
      const bridges = await response.json() as Array<{ id: string; internalipaddress: string }>;
      if (bridges.length > 0) {
        return bridges[0].internalipaddress;
      }
    }
  } catch {
    // Discovery failed, will ask for manual input
  }

  return null;
}

async function createHueUser(bridgeIp: string): Promise<string | null> {
  console.log('\n⚡ Creating Hue username...');
  console.log('   (Make sure you pressed the link button!)\n');

  try {
    const response = await fetch(`http://${bridgeIp}/api`, {
      method: 'POST',
      body: JSON.stringify({ devicetype: 'ferni#smart-home' }),
    });

    if (response.ok) {
      const result = await response.json() as Array<{ success?: { username: string }; error?: { description: string } }>;
      if (result[0]?.success?.username) {
        return result[0].success.username;
      } else if (result[0]?.error) {
        console.log(`   ❌ Error: ${result[0].error.description}`);
        if (result[0].error.description.includes('link button')) {
          console.log('   👆 Press the link button on your Hue Bridge and try again!');
        }
      }
    }
  } catch (error) {
    console.log(`   ❌ Failed to connect: ${error}`);
  }

  return null;
}

async function testHueConnection(bridgeIp: string, username: string): Promise<boolean> {
  try {
    const response = await fetch(`http://${bridgeIp}/api/${username}/lights`);
    if (response.ok) {
      const lights = await response.json();
      const count = Object.keys(lights).length;
      console.log(`\n✅ Connected! Found ${count} light(s)`);
      return true;
    }
  } catch {
    // Connection failed
  }
  return false;
}

async function setupHue(rl: readline.Interface, env: Record<string, string>): Promise<void> {
  console.log('\n' + '═'.repeat(60));
  console.log('💡 PHILIPS HUE SETUP (Direct Bridge - No Cloud!)');
  console.log('═'.repeat(60));

  if (env.HUE_BRIDGE_IP && env.HUE_USERNAME) {
    console.log(`\n✅ Already configured:`);
    console.log(`   Bridge IP: ${env.HUE_BRIDGE_IP}`);
    console.log(`   Username: ${env.HUE_USERNAME.slice(0, 8)}...`);

    const works = await testHueConnection(env.HUE_BRIDGE_IP, env.HUE_USERNAME);
    if (works) {
      const reconfigure = await promptYesNo(rl, 'Reconfigure anyway?');
      if (!reconfigure) return;
    } else {
      console.log('   ⚠️ Connection test failed - let\'s reconfigure');
    }
  }

  // Try to find bridge automatically
  let bridgeIp = await findHueBridge();

  if (bridgeIp) {
    console.log(`\n✅ Found Hue Bridge at: ${bridgeIp}`);
    const useFound = await promptYesNo(rl, 'Use this bridge?');
    if (!useFound) {
      bridgeIp = null;
    }
  } else {
    console.log('   Could not auto-discover bridge');
  }

  if (!bridgeIp) {
    console.log('\n📋 To find your Hue Bridge IP:');
    console.log('   - Check your router\'s connected devices');
    console.log('   - Or look in the Hue app under Settings → Bridge\n');

    bridgeIp = await prompt(rl, 'Enter your Hue Bridge IP (or press Enter to skip): ');
    if (!bridgeIp) {
      console.log('   Skipped Hue setup');
      return;
    }
  }

  // Test if we can reach the bridge
  console.log(`\n🔌 Testing connection to ${bridgeIp}...`);
  try {
    const response = await fetch(`http://${bridgeIp}/api/config`, { signal: AbortSignal.timeout(5000) });
    if (!response.ok) {
      console.log('   ❌ Cannot reach bridge. Check the IP address.');
      return;
    }
    console.log('   ✅ Bridge is reachable');
  } catch {
    console.log('   ❌ Cannot reach bridge. Check the IP and make sure you\'re on the same network.');
    return;
  }

  // Create username
  console.log('\n' + '─'.repeat(40));
  console.log('👆 PRESS THE LINK BUTTON ON YOUR HUE BRIDGE NOW!');
  console.log('─'.repeat(40));
  await prompt(rl, 'Press Enter when ready...');

  let username = await createHueUser(bridgeIp);

  // Retry a few times
  let attempts = 0;
  while (!username && attempts < 3) {
    attempts++;
    const retry = await promptYesNo(rl, 'Try again?');
    if (!retry) break;
    console.log('\n👆 Press the link button and then press Enter...');
    await prompt(rl, '');
    username = await createHueUser(bridgeIp);
  }

  if (username) {
    env.HUE_BRIDGE_IP = bridgeIp;
    env.HUE_USERNAME = username;
    console.log('\n✅ Hue setup complete!');
    await testHueConnection(bridgeIp, username);
  } else {
    console.log('\n⚠️ Could not create Hue username. You can try again later.');
    console.log('   Or manually set HUE_BRIDGE_IP and HUE_USERNAME in .env.local');
  }
}

// =============================================================================
// LIFX SETUP
// =============================================================================

async function testLifxConnection(token: string): Promise<boolean> {
  try {
    const response = await fetch('https://api.lifx.com/v1/lights/all', {
      headers: { Authorization: `Bearer ${token}` },
    });

    if (response.ok) {
      const lights = await response.json() as Array<{ label: string }>;
      console.log(`\n✅ Connected! Found ${lights.length} light(s):`);
      for (const light of lights.slice(0, 5)) {
        console.log(`   • ${light.label}`);
      }
      if (lights.length > 5) {
        console.log(`   ... and ${lights.length - 5} more`);
      }
      return true;
    } else if (response.status === 401) {
      console.log('\n❌ Invalid token');
    }
  } catch (error) {
    console.log(`\n❌ Connection failed: ${error}`);
  }
  return false;
}

async function setupLifx(rl: readline.Interface, env: Record<string, string>): Promise<void> {
  console.log('\n' + '═'.repeat(60));
  console.log('💡 LIFX SETUP (Cloud API)');
  console.log('═'.repeat(60));

  if (env.LIFX_TOKEN) {
    console.log(`\n✅ Already configured: ${env.LIFX_TOKEN.slice(0, 8)}...`);
    const works = await testLifxConnection(env.LIFX_TOKEN);
    if (works) {
      const reconfigure = await promptYesNo(rl, 'Reconfigure anyway?');
      if (!reconfigure) return;
    } else {
      console.log('   Token seems invalid - let\'s get a new one');
    }
  }

  console.log('\n📋 Steps to get your LIFX Token:\n');
  console.log('   1. Go to: https://cloud.lifx.com/settings');
  console.log('   2. Sign in with your LIFX account');
  console.log('   3. Under "Personal Access Tokens", click "Generate New Token"');
  console.log('   4. Name: "Ferni" (or anything)');
  console.log('   5. Copy the token\n');

  const token = await prompt(rl, 'Enter your LIFX Token (or press Enter to skip): ');

  if (token) {
    const works = await testLifxConnection(token);
    if (works) {
      env.LIFX_TOKEN = token;
      console.log('\n✅ LIFX setup complete!');
    } else {
      const saveAnyway = await promptYesNo(rl, 'Save token anyway?');
      if (saveAnyway) {
        env.LIFX_TOKEN = token;
      }
    }
  } else {
    console.log('   Skipped LIFX setup');
  }
}

// =============================================================================
// MAIN
// =============================================================================

async function main(): Promise<void> {
  console.log('\n' + '═'.repeat(60));
  console.log('🏠 FERNI SMART HOME SETUP');
  console.log('═'.repeat(60));
  console.log('\nThis will help you set up direct integrations with your');
  console.log('smart home devices. No Home Assistant required!\n');

  const rl = createReadline();
  const env = loadEnvFile();

  // Set default user ID
  if (!env.TEST_USER_ID) {
    const userId = await prompt(rl, 'Enter a user ID (e.g., your name): ');
    env.TEST_USER_ID = userId || 'test-user';
  }

  // Check what devices they have
  console.log('\n📱 What smart home devices do you have?\n');

  const hasEcobee = await promptYesNo(rl, 'Ecobee thermostat?');
  const hasHue = await promptYesNo(rl, 'Philips Hue lights?');
  const hasLifx = await promptYesNo(rl, 'LIFX lights?');

  if (!hasEcobee && !hasHue && !hasLifx) {
    console.log('\n⚠️ No supported devices selected.');
    console.log('   You can still run tests with simulated/mock devices.');
    rl.close();
    return;
  }

  // Set up each integration
  if (hasEcobee) await setupEcobee(rl, env);
  if (hasHue) await setupHue(rl, env);
  if (hasLifx) await setupLifx(rl, env);

  // Save configuration
  saveEnvFile(env);

  // Summary
  console.log('\n' + '═'.repeat(60));
  console.log('📊 SETUP SUMMARY');
  console.log('═'.repeat(60));
  console.log(`\n   Ecobee:  ${env.ECOBEE_API_KEY ? '✅ Configured' : '❌ Not configured'}`);
  console.log(`   Hue:     ${env.HUE_BRIDGE_IP ? '✅ Configured' : '❌ Not configured'}`);
  console.log(`   LIFX:    ${env.LIFX_TOKEN ? '✅ Configured' : '❌ Not configured'}`);

  // Next steps
  console.log('\n📋 NEXT STEPS:\n');

  if (env.ECOBEE_API_KEY) {
    console.log('   1. Complete Ecobee authorization:');
    console.log('      pnpm ecobee:auth\n');
  }

  console.log('   2. Test your integrations:');
  console.log('      pnpm test:real-home:status\n');

  console.log('   3. Run device control tests (will change your home!):');
  console.log('      pnpm test:real-home:control\n');

  rl.close();
}

main().catch(console.error);
