#!/usr/bin/env python3
"""
Ferni Router Model Training - FTIS V3 (Apple Silicon MPS)

Train the FTIS V3 model using Qwen3-1.7B on Apple M1/M2/M3/M4 GPU via MPS.

Key improvements in V3:
- Qwen3-1.7B base model (better tool calling than Qwen2.5)
- 70%+ open intent examples (reduces false positive tool calls)
- Hard negatives for confusing tool pairs
- Edge cases for ambiguous queries

Usage:
  cd apps/ml-training/router
  source .venv/bin/activate
  pip install -r requirements.txt
  python train_mps.py

Data location: ./data/ (generated by scripts/generate-ftis-v3-training.ts)
"""

import os
import json
import torch
from pathlib import Path
from datasets import Dataset
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)
from peft import LoraConfig, get_peft_model, TaskType
from sklearn.metrics import f1_score, precision_score, recall_score
import numpy as np

# ==============================================================================
# CONFIG - FTIS V3
# ==============================================================================
# Qwen3-1.7B: Better tool calling, BFCL leader, outperforms Qwen2.5-3B
BASE_MODEL = "Qwen/Qwen3-1.7B"

# V3 training data (70%+ open intents, hard negatives, edge cases)
DATA_DIR = Path(__file__).parent / "data"  # ./data relative to this script
OUTPUT_DIR = Path("outputs/ferni-router-v3")
ONNX_OUTPUT_DIR = Path("/Users/sethford/Documents/voiceai/models/ferni-router-v3")

# LoRA config - optimized for Qwen3-1.7B on MPS
LORA_R = 16         # Increased for better quality
LORA_ALPHA = 32     # 2x r for standard scaling
LORA_DROPOUT = 0.05 # Lower dropout for small dataset

# Training config - optimized for M4 Pro with 5,500+ examples
MAX_LENGTH = 128    # Voice queries are short - reduce for speed
BATCH_SIZE = 8      # Larger batch with shorter sequences
GRADIENT_ACCUMULATION = 2  # Effective batch = 16 (faster training)
EPOCHS = 3          # Fewer epochs since we have more data
LEARNING_RATE = 3e-5  # Higher LR for faster convergence with more data

# Force MPS
os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"  # Prevent MPS OOM

def setup_device():
    """Configure device for Apple Silicon."""
    if torch.backends.mps.is_available():
        device = torch.device("mps")
        print(f"✅ Using MPS (Apple Silicon GPU)")
    else:
        device = torch.device("cpu")
        print("⚠️ MPS not available, using CPU")
    return device

def load_jsonl(path):
    """Load JSONL file."""
    with open(path, 'r') as f:
        return [json.loads(line) for line in f]

def build_label_map(train_data, val_data):
    """Build label map from all unique tool names in data."""
    all_tools = set()
    for item in train_data + val_data:
        for tool in item.get('selected_tools', []):
            all_tools.add(tool)

    # Sort for reproducibility
    sorted_tools = sorted(all_tools)
    label_map = {tool: idx for idx, tool in enumerate(sorted_tools)}
    return label_map

def load_data():
    """Load V3 training data and build label map."""
    train_data = load_jsonl(DATA_DIR / "train.jsonl")
    val_data = load_jsonl(DATA_DIR / "validation.jsonl")

    # Check for existing label_map or build from data
    label_map_path = DATA_DIR / "label_map.json"
    if label_map_path.exists():
        with open(label_map_path, 'r') as f:
            label_map = json.load(f)
        print("  Loaded existing label_map.json")
    else:
        label_map = build_label_map(train_data, val_data)
        # Save for reproducibility
        with open(label_map_path, 'w') as f:
            json.dump(label_map, f, indent=2)
        print("  Built and saved new label_map.json")

    # Count open intents
    train_open = sum(1 for d in train_data if d.get('is_open_intent', False))
    val_open = sum(1 for d in val_data if d.get('is_open_intent', False))

    print(f"Train: {len(train_data):,} ({train_open:,} open intents = {100*train_open/len(train_data):.1f}%)")
    print(f"Val:   {len(val_data):,} ({val_open:,} open intents = {100*val_open/len(val_data):.1f}%)")
    print(f"Labels: {len(label_map)} tools")

    return train_data, val_data, label_map

def convert_to_multilabel(data, label_map, num_labels):
    """Convert to multi-label format."""
    processed = []
    for item in data:
        labels = [0.0] * num_labels
        for tool in item.get('selected_tools', []):
            if tool in label_map:
                labels[label_map[tool]] = 1.0
        processed.append({
            'text': item['query'],
            'labels': labels,
        })
    return processed

def compute_metrics(eval_pred):
    """Compute F1, accuracy, and open intent metrics for V3."""
    logits, labels = eval_pred
    probs = 1 / (1 + np.exp(-logits))
    preds = (probs > 0.5).astype(int)

    # Identify open intents (no labels = all zeros)
    is_open_intent = (labels.sum(axis=1) == 0)
    has_tool_intent = ~is_open_intent

    # Open intent accuracy: should predict NO tools (all probs < 0.5)
    if is_open_intent.sum() > 0:
        open_preds = preds[is_open_intent]
        # Correct if no tool predicted (all zeros)
        open_correct = (open_preds.sum(axis=1) == 0)
        open_intent_acc = open_correct.mean()
    else:
        open_intent_acc = 0.0

    # Tool intent metrics (only for examples that SHOULD have tools)
    if has_tool_intent.sum() > 0:
        tool_probs = probs[has_tool_intent]
        tool_labels = labels[has_tool_intent]
        tool_preds = preds[has_tool_intent]

        # Top-1 accuracy for tool intents
        top1_indices = np.argmax(tool_probs, axis=1)
        label_indices = np.argmax(tool_labels, axis=1)
        top1_acc = (top1_indices == label_indices).mean()

        # Top-3 accuracy for tool intents
        top3_indices = np.argsort(tool_probs, axis=1)[:, -3:]
        top3_acc = np.array([label_indices[i] in top3_indices[i] for i in range(len(label_indices))]).mean()

        # F1 for tool intents
        f1 = f1_score(tool_labels, tool_preds, average='micro', zero_division=0)
    else:
        top1_acc = 0.0
        top3_acc = 0.0
        f1 = 0.0

    # Overall F1 (including open intents as "no prediction correct")
    overall_f1 = f1_score(labels, preds, average='micro', zero_division=0)

    return {
        'f1': overall_f1,
        'tool_f1': f1,
        'top1_acc': top1_acc,
        'top3_acc': top3_acc,
        'open_intent_acc': open_intent_acc,  # Critical for false positive reduction!
    }

def main():
    print("=" * 60)
    print("🚀 Ferni Router Model Training (MPS)")
    print("=" * 60)
    
    device = setup_device()
    
    # Load data
    print("\n📂 Loading data...")
    train_data, val_data, label_map = load_data()
    NUM_LABELS = len(label_map)
    
    # Convert to datasets
    train_processed = convert_to_multilabel(train_data, label_map, NUM_LABELS)
    val_processed = convert_to_multilabel(val_data, label_map, NUM_LABELS)
    
    train_dataset = Dataset.from_list(train_processed)
    val_dataset = Dataset.from_list(val_processed)
    
    # Load tokenizer
    print(f"\n🔤 Loading tokenizer: {BASE_MODEL}")
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    # Load model
    print(f"\n🧠 Loading model: {BASE_MODEL}")
    model = AutoModelForSequenceClassification.from_pretrained(
        BASE_MODEL,
        num_labels=NUM_LABELS,
        problem_type="multi_label_classification",
        trust_remote_code=True,
        dtype=torch.float32,  # MPS works better with fp32
    )
    model.config.pad_token_id = tokenizer.pad_token_id
    
    print(f"   Parameters: {sum(p.numel() for p in model.parameters()):,}")
    
    # Add LoRA
    print(f"\n🔧 Adding LoRA (r={LORA_R}, alpha={LORA_ALPHA})")
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=LORA_DROPOUT,
        bias="none",
        task_type=TaskType.SEQ_CLS,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    
    # Move to MPS
    model = model.to(device)
    
    # Tokenize
    print(f"\n📝 Tokenizing (max_length={MAX_LENGTH})...")
    def tokenize_fn(examples):
        return tokenizer(
            examples["text"],
            padding="max_length",
            truncation=True,
            max_length=MAX_LENGTH,
        )
    
    train_dataset = train_dataset.map(tokenize_fn, batched=True)
    val_dataset = val_dataset.map(tokenize_fn, batched=True)
    
    train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
    val_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
    
    # Training args
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Calculate eval steps based on dataset size
    steps_per_epoch = len(train_dataset) // (BATCH_SIZE * GRADIENT_ACCUMULATION)
    eval_steps = max(50, steps_per_epoch // 2)  # Eval twice per epoch minimum

    training_args = TrainingArguments(
        output_dir=str(OUTPUT_DIR),
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE * 2,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION,
        learning_rate=LEARNING_RATE,
        warmup_ratio=0.1,
        weight_decay=0.01,
        eval_strategy="steps",
        eval_steps=eval_steps,
        save_strategy="steps",
        save_steps=eval_steps * 2,
        save_total_limit=3,
        load_best_model_at_end=True,
        # Use tool_f1 as primary metric (open_intent_acc is secondary)
        metric_for_best_model="tool_f1",
        greater_is_better=True,
        logging_dir=str(OUTPUT_DIR / "logs"),
        logging_steps=20,
        report_to="tensorboard",
        remove_unused_columns=False,
        # MPS-specific
        use_mps_device=True,
        dataloader_pin_memory=False,  # Required for MPS
    )
    
    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    )
    
    # Train!
    print("\n" + "=" * 60)
    print("🏋️ Starting training...")
    print(f"   Epochs: {EPOCHS}")
    print(f"   Batch: {BATCH_SIZE} x {GRADIENT_ACCUMULATION} = {BATCH_SIZE * GRADIENT_ACCUMULATION}")
    print(f"   Train samples: {len(train_dataset):,}")
    print("=" * 60 + "\n")
    
    trainer.train()
    
    # Evaluate
    print("\n📊 Final evaluation:")
    results = trainer.evaluate()
    print("=" * 50)
    print("TOOL CALLING METRICS (should be high):")
    print(f"   Tool F1:        {results['eval_tool_f1']:.4f}")
    print(f"   Top-1 Accuracy: {results['eval_top1_acc']:.4f}")
    print(f"   Top-3 Accuracy: {results['eval_top3_acc']:.4f}")
    print("")
    print("OPEN INTENT METRICS (critical for false positive reduction):")
    print(f"   Open Intent Acc: {results['eval_open_intent_acc']:.4f}")
    print("=" * 50)
    print(f"Overall F1: {results['eval_f1']:.4f}")
    
    # Save
    final_dir = OUTPUT_DIR / "final"
    trainer.save_model(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    
    # Copy label map
    import shutil
    shutil.copy(DATA_DIR / "label_map.json", final_dir / "label_map.json")
    
    print(f"\n✅ Model saved to {final_dir}")
    
    # Export to ONNX
    print("\n📦 Exporting to ONNX...")
    export_to_onnx(model, tokenizer, label_map, final_dir)
    
    print("\n" + "=" * 60)
    print("✅ FTIS V3 TRAINING COMPLETE!")
    print("=" * 60)
    print(f"   Model:        Qwen3-1.7B + LoRA")
    print(f"   ONNX Output:  {ONNX_OUTPUT_DIR}")
    print(f"   Checkpoint:   {OUTPUT_DIR / 'final'}")
    print("")
    print("Next steps:")
    print("   1. Run decision boundary computation (Task #2)")
    print("   2. Deploy V3 model to semantic router (Task #3)")
    print("   3. Implement confidence calibration (Task #6)")
    print("=" * 60)

def export_to_onnx(model, tokenizer, label_map, checkpoint_dir):
    """Export to ONNX format for production inference."""
    import shutil

    try:
        from optimum.onnxruntime import ORTModelForSequenceClassification

        # Merge LoRA weights back into base model
        print("   Merging LoRA weights...")
        merged_model = model.merge_and_unload()
        merged_dir = OUTPUT_DIR / "merged"
        merged_model.save_pretrained(str(merged_dir))
        tokenizer.save_pretrained(str(merged_dir))

        # Export to ONNX
        print("   Exporting to ONNX...")
        ONNX_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        ort_model = ORTModelForSequenceClassification.from_pretrained(
            str(merged_dir),
            export=True,
        )
        ort_model.save_pretrained(str(ONNX_OUTPUT_DIR))

        # Copy label map and metadata
        label_map_src = DATA_DIR / "label_map.json"
        if label_map_src.exists():
            shutil.copy(label_map_src, ONNX_OUTPUT_DIR / "label_map.json")
        else:
            # Save label_map we built
            with open(ONNX_OUTPUT_DIR / "label_map.json", 'w') as f:
                json.dump(label_map, f, indent=2)

        # Copy metadata for version tracking
        metadata_src = DATA_DIR / "metadata.json"
        if metadata_src.exists():
            shutil.copy(metadata_src, ONNX_OUTPUT_DIR / "training_metadata.json")

        print(f"   ✅ ONNX exported to {ONNX_OUTPUT_DIR}")

    except ImportError:
        print("   ⚠️ optimum not installed. Run: pip install optimum[onnxruntime]")
        print("   You can export manually later with export_onnx.py")
    except Exception as e:
        print(f"   ⚠️ ONNX export failed: {e}")
        print("   You can export manually later with export_onnx.py")

if __name__ == "__main__":
    main()
