"""
Ferni Router V7 - Hierarchical Taxonomy
Maps 860 tools → 43 domains × ~200 meta-tools

Usage:
    from v7_taxonomy import TOOL_TO_DOMAIN, TOOL_TO_META, DOMAINS, get_domain, get_meta_tool

Architecture:
    Stage 1: Domain classifier (43 classes) - "what area of life?"
    Stage 2: Meta-tool classifier (2-8 per domain) - "what action?"
    Stage 3: LLM parameter extraction - "what specifics?"
"""

from typing import NamedTuple

class ToolMapping(NamedTuple):
    domain: str
    meta_tool: str

# ─────────────────────────────────────────────
# Complete tool → (domain, meta_tool) mapping
# ─────────────────────────────────────────────

TAXONOMY: dict[str, ToolMapping] = {
    # ═══ CALENDAR (4 meta-tools) ═══
    "getCalendarEvents":        ToolMapping("calendar", "calendar.read"),
    "getDailyBriefing":         ToolMapping("calendar", "calendar.read"),
    "morningBriefing":          ToolMapping("calendar", "calendar.read"),
    "checkAvailability":        ToolMapping("calendar", "calendar.read"),
    "getUpcomingBirthdays":     ToolMapping("calendar", "calendar.read"),
    "prepareForUpcomingEvent":  ToolMapping("calendar", "calendar.read"),
    "createCalendarEvent":      ToolMapping("calendar", "calendar.create"),
    "scheduleEvent":            ToolMapping("calendar", "calendar.create"),
    "calendarArchitecture":     ToolMapping("calendar", "calendar.create"),
    "scheduleAtBestTime":       ToolMapping("calendar", "calendar.create"),
    "setAnniversary":           ToolMapping("calendar", "calendar.create"),
    "setBirthday":              ToolMapping("calendar", "calendar.create"),
    "modifyEvent":              ToolMapping("calendar", "calendar.modify"),
    "rescheduleEvent":          ToolMapping("calendar", "calendar.modify"),
    "manageAppointment":        ToolMapping("calendar", "calendar.modify"),
    "cancelEvent":              ToolMapping("calendar", "calendar.delete"),

    # ═══ TASKS_REMINDERS (6 meta-tools) ═══
    "addTask":                  ToolMapping("tasks_reminders", "task.create"),
    "addProjectTask":           ToolMapping("tasks_reminders", "task.create"),
    "createTodo":               ToolMapping("tasks_reminders", "task.create"),
    "createProject":            ToolMapping("tasks_reminders", "task.create"),
    "completeTask":             ToolMapping("tasks_reminders", "task.complete"),
    "completeProjectTask":      ToolMapping("tasks_reminders", "task.complete"),
    "markDone":                 ToolMapping("tasks_reminders", "task.complete"),
    "closeFollowUp":            ToolMapping("tasks_reminders", "task.complete"),
    "getTasks":                 ToolMapping("tasks_reminders", "task.read"),
    "listTodos":                ToolMapping("tasks_reminders", "task.read"),
    "getProjectStatus":         ToolMapping("tasks_reminders", "task.read"),
    "listProjectTemplates":     ToolMapping("tasks_reminders", "task.read"),
    "getPriorities":            ToolMapping("tasks_reminders", "task.read"),
    "getFollowUpNeeded":        ToolMapping("tasks_reminders", "task.read"),
    "listScheduled":            ToolMapping("tasks_reminders", "task.read"),
    "trackFollowUp":            ToolMapping("tasks_reminders", "task.read"),
    "createReminder":           ToolMapping("tasks_reminders", "reminder.create"),
    "setReminder":              ToolMapping("tasks_reminders", "reminder.create"),
    "scheduleReminder":         ToolMapping("tasks_reminders", "reminder.create"),
    "scheduleFollowUp":         ToolMapping("tasks_reminders", "reminder.create"),
    "cancelReminder":           ToolMapping("tasks_reminders", "reminder.manage"),
    "listReminders":            ToolMapping("tasks_reminders", "reminder.manage"),
    "cancelScheduled":          ToolMapping("tasks_reminders", "reminder.manage"),
    "setPriority":              ToolMapping("tasks_reminders", "task.prioritize"),

    # ═══ TIMERS_ALARMS (2 meta-tools) ═══
    "createTimer":              ToolMapping("timers_alarms", "timer.manage"),
    "setTimer":                 ToolMapping("timers_alarms", "timer.manage"),
    "checkTimer":               ToolMapping("timers_alarms", "timer.manage"),
    "stopTimer":                ToolMapping("timers_alarms", "timer.manage"),
    "listTimers":               ToolMapping("timers_alarms", "timer.manage"),
    "createAlarm":              ToolMapping("timers_alarms", "alarm.manage"),
    "setAlarm":                 ToolMapping("timers_alarms", "alarm.manage"),
    "cancelAlarm":              ToolMapping("timers_alarms", "alarm.manage"),
    "snoozeAlarm":              ToolMapping("timers_alarms", "alarm.manage"),
    "listAlarms":               ToolMapping("timers_alarms", "alarm.manage"),

    # ═══ COMMUNICATION (5 meta-tools) ═══
    "sendEmail":                ToolMapping("communication", "message.send"),
    "composeEmail":             ToolMapping("communication", "message.send"),
    "sendMessage":              ToolMapping("communication", "message.send"),
    "sendMessageNow":           ToolMapping("communication", "message.send"),
    "textContact":              ToolMapping("communication", "message.send"),
    "sendSMS":                  ToolMapping("communication", "message.send"),
    "broadcastMessage":         ToolMapping("communication", "message.send"),
    "scheduleEmail":            ToolMapping("communication", "message.schedule"),
    "scheduleMessage":          ToolMapping("communication", "message.schedule"),
    "getOptimalSendTime":       ToolMapping("communication", "message.schedule"),
    "analyzeMessage":           ToolMapping("communication", "message.analyze"),
    "analyzeInboxPriority":     ToolMapping("communication", "message.analyze"),
    "summarizeThread":          ToolMapping("communication", "message.analyze"),
    "blockSender":              ToolMapping("communication", "message.manage"),
    "bulkUnsubscribe":          ToolMapping("communication", "message.manage"),
    "markVipSender":            ToolMapping("communication", "message.manage"),
    "manageContact":            ToolMapping("communication", "message.manage"),
    "saveContactInfo":          ToolMapping("communication", "message.manage"),
    "messageCrafting":          ToolMapping("communication", "message.craft"),
    "difficultEmailDraft":      ToolMapping("communication", "message.craft"),
    "anticipateResponses":      ToolMapping("communication", "message.craft"),
    "generateProactiveMessage": ToolMapping("communication", "message.craft"),

    # ═══ MUSIC_AUDIO (3 meta-tools) ═══
    "playMusic":                ToolMapping("music_audio", "music.play"),
    "music_play":               ToolMapping("music_audio", "music.play"),
    "spotify_play":             ToolMapping("music_audio", "music.play"),
    "playMoodMusic":            ToolMapping("music_audio", "music.play"),
    "playSonosMusic":           ToolMapping("music_audio", "music.play"),
    "playSonosFavorite":        ToolMapping("music_audio", "music.play"),
    "findSong":                 ToolMapping("music_audio", "music.play"),
    "searchMusic":              ToolMapping("music_audio", "music.play"),
    "pauseMusic":               ToolMapping("music_audio", "music.control"),
    "pauseSonos":               ToolMapping("music_audio", "music.control"),
    "resumeMusic":              ToolMapping("music_audio", "music.control"),
    "resumeSonos":              ToolMapping("music_audio", "music.control"),
    "skipTrack":                ToolMapping("music_audio", "music.control"),
    "musicControl":             ToolMapping("music_audio", "music.control"),
    "adjustVolume":             ToolMapping("music_audio", "music.control"),
    "setSonosVolume":           ToolMapping("music_audio", "music.control"),
    "musicInfo":                ToolMapping("music_audio", "music.info"),
    "whatsSonosPlaying":        ToolMapping("music_audio", "music.info"),
    "listSonosRooms":           ToolMapping("music_audio", "music.info"),
    "searchSonosFavorites":     ToolMapping("music_audio", "music.info"),
    "setSonosRoom":             ToolMapping("music_audio", "music.info"),

    # ═══ SMART_HOME (3 meta-tools) ═══
    "controlLight":             ToolMapping("smart_home", "home.control"),
    "controlLights":            ToolMapping("smart_home", "home.control"),
    "setLights":                ToolMapping("smart_home", "home.control"),
    "controlLock":              ToolMapping("smart_home", "home.control"),
    "adjustTemperature":        ToolMapping("smart_home", "home.control"),
    "setThermostat":            ToolMapping("smart_home", "home.control"),
    "activateScene":            ToolMapping("smart_home", "home.control"),
    "toggleAmbientMode":        ToolMapping("smart_home", "home.control"),
    "triggerAutomation":        ToolMapping("smart_home", "home.automation"),
    "createAutomation":         ToolMapping("smart_home", "home.automation"),
    "deleteAutomation":         ToolMapping("smart_home", "home.automation"),
    "pauseAutomation":          ToolMapping("smart_home", "home.automation"),
    "resumeAutomation":         ToolMapping("smart_home", "home.automation"),
    "listAutomations":          ToolMapping("smart_home", "home.automation"),
    "listDevices":              ToolMapping("smart_home", "home.info"),
    "setQuietHours":            ToolMapping("smart_home", "home.info"),
    "getAmbientContext":        ToolMapping("smart_home", "home.info"),
    "getAmbientPreferences":    ToolMapping("smart_home", "home.info"),
    "getFullAmbientIntelligence": ToolMapping("smart_home", "home.info"),

    # ═══ HEALTH_FITNESS (4 meta-tools) ═══
    "trackFitnessGoal":         ToolMapping("health_fitness", "health.track"),
    "logExercise":              ToolMapping("health_fitness", "health.track"),
    "trackWorkout":             ToolMapping("health_fitness", "health.track"),
    "logSleep":                 ToolMapping("health_fitness", "health.track"),
    "trackSleep":               ToolMapping("health_fitness", "health.track"),
    "logSymptom":               ToolMapping("health_fitness", "health.track"),
    "symptomTracking":          ToolMapping("health_fitness", "health.track"),
    "trackHydration":           ToolMapping("health_fitness", "health.track"),
    "logWater":                 ToolMapping("health_fitness", "health.track"),
    "suggestWorkout":           ToolMapping("health_fitness", "health.coach"),
    "joyfulMovement":           ToolMapping("health_fitness", "health.coach"),
    "suggestSleepHygiene":      ToolMapping("health_fitness", "health.coach"),
    "sleepSupport":             ToolMapping("health_fitness", "health.coach"),
    "sleepDeprivation":         ToolMapping("health_fitness", "health.coach"),
    "suggestEnergyBoost":       ToolMapping("health_fitness", "health.coach"),
    "restoreEnergy":            ToolMapping("health_fitness", "health.coach"),
    "naturePrescription":       ToolMapping("health_fitness", "health.coach"),
    "walkingMeditation":        ToolMapping("health_fitness", "health.coach"),
    "assessEnergyLevel":        ToolMapping("health_fitness", "health.assess"),
    "analyzeSleepPattern":      ToolMapping("health_fitness", "health.assess"),
    "wellnessCheck":            ToolMapping("health_fitness", "health.assess"),
    "wellnessCheckin":          ToolMapping("health_fitness", "health.assess"),
    "energyBudgeting":          ToolMapping("health_fitness", "health.assess"),
    "getEnergyWaveAwareness":   ToolMapping("health_fitness", "health.assess"),
    "prepareForDoctorVisit":    ToolMapping("health_fitness", "health.medical"),
    "scheduleHealthcareAppointment": ToolMapping("health_fitness", "health.medical"),
    "prepareSecondOpinionQuestions": ToolMapping("health_fitness", "health.medical"),
    "remindPreventiveCare":     ToolMapping("health_fitness", "health.medical"),
    "diagnosisShock":           ToolMapping("health_fitness", "health.medical"),
    "chronicIllnessLife":       ToolMapping("health_fitness", "health.medical"),
    "invisibleIllness":         ToolMapping("health_fitness", "health.medical"),

    # ═══ FOOD_NUTRITION (3 meta-tools) ═══
    "logMeal":                  ToolMapping("food_nutrition", "food.log"),
    "trackNutrition":           ToolMapping("food_nutrition", "food.log"),
    "trackDietaryPreferences":  ToolMapping("food_nutrition", "food.log"),
    "mindfulEating":            ToolMapping("food_nutrition", "food.log"),
    "emotionalEating":          ToolMapping("food_nutrition", "food.log"),
    "suggestMeals":             ToolMapping("food_nutrition", "food.plan"),
    "planWeeklyMeals":          ToolMapping("food_nutrition", "food.plan"),
    "addRecipe":                ToolMapping("food_nutrition", "food.plan"),
    "searchRecipes":            ToolMapping("food_nutrition", "food.plan"),
    "markRecipeCooked":         ToolMapping("food_nutrition", "food.plan"),
    "generateShoppingList":     ToolMapping("food_nutrition", "food.plan"),
    "coachOnNutrition":         ToolMapping("food_nutrition", "food.plan"),
    "announceDinner":           ToolMapping("food_nutrition", "food.plan"),
    "orderGroceries":           ToolMapping("food_nutrition", "food.order"),
    "foodDelivery":             ToolMapping("food_nutrition", "food.order"),

    # ═══ HABITS_ROUTINES (4 meta-tools) ═══
    "addHabit":                 ToolMapping("habits_routines", "habit.manage"),
    "createHabit":              ToolMapping("habits_routines", "habit.manage"),
    "trackHabit":               ToolMapping("habits_routines", "habit.manage"),
    "logHabit":                 ToolMapping("habits_routines", "habit.manage"),
    "markHabitComplete":        ToolMapping("habits_routines", "habit.manage"),
    "viewStreak":               ToolMapping("habits_routines", "habit.manage"),
    "compareToYesterday":       ToolMapping("habits_routines", "habit.manage"),
    "buildCreativeHabit":       ToolMapping("habits_routines", "habit.manage"),
    "habitCoaching":            ToolMapping("habits_routines", "habit.coach"),
    "getHabitAdvice":           ToolMapping("habits_routines", "habit.coach"),
    "conductHabitAutopsy":      ToolMapping("habits_routines", "habit.coach"),
    "detectKeystone":           ToolMapping("habits_routines", "habit.coach"),
    "behaviorArchitecture":     ToolMapping("habits_routines", "habit.coach"),
    "trackHabitDNA":            ToolMapping("habits_routines", "habit.coach"),
    "assessTendency":           ToolMapping("habits_routines", "habit.coach"),
    "gentleAccountability":     ToolMapping("habits_routines", "habit.coach"),
    "suggestNudge":             ToolMapping("habits_routines", "habit.coach"),
    "habitStats":               ToolMapping("habits_routines", "habit.stats"),
    "getHabitProgress":         ToolMapping("habits_routines", "habit.stats"),
    "mapFriction":              ToolMapping("habits_routines", "habit.stats"),
    "createRoutine":            ToolMapping("habits_routines", "routine.manage"),
    "runRoutine":               ToolMapping("habits_routines", "routine.manage"),
    "listRoutines":             ToolMapping("habits_routines", "routine.manage"),
    "toggleRoutine":            ToolMapping("habits_routines", "routine.manage"),
    "removeRoutine":            ToolMapping("habits_routines", "routine.manage"),
    "suggestRoutines":          ToolMapping("habits_routines", "routine.manage"),

    # ═══ TRAVEL (3 meta-tools) ═══
    "planTrip":                 ToolMapping("travel", "travel.plan"),
    "getTripSuggestions":       ToolMapping("travel", "travel.plan"),
    "getSavedTrips":            ToolMapping("travel", "travel.plan"),
    "searchFlights":            ToolMapping("travel", "travel.plan"),
    "getFlightPrice":           ToolMapping("travel", "travel.plan"),
    "searchHotels":             ToolMapping("travel", "travel.plan"),
    "requestHotelQuotes":       ToolMapping("travel", "travel.plan"),
    "requestRide":              ToolMapping("travel", "travel.ride"),
    "getRideStatus":            ToolMapping("travel", "travel.ride"),
    "cancelRide":               ToolMapping("travel", "travel.ride"),
    "scheduleRide":             ToolMapping("travel", "travel.ride"),
    "getCommuteTime":           ToolMapping("travel", "travel.ride"),
    "logMileage":               ToolMapping("travel", "travel.ride"),
    "planMove":                 ToolMapping("travel", "travel.move"),
    "moving":                   ToolMapping("travel", "travel.move"),

    # ═══ FINANCE_SHOPPING (3 meta-tools) ═══
    "comparePrices":            ToolMapping("finance_shopping", "finance.manage"),
    "detectSubscriptions":      ToolMapping("finance_shopping", "finance.manage"),
    "cancelSubscription":       ToolMapping("finance_shopping", "finance.manage"),
    "getSubscriptionSummary":   ToolMapping("finance_shopping", "finance.manage"),
    "organizeReceipts":         ToolMapping("finance_shopping", "finance.manage"),
    "prepareForTaxSeason":      ToolMapping("finance_shopping", "finance.manage"),
    "planCharitableGiving":     ToolMapping("finance_shopping", "finance.plan"),
    "alignGivingWithValues":    ToolMapping("finance_shopping", "finance.plan"),
    "promptEstatePlanning":     ToolMapping("finance_shopping", "finance.plan"),
    "writeEthicalWill":         ToolMapping("finance_shopping", "finance.plan"),
    "reviewBeneficiaries":      ToolMapping("finance_shopping", "finance.plan"),
    "reviewInsuranceCoverage":  ToolMapping("finance_shopping", "finance.plan"),
    "findFinancialAssistance":  ToolMapping("finance_shopping", "finance.research"),
    "researchSalary":           ToolMapping("finance_shopping", "finance.research"),

    # ═══ KNOWLEDGE_SEARCH (3 meta-tools) ═══
    "search":                   ToolMapping("knowledge_search", "knowledge.search"),
    "webSearch":                ToolMapping("knowledge_search", "knowledge.search"),
    "lookup":                   ToolMapping("knowledge_search", "knowledge.search"),
    "explainConcept":           ToolMapping("knowledge_search", "knowledge.search"),
    "getWeather":               ToolMapping("knowledge_search", "knowledge.search"),
    "getWeatherForecast":       ToolMapping("knowledge_search", "knowledge.search"),
    "weatherForecast":          ToolMapping("knowledge_search", "knowledge.search"),
    "getRecommendations":       ToolMapping("knowledge_search", "knowledge.search"),
    "recommendResource":        ToolMapping("knowledge_search", "knowledge.search"),
    "getBookDetails":           ToolMapping("knowledge_search", "knowledge.media"),
    "getBookRecommendations":   ToolMapping("knowledge_search", "knowledge.media"),
    "searchBooks":              ToolMapping("knowledge_search", "knowledge.media"),
    "getPopularBooks":          ToolMapping("knowledge_search", "knowledge.media"),
    "getPodcastEpisodes":       ToolMapping("knowledge_search", "knowledge.media"),
    "getPodcastRecommendations": ToolMapping("knowledge_search", "knowledge.media"),
    "getTopPodcasts":           ToolMapping("knowledge_search", "knowledge.media"),
    "searchPodcasts":           ToolMapping("knowledge_search", "knowledge.media"),
    "getVideoDetails":          ToolMapping("knowledge_search", "knowledge.media"),
    "getVideoRecommendations":  ToolMapping("knowledge_search", "knowledge.media"),
    "getTrendingVideos":        ToolMapping("knowledge_search", "knowledge.media"),
    "searchYouTube":            ToolMapping("knowledge_search", "knowledge.media"),
    "getNews":                  ToolMapping("knowledge_search", "knowledge.news"),
    "getSports":                ToolMapping("knowledge_search", "knowledge.news"),
    "headlines":                ToolMapping("knowledge_search", "knowledge.news"),

    # ═══ MEMORY_RECALL (3 meta-tools) ═══
    "rememberThis":             ToolMapping("memory_recall", "memory.save"),
    "saveMemory":               ToolMapping("memory_recall", "memory.save"),
    "storeInfo":                ToolMapping("memory_recall", "memory.save"),
    "archiveInsight":           ToolMapping("memory_recall", "memory.save"),
    "recordPattern":            ToolMapping("memory_recall", "memory.save"),
    "captureEventMeaning":      ToolMapping("memory_recall", "memory.save"),
    "captureLifeStory":         ToolMapping("memory_recall", "memory.save"),
    "createTimeCapsule":        ToolMapping("memory_recall", "memory.save"),
    "recordMeaningfulMoment":   ToolMapping("memory_recall", "memory.save"),
    "recordOralHistory":        ToolMapping("memory_recall", "memory.save"),
    "logReflection":            ToolMapping("memory_recall", "memory.save"),
    "journalPrompt":            ToolMapping("memory_recall", "memory.save"),
    "reflectionExercise":       ToolMapping("memory_recall", "memory.save"),
    "ceoJournal":               ToolMapping("memory_recall", "memory.save"),
    "getMemory":                ToolMapping("memory_recall", "memory.recall"),
    "recallMemory":             ToolMapping("memory_recall", "memory.recall"),
    "recallEmotionalContext":   ToolMapping("memory_recall", "memory.recall"),
    "recallEventPatterns":      ToolMapping("memory_recall", "memory.recall"),
    "recallVisualMemory":       ToolMapping("memory_recall", "memory.recall"),
    "whatDoYouKnow":            ToolMapping("memory_recall", "memory.recall"),
    "countVisualMemories":      ToolMapping("memory_recall", "memory.recall"),
    "getConversationAwareness": ToolMapping("memory_recall", "memory.recall"),
    "getCurrentContext":        ToolMapping("memory_recall", "memory.recall"),
    "getUserContext":           ToolMapping("memory_recall", "memory.recall"),
    "describeSharedPhoto":      ToolMapping("memory_recall", "memory.photos"),
    "listRecentPhotos":         ToolMapping("memory_recall", "memory.photos"),

    # ═══ TELEPHONY (2 meta-tools) ═══
    "callContact":              ToolMapping("telephony", "call.make"),
    "makeCall":                 ToolMapping("telephony", "call.make"),
    "callAndConverse":          ToolMapping("telephony", "call.make"),
    "callOnBehalf":             ToolMapping("telephony", "call.make"),
    "intercomCall":             ToolMapping("telephony", "call.make"),
    "inviteFriendByCall":       ToolMapping("telephony", "call.make"),
    "sendSupportCall":          ToolMapping("telephony", "call.make"),
    "scheduleCall":             ToolMapping("telephony", "call.schedule"),

    # ═══ HOME_MAINTENANCE (3 meta-tools) ═══
    "getMaintenanceSchedule":   ToolMapping("home_maintenance", "home_maint.schedule"),
    "homeMaintenanceReminder":  ToolMapping("home_maintenance", "home_maint.schedule"),
    "remindHomeMaintenance":    ToolMapping("home_maintenance", "home_maint.schedule"),
    "reminderAnnualTasks":      ToolMapping("home_maintenance", "home_maint.schedule"),
    "setInsuranceRenewal":      ToolMapping("home_maintenance", "home_maint.schedule"),
    "setRegistrationExpiry":    ToolMapping("home_maintenance", "home_maint.schedule"),
    "trackExpiration":          ToolMapping("home_maintenance", "home_maint.schedule"),
    "trackRenewal":             ToolMapping("home_maintenance", "home_maint.schedule"),
    "homeProjectPlanner":       ToolMapping("home_maintenance", "home_maint.project"),
    "planHomeProject":          ToolMapping("home_maintenance", "home_maint.project"),
    "homeRepairAdvice":         ToolMapping("home_maintenance", "home_maint.project"),
    "renovation":               ToolMapping("home_maintenance", "home_maint.project"),
    "manageContractor":         ToolMapping("home_maintenance", "home_maint.project"),
    "findContractor":           ToolMapping("home_maintenance", "home_maint.project"),
    "getServiceQuotes":         ToolMapping("home_maintenance", "home_maint.project"),
    "organizeSpace":            ToolMapping("home_maintenance", "home_maint.project"),
    "coachDecluttering":        ToolMapping("home_maintenance", "home_maint.project"),
    "getWarrantyStatus":        ToolMapping("home_maintenance", "home_maint.track"),
    "trackServiceHistory":      ToolMapping("home_maintenance", "home_maint.track"),
    "trackRepair":              ToolMapping("home_maintenance", "home_maint.track"),
    "assessEmergencyPreparedness": ToolMapping("home_maintenance", "home_maint.track"),
    "addVehicle":               ToolMapping("home_maintenance", "home_maint.track"),

    # ═══ DOCUMENTS_FILES (1 meta-tool) ═══
    "findDocument":             ToolMapping("documents_files", "document.manage"),
    "locateDocument":           ToolMapping("documents_files", "document.manage"),
    "searchFiles":              ToolMapping("documents_files", "document.manage"),
    "organizeDocuments":        ToolMapping("documents_files", "document.manage"),
    "saveDocument":             ToolMapping("documents_files", "document.manage"),

    # ═══ SOCIAL_MEDIA (1 meta-tool) ═══
    "postToLinkedIn":           ToolMapping("social_media", "social.post"),
    "postToTwitter":            ToolMapping("social_media", "social.post"),
    "generateSocialContent":    ToolMapping("social_media", "social.post"),
    "listScheduledPosts":       ToolMapping("social_media", "social.post"),

    # ═══ GRIEF_LOSS (3 meta-tools) ═══
    "processGrief":             ToolMapping("grief_loss", "grief.process"),
    "processGriefForWhatWas":   ToolMapping("grief_loss", "grief.process"),
    "griefSupport":             ToolMapping("grief_loss", "grief.process"),
    "companionInGrief":         ToolMapping("grief_loss", "grief.process"),
    "navigateGriefWave":        ToolMapping("grief_loss", "grief.process"),
    "validateGrief":            ToolMapping("grief_loss", "grief.process"),
    "anticipatoryGrief":        ToolMapping("grief_loss", "grief.process"),
    "spiritualGrief":           ToolMapping("grief_loss", "grief.process"),
    "navigateAmbiguousLoss":    ToolMapping("grief_loss", "grief.process"),
    "grievingRelationship":     ToolMapping("grief_loss", "grief.process"),
    "processBreakup":           ToolMapping("grief_loss", "grief.process"),
    "acknowledgeLoss":          ToolMapping("grief_loss", "grief.acknowledge"),
    "acknowledgeWhatWas":       ToolMapping("grief_loss", "grief.acknowledge"),
    "grieveWhatWas":            ToolMapping("grief_loss", "grief.acknowledge"),
    "honorEnding":              ToolMapping("grief_loss", "grief.acknowledge"),
    "processEnding":            ToolMapping("grief_loss", "grief.acknowledge"),
    "honorUnfulfilled":         ToolMapping("grief_loss", "grief.acknowledge"),
    "rememberLoved":            ToolMapping("grief_loss", "grief.acknowledge"),
    "rememberWhen":             ToolMapping("grief_loss", "grief.acknowledge"),
    "jobLossGrief":             ToolMapping("grief_loss", "grief.specific"),
    "griefOfChronicIllness":    ToolMapping("grief_loss", "grief.specific"),
    "getTeamGriefContext":      ToolMapping("grief_loss", "grief.specific"),
    "shareGriefInsight":        ToolMapping("grief_loss", "grief.specific"),

    # ═══ EMOTIONAL_SUPPORT (4 meta-tools) ═══
    "deEscalateAnxiety":        ToolMapping("emotional_support", "emotional.calm"),
    "calmingTechnique":         ToolMapping("emotional_support", "emotional.calm"),
    "groundingExercise":        ToolMapping("emotional_support", "emotional.calm"),
    "guideGroundingExercise":   ToolMapping("emotional_support", "emotional.calm"),
    "groundInBody":             ToolMapping("emotional_support", "emotional.calm"),
    "groundingForTrauma":       ToolMapping("emotional_support", "emotional.calm"),
    "breatheWithMe":            ToolMapping("emotional_support", "emotional.calm"),
    "somaticSupport":           ToolMapping("emotional_support", "emotional.calm"),
    "windowOfTolerance":        ToolMapping("emotional_support", "emotional.calm"),
    "traumaResponses":          ToolMapping("emotional_support", "emotional.calm"),
    "autismSensoryRegulation":  ToolMapping("emotional_support", "emotional.calm"),
    "holdSpace":                ToolMapping("emotional_support", "emotional.presence"),
    "expressPresence":          ToolMapping("emotional_support", "emotional.presence"),
    "protectPresence":          ToolMapping("emotional_support", "emotional.presence"),
    "noticeThisMoment":         ToolMapping("emotional_support", "emotional.presence"),
    "returnToPresent":          ToolMapping("emotional_support", "emotional.presence"),
    "slowDown":                 ToolMapping("emotional_support", "emotional.presence"),
    "holdDualEmotions":         ToolMapping("emotional_support", "emotional.presence"),
    "holdParadox":              ToolMapping("emotional_support", "emotional.presence"),
    "holdHopeWhenCant":         ToolMapping("emotional_support", "emotional.presence"),
    "holdSecret":               ToolMapping("emotional_support", "emotional.presence"),
    "thisTooPasses":            ToolMapping("emotional_support", "emotional.presence"),
    "postTraumaticGrowth":      ToolMapping("emotional_support", "emotional.presence"),
    "identifyResistance":       ToolMapping("emotional_support", "emotional.presence"),
    "processing":               ToolMapping("emotional_support", "emotional.presence"),
    "betrayalTrauma":           ToolMapping("emotional_support", "emotional.presence"),
    "encouragement":            ToolMapping("emotional_support", "emotional.encourage"),
    "getMotivation":            ToolMapping("emotional_support", "emotional.encourage"),
    "remindOfProgress":         ToolMapping("emotional_support", "emotional.encourage"),
    "affirmWorth":              ToolMapping("emotional_support", "emotional.encourage"),
    "enoughForToday":           ToolMapping("emotional_support", "emotional.encourage"),
    "enoughness":               ToolMapping("emotional_support", "emotional.encourage"),
    "trackEnough":              ToolMapping("emotional_support", "emotional.encourage"),
    "motivationCoaching":       ToolMapping("emotional_support", "emotional.encourage"),
    "analyzeSetbackPattern":    ToolMapping("emotional_support", "emotional.encourage"),
    "checkInOnJourney":         ToolMapping("emotional_support", "emotional.encourage"),
    "moodCheck":                ToolMapping("emotional_support", "emotional.check"),
    "releaseUrgency":           ToolMapping("emotional_support", "emotional.check"),
    "shiftMode":                ToolMapping("emotional_support", "emotional.check"),
    "triggerAwareness":         ToolMapping("emotional_support", "emotional.check"),
    "autismSocialEnergy":       ToolMapping("emotional_support", "emotional.check"),

    # ═══ SELF_COMPASSION (3 meta-tools) ═══
    "selfCompassionBreak":      ToolMapping("self_compassion", "self_compassion.practice"),
    "selfCompassionCoaching":   ToolMapping("self_compassion", "self_compassion.practice"),
    "selfCompassionTrauma":     ToolMapping("self_compassion", "self_compassion.practice"),
    "practiceSelfAcceptance":   ToolMapping("self_compassion", "self_compassion.practice"),
    "practiceSelfForgiveness":  ToolMapping("self_compassion", "self_compassion.practice"),
    "practiceSelfKindness":     ToolMapping("self_compassion", "self_compassion.practice"),
    "speakToYourselfAsAFriend": ToolMapping("self_compassion", "self_compassion.practice"),
    "compassionateLetter":      ToolMapping("self_compassion", "self_compassion.practice"),
    "compassionateReset":       ToolMapping("self_compassion", "self_compassion.practice"),
    "forgivenessJourney":       ToolMapping("self_compassion", "self_compassion.practice"),
    "innerCritic":              ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "noticeInnerCritic":        ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "reframeInnerCritic":       ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "innerCriticBody":          ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "addressPerfectionism":     ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "perfectionismTriggers":    ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "understandPerfectionism":  ToolMapping("self_compassion", "self_compassion.inner_critic"),
    "mirrorWork":               ToolMapping("self_compassion", "self_compassion.worth"),
    "giveYourselfCredit":       ToolMapping("self_compassion", "self_compassion.worth"),
    "goodEnough":               ToolMapping("self_compassion", "self_compassion.worth"),
    "healthyStriving":          ToolMapping("self_compassion", "self_compassion.worth"),
    "embraceImperfection":      ToolMapping("self_compassion", "self_compassion.worth"),
    "embracePlateau":           ToolMapping("self_compassion", "self_compassion.worth"),
    "comparisonDetox":          ToolMapping("self_compassion", "self_compassion.worth"),
    "comparisonTrap":           ToolMapping("self_compassion", "self_compassion.worth"),
    "rebuildingConfidence":     ToolMapping("self_compassion", "self_compassion.worth"),
    "transformEnvy":            ToolMapping("self_compassion", "self_compassion.worth"),
    "understandEnvy":           ToolMapping("self_compassion", "self_compassion.worth"),
    "recoverFromPeoplePleasing": ToolMapping("self_compassion", "self_compassion.worth"),

    # ═══ ANGER_CONFLICT (3 meta-tools) ═══
    "angerCoaching":            ToolMapping("anger_conflict", "anger.manage"),
    "angerCoolDown":            ToolMapping("anger_conflict", "anger.manage"),
    "angerInTheMoment":         ToolMapping("anger_conflict", "anger.manage"),
    "understandAnger":          ToolMapping("anger_conflict", "anger.manage"),
    "chronicAnger":             ToolMapping("anger_conflict", "anger.manage"),
    "expressAngerHealthily":    ToolMapping("anger_conflict", "anger.manage"),
    "identifyAngerTriggers":    ToolMapping("anger_conflict", "anger.manage"),
    "repairAfterAnger":         ToolMapping("anger_conflict", "anger.repair"),
    "conflictResolution":       ToolMapping("anger_conflict", "anger.repair"),
    "navigateConflict":         ToolMapping("anger_conflict", "anger.repair"),
    "valueConflictResolution":  ToolMapping("anger_conflict", "anger.repair"),
    "releaseResentment":        ToolMapping("anger_conflict", "anger.repair"),
    "resentmentInventory":      ToolMapping("anger_conflict", "anger.repair"),
    "understandResentment":     ToolMapping("anger_conflict", "anger.repair"),
    "assertNotAggressive":      ToolMapping("anger_conflict", "anger.assert"),
    "flagAngerPatternForMaya":  ToolMapping("anger_conflict", "anger.assert"),
    "shareAngerInsightWithNayan": ToolMapping("anger_conflict", "anger.assert"),

    # ═══ CRISIS_SAFETY (2 meta-tools) ═══
    "crisisSupport":            ToolMapping("crisis_safety", "crisis.support"),
    "emergencyHelp":            ToolMapping("crisis_safety", "crisis.support"),
    "provideCrisisResources":   ToolMapping("crisis_safety", "crisis.support"),
    "quickCrisisResources":     ToolMapping("crisis_safety", "crisis.support"),
    "createSafetyPlan":         ToolMapping("crisis_safety", "crisis.support"),
    "createSafeSpace":          ToolMapping("crisis_safety", "crisis.support"),
    "findSafeResources":        ToolMapping("crisis_safety", "crisis.support"),
    "evaluateHumanTransfer":    ToolMapping("crisis_safety", "crisis.escalate"),
    "connectToHumanExpert":     ToolMapping("crisis_safety", "crisis.escalate"),

    # ═══ RELATIONSHIPS_DATING (4 meta-tools) ═══
    "deepenAcquaintance":       ToolMapping("relationships_dating", "relationship.deepen"),
    "deepenFriendship":         ToolMapping("relationships_dating", "relationship.deepen"),
    "moveFromAcquaintanceToFriend": ToolMapping("relationships_dating", "relationship.deepen"),
    "maintainFriendships":      ToolMapping("relationships_dating", "relationship.deepen"),
    "reconnectAfterTime":       ToolMapping("relationships_dating", "relationship.deepen"),
    "reconnecting":             ToolMapping("relationships_dating", "relationship.deepen"),
    "identifyNeglectedRelationships": ToolMapping("relationships_dating", "relationship.deepen"),
    "mapRelationshipCircles":   ToolMapping("relationships_dating", "relationship.deepen"),
    "getRelationshipNetworkContext": ToolMapping("relationships_dating", "relationship.deepen"),
    "assessConnectionHealth":   ToolMapping("relationships_dating", "relationship.deepen"),
    "datingAdvice":             ToolMapping("relationships_dating", "relationship.dating"),
    "datingAppFatigue":         ToolMapping("relationships_dating", "relationship.dating"),
    "datingAppStrategy":        ToolMapping("relationships_dating", "relationship.dating"),
    "datingIntentions":         ToolMapping("relationships_dating", "relationship.dating"),
    "datingReadiness":          ToolMapping("relationships_dating", "relationship.dating"),
    "datingRedFlags":           ToolMapping("relationships_dating", "relationship.dating"),
    "datingRejection":          ToolMapping("relationships_dating", "relationship.dating"),
    "datingValues":             ToolMapping("relationships_dating", "relationship.dating"),
    "dealbreakers":             ToolMapping("relationships_dating", "relationship.dating"),
    "afterDateReflection":      ToolMapping("relationships_dating", "relationship.dating"),
    "emotionalIntimacy":        ToolMapping("relationships_dating", "relationship.intimacy"),
    "intimacyBarriers":         ToolMapping("relationships_dating", "relationship.intimacy"),
    "intimacyTypes":            ToolMapping("relationships_dating", "relationship.intimacy"),
    "vulnerabilityInRelationship": ToolMapping("relationships_dating", "relationship.intimacy"),
    "communicatingDesires":     ToolMapping("relationships_dating", "relationship.intimacy"),
    "couplesRediscovery":       ToolMapping("relationships_dating", "relationship.intimacy"),
    "relationshipAfterBaby":    ToolMapping("relationships_dating", "relationship.intimacy"),
    "shouldWeStay":             ToolMapping("relationships_dating", "relationship.intimacy"),
    "understandLoveLanguages":  ToolMapping("relationships_dating", "relationship.intimacy"),
    "relationshipAdvice":       ToolMapping("relationships_dating", "relationship.repair"),
    "assessRelationshipHealth": ToolMapping("relationships_dating", "relationship.repair"),
    "repairRelationshipRupture": ToolMapping("relationships_dating", "relationship.repair"),
    "breakupSupport":           ToolMapping("relationships_dating", "relationship.repair"),
    "trustRecovery":            ToolMapping("relationships_dating", "relationship.repair"),
    "understandingWhyICheated": ToolMapping("relationships_dating", "relationship.repair"),
    # ═══ CAREER_WORK (4 meta-tools) ═══
    "clarifyCareerGoals":       ToolMapping("career_work", "career.plan"),
    "planCareerTransition":     ToolMapping("career_work", "career.plan"),
    "assessCareerSatisfaction": ToolMapping("career_work", "career.plan"),
    "findMeaningInWork":        ToolMapping("career_work", "career.plan"),
    "job-search":               ToolMapping("career_work", "career.job_search"),
    "suggestJobSearchStrategy": ToolMapping("career_work", "career.job_search"),
    "trackJobApplication":      ToolMapping("career_work", "career.job_search"),
    "jobSearchMentalHealth":    ToolMapping("career_work", "career.job_search"),
    "practiceInterview":        ToolMapping("career_work", "career.job_search"),
    "prepareSTARStories":       ToolMapping("career_work", "career.job_search"),
    "rolePlayNegotiation":      ToolMapping("career_work", "career.job_search"),
    "identityAfterLayoff":      ToolMapping("career_work", "career.job_search"),
    "assessBurnout":            ToolMapping("career_work", "career.burnout"),
    "assessWorkBurnout":        ToolMapping("career_work", "career.burnout"),
    "burnoutCoaching":          ToolMapping("career_work", "career.burnout"),
    "burnoutRecoveryPlan":      ToolMapping("career_work", "career.burnout"),
    "burnoutWarningSigns":      ToolMapping("career_work", "career.burnout"),
    "sandwichBurnout":          ToolMapping("career_work", "career.burnout"),
    "sandwichGuilt":            ToolMapping("career_work", "career.burnout"),
    "imposterSyndrome":         ToolMapping("career_work", "career.confidence"),
    "addressImposter":          ToolMapping("career_work", "career.confidence"),
    "fearOfFailure":            ToolMapping("career_work", "career.confidence"),

    # ═══ FAMILY_PARENTING (4 meta-tools) ═══
    "parentingSupport":         ToolMapping("family_parenting", "family.parenting"),
    "newParentSurvival":        ToolMapping("family_parenting", "family.parenting"),
    "disciplineStrategy":       ToolMapping("family_parenting", "family.parenting"),
    "navigateDiscipline":       ToolMapping("family_parenting", "family.parenting"),
    "suggestAgeAppropriateActivity": ToolMapping("family_parenting", "family.parenting"),
    "coachParentingChallenge":  ToolMapping("family_parenting", "family.parenting"),
    "parentIdentityShift":      ToolMapping("family_parenting", "family.parenting"),
    "postpartumCheckin":        ToolMapping("family_parenting", "family.parenting"),
    "trackChildMilestone":      ToolMapping("family_parenting", "family.parenting"),
    "navigateFamilyConflict":   ToolMapping("family_parenting", "family.conflict"),
    "resentmentInFamily":       ToolMapping("family_parenting", "family.conflict"),
    "blendedFamilyConflict":    ToolMapping("family_parenting", "family.conflict"),
    "holidaysBlended":          ToolMapping("family_parenting", "family.conflict"),
    "stepParentStruggle":       ToolMapping("family_parenting", "family.conflict"),
    "coParentingAfterDivorce":  ToolMapping("family_parenting", "family.conflict"),
    "coordinateElderCare":      ToolMapping("family_parenting", "family.eldercare"),
    "elderCareSupport":         ToolMapping("family_parenting", "family.eldercare"),
    "caregiverBurnout":         ToolMapping("family_parenting", "family.eldercare"),
    "caregiverGuilt":           ToolMapping("family_parenting", "family.eldercare"),
    "caregiverIdentityLoss":    ToolMapping("family_parenting", "family.eldercare"),
    "balancingCare":            ToolMapping("family_parenting", "family.eldercare"),
    "respiteNeed":              ToolMapping("family_parenting", "family.eldercare"),
    "familyStoryPrompts":       ToolMapping("family_parenting", "family.traditions"),
    "createFamilyTradition":    ToolMapping("family_parenting", "family.traditions"),
    "celebrateFamilyMoment":    ToolMapping("family_parenting", "family.traditions"),
    "planFamilyMeeting":        ToolMapping("family_parenting", "family.traditions"),
    "supportFamilyTransition":  ToolMapping("family_parenting", "family.traditions"),
    "faithAndFamily":           ToolMapping("family_parenting", "family.traditions"),
    "emptyNest":                ToolMapping("family_parenting", "family.traditions"),
    "emptyNestGrief":           ToolMapping("family_parenting", "family.traditions"),
    "freedomAfterKids":         ToolMapping("family_parenting", "family.traditions"),

    # ═══ LIFE_TRANSITIONS (3 meta-tools) ═══
    "navigateTransition":       ToolMapping("life_transitions", "transition.navigate"),
    "acknowledgeTransition":    ToolMapping("life_transitions", "transition.navigate"),
    "anticipateTransition":     ToolMapping("life_transitions", "transition.navigate"),
    "findMeaningInTransition":  ToolMapping("life_transitions", "transition.navigate"),
    "adaptToNewNormal":         ToolMapping("life_transitions", "transition.navigate"),
    "transitionStage":          ToolMapping("life_transitions", "transition.navigate"),
    "createTransitionRitual":   ToolMapping("life_transitions", "transition.navigate"),
    "assessReadinessForChange": ToolMapping("life_transitions", "transition.navigate"),
    "navigateFirstTime":        ToolMapping("life_transitions", "transition.navigate"),
    "preserveWhatMatters":      ToolMapping("life_transitions", "transition.navigate"),
    "identifyWhatToKeep":       ToolMapping("life_transitions", "transition.navigate"),
    "buildCourageForWhatNext":  ToolMapping("life_transitions", "transition.navigate"),
    "createComebackPlan":       ToolMapping("life_transitions", "transition.navigate"),
    "embraceNewIdentity":       ToolMapping("life_transitions", "transition.identity"),
    "embraceBeginning":         ToolMapping("life_transitions", "transition.identity"),
    "exploreLifeChapter":       ToolMapping("life_transitions", "transition.identity"),
    "exploreIdentityShift":     ToolMapping("life_transitions", "transition.identity"),
    "trackIdentityShift":       ToolMapping("life_transitions", "transition.identity"),
    "rebuildIdentity":          ToolMapping("life_transitions", "transition.identity"),
    "rediscoverSelf":           ToolMapping("life_transitions", "transition.identity"),
    "rediscoverYourself":       ToolMapping("life_transitions", "transition.identity"),
    "whoAmIBecoming":           ToolMapping("life_transitions", "transition.identity"),
    "exploreGrowthAreas":       ToolMapping("life_transitions", "transition.identity"),
    "revealHiddenSelf":         ToolMapping("life_transitions", "transition.identity"),
    "honorWhoYouWere":          ToolMapping("life_transitions", "transition.identity"),
    "alternativeLife":          ToolMapping("life_transitions", "transition.midlife"),
    "futureSelf":               ToolMapping("life_transitions", "transition.midlife"),
    "decadeView":               ToolMapping("life_transitions", "transition.midlife"),
    "midlifeReckoning":         ToolMapping("life_transitions", "transition.midlife"),
    "reinventionMidlife":       ToolMapping("life_transitions", "transition.midlife"),
    "secondHalfPurpose":        ToolMapping("life_transitions", "transition.midlife"),

    # ═══ VALUES_PURPOSE (3 meta-tools) ═══
    "clarifyValues":            ToolMapping("values_purpose", "values.explore"),
    "checkValuesAlignment":     ToolMapping("values_purpose", "values.explore"),
    "discussValues":            ToolMapping("values_purpose", "values.explore"),
    "valuesCardSort":           ToolMapping("values_purpose", "values.explore"),
    "valuesCardSortRespond":    ToolMapping("values_purpose", "values.explore"),
    "authenticLiving":          ToolMapping("values_purpose", "values.explore"),
    "livingAuthentically":      ToolMapping("values_purpose", "values.explore"),
    "practiceTruth":            ToolMapping("values_purpose", "values.explore"),
    "faithDeconstruction":      ToolMapping("values_purpose", "values.explore"),
    "beliefRebuilding":         ToolMapping("values_purpose", "values.explore"),
    "spiritualPracticeSupport": ToolMapping("values_purpose", "values.explore"),
    "clarifyIntention":         ToolMapping("values_purpose", "values.explore"),
    "explorePurpose":           ToolMapping("values_purpose", "values.purpose"),
    "alignActionsWithPurpose":  ToolMapping("values_purpose", "values.purpose"),
    "createPersonalMission":    ToolMapping("values_purpose", "values.purpose"),
    "dailyMeaningPractice":     ToolMapping("values_purpose", "values.purpose"),
    "findMeaningInSuffering":   ToolMapping("values_purpose", "values.purpose"),
    "reconnectWithDreams":      ToolMapping("values_purpose", "values.purpose"),
    "reflectOnContribution":    ToolMapping("values_purpose", "values.purpose"),
    "bucketList":               ToolMapping("values_purpose", "values.purpose"),
    "defineLegacy":             ToolMapping("values_purpose", "values.legacy"),
    "legacyBuilding":           ToolMapping("values_purpose", "values.legacy"),
    "whatWillMatter":           ToolMapping("values_purpose", "values.legacy"),
    "exploreMortality":         ToolMapping("values_purpose", "values.legacy"),
    "mortalityPerspective":     ToolMapping("values_purpose", "values.legacy"),
    "endOfLifeConversation":    ToolMapping("values_purpose", "values.legacy"),

    # ═══ WISDOM_PHILOSOPHY (2 meta-tools) ═══
    "sitWithBigQuestion":       ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "exploreQuestion":          ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "captureQuestion":          ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "generatePersonalKoan":     ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "embraceMystery":           ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "embraceUncertainty":       ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "exploreLifePhilosophy":    ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "intellectualExploration":  ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "captureDream":             ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "exploreDream":             ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "cultivateBeginnersMind":   ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "trackWisdomIncubation":    ToolMapping("wisdom_philosophy", "wisdom.inquire"),
    "counterIntuitiveInsight":  ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "crossDomainConnection":    ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "ancientParallel":          ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "historicalParallel":       ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "ancestralWisdom":          ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "applySeasonalWisdom":      ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "seasonalWisdom":           ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "winterSeason":             ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "getSeasonalAwareness":     ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "getTodaySignificance":     ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "simulateCounterfactual":   ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "whatIf":                   ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "discoverPattern":          ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "findNarrativeThread":      ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "findTheLessons":           ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "reflectOnJourney":         ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "reflectOnPastDecisions":   ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "reframeNarrative":         ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "rewriteStory":             ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "revealBlindSpot":          ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "surfacePatternInsight":    ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "surfacePatternMirrorInsight": ToolMapping("wisdom_philosophy", "wisdom.perspective"),
    "zoomOut":                  ToolMapping("wisdom_philosophy", "wisdom.perspective"),

    # ═══ CELEBRATION_JOY (2 meta-tools) ═══
    "celebrateTinyWin":         ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateTinyWins":        ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateWin":             ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateYourself":        ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateCompletion":      ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateCreation":        ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateMaintenance":     ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateProgress":        ToolMapping("celebration_joy", "joy.celebrate"),
    "celebrateOthers":          ToolMapping("celebration_joy", "joy.celebrate"),
    "noticeJoy":                ToolMapping("celebration_joy", "joy.celebrate"),
    "noteThatWasFun":           ToolMapping("celebration_joy", "joy.celebrate"),
    "findMomentsOfJoy":         ToolMapping("celebration_joy", "joy.celebrate"),
    "savorExperience":          ToolMapping("celebration_joy", "joy.celebrate"),
    "markTheMoment":            ToolMapping("celebration_joy", "joy.celebrate"),
    "expressGratitude":         ToolMapping("celebration_joy", "joy.celebrate"),
    "gratitudeEntry":           ToolMapping("celebration_joy", "joy.celebrate"),
    "logGratitude":             ToolMapping("celebration_joy", "joy.celebrate"),
    "mapJoy":                   ToolMapping("celebration_joy", "joy.celebrate"),
    "anniversarySupport":       ToolMapping("celebration_joy", "joy.celebrate"),
    "scheduleJoy":              ToolMapping("celebration_joy", "joy.celebrate"),
    "createTradition":          ToolMapping("celebration_joy", "joy.celebrate"),
    "wedding":                  ToolMapping("celebration_joy", "joy.celebrate"),
    "checkCelebrationHealth":   ToolMapping("celebration_joy", "joy.celebrate"),
    "experienceWonder":         ToolMapping("celebration_joy", "joy.play"),
    "cultivatePlayfulness":     ToolMapping("celebration_joy", "joy.play"),
    "playfulCreativity":        ToolMapping("celebration_joy", "joy.play"),
    "playWithPossibility":      ToolMapping("celebration_joy", "joy.play"),
    "becomeSilly":              ToolMapping("celebration_joy", "joy.play"),
    "givePermissionToPlay":     ToolMapping("celebration_joy", "joy.play"),
    "spontaneityChallenge":     ToolMapping("celebration_joy", "joy.play"),
    "anticipationBuilder":      ToolMapping("celebration_joy", "joy.play"),
    "buildCountdown":           ToolMapping("celebration_joy", "joy.play"),
    "embraceLightness":         ToolMapping("celebration_joy", "joy.play"),
    "findInspiration":          ToolMapping("celebration_joy", "joy.play"),
    "reclaimLostHobby":         ToolMapping("celebration_joy", "joy.play"),

    # ═══ BOUNDARIES_SELFCARE (2 meta-tools) ═══
    "setBoundary":              ToolMapping("boundaries_selfcare", "boundary.set"),
    "setBoundaryConversation":  ToolMapping("boundaries_selfcare", "boundary.set"),
    "setRelationshipBoundary":  ToolMapping("boundaries_selfcare", "boundary.set"),
    "setWorkBoundary":          ToolMapping("boundaries_selfcare", "boundary.set"),
    "boundaryCoaching":         ToolMapping("boundaries_selfcare", "boundary.set"),
    "boundaryInventory":        ToolMapping("boundaries_selfcare", "boundary.set"),
    "identifyBoundaryNeeds":    ToolMapping("boundaries_selfcare", "boundary.set"),
    "maintainBoundary":         ToolMapping("boundaries_selfcare", "boundary.set"),
    "healFromBoundaryViolation": ToolMapping("boundaries_selfcare", "boundary.set"),
    "sayNoWithGrace":           ToolMapping("boundaries_selfcare", "boundary.set"),
    "practiceDecline":          ToolMapping("boundaries_selfcare", "boundary.set"),
    "advocatingForSelf":        ToolMapping("boundaries_selfcare", "boundary.set"),
    "noContact":                ToolMapping("boundaries_selfcare", "boundary.set"),
    "phoneFreeTime":            ToolMapping("boundaries_selfcare", "boundary.digital"),
    "digitalBoundaries":        ToolMapping("boundaries_selfcare", "boundary.digital"),
    "digitalAudit":             ToolMapping("boundaries_selfcare", "boundary.digital"),
    "mindfulTechUse":           ToolMapping("boundaries_selfcare", "boundary.digital"),
    "notificationDetox":        ToolMapping("boundaries_selfcare", "boundary.digital"),
    "screenTimeInsights":       ToolMapping("boundaries_selfcare", "boundary.digital"),
    "restAsSkill":              ToolMapping("boundaries_selfcare", "boundary.digital"),
    "honorTheRest":             ToolMapping("boundaries_selfcare", "boundary.digital"),

    # ═══ SOCIAL_CONNECTION (3 meta-tools) ═══
    "makeAdultFriends":         ToolMapping("social_connection", "social.connect"),
    "makeFriendsAsAdult":       ToolMapping("social_connection", "social.connect"),
    "joinNewGroups":            ToolMapping("social_connection", "social.connect"),
    "findYourPeople":           ToolMapping("social_connection", "social.connect"),
    "findCommunityGroup":       ToolMapping("social_connection", "social.connect"),
    "expandNetwork":            ToolMapping("social_connection", "social.connect"),
    "networkAuthentically":     ToolMapping("social_connection", "social.connect"),
    "smallActsOfConnection":    ToolMapping("social_connection", "social.connect"),
    "suggestConnectionAction":  ToolMapping("social_connection", "social.connect"),
    "checkInOnSomeone":         ToolMapping("social_connection", "social.connect"),
    "identifySupports":         ToolMapping("social_connection", "social.connect"),
    "buildSupportSystem":       ToolMapping("social_connection", "social.connect"),
    "findVolunteerOpportunity": ToolMapping("social_connection", "social.connect"),
    "trackVolunteerHours":      ToolMapping("social_connection", "social.connect"),
    "engageCivically":          ToolMapping("social_connection", "social.connect"),
    "shareConnectionInsight":   ToolMapping("social_connection", "social.connect"),
    "shareConnectionWisdom":    ToolMapping("social_connection", "social.connect"),
    "smallTalkMastery":         ToolMapping("social_connection", "social.skills"),
    "startConversation":        ToolMapping("social_connection", "social.skills"),
    "conversationDeepener":     ToolMapping("social_connection", "social.skills"),
    "practiceConversation":     ToolMapping("social_connection", "social.skills"),
    "handleSocialRejection":    ToolMapping("social_connection", "social.skills"),
    "navigateSocialAnxiety":    ToolMapping("social_connection", "social.skills"),
    "socialFriendshipSkills":   ToolMapping("social_connection", "social.skills"),
    "acknowledgeLoneliness":    ToolMapping("social_connection", "social.loneliness"),
    "exploreLonelinessType":    ToolMapping("social_connection", "social.loneliness"),
    "sitWithLoneliness":        ToolMapping("social_connection", "social.loneliness"),
    "createBelonging":          ToolMapping("social_connection", "social.loneliness"),
    "balanceAloneAndTogether":  ToolMapping("social_connection", "social.loneliness"),
    "recognizeToxicFriendship": ToolMapping("social_connection", "social.loneliness"),
    "socialMediaRelationship":  ToolMapping("social_connection", "social.loneliness"),
    "flagConnectionConcernForMaya": ToolMapping("social_connection", "social.loneliness"),

    # ═══ DIFFICULT_CONVERSATIONS (2 meta-tools) ═══
    "prepareForDifficultConversation": ToolMapping("difficult_conversations", "conversation.prepare"),
    "prepareHardConversation":  ToolMapping("difficult_conversations", "conversation.prepare"),
    "communicationStrategy":    ToolMapping("difficult_conversations", "conversation.prepare"),
    "planStakeholderCommunication": ToolMapping("difficult_conversations", "conversation.prepare"),
    "handlingReactions":        ToolMapping("difficult_conversations", "conversation.prepare"),
    "majorAnnouncement":        ToolMapping("difficult_conversations", "conversation.prepare"),
    "tellingOthers":            ToolMapping("difficult_conversations", "conversation.prepare"),
    "comingOutPlanning":        ToolMapping("difficult_conversations", "conversation.prepare"),
    "comingOutToSelf":          ToolMapping("difficult_conversations", "conversation.prepare"),
    "craftApology":             ToolMapping("difficult_conversations", "conversation.repair"),
    "makeAmends":               ToolMapping("difficult_conversations", "conversation.repair"),

    # ═══ TEAM_HANDOFF (1 meta-tool) ═══
    "handoffToAlex":            ToolMapping("team_handoff", "team.handoff"),
    "handoffToFerni":           ToolMapping("team_handoff", "team.handoff"),
    "handoffToJordan":          ToolMapping("team_handoff", "team.handoff"),
    "handoffToMaya":            ToolMapping("team_handoff", "team.handoff"),
    "handoffToNayan":           ToolMapping("team_handoff", "team.handoff"),
    "handoffToPeter":           ToolMapping("team_handoff", "team.handoff"),
    "requestAlexProductivitySupport": ToolMapping("team_handoff", "team.handoff"),
    "requestMayaHabitIntervention": ToolMapping("team_handoff", "team.handoff"),
    "requestPeterAnalysis":     ToolMapping("team_handoff", "team.handoff"),
    "sharePatternWithTeam":     ToolMapping("team_handoff", "team.handoff"),
    "getTeamInsights":          ToolMapping("team_handoff", "team.handoff"),
    "startRoundtable":          ToolMapping("team_handoff", "team.handoff"),
    "inviteCameo":              ToolMapping("team_handoff", "team.handoff"),
    "completeCameo":            ToolMapping("team_handoff", "team.handoff"),
    "checkCameoOpportunity":    ToolMapping("team_handoff", "team.handoff"),
    "endGroupConversation":     ToolMapping("team_handoff", "team.handoff"),
    "inviteParticipant":        ToolMapping("team_handoff", "team.handoff"),
    "shareConversationWisdom":  ToolMapping("team_handoff", "team.handoff"),
    "shareSecondChanceWisdom":  ToolMapping("team_handoff", "team.handoff"),
    "flagMilestoneForJordan":   ToolMapping("team_handoff", "team.handoff"),
    "flagTransitionForJordan":  ToolMapping("team_handoff", "team.handoff"),
    "flagPerfectionismPatternForMaya": ToolMapping("team_handoff", "team.handoff"),
    "flagProcrastinationPatternForMaya": ToolMapping("team_handoff", "team.handoff"),
    "shareInnerCriticWithNayan": ToolMapping("team_handoff", "team.handoff"),

    # ═══ BACKGROUND_TASKS (1 meta-tool) ═══
    "backgroundCall":           ToolMapping("background_tasks", "background.task"),
    "backgroundFollowUp":       ToolMapping("background_tasks", "background.task"),
    "backgroundHabitReminder":  ToolMapping("background_tasks", "background.task"),
    "backgroundResearch":       ToolMapping("background_tasks", "background.task"),
    "backgroundReservation":    ToolMapping("background_tasks", "background.task"),
    "checkBackgroundJob":       ToolMapping("background_tasks", "background.task"),

    # ═══ PRODUCTIVITY_FOCUS (3 meta-tools) ═══
    "breakDownTask":            ToolMapping("productivity_focus", "focus.start"),
    "twoMinuteRule":            ToolMapping("productivity_focus", "focus.start"),
    "chaosToOrder":             ToolMapping("productivity_focus", "focus.start"),
    "getStarted":               ToolMapping("productivity_focus", "focus.start"),
    "defineFirstStep":          ToolMapping("productivity_focus", "focus.start"),
    "procrastinationPatterns":  ToolMapping("productivity_focus", "focus.start"),
    "procrastinationRootCause": ToolMapping("productivity_focus", "focus.start"),
    "procrastinationSupport":   ToolMapping("productivity_focus", "focus.start"),
    "emotionalProcrastination": ToolMapping("productivity_focus", "focus.start"),
    "adhdBodyDoubling":         ToolMapping("productivity_focus", "focus.start"),
    "adhdTaskStart":            ToolMapping("productivity_focus", "focus.start"),
    "adhdTimeBlindness":        ToolMapping("productivity_focus", "focus.start"),
    "executiveFunctionSupport": ToolMapping("productivity_focus", "focus.start"),
    "navigateCreativeBlock":    ToolMapping("productivity_focus", "focus.start"),
    "scoreDecision":            ToolMapping("productivity_focus", "focus.decide"),
    "scoreOptions":             ToolMapping("productivity_focus", "focus.decide"),
    "analyzeProsAndCons":       ToolMapping("productivity_focus", "focus.decide"),
    "walkThroughDecisionFramework": ToolMapping("productivity_focus", "focus.decide"),
    "frameMajorDecision":       ToolMapping("productivity_focus", "focus.decide"),
    "assessRisk":               ToolMapping("productivity_focus", "focus.decide"),
    "reviewCommitments":        ToolMapping("productivity_focus", "focus.goals"),
    "trackCommitment":          ToolMapping("productivity_focus", "focus.goals"),
    "trackGoal":                ToolMapping("productivity_focus", "focus.goals"),
    "getGoalProgress":          ToolMapping("productivity_focus", "focus.goals"),
    "setGoal":                  ToolMapping("productivity_focus", "focus.goals"),
    "gentleGoals":              ToolMapping("productivity_focus", "focus.goals"),
    "dopamineManagement":       ToolMapping("productivity_focus", "focus.goals"),
    "recognizeFlow":            ToolMapping("productivity_focus", "focus.goals"),
    "adjustPacing":             ToolMapping("productivity_focus", "focus.goals"),
    "pacingPlan":               ToolMapping("productivity_focus", "focus.goals"),
    "findSustainablePace":      ToolMapping("productivity_focus", "focus.goals"),
    "trackCreativeProject":     ToolMapping("productivity_focus", "focus.goals"),
    "setCreativeGoal":          ToolMapping("productivity_focus", "focus.goals"),
    "checkPlanningReadiness":   ToolMapping("productivity_focus", "focus.goals"),
    "detectMilestones":         ToolMapping("productivity_focus", "focus.goals"),

    # ═══ GAMES (2 meta-tools) ═══
    "startGame":                ToolMapping("games", "games.play"),
    "startTextGame":            ToolMapping("games", "games.play"),
    "startReflectionGame":      ToolMapping("games", "games.play"),
    "suggestGame":              ToolMapping("games", "games.play"),
    "getGameHint":              ToolMapping("games", "games.play"),
    "makeTextGameMove":         ToolMapping("games", "games.play"),
    "submitGameAnswer":         ToolMapping("games", "games.play"),
    "getTextGameBoard":         ToolMapping("games", "games.play"),
    "headlineWriter":           ToolMapping("games", "games.play"),
    "headlineWriterRespond":    ToolMapping("games", "games.play"),
    "threeWordDay":             ToolMapping("games", "games.play"),
    "threeWordDayRespond":      ToolMapping("games", "games.play"),
    "endGame":                  ToolMapping("games", "games.manage"),
    "endTextGame":              ToolMapping("games", "games.manage"),
    "skipGameRound":            ToolMapping("games", "games.manage"),
    "getGameStatus":            ToolMapping("games", "games.manage"),
    "getGameHistory":           ToolMapping("games", "games.manage"),

    # ═══ LEARNING (1 meta-tool) ═══
    "createLearningPath":       ToolMapping("learning", "learning.manage"),
    "getLearningPath":          ToolMapping("learning", "learning.manage"),
    "setLearningGoal":          ToolMapping("learning", "learning.manage"),
    "trackLearningProgress":    ToolMapping("learning", "learning.manage"),
    "addToReadingList":         ToolMapping("learning", "learning.manage"),
    "getReadingList":           ToolMapping("learning", "learning.manage"),
    "getReadingStats":          ToolMapping("learning", "learning.manage"),
    "markBookRead":             ToolMapping("learning", "learning.manage"),
    "updateReadingProgress":    ToolMapping("learning", "learning.manage"),
    "trackBooksRead":           ToolMapping("learning", "learning.manage"),
    "removeFromReadingList":    ToolMapping("learning", "learning.manage"),
    "overcomeLearningBlock":    ToolMapping("learning", "learning.manage"),
    "planStudySession":         ToolMapping("learning", "learning.manage"),
    "scheduleSpacedRepetition": ToolMapping("learning", "learning.manage"),
    "testKnowledge":            ToolMapping("learning", "learning.manage"),
    "reflectOnLearning":        ToolMapping("learning", "learning.manage"),
    "exploreNewHobby":          ToolMapping("learning", "learning.manage"),
    "suggestHobbyBasedOnInterests": ToolMapping("learning", "learning.manage"),

    # ═══ BODY_IMAGE (1 meta-tool) ═══
    "bodyCheckingAwareness":    ToolMapping("body_image", "body.support"),
    "bodyGratitude":            ToolMapping("body_image", "body.support"),
    "bodyImageCompassion":      ToolMapping("body_image", "body.support"),
    "bodyImageExplore":         ToolMapping("body_image", "body.support"),
    "bodyNeutrality":           ToolMapping("body_image", "body.support"),

    # ═══ RECOVERY (1 meta-tool) ═══
    "soberSocializing":         ToolMapping("recovery", "recovery.support"),
    "sobrietyCheckin":          ToolMapping("recovery", "recovery.support"),
    "sobrietyGrief":            ToolMapping("recovery", "recovery.support"),
    "supportRecoveryJourney":   ToolMapping("recovery", "recovery.support"),
    "cravingSupport":           ToolMapping("recovery", "recovery.support"),
    "trackSobrietyMilestone":   ToolMapping("recovery", "recovery.support"),
    "maskingRecovery":          ToolMapping("recovery", "recovery.support"),
    "boundariesForRecovery":    ToolMapping("recovery", "recovery.support"),

    # ═══ DIVORCE (1 meta-tool) ═══
    "divorceFAQ":               ToolMapping("divorce", "divorce.support"),
    "divorceGrief":             ToolMapping("divorce", "divorce.support"),
    "divorceIdentityShift":     ToolMapping("divorce", "divorce.support"),
    "lifeAfterDivorce":         ToolMapping("divorce", "divorce.support"),

    # ═══ SHAME (1 meta-tool) ═══
    "processShame":             ToolMapping("shame", "shame.process"),
    "processShameExperience":   ToolMapping("shame", "shame.process"),
    "exploreShame":             ToolMapping("shame", "shame.process"),
    "distinguishShameFromGuilt": ToolMapping("shame", "shame.process"),
    "healCoreShame":            ToolMapping("shame", "shame.process"),
    "identifyShameTriggers":    ToolMapping("shame", "shame.process"),

    # ═══ DEVELOPER (1 meta-tool) ═══
    "gitStatus":                ToolMapping("developer", "dev.tools"),
    "gitDiff":                  ToolMapping("developer", "dev.tools"),
    "gitLog":                   ToolMapping("developer", "dev.tools"),
    "gitCommit":                ToolMapping("developer", "dev.tools"),
    "runBash":                  ToolMapping("developer", "dev.tools"),
    "runFerniCommand":          ToolMapping("developer", "dev.tools"),
    "systemDesign":             ToolMapping("developer", "dev.tools"),
    "editFile":                 ToolMapping("developer", "dev.tools"),
    "readFile":                 ToolMapping("developer", "dev.tools"),
    "buildScript":              ToolMapping("developer", "dev.tools"),
    "dataStorytelling":         ToolMapping("developer", "dev.tools"),
    "detectAnomaly":            ToolMapping("developer", "dev.tools"),
    "findCorrelation":          ToolMapping("developer", "dev.tools"),
    "patternPrediction":        ToolMapping("developer", "dev.tools"),
    "predictPattern":           ToolMapping("developer", "dev.tools"),
    "getPredictions":           ToolMapping("developer", "dev.tools"),
    "getProactiveInsights":     ToolMapping("developer", "dev.tools"),
    "getMarketingAnalytics":    ToolMapping("developer", "dev.tools"),
    "getWebhookStatus":         ToolMapping("developer", "dev.tools"),
    "listWebhooks":             ToolMapping("developer", "dev.tools"),
    "listWorkflowTemplates":    ToolMapping("developer", "dev.tools"),
    "triggerWebhook":           ToolMapping("developer", "dev.tools"),
    "trackImpact":              ToolMapping("developer", "dev.tools"),
    "suggestGift":              ToolMapping("developer", "dev.tools"),

    # ═══ CONCIERGE (1 meta-tool) ═══
    "findBusiness":             ToolMapping("concierge", "concierge.manage"),
    "getBusinessInfo":          ToolMapping("concierge", "concierge.manage"),
    "getBusinessReviews":       ToolMapping("concierge", "concierge.manage"),
    "lookupBusinessByPhone":    ToolMapping("concierge", "concierge.manage"),
    "findRestaurants":          ToolMapping("concierge", "concierge.manage"),
    "restaurant":               ToolMapping("concierge", "concierge.manage"),
    "makeRestaurantReservation": ToolMapping("concierge", "concierge.manage"),
    "searchLocalBusinesses":    ToolMapping("concierge", "concierge.manage"),
    "checkLocalSearchStatus":   ToolMapping("concierge", "concierge.manage"),
    "proactiveConciergeCheckIn": ToolMapping("concierge", "concierge.manage"),
    "checkConciergeStatus":     ToolMapping("concierge", "concierge.manage"),
    "getGuestInsights":         ToolMapping("concierge", "concierge.manage"),
    "trackGift":                ToolMapping("concierge", "concierge.manage"),

    # ═══ __NO_TOOL__ ═══
    "__no_tool__":              ToolMapping("__no_tool__", "__no_tool__"),
}

# ─────────────────────────────────────────────
# Derived lookups
# ─────────────────────────────────────────────

TOOL_TO_DOMAIN: dict[str, str] = {k: v.domain for k, v in TAXONOMY.items()}
TOOL_TO_META: dict[str, str] = {k: v.meta_tool for k, v in TAXONOMY.items()}

# All unique domains (sorted)
DOMAINS: list[str] = sorted(set(v.domain for v in TAXONOMY.values()))

# All unique meta-tools per domain
META_TOOLS_BY_DOMAIN: dict[str, list[str]] = {}
for tool, mapping in TAXONOMY.items():
    META_TOOLS_BY_DOMAIN.setdefault(mapping.domain, set()).add(mapping.meta_tool)
META_TOOLS_BY_DOMAIN = {k: sorted(v) for k, v in META_TOOLS_BY_DOMAIN.items()}

# All unique meta-tools (sorted)
ALL_META_TOOLS: list[str] = sorted(set(v.meta_tool for v in TAXONOMY.values()))

def get_domain(tool_name: str) -> str | None:
    """Get domain for a tool name. Returns None if unknown."""
    return TOOL_TO_DOMAIN.get(tool_name)

def get_meta_tool(tool_name: str) -> str | None:
    """Get meta-tool for a tool name. Returns None if unknown."""
    return TOOL_TO_META.get(tool_name)


# ─────────────────────────────────────────────
# Validation & statistics
# ─────────────────────────────────────────────

if __name__ == "__main__":
    import json

    # Load original label map for coverage check
    print(f"V7 Taxonomy Statistics")
    print(f"{'='*50}")
    print(f"Total tools mapped:    {len(TAXONOMY)}")
    print(f"Domains:               {len(DOMAINS)}")
    print(f"Meta-tools:            {len(ALL_META_TOOLS)}")
    print(f"")
    print(f"Domain breakdown:")
    for domain in DOMAINS:
        tools_in_domain = [k for k, v in TAXONOMY.items() if v.domain == domain]
        meta_count = len(META_TOOLS_BY_DOMAIN[domain])
        print(f"  {domain:30s}  {len(tools_in_domain):3d} tools → {meta_count} meta-tools")

    # Check coverage against label_map.json
    try:
        with open("../../models/ferni-router-v5-860/label_map.json") as f:
            label_map = json.load(f)
        missing = set(label_map.keys()) - set(TAXONOMY.keys())
        extra = set(TAXONOMY.keys()) - set(label_map.keys())
        if missing:
            print(f"\n⚠️  Missing from taxonomy ({len(missing)}):")
            for m in sorted(missing):
                print(f"    - {m}")
        if extra:
            print(f"\n⚠️  Extra in taxonomy ({len(extra)}):")
            for e in sorted(extra):
                print(f"    - {e}")
        if not missing and not extra:
            print(f"\n✅ Perfect coverage: all {len(label_map)} tools mapped")
    except FileNotFoundError:
        print("\n(label_map.json not found - skipping coverage check)")
