#!/usr/bin/env node
/**
 * Token Drift Checker
 * 
 * Validates that generated token files are in sync with source JSON.
 * Run this in CI to catch token drift before deploy.
 * 
 * Usage:
 *   node design-system/check-drift.js
 *   npm run tokens:check
 * 
 * Exit codes:
 *   0 - All tokens in sync
 *   1 - Drift detected (need to run npm run tokens:sync)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.dirname(__dirname);

// ============================================================================
// CONFIGURATION
// ============================================================================

const TOKEN_SOURCES = [
  'design-system/tokens/colors.json',
  'design-system/tokens/spacing.json',
  'design-system/tokens/typography.json',
  'design-system/tokens/animation.json',
  'design-system/tokens/personas.json',
];

const GENERATED_FILES = [
  'design-system/dist/tokens.css',
  'apps/web/public/design-system/tokens.css',
  'apps/website/ferni-website/css/design-tokens.css',
  'apps/website/ferni-website/src/css/_tokens.css',
  'apps/website/developers-portal/src/css/tokens.css',
  'apps/website/design-system-portal/src/css/tokens.css',
  'brand/ferni-design-tokens.css',
];

const DEPRECATED_FILES = [
  // brand/ferni-design-tokens.css is now auto-generated by sync-promo-tokens.js
];

// ============================================================================
// HELPERS
// ============================================================================

function hashFile(filepath) {
  try {
    const content = fs.readFileSync(filepath, 'utf-8');
    return createHash('md5').update(content).digest('hex');
  } catch {
    return null;
  }
}

function getFileAge(filepath) {
  try {
    const stats = fs.statSync(filepath);
    return Date.now() - stats.mtimeMs;
  } catch {
    return Infinity;
  }
}

function formatAge(ms) {
  const hours = Math.floor(ms / (1000 * 60 * 60));
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

// ============================================================================
// CHECKS
// ============================================================================

function checkSourcesExist() {
  const missing = [];
  for (const file of TOKEN_SOURCES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    if (!fs.existsSync(fullPath)) {
      missing.push(file);
    }
  }
  return missing;
}

function checkGeneratedFilesExist() {
  const missing = [];
  for (const file of GENERATED_FILES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    if (!fs.existsSync(fullPath)) {
      missing.push(file);
    }
  }
  return missing;
}

function checkDeprecatedFiles() {
  const found = [];
  for (const file of DEPRECATED_FILES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    if (fs.existsSync(fullPath)) {
      // Check if it's different from design-system source
      const deprecatedContent = fs.readFileSync(fullPath, 'utf-8');
      const isAutoGenerated = deprecatedContent.includes('AUTO-GENERATED');
      found.push({ file, isAutoGenerated });
    }
  }
  return found;
}

function checkGeneratedFreshness() {
  const stale = [];

  // Get newest source file timestamp
  let newestSource = 0;
  for (const file of TOKEN_SOURCES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    try {
      const stats = fs.statSync(fullPath);
      if (stats.mtimeMs > newestSource) {
        newestSource = stats.mtimeMs;
      }
    } catch {
      // Skip missing files
    }
  }

  // In CI, git checkout sets all file timestamps to roughly the same time.
  // Use a tolerance of 60 seconds to avoid false positives.
  const FRESHNESS_TOLERANCE_MS = 60_000;

  // Check if generated files are significantly older than sources
  for (const file of GENERATED_FILES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    try {
      const stats = fs.statSync(fullPath);
      if (stats.mtimeMs < newestSource - FRESHNESS_TOLERANCE_MS) {
        stale.push({
          file,
          generatedAge: formatAge(Date.now() - stats.mtimeMs),
          sourceAge: formatAge(Date.now() - newestSource),
        });
      }
    } catch {
      // Skip missing files (already caught by existence check)
    }
  }

  return stale;
}

function checkPersonaConsistency() {
  const issues = [];
  
  // Load both persona sources
  const colorsPath = path.join(PROJECT_ROOT, 'design-system/tokens/colors.json');
  const personasPath = path.join(PROJECT_ROOT, 'design-system/tokens/personas.json');
  
  try {
    const colors = JSON.parse(fs.readFileSync(colorsPath, 'utf-8'));
    const personas = JSON.parse(fs.readFileSync(personasPath, 'utf-8'));
    
    const colorPersonas = Object.keys(colors.personas || {}).filter(k => !k.startsWith('_'));
    const personaKeys = Object.keys(personas.personas || {}).filter(k => !k.startsWith('_'));
    
    // Check for personas in personas.json but missing from colors.json
    for (const p of personaKeys) {
      if (!colorPersonas.includes(p)) {
        issues.push(`Persona "${p}" in personas.json but missing from colors.json`);
      }
    }
    
    // Check for personas in colors.json but missing from personas.json
    for (const p of colorPersonas) {
      if (!personaKeys.includes(p)) {
        issues.push(`Persona "${p}" in colors.json but missing from personas.json`);
      }
    }
  } catch (e) {
    issues.push(`Error reading persona files: ${e.message}`);
  }
  
  return issues;
}

// ============================================================================
// MAIN
// ============================================================================

function main() {
  console.log('🔍 Checking token drift...\n');
  
  let hasErrors = false;
  let hasWarnings = false;
  
  // Check 1: Source files exist
  const missingSources = checkSourcesExist();
  if (missingSources.length > 0) {
    console.log('❌ Missing source files:');
    missingSources.forEach(f => console.log(`   - ${f}`));
    hasErrors = true;
  } else {
    console.log('✅ All source files exist');
  }
  
  // Check 2: Generated files exist
  const missingGenerated = checkGeneratedFilesExist();
  if (missingGenerated.length > 0) {
    console.log('❌ Missing generated files:');
    missingGenerated.forEach(f => console.log(`   - ${f}`));
    console.log('   Run: npm run tokens:sync');
    hasErrors = true;
  } else {
    console.log('✅ All generated files exist');
  }
  
  // Check 3: Deprecated files
  const deprecated = checkDeprecatedFiles();
  if (deprecated.length > 0) {
    console.log('⚠️  Deprecated files found:');
    deprecated.forEach(({ file, isAutoGenerated }) => {
      console.log(`   - ${file} ${isAutoGenerated ? '(auto-generated, consider removing)' : '(MANUAL EDITS - needs migration)'}`);
    });
    hasWarnings = true;
  }
  
  // Check 4: Generated files freshness
  const stale = checkGeneratedFreshness();
  if (stale.length > 0) {
    console.log('❌ Stale generated files (older than sources):');
    stale.forEach(({ file, generatedAge, sourceAge }) => {
      console.log(`   - ${file}`);
      console.log(`     Generated: ${generatedAge}, Source: ${sourceAge}`);
    });
    console.log('   Run: npm run tokens:sync');
    hasErrors = true;
  } else {
    console.log('✅ Generated files are up to date');
  }
  
  // Check 5: Persona consistency
  const personaIssues = checkPersonaConsistency();
  if (personaIssues.length > 0) {
    console.log('❌ Persona consistency issues:');
    personaIssues.forEach(issue => console.log(`   - ${issue}`));
    hasErrors = true;
  } else {
    console.log('✅ Personas are consistent across files');
  }
  
  // Summary
  console.log('\n' + '─'.repeat(50));
  if (hasErrors) {
    console.log('❌ DRIFT DETECTED - Run: npm run tokens:sync');
    process.exit(1);
  } else if (hasWarnings) {
    console.log('⚠️  Warnings found - consider cleanup');
    process.exit(0);
  } else {
    console.log('✅ All tokens in sync!');
    process.exit(0);
  }
}

main();

