#!/usr/bin/env node
/**
 * Token Drift Checker
 *
 * Validates that generated token files exist and persona definitions are consistent.
 * Run this in CI to catch missing files and configuration drift.
 *
 * Usage:
 *   node design-system/check-drift.js           # Standard check (CI-safe)
 *   node design-system/check-drift.js --strict  # Add timestamp comparison (local only)
 *   npm run tokens:check
 *
 * Exit codes:
 *   0 - All tokens in sync
 *   1 - Drift detected (need to run npm run tokens:sync)
 *
 * CI Note: By default, skips timestamp comparison because fresh Git checkouts
 * have uniform timestamps, causing false positives. Use --strict for local dev
 * where timestamps are reliable.
 *
 * Actual drift is caught by pre-commit hooks which regenerate tokens and fail
 * if there are uncommitted changes.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.dirname(__dirname);

// Parse CLI args
const args = process.argv.slice(2);
const STRICT_MODE = args.includes('--strict');
const VERBOSE = args.includes('--verbose') || args.includes('-v');

// ============================================================================
// CONFIGURATION
// ============================================================================

const TOKEN_SOURCES = [
  'design-system/tokens/colors.json',
  'design-system/tokens/spacing.json',
  'design-system/tokens/typography.json',
  'design-system/tokens/animation.json',
  'design-system/tokens/personas.json',
];

const GENERATED_FILES = [
  'design-system/dist/tokens.css',
  'apps/web/public/design-system/tokens.css',
  'apps/website/ferni-website/css/design-tokens.css',
  'apps/website/ferni-website/src/css/_tokens.css',
  'apps/website/developers-portal/src/css/tokens.css',
  'apps/website/design-system-portal/src/css/tokens.css',
  'brand/ferni-design-tokens.css',
];

const DEPRECATED_FILES = [
  // brand/ferni-design-tokens.css is now auto-generated by sync-promo-tokens.js
];

// ============================================================================
// HELPERS
// ============================================================================

function getFileAge(filepath) {
  try {
    const stats = fs.statSync(filepath);
    return Date.now() - stats.mtimeMs;
  } catch {
    return Infinity;
  }
}

function formatAge(ms) {
  const hours = Math.floor(ms / (1000 * 60 * 60));
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

// ============================================================================
// CHECKS
// ============================================================================

function checkSourcesExist() {
  const missing = [];
  for (const file of TOKEN_SOURCES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    if (!fs.existsSync(fullPath)) {
      missing.push(file);
    }
  }
  return missing;
}

function checkGeneratedFilesExist() {
  const missing = [];
  for (const file of GENERATED_FILES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    if (!fs.existsSync(fullPath)) {
      missing.push(file);
    }
  }
  return missing;
}

function checkDeprecatedFiles() {
  const found = [];
  for (const file of DEPRECATED_FILES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    if (fs.existsSync(fullPath)) {
      // Check if it's different from design-system source
      const deprecatedContent = fs.readFileSync(fullPath, 'utf-8');
      const isAutoGenerated = deprecatedContent.includes('AUTO-GENERATED');
      found.push({ file, isAutoGenerated });
    }
  }
  return found;
}

/**
 * TIMESTAMP-BASED CHECK (--strict mode only)
 * Fast but unreliable in CI fresh checkouts where all files have same mtime.
 * Only run locally where file timestamps are meaningful.
 */
function checkGeneratedFreshnessTimestamp() {
  const stale = [];

  // Get newest source file timestamp
  let newestSource = 0;
  let newestSourceFile = '';
  for (const file of TOKEN_SOURCES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    try {
      const stats = fs.statSync(fullPath);
      if (stats.mtimeMs > newestSource) {
        newestSource = stats.mtimeMs;
        newestSourceFile = file;
      }
    } catch {
      // Skip missing files
    }
  }

  // Check if generated files are older than sources
  // Add 1 second tolerance for filesystem precision
  const TOLERANCE_MS = 1000;
  for (const file of GENERATED_FILES) {
    const fullPath = path.join(PROJECT_ROOT, file);
    try {
      const stats = fs.statSync(fullPath);
      if (stats.mtimeMs < newestSource - TOLERANCE_MS) {
        stale.push({
          file,
          generatedAge: formatAge(Date.now() - stats.mtimeMs),
          sourceAge: formatAge(Date.now() - newestSource),
          newestSource: newestSourceFile,
        });
      }
    } catch {
      // Skip missing files (already caught by existence check)
    }
  }

  return stale;
}

function checkPersonaConsistency() {
  const issues = [];

  // Load both persona sources
  const colorsPath = path.join(PROJECT_ROOT, 'design-system/tokens/colors.json');
  const personasPath = path.join(PROJECT_ROOT, 'design-system/tokens/personas.json');

  try {
    const colors = JSON.parse(fs.readFileSync(colorsPath, 'utf-8'));
    const personas = JSON.parse(fs.readFileSync(personasPath, 'utf-8'));

    const colorPersonas = Object.keys(colors.personas || {}).filter((k) => !k.startsWith('_'));
    const personaKeys = Object.keys(personas.personas || {}).filter((k) => !k.startsWith('_'));

    // Check for personas in personas.json but missing from colors.json
    for (const p of personaKeys) {
      if (!colorPersonas.includes(p)) {
        issues.push(`Persona "${p}" in personas.json but missing from colors.json`);
      }
    }

    // Check for personas in colors.json but missing from personas.json
    // Note: colors.json may have additional personas (like "joel") that are
    // color-only and not full personas. Only warn, don't fail.
    for (const p of colorPersonas) {
      if (!personaKeys.includes(p)) {
        // This is a warning, not an error - some personas are color-only
        if (VERBOSE) {
          console.log(`  [info] Persona "${p}" in colors.json but missing from personas.json (color-only persona)`);
        }
      }
    }
  } catch (e) {
    issues.push(`Error reading persona files: ${e.message}`);
  }

  return issues;
}

/**
 * Check that generated CSS files have expected structure
 * (contain root variables, theme selectors, etc.)
 */
function checkGeneratedFileStructure() {
  const issues = [];

  const mainTokensPath = path.join(PROJECT_ROOT, 'design-system/dist/tokens.css');
  if (fs.existsSync(mainTokensPath)) {
    const content = fs.readFileSync(mainTokensPath, 'utf-8');

    // Check for essential content
    if (!content.includes(':root')) {
      issues.push('tokens.css missing :root selector');
    }
    if (!content.includes('--color-')) {
      issues.push('tokens.css missing color variables');
    }
    if (!content.includes('[data-theme=')) {
      issues.push('tokens.css missing theme selectors');
    }
    if (!content.includes('[data-persona=')) {
      issues.push('tokens.css missing persona selectors');
    }

    // Check file isn't empty or truncated
    if (content.length < 1000) {
      issues.push(`tokens.css seems truncated (only ${content.length} bytes)`);
    }
  }

  return issues;
}

// ============================================================================
// MAIN
// ============================================================================

function main() {
  console.log('🔍 Checking token drift...');
  if (STRICT_MODE) {
    console.log('   (--strict mode: including timestamp comparison)\n');
  } else {
    console.log('   (CI-safe mode: skipping timestamp check, using structure validation)\n');
  }

  let hasErrors = false;
  let hasWarnings = false;

  // Check 1: Source files exist
  const missingSources = checkSourcesExist();
  if (missingSources.length > 0) {
    console.log('❌ Missing source files:');
    missingSources.forEach((f) => console.log(`   - ${f}`));
    hasErrors = true;
  } else {
    console.log('✅ All source files exist');
  }

  // Check 2: Generated files exist
  const missingGenerated = checkGeneratedFilesExist();
  if (missingGenerated.length > 0) {
    console.log('❌ Missing generated files:');
    missingGenerated.forEach((f) => console.log(`   - ${f}`));
    console.log('   Run: npm run tokens:sync');
    hasErrors = true;
  } else {
    console.log('✅ All generated files exist');
  }

  // Check 3: Generated file structure (CI-safe content validation)
  const structureIssues = checkGeneratedFileStructure();
  if (structureIssues.length > 0) {
    console.log('❌ Generated file structure issues:');
    structureIssues.forEach((issue) => console.log(`   - ${issue}`));
    console.log('   Run: npm run tokens:sync');
    hasErrors = true;
  } else {
    console.log('✅ Generated files have valid structure');
  }

  // Check 4: Deprecated files
  const deprecated = checkDeprecatedFiles();
  if (deprecated.length > 0) {
    console.log('⚠️  Deprecated files found:');
    deprecated.forEach(({ file, isAutoGenerated }) => {
      console.log(
        `   - ${file} ${isAutoGenerated ? '(auto-generated, consider removing)' : '(MANUAL EDITS - needs migration)'}`
      );
    });
    hasWarnings = true;
  }

  // Check 5: Timestamp freshness (--strict mode only, unreliable in CI)
  if (STRICT_MODE) {
    const stale = checkGeneratedFreshnessTimestamp();
    if (stale.length > 0) {
      console.log('❌ Stale generated files (older than sources):');
      stale.forEach(({ file, generatedAge, sourceAge, newestSource }) => {
        console.log(`   - ${file}`);
        console.log(`     Generated: ${generatedAge}, Source: ${sourceAge} (${newestSource})`);
      });
      console.log('   Run: npm run tokens:sync');
      hasErrors = true;
    } else {
      console.log('✅ Generated files are fresher than sources');
    }
  } else {
    console.log('ℹ️  Timestamp check skipped (use --strict for local validation)');
  }

  // Check 6: Persona consistency
  const personaIssues = checkPersonaConsistency();
  if (personaIssues.length > 0) {
    console.log('❌ Persona consistency issues:');
    personaIssues.forEach((issue) => console.log(`   - ${issue}`));
    hasErrors = true;
  } else {
    console.log('✅ Personas are consistent across files');
  }

  // Summary
  console.log('\n' + '─'.repeat(50));
  if (hasErrors) {
    console.log('❌ DRIFT DETECTED - Run: npm run tokens:sync');
    process.exit(1);
  } else if (hasWarnings) {
    console.log('⚠️  Warnings found - consider cleanup');
    process.exit(0);
  } else {
    console.log('✅ All tokens in sync!');
    process.exit(0);
  }
}

main();
